- .github/workflows/lint-test.yaml
- .github/workflows/linter.yml
- .github/workflows/release.yaml
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- README.md
- charts/grafana/Chart.yaml
- charts/grafana/README.md
- ct.yaml
- added top level README, CODE_OF_CONDUCT and CONTRIBUTING guidelines
This is just a proposal. Feel free to adjust,
Code of conduct is taken from https://raw.githubusercontent.com/grafana/grafana/master/CODE_OF_CONDUCT.md
- update grafana chart README to reflect new location
- fix linting issues
- add GitHub workflow for linter, chart-testing and release
@zanhsieh This assumes that the repository will be renamed to `helm-charts`. You can safely rename it as GitHub will redirect to the new name.
> First release in new repository

- charts/grafana/Chart.yaml
- charts/grafana/templates/poddisruptionbudget.yaml
the default PodDisruptionBudget name is `grafana` . Attempting to install 2 grafana releases in the same namespace results in the following exception:
```
Error: rendered manifests contain a resource that already exists. Unable to continue with install: existing resource conflict: namespace: monitoring, name: grafana, existing_kind: policy/v1beta1, Kind=PodDisruptionBudget, new_kind: policy/v1beta1, Kind=PodDisruptionBudget
```
This change updates the name to `grafana-RELEASE`
Signed-off-by: S.Cavallo <smcavallo@hotmail.com>
> grafana - set per-release PodDisruptionBudget name

- charts/grafana/Chart.yaml
- charts/grafana/README.md
- charts/grafana/templates/servicemonitor.yaml
- charts/grafana/values.yaml
add support for optional prometheus serviceMonitor
This is a pattern that is pretty standard across helm charts.  Some examples:
https://github.com/helm/charts/blob/master/stable/prometheus-redis-exporter/templates/servicemonitor.yaml
https://github.com/helm/charts/blob/master/stable/prometheus-cloudwatch-exporter/templates/servicemonitor.yaml
https://github.com/helm/charts/blob/master/stable/coredns/templates/servicemonitor.yaml
It would be helpful to have this built into the grafana helm chart as well for ease of monitoring.
Signed-off-by: S.Cavallo <smcavallo@hotmail.com>
> grafana - add support for prometheus serviceMonitor

- charts/grafana/Chart.yaml
- charts/grafana/README.md
- charts/grafana/templates/configmap-dashboard-provider.yaml
- charts/grafana/values.yaml
This adds a option `foldersFromFilesStructure`. It allows grafana to
replicate filesystem structure of json files in the dashboard.
More info about the feature:
https://grafana.com/docs/grafana/latest/administration/provisioning/#provision-folders-structure-from-filesystem-to-grafana
Fixes: #11
> grafana chart: Add option foldersFromFilesStructure

- charts/grafana/Chart.yaml
- charts/grafana/values.yaml
https://grafana.com/docs/grafana/latest/auth/github/ has the correct URL, fixing it in the chart as OAurth will never work with the current URL.
> Fixing Github API URL

- charts/grafana/Chart.yaml
- charts/grafana/README.md
This PR adds an example on how to securely reference secrets in grafana.ini. Originally requested [here](https://github.com/helm/charts/issues/22473#issuecomment-662361020).
Adding to README to increase visibility.
> Add example on how to use secrets in grafana.ini

- charts/grafana/Chart.yaml
- charts/grafana/README.md
- charts/grafana/templates/_pod.tpl
- charts/grafana/values.yaml
Grafana config files [allow the use of environment variables](https://grafana.com/docs/grafana/latest/administration/provisioning/#using-environment-variables). This change allows a secret to be specified for the datasources sidecar. Its defined keys will then be made available to the sidecar via environment variables.
> add envFromSecret parameter for datasources sidecar

- charts/grafana/Chart.yaml
- charts/grafana/README.md
- charts/grafana/templates/_helpers.tpl
- charts/grafana/templates/_pod.tpl
- charts/grafana/templates/image-renderer-deployment.yaml
- charts/grafana/templates/image-renderer-network-policy.yaml
- charts/grafana/templates/image-renderer-service.yaml
- charts/grafana/values.yaml
Sets up a remote rendering service as per https://github.com/grafana/grafana-image-renderer/blob/master/docs/remote_rendering_using_docker.md
> feat: add an image-renderer deployment

- charts/grafana/Chart.yaml
- charts/grafana/values.yaml
This adds support for arm64/arm images as well.
https://hub.docker.com/layers/kiwigrid/k8s-sidecar/0.1.209/
> [grafana] Update kiwigrid/k8s-sidecar

- charts/grafana/Chart.yaml
- charts/grafana/templates/_pod.tpl
- charts/grafana/templates/image-renderer-deployment.yaml
- charts/grafana/values.yaml
AWS EKS support for cloudwatch with an example in values.yaml
Background:
I'm using AWS EKS and CloudWatch for some of my metrics in kube-prometheus-stack (previously known as prometheus-operator)
This is my minimal patch and example configuration with a howto guide on using EKS iam roles for service accounts to gain access to cloudwatch metrics.
If this patch is merged it will save me some effort next time i need to upgrade
This is not a breaking change although it adds new functionality in form of the projected field.
> AWS EKS support for cloudwatch with an example in values.yaml

- charts/grafana/Chart.yaml
- charts/grafana/README.md
- charts/grafana/templates/clusterrole.yaml
- charts/grafana/templates/clusterrolebinding.yaml
- charts/grafana/templates/role.yaml
- charts/grafana/templates/rolebinding.yaml
- charts/grafana/values.yaml
What this PR does / why we need it:
This add useExistingRole option, which enables chart to skip role creation and instead bind to existing role - which is needed in f.ex. some RHEL openshift+jenkins setups, where "normal users" are not allowed to create role's (but can do the rolebinding and sa creation to the existing role).
Checklist
x DCO signed
x Chart Version bumped
x Variables are documented in the README.md
https://github.com/helm/charts/pull/23370 - reimplementation in new repo as requested.
Same option is in among others - Prometheus (upstreamed by me :)
> add useExistingRole support.

- charts/grafana/Chart.yaml
- charts/grafana/README.md
- charts/grafana/templates/_pod.tpl
- charts/grafana/values.yaml
...  that allows to create folder structure in Grafana by annotating config maps passed to
sidecar container
Signed-off-by: Tomáš Hejátko <tomas.hejatko@gmail.com>
> Add `sidecar.dashboards.folderAnnotation` parameter,

- charts/grafana/Chart.yaml
- charts/grafana/templates/podsecuritypolicy.yaml
With K8S 1.19 this is required, closes https://github.com/grafana/helm-charts/issues/59
> Update PSP to allow runtime/default

- charts/grafana/Chart.yaml
- charts/grafana/templates/_pod.tpl
Specifically set runAsNonRoot to false for initChown container so that
it can always run as root. This is to avoid any pod.securityContext overriding
runAsNonRoot.
> Add runAsNonRoot to false for initChown

- charts/grafana/Chart.yaml
- charts/grafana/README.md
- charts/grafana/templates/_pod.tpl
- charts/grafana/templates/podsecuritypolicy.yaml
- charts/grafana/templates/tests/test-podsecuritypolicy.yaml
- charts/grafana/values.yaml
Support for mounting secrets from a CSI provider 
**Background:**
I'm using Azure Key Vault (AKV) for the management of secrets.
Following [Microsoft guidelines](https://docs.microsoft.com/en-us/azure/key-vault/general/key-vault-integrate-kubernetes) the recommended integration of AKV is to use a CSI driver
This is not a breaking change - it adds new functionality `csi` under `extraSecretMounts` section
Signed-off-by: Maurycy Widera <mauryc@gmail.com>
> Add support for  Container Storage Interface (CSI) secret providers

- charts/grafana/Chart.yaml
- charts/grafana/values.yaml
This PR bumps the app- and image version to grafana 7.3.1
> bump appversion and image to 7.3.1

- charts/grafana/Chart.yaml
- charts/grafana/templates/servicemonitor.yaml
Signed-off-by: Cédric Menassa <cedric.menassa@gmail.com>
It seems  that the serviceMonitor `selector` `matchLabels` don't target correctly grafana pods.
Doesn't work:
```yaml 
selector:
matchLabels:
app: {{ template "grafana.name" . }}
release: "{{ .Release.Name }}"
```
Works:
```yaml
selector:
matchLabels:
{{- include "grafana.selectorLabels" . | nindent 8 }}
```
> Fix serviceMonitor selector matchLabels

- charts/grafana/Chart.yaml
- charts/grafana/templates/ingress.yaml
- charts/grafana/values.yaml
Signed-off-by: Christian Niehoff <mail@christian-niehoff.com>
Resolves #77 
This pull request will add support for the new `ingressClassName` field.
See https://kubernetes.io/blog/2020/04/02/improvements-to-the-ingress-api-in-kubernetes-1.18/#specifying-the-class-of-an-ingress
> add IngressClass support

- charts/grafana/Chart.yaml
- charts/grafana/templates/secret.yaml
Hi,
I want to provide a blueprint in our company. Currently I'm using the `existingSecret` to provide a ldap.toml. But if ldap.toml has been changed, grafana will not do a reload or restart and needs a manual restart.
If I could embed the ldap.config inside the values.yaml, the restart annotation should work as expected.
> Support templating in `ldap-toml` values

- .github/workflows/lint-test.yaml
- .github/workflows/release.yaml
- .gitignore
This updates GitHub actions and tools used in GitHub workflows to the
latest versions.
See https://github.com/helm/charts-repo-actions-demo for reference.
This update adds support for GPG signing which will be required for the
planned addition of Loki charts. See grafana/loki/issues/2593
Signed-off-by: Reinhard Nägele <unguiculus@gmail.com>
> Update tools versions in GitHub workflow

- .github/CODEOWNERS
- .github/workflows/check-codeowners.yaml
- charts/grafana/Chart.yaml
- scripts/check-codeowners.sh
This adds a CODEOWNERS file as suggested in https://github.com/grafana/loki/issues/2593#issuecomment-718442894.
There is also a new workflow, which contains a check so that we cannot forget to reflect changes in chart maintainers also in that file.
@maorfr @rtluckie @Xtigyro @zanhsieh I also added myself as maintainer. Hope that's ok if not then I am happy to remove it.
So far I have hardly reviewed PRs and only added comments as I felt not entitled to do so. In the end I just helped with the chart migration ;-)
> Add CODEOWNERS + add myself as maintainer

- charts/grafana/Chart.yaml
- charts/grafana/README.md
Helm no longer accepts the `--name` argument, but rather want you to input the name directly.
```
$ helm version
version.BuildInfo{Version:"v3.4.1", GitCommit:"xxxx", GitTreeState:"dirty", GoVersion:"go1.15.4"}
$ helm install --name grafana --namespace infra  grafana/grafana
Error: unknown flag: --name
$ helm install grafana --namespace infra grafana/grafana
NAME: grafana
LAST DEPLOYED: Mon Nov 23 19:04:47 2020
NAMESPACE: infra
STATUS: deployed
```
> Remove argument from helm install command

- charts/grafana/Chart.yaml
- charts/grafana/values.yaml
This PR fixes https://github.com/grafana/helm-charts/issues/95 for Helm v3.1.3.
> Add missing default value for `imageRenderer.service.targetPort`

- charts/grafana/Chart.yaml
- charts/grafana/values.yaml
Hello 👋 
I was using your HelmChart today to install the ImageRenderer plugin and experienced some confusion when my Grafana instance couldn't talk to the imageRenderer.
It seems the default values.yaml Values don't provide a working setup, I've tweaked them to fix that.
Thanks!
> fix: Fix network communication with ImageRenderer so it works with the

- charts/grafana/Chart.yaml
- charts/grafana/templates/pvc.yaml
- charts/grafana/templates/statefulset.yaml
- charts/grafana/values.yaml
In some on prem datacenter deployments you have static PVs where you match pre-created PVCs/VolumeClaimTemplates to a fixed PV. This allows use of this by optionally allowing users to specify a `labelSelector` for their persistence.
Currently the only real option is to have a single instance where you pass in a pre-created PVC - whilst this is an option for a single instance of grafana - it obviously doesn't work if you want to use a stateful set for multiple instances
> Allow specifying pvc selectors in the chart

- charts/grafana/Chart.yaml
- charts/grafana/README.md
The README states that this chart requires Helm 3.4.0, which is not correct, as somebody found out in https://github.com/prometheus-community/helm-charts/pull/460#discussion_r537541527.
> Fix incorrect requirement on Helm version

- charts/loki-distributed/Chart.yaml
- charts/loki-distributed/README.md
- charts/loki-distributed/templates/gateway/service-gateway.yaml
- charts/loki-distributed/values.yaml
This allows setting annotations on the gateway service, which is needed to have deployments with container native loadbalancing in Google Cloud's GKE, see https://cloud.google.com/kubernetes-engine/docs/how-to/container-native-load-balancing#create_service
Example usage:
```yaml
gateway:
service:
type: ClusterIP
annotations:
cloud.google.com/neg: '{"ingress": true}'
ingress:
enabled: true
annotations:
kubernetes.io/ingress.class: "gce-internal" # internal loadbalancer
hosts:
- paths:
- /*
```
> [loki-distributed] Add setting for gateway service annotations

- .github/workflows/validate-pr.yaml
- scripts/validate-pr.sh
Now that we have multiple charts in the repo, it makes sense to enforce
that a pull request title starts with a prefix that contains the chart
name. Additionally, this will require that a single pull request cannot
make changes to multiple charts.
> Add workflow for pull request validation

- charts/loki-distributed/Chart.yaml
- charts/loki-distributed/README.md
- charts/loki-distributed/templates/serviceaccount.yaml
Using the correct template for the `ServiceAccount` name in `loki-distributed`
> [loki-distributed] Change the `ServiceAccount`'s name to use the correct template

- charts/loki-distributed/Chart.yaml
- charts/loki-distributed/README.md
- charts/loki-distributed/templates/compactor/deployment-compactor.yaml
- charts/loki-distributed/templates/ingester/statefulset-ingester.yaml
- charts/loki-distributed/templates/querier/statefulset-querier.yaml
- charts/loki-distributed/templates/ruler/deployment-ruler.yaml
- charts/loki-distributed/templates/table-manager/deployment-table-manager.yaml
- charts/loki-distributed/values.yaml
**Description of changes**
Add the capability to add Volumes and Volume mounts to the needed services. This is needed to be able to mount the GCP service account for example.
**Benefits**
Able to mount the GCP service account json file to the needed services.
**Additional Information**
It's the same capability as PR https://github.com/grafana/helm-charts/pull/148 but not a global level.
> [loki-distributed] Add capability to add Volumes and Volume mounts

- charts/grafana/Chart.yaml
- charts/grafana/templates/_pod.tpl
- charts/grafana/values.yaml
Need to align with company security requirements, and current psp of Grafana is too wide.
Being able to override default containerSecurityContext settings will help us to cover security related aspects.
> [grafana] Add support for overriding container securityContext

- charts/grafana/Chart.yaml
- charts/grafana/README.md
- charts/grafana/templates/_pod.tpl
- charts/grafana/values.yaml
* Allows specification of the LABEL_VALUE environment variable on the
kiwigrid/k8s-sidecar as labelValue helm value for the datasource and
dashboard sidecars.
Signed-off-by: Ryan Probus <ryan.probus@appian.com>
> [grafana] add sidecar configmap label value select

- charts/promtail/Chart.yaml
- charts/promtail/README.md
- charts/promtail/values.yaml
The default config was missing a few drop actions. This had caused logs
to be added twice, once the correct way and once with an incorrect job
label.
In order to help debug the config, the flag
`config.snippets.addScrapeJobLabel` is introduced. If enabled, an
additional label `scrape_job` is added which identifies the scrape job
that picked up the log message.
> [promtail] Fix scrape configs

- charts/loki-distributed/Chart.yaml
- charts/loki-distributed/README.md
- charts/loki-distributed/values.yaml
This allows configuring 2 options:
- `clusterDomain` nor all clusters use `cluster.local`
- `dnsService` - not all clusters have the default DNS service under this name, we have some clusters that go with `coredns`
> [loki-distributed] Add clusterDomain and dnsService config options

- charts/promtail/Chart.yaml
- charts/promtail/README.md
- charts/promtail/templates/role.yaml
- charts/promtail/values.yaml
There are 2 issues when you try to run promtail on a cluster that enforces PSPs
(and you have in the config:
```yaml
rbac:
create: true
pspEnabled: true
```
* API group reference in role is wrong (must be `policy`
* the PSP doesn't allow for `privileged`, but must run as user 0
Credits: @glitchcrab
Signed-off-by: Łukasz Piątkowski <piontec@gmail.com>
> [promtail] fix: PSP reference in role was wrong and PSP needs to allow privileged

- charts/promtail/Chart.yaml
- charts/promtail/README.md
- charts/promtail/values.yaml
The Promtail initContainer is enabled by default which sets the `fs.inotify.max_user_instances` sysctl to `128`.
This sysctl is not namespaced and it's value is applied to the node.
Also the default value of `128` is too low and can cause issues for other pods running on bigger nodes.
Therefore the sysctl must be disabled by default.
> [promtail] Disable initContainer by default

- charts/promtail/Chart.yaml
- charts/promtail/README.md
- charts/promtail/values.yaml
Kubernetes uses `kubernetes.io/config.hash` annotation value for pod log paths if present, otherwise the pod UID is used.
This change adds support for pod logs which have the above annotation set.
> [promtail] Support pod logs that use config.hash

- charts/promtail/Chart.yaml
- charts/promtail/README.md
- charts/promtail/README.md.gotmpl
- charts/promtail/ci/service-values.yaml
- charts/promtail/values.yaml
This PR adds the following options, which were available previously:
- add custom keys to the `client` section of the config file
- add extra scrape configs directly (to allow for journal or static scrapping)
> [promtail] Add more customizations to values.yaml

- charts/grafana/Chart.yaml
- charts/grafana/README.md
- charts/grafana/templates/_pod.tpl
- charts/grafana/values.yaml
This PR adds support for mounting the Grafana non-persistent local storage in-memory (tmpfs).
That allows to get better performance when you don't need persistence and when the load on Grafana is high enough to create a lot of "locked db" issues, but not enough to warrant a dedicated external RDBMS.
> [grafana] Support in-memory for non-persistent local storage

- .github/CODEOWNERS
Adds tempo maintainers as code owners for upcoming tempo charts.
> Add tempo maintainers to upcoming tempo charts

- .github/CODEOWNERS
@swartz-k is the original author of the tempo helm charts and wants to participate in maintaining them moving forward.
> Make swartz-k a tempo codeowner

- charts/grafana/Chart.yaml
- charts/grafana/README.md
- charts/grafana/values.yaml
Signed-off-by: André Bauer <monotek23@gmail.com>
* updates grafana to 7.4.2
* updates k8s-sidcar image to 1.10.6 (fixes https://github.com/grafana/helm-charts/issues/233)
* changed sidcar repo to quay.io to prevent dockerhub limits errors
> [grafana] updated grafana / sidecar image & repo

- charts/grafana/Chart.yaml
- charts/grafana/templates/configmap.yaml
- charts/grafana/values.yaml
Signed-off-by: dkusidlo <dennis.kusidlo@gmail.com>
When using GitHub Enterprise for local dashboards the raw token expires after 14 days and tokenless curl is not supported.
Personal access tokens do not expire and would fix this problem, but do not work when provided in the URL with `?token=`. There we would need support for an optional `Authorization` header in the curl command of the download_dashboards.sh.
> [grafana] Added support for auth tokens for local dashboards

- charts/tempo-distributed/Chart.yaml
- charts/tempo-distributed/README.md
- charts/tempo-distributed/README.md.gotmpl
- charts/tempo-distributed/templates/distributor/deployment-distributor.yaml
- charts/tempo-distributed/templates/distributor/service-distributor.yaml
- charts/tempo-distributed/templates/query-frontend/deployment-query-frontend.yaml
- charts/tempo-distributed/templates/query-frontend/service-query-frontend.yaml
- charts/tempo-distributed/values.yaml
**Description of changes**
With this change it would be possible to set additional settings in the Distributor service if you will use a `LoadBalancer` to receive traffic. Also fixed to add annotations in the QueryFrontend.
**Benefits**
- Specify which IP the LoadBalancer should get.
- Specify which IP ranges are allowed.
- Fix annotations in the queryFrontend service.
> [tempo-distributed] Add options for LoadBalancer Distributor.

- charts/tempo-distributed/Chart.yaml
- charts/tempo-distributed/README.md
- charts/tempo-distributed/templates/querier/deployment-querier.yaml
- charts/tempo-distributed/templates/query-frontend/deployment-query-frontend.yaml
Querier didn't had the correct replicas value pointed to it. Upgrading of a chart was not possible due to not using selector labels in the querier and queryFrontend deployment. Removed the hardcoded Jaeger client setting in `tempo-query`.
**Additional Information.**
Don't know if we need to make the chart `0.9.0` or `0.8.1` as upgrading was not working before and the actual deployments need to be deleted to make the upgrade work.
> [tempo-distributed] Fix replicas querier & deployment selectorlabels

- charts/grafana/Chart.yaml
- charts/grafana/templates/configmap.yaml
Addresses the same issue as https://github.com/grafana/helm-charts/pull/201 but works. 
Only difference in output is whitespace output when nil values are supplied.
> [grafana] support templating grafana ini options

- charts/grafana/Chart.yaml
- charts/grafana/templates/ingress.yaml
current implementation does not aligned well with the case when `networking.k8s.io/v1beta1` API group DO exist but does not contain Ingress resource defined inside. E.g. it might consist only of NetworkPolicy object and nothing else.
the proposed change adds more precise verification whether Ingress resource is really present inside the API groups.
> [grafana] fix Ingress resource API version compatibility check

- charts/promtail/Chart.yaml
- charts/promtail/README.md
- charts/promtail/values.yaml
Since https://github.com/grafana/helm-charts/pull/202, with the default config, promtail sends duplicate logs for pods with container of the same name running on the same host. See this fix and the discussion above for the technical details: https://github.com/grafana/helm-charts/pull/202#commitcomment-47148139
This PR uses @shkrid fix (thanks by the way), which adds a check that the `kubernetes.io/config.hash` annotation is present before replacing.
This might also fix https://github.com/grafana/loki/issues/3443
> [promtail] Disable __path__ override when config.hash annotation is not present

- charts/promtail/Chart.yaml
- charts/promtail/README.md
- charts/promtail/README.md.gotmpl
- charts/promtail/values.yaml
This change adds the option to customize the existent log_level configuration in the config file without needing to replace the whole file in the local values.yaml as `file:` is a single string.
Signed-off-by: lucioveloso <lucio.veloso@gmail.com>
> [promtail] Set log_level without needing to overwrite server file

- charts/grafana/Chart.yaml
- charts/grafana/README.md
- charts/grafana/templates/_pod.tpl
- charts/grafana/values.yaml
Enables fetching `token` for dashboard download from secret
Example would be:
```
...
downloadDashboards:
envFromSecret: "my-github-private-token"
...
dashboards:
default:
example:
url: https://github.com/raw/my-private-repo/<commit_hash>/dashboard.json
token: ${MY_GITHUB_PRIVATE_TOKEN}
...
```
Renders:
```
...
initContainers:
- name: download-dashboards
...
envFrom:
- secretRef:
name: my-secret-token
...
```
Signed-off-by: Yurii Matsiuk <ymatsiuk@users.noreply.github.com>
> [grafana] Add envFromSecret to downloadDashboards

- charts/tempo-distributed/Chart.yaml
- charts/tempo-distributed/README.md
- charts/tempo-distributed/templates/compactor/deployment-compactor.yaml
- charts/tempo-distributed/templates/distributor/deployment-distributor.yaml
- charts/tempo-distributed/templates/ingester/statefulset-ingester.yaml
- charts/tempo-distributed/templates/querier/deployment-querier.yaml
- charts/tempo-distributed/templates/query-frontend/deployment-query-frontend.yaml
- charts/tempo-distributed/templates/query-frontend/service-query-frontend.yaml
- charts/tempo-distributed/templates/query-frontend/servicemonitor-jaeger-query.yaml
With this PR the last servicemonitor is added for the jaeger query metrics that are exposed. The service of the query-frontend needed to be updated for it. Next to this I added the capability so that when the config changes for the services it will restart them to reload the conifguration.
**Added Benefits**
- All services are now monitored.
- Auto reload config when it changes.
> [tempo-distributed] Add config reload and Servicemonitor JQ.

- charts/grafana/Chart.yaml
- charts/grafana/README.md
- charts/grafana/values.yaml
Updated Sidecar version to fix issue.
Fixes https://github.com/grafana/helm-charts/issues/259
Ref:
https://github.com/kiwigrid/k8s-sidecar/pull/115
https://github.com/kiwigrid/k8s-sidecar/issues/114
> [grafana] Updated Grafana Sidecar Version

- charts/promtail/Chart.yaml
- charts/promtail/README.md
- charts/promtail/templates/networkpolicy.yaml
The *-egress-extra-ports NetworkPolicy was always declared
regardless of the value of .Values.networkPolicy.enabled.
This commit fixes this behavior to declare the policy
only if network policies are enabled for the chart.
Signed-off-by: Tomasz Kuzemko <tomasz@kuzemko.net>
> [promtail] fix extraPorts NetworkPolicy

- charts/tempo/Chart.yaml
- charts/tempo/README.md
- charts/tempo/values.yaml
This PR is setting a specific version for the `temp-query` image. Without this change the query fails because of https://github.com/grafana/tempo/pull/574.
> [tempo] Use specific tag for tempo-query image

- charts/tempo/Chart.yaml
- charts/tempo/README.md
- charts/tempo/templates/statefulset.yaml
This PR fixes broken indents, which causes the error below when extraVolumeMounts is enabled.
```
Error: YAML parse error on tempo/templates/statefulset.yaml: error converting YAML to JSON: yaml: line 61: did not find expected key
```
I also added trim markers for removing empty lines.
> [tempo] Fix tempo template for extraVolumeMounts

- charts/grafana/Chart.yaml
- charts/grafana/README.md
- charts/grafana/values.yaml
Update image tag in chart. It is actually 7.4.5
In that release fixed  many [CVE](https://github.com/grafana/grafana/blob/master/CHANGELOG.md)
> [grafana] Release helm chart  6.6.4, fixed CVE

- .github/CODEOWNERS
Was called metrics-enterprise, now called enterprise-metrics
> chore: Update CODEOWNERS for metrics-enterprise chart

- .github/CODEOWNERS
- charts/tempo-distributed/Chart.yaml
- charts/tempo-distributed/README.md
- Add all CODEOWNERS as maintainers to tempo-distrubuted chart.
- use GitHub usernames as maintainer names
- sort CODEOWNERS by GitHub username
Related to https://github.com/grafana/helm-charts/pull/345
Signed-off-by: Torsten Walter <mail@torstenwalter.de>
> [tempo-distributed] update maintainers

- .github/CODEOWNERS
- charts/tempo/Chart.yaml
- charts/tempo/README.md
- Add all CODEOWNERS as maintainers to tempo chart.
- use GitHub usernames as maintainer names
- sort CODEOWNERS by GitHub username
Signed-off-by: Torsten Walter <mail@torstenwalter.de>
> [tempo] update maintainers

- charts/tempo/Chart.yaml
- charts/tempo/README.md
- charts/tempo/templates/service.yaml
- charts/tempo/templates/statefulset.yaml
The OTLP change the default ports for http and grpc:
https://github.com/open-telemetry/opentelemetry-collector/blob/main/receiver/otlpreceiver/README.md
this also fixed a startup issue when defining both of the otlp protocols.
I kept the original one likewise the OTLP team seems to do this during transition phase
```
level=error ts=2021-03-29T19:00:27.711699252Z caller=app.go:235 msg="module failed" module=distributor err="invalid service state: Failed, expected: Running, failure: failed to start subservices not healthy, 0 terminated, 1 failed: [Error starting receiver listen tcp 0.0.0.0:55680: bind: address already in use]"
```
values in single-binary helm chart would then look like this:
```
receivers:
otlp:
protocols:
http:
endpoint: 0.0.0.0:55681
grpc:
endpoint: 0.0.0.0:4317
```
> [tempo] add additional otlp ports

- charts/grafana/Chart.yaml
- charts/grafana/values.yaml
Bump app and image to Grafana v7.5.3
https://github.com/grafana/grafana/releases/tag/v7.5.3
> [grafana] Bump Grafana to v7.5.3

- charts/grafana/Chart.yaml
- charts/grafana/templates/secret.yaml
Goals: 
There is a common use case that credentials need to be fetched from  Vault when deploying grafana, some annotations need to be added for secret.yaml
example like this:
https://banzaicloud.com/blog/inject-secrets-into-pods-vault-revisited/
apiVersion: v1
kind: Secret
metadata:
name: sample-secret
annotations:
vault.security.banzaicloud.io/vault-addr: "https://vault.default.svc.cluster.local:8200"
vault.security.banzaicloud.io/vault-role: "default" # In case of Secrets the webhook's ServiceAccount is used
vault.security.banzaicloud.io/vault-skip-verify: "true"
vault.security.banzaicloud.io/vault-path: "kubernetes"
type: kubernetes.io/dockerconfigjson
data:
......
> [grafana] Add annotations for grafana template secret.yaml

- charts/tempo-distributed/Chart.yaml
- charts/tempo-distributed/README.md
There was an issue rebuilding the tempo-distributed chart with 0.7.0. This version bump will force a rebuild and hopefully rebuild the chart correctly.
> [tempo-distributed] Rebuild chart for 0.7.0

- charts/grafana/Chart.yaml
- charts/grafana/README.md
- charts/grafana/templates/_pod.tpl
- charts/grafana/values.yaml
Our service account for the grafana sidecar has only "view" permissions. By default. view does include to view secrets. Good enough for dashboards...
> [grafana] Expose RESOURCE option of grafana sidecar

- charts/grafana/Chart.yaml
- charts/grafana/templates/deployment.yaml
- charts/grafana/templates/hpa.yaml
- charts/grafana/values.yaml
Looking to add horizontal pod autoscaling for grafana when using a deployment resource.
Have tested this locally and seems to work as expected.  This is my first time attempting to contribute here so if there is anything I missed just let me know.
Thanks!
> [grafana] Add horizontal pod autoscaling

- charts/grafana/Chart.yaml
- charts/grafana/templates/deployment.yaml
- charts/grafana/templates/secret.yaml
- charts/grafana/templates/statefulset.yaml
Add a check for `env.GF_SECURITY_DISABLE_INITIAL_ADMIN_CREATION` not being present when generating admin secret or its related checksums.
> [grafana] don't generate secret if admin disabled 

- charts/tempo-distributed/Chart.yaml
- charts/tempo-distributed/README.md
- charts/tempo-distributed/templates/query-frontend/service-query-frontend.yaml
- charts/tempo-distributed/values.yaml
I want to get rid of issue #399.
It should be pretty straightforward just creating the variable `.Values.queryFrontend.service.type`.
> [tempo-distributed] Make possible to change service type for queryFrontend

- charts/loki-distributed/Chart.yaml
- charts/loki-distributed/README.md
- charts/loki-distributed/README.md.gotmpl
- charts/loki-distributed/templates/ingester/statefulset-ingester.yaml
- charts/loki-distributed/templates/querier/statefulset-querier.yaml
upgraded the podManagementPolicy to Parallel and bumped the chart major version. This PR addresses #435 
Signed-off-by: Sherif Ayad <sherif.k.ayad@gmail.com>
> [loki-distributed] upgraded the podManagementPolicy to Parallel and bumped the chart major version

- charts/fluent-bit/Chart.yaml
- charts/fluent-bit/README.md
- charts/fluent-bit/templates/NOTES.txt
As discussed on Slack; This chart should be deprecated as there as an official helm chart from Fluent-bit and Loki is an official output. 
**Changes**
- Set the `deprecrated` flag. So users will get a warning when installing this chart.
- Updated README to point to the official chart and guide.
**Additional Information**
This [page](https://grafana.com/docs/loki/latest/clients/fluentbit/) should probably be updated.
> [fluent-bit] Deprecate the Fluent-bit chart.

- charts/tempo-distributed/Chart.yaml
- charts/tempo-distributed/README.md
- charts/tempo-distributed/templates/configmap-tempo.yaml
- charts/tempo-distributed/values.yaml
Can't easily generate tenant specific overrides in the `tempo-distributed` helm deployment. 
Explicitly set [ingestion overrides](https://grafana.com/docs/tempo/latest/configuration/ingestion-limit/).
> [tempo-distributed] Explicitly set ingestion overrides

- charts/loki-distributed/Chart.yaml
- charts/loki-distributed/README.md
- charts/loki-distributed/templates/compactor/servicemonitor-compactor.yaml
- charts/loki-distributed/templates/distributor/servicemonitor-distributor.yaml
- charts/loki-distributed/templates/ingester/servicemonitor-ingester.yaml
- charts/loki-distributed/templates/memcached-chunks/servicemonitor-memcached-chunks.yaml
- charts/loki-distributed/templates/memcached-frontend/servicemonitor-memcached-frontend.yaml
- charts/loki-distributed/templates/memcached-index-queries/servicemonitor-memcached-index-queries.yaml
- charts/loki-distributed/templates/memcached-index-writes/servicemonitor-memcached-index-writes.yaml
- charts/loki-distributed/templates/querier/servicemonitor-querier.yaml
- charts/loki-distributed/templates/query-frontend/servicemonitor-query-frontend.yaml
- charts/loki-distributed/templates/ruler/servicemonitor-ruler.yaml
- charts/loki-distributed/templates/table-manager/servicemonitor-table-manager.yaml
- charts/loki-distributed/values.yaml
Example:
```yaml
serviceMonitor:
enabled: true
relabelings:
- separator: /
sourceLabels:
- namespace
- __meta_kubernetes_pod_label_app_kubernetes_io_component
targetLabel: job
```
> [loki-distributed] Add relabelings to ServiceMonitor

- charts/grafana/Chart.yaml
- charts/grafana/README.md
We ran into an issue where we had `ingress.hosts: [ ]` and `ingress.extraPaths` set for ssl-redirect. After debugging everything outside of the chart, we checked the rendered template to see our extraPaths were never actually set. This hopefully prevents confusion for others. 
https://github.com/grafana/helm-charts/blob/6858ff17c334edc297b075e0bae15570ec3e05f0/charts/grafana/templates/ingress.yaml#L39-L79
(in collaboration with @jones2026)
> [grafana] docs: add clarification for ingress.extraPaths

- charts/grafana/Chart.yaml
- charts/grafana/templates/_helpers.tpl
- charts/grafana/templates/secret.yaml
Solving #10 
Using a lookup function to check if the password secret exists or not before generating new one, If It's indeed exit It'll be reused. 
Lookup functions are [first introduced in helm3](https://helm.sh/docs/chart_template_guide/functions_and_pipelines/#using-the-lookup-function) so By introducing a new lookup function this chart is pretty much incompatible with Helm2 But at this point of time, I'm not really sure that this is a problem cause 
[On November 13, 2020, Helm v2 support will formally end](https://github.com/helm/charts#status-of-the-project)
> [grafana] Prevent admin password from changing every upgrade

- charts/grafana/Chart.yaml
- charts/grafana/templates/_pod.tpl
When the user sets the grafana.ini.paths.* values for the Helm chart,
it is expected that Grafana is also started with the appropriate
configuration (instead of "just" setting the values in the config file).
This patch implements the behavior.
Fixes https://github.com/grafana/helm-charts/issues/450
Signed-off-by: Jack Henschel <jackdev@mailbox.org>
> [grafana] Start Grafana container with GF_PATHS_* env vars

- charts/grafana/Chart.yaml
- charts/grafana/values.yaml
The grafana container image uses /var/lib/grafana (instead of
/var/lib/grafana/data) as the default data path.
This patch aligns the behavior and mitigates a regression introduced
by https://github.com/grafana/helm-charts/pull/453
Signed-off-by: Jack Henschel <jackdev@mailbox.org>
> [grafana] Use same data path as grafana container image

- charts/promtail/Chart.yaml
- charts/promtail/README.md
- charts/promtail/values.yaml
The Kubernetes project is moving away from offensive wording and as part
of this KEP-2067 was accepted to replace the
`node-role.kubernetes.io/master:NoSchedule` taint with
`node-role.kubernetes.io/control-plane:NoSchedule`.
To be compatible with clusters that already use the new taint this pull
request adds an additional toleration for it. This change can't really
break existing setups because we continue to tolerate the old taint as
well.
Additional links:
- https://github.com/kubernetes/enhancements/blob/master/keps/sig-cluster-lifecycle/kubeadm/2067-rename-master-label-taint/README.md
- https://github.com/kubernetes/enhancements/issues/2067
- https://github.com/kubernetes/kubeadm/issues/2200
Signed-off-by: Max Rosin <git@hackrid.de>
> [promtail] Tolerate node-role.kubernetes.io/control-plane:NoSchedule taints

- charts/grafana/Chart.yaml
- charts/grafana/values.yaml
This updates the Grafana version to 8.0.0. Tested this on my own set-up without any issues :tada:
Resolves: #483
> [grafana] Update to 8.0.0

- charts/grafana/Chart.yaml
- charts/grafana/values.yaml
Bump app and image to Grafana v8.0.1
https://github.com/grafana/grafana/releases/tag/v8.0.1
> [grafana] Bump Grafana to v8.0.1

- charts/loki-distributed/Chart.yaml
- charts/loki-distributed/templates/compactor/persistentvolumeclaim-compactor.yaml
- charts/loki-distributed/templates/compactor/service-compactor.yaml
- charts/loki-distributed/templates/ruler/deployment-ruler.yaml
- charts/loki-distributed/templates/ruler/persistentvolumeclaim-ruler.yaml
The current chart allows you to enable persistence to true for compactor and deploy a pvc even though the compactor is disabled causing the helm deployment to fail. In addition we have defined persistence for the ruler but it is not being created anywhere. This PR attempts to fix both issues.
> [loki-distributed] chore: do not deploy pvc if compactor not enabled. create pv for ruler

- charts/tempo-distributed/Chart.yaml
- charts/tempo-distributed/README.md
- charts/tempo-distributed/templates/service-gossip-ring.yaml
Set gossip ring to be a headless service to provide a more consistent cluster connection.
Note that I incremented the patch version twice. Please merge this first:
https://github.com/grafana/helm-charts/pull/497
> [tempo-distributed] Gossip ring headless

- charts/grafana/Chart.yaml
- charts/grafana/README.md
- charts/grafana/values.yaml
Hi folks
`kiwigrid/k8s-sidecar` [was vulnerable to some CVEs](https://github.com/kiwigrid/k8s-sidecar/pull/133) - v1.12.2 fixes them. Could you update the reference?
I tested locally that the grafana dashboard import still works - so should be quite safe to bump it.
> [grafana] bump kiwigrid/k8s-sidecar to v1.12.2

- charts/grafana/Chart.yaml
- charts/grafana/README.md
- charts/grafana/templates/_pod.tpl
- charts/grafana/values.yaml
https://github.com/grafana/grafana/pull/33682 added a feature to enable Jaeger tracing when environment variables such as `JAEGER_AGENT_HOST` and `JAEGER_AGENT_PORT` are both set.
If you have a Kubernetes service in the same namespace named `jaeger`, and `enableServiceLinks` which defaults to `true` is set, this causes `JAEGER_AGENT_PORT` to be set to something like `udp://172.18.64.21:5775`, resulting in errors
```
service init failed: cannot obtain reporter config from env: cannot parse env var JAEGER_AGENT_PORT=udp://172.18.64.21:5775: strconv.ParseInt: parsing "udp://172.18.64.21:5775": invalid s
```
This option allows the disabling of the injected service environment variables.
Tested it out on my own installation.
> [grafana] Add `enableServiceLinks` Chart Option

- charts/loki/Chart.yaml
- charts/loki/templates/serviceaccount.yaml
- charts/loki/values.yaml
**What this PR does / why we need it:**
Allow for specifying the automountServiceAccountToken field on all Loki service accounts. Details about this toggle and what it's used for can be found [here](https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#use-the-default-service-account-to-access-the-api-server)
Also see corresponding PRs for loki-canary (#512) and loki-distributed (#513).
> [loki] Allow for specifying automountServiceAccountToken for Loki Helm Charts

- charts/loki-canary/Chart.yaml
- charts/loki-canary/README.md
- charts/loki-canary/templates/serviceaccount.yaml
- charts/loki-canary/values.yaml
What this PR does / why we need it:
Allow for specifying the automountServiceAccountToken field on the loki-canary service account. Related to #506
> [loki-canary] Allow for specifying automountServiceAccountToken for Loki Helm Charts

- .gitignore
- charts/enterprise-metrics/CHANGELOG.md
- charts/enterprise-metrics/Chart.yaml
- charts/enterprise-metrics/vendor/tanka-util
Symlinks break Rancher helm repository import.
Fixes #502 
Signed-off-by: Jack Baldry <jack.baldry@grafana.com>
> [enterprise-metrics] fix: Remove jsonnet-bundler symlink for tanka-util

- charts/grafana/Chart.yaml
- charts/grafana/templates/image-renderer-deployment.yaml
https://github.com/grafana/helm-charts/pull/34 added the ability to configure a remote image rendering service. Unfortunately, when trying to set `imageRenderer.securityContext` or `imageRenderer.hostAliases`, the indentation breaks when the configuration contains more than one element. 
For example (`values.yaml`):
```yaml
imageRenderer:
securityContext:
runAsGroup: 200
runAsUser: 100
```
results in:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
name: my-grafana-release-image-renderer
...
securityContext:
runAsGroup: 200
runAsUser: 100
...
```
This pull requests fixes the issue by setting the correct indentation.
> [grafana] Fix `imageRenderer.securityContext` indentation issue

- charts/grafana/Chart.yaml
- charts/grafana/values.yaml
Bump app and image to Grafana v8.0.5
https://github.com/grafana/grafana/releases/tag/v8.0.5
> [grafana] Bump Grafana to v8.0.5

- charts/tempo-distributed/Chart.yaml
- charts/tempo-distributed/README.md
- charts/tempo-distributed/templates/query-frontend/deployment-query-frontend.yaml
- charts/tempo-distributed/templates/query-frontend/service-query-frontend.yaml
- charts/tempo-distributed/values.yaml
This also add to fully arm64 compatibility, tempo-query is not needed  for grafana > 7.5
> [tempo-distributed] Add option to disable tempo-query sidecar

- charts/tempo/Chart.yaml
- charts/tempo/README.md
- charts/tempo/templates/statefulset.yaml
Respecting `affinity`, `nodeSelector` and `tolerations` parameters from `values.yaml` in the StatefulSet template.
Resolves #572
Signed-off-by: Stanislav Vitkovskiy <stas.vitkovsky@gmail.com>
> [tempo] Enabling affinity, nodeSelector and tolerations for tempo statefulset

- charts/grafana/Chart.yaml
- charts/grafana/README.md
- charts/grafana/templates/_pod.tpl
- charts/grafana/values.yaml
**Description of the change**
It disables the automounting of the service account token in the pod. Grafana does not need this by itself. This commit disables it by default, but leaves it configurable if anyone needs to use it.
**Benefits**
By disabling the automount, potential attackers cannot access the Kubernetes API on behalf/through the pod.
**Possible drawbacks**
In the unlikely event that anyone is using some sidecar or plugin to access the Kubernetes API, they will have to explicitly enable the mounting of the SA token in the values.
**Applicable issues**
If raising an issue is required or helpful, please tell me and I'd be glad to do so.
> [grafana] Optionally automount SA token

- charts/grafana/Chart.yaml
- charts/grafana/README.md
- charts/grafana/values.yaml
In #571 / b6015e2 an option was introduced to optionally automount the serviceaccount token. Due to an oversight at my part, I missed the fact that [a lot of people (including myself) use side cars for dashboards/datasource discovery from K8S configmaps](https://github.com/grafana/helm-charts/pull/571#issuecomment-882704321). So the default should be to **enable** the automount of the SA token, to keep these sidecars working.
> [grafana] Fix default for automounting of SA token

- charts/promtail/Chart.yaml
- charts/promtail/README.md
- charts/promtail/templates/daemonset.yaml
- charts/promtail/templates/networkpolicy.yaml
- charts/promtail/templates/role.yaml
- charts/promtail/templates/rolebinding.yaml
- charts/promtail/templates/secret.yaml
- charts/promtail/templates/service-extra.yaml
- charts/promtail/templates/service-metrics.yaml
- charts/promtail/templates/serviceaccount.yaml
- charts/promtail/templates/servicemonitor.yaml
Description of the change
This PR adds .Release.Namespace to objects meta for promtail chart. Related to discussion in this [issue](https://github.com/bitnami/charts/issues/2006).
Benefits
Ability to use the helm chart when having declarative definition of all cluster objects rendered using helm template.
Possible drawbacks
I don't see any, it will work as previously for helm install
Signed-off-by: Mariusz Waligóra <mariusz@piwik.pro>
> [promtail] Introduce .Release.Namespace in objects meta

- charts/tempo/Chart.yaml
- charts/tempo/README.md
- charts/tempo/values.yaml
In the Tempo values file it is mentioned that all ports and protocols that Tempo supports are enabled. However not all of them actually are enabled. I added opencensus, there are more like Zipkin that I could add but I haven't tested them personally. I did test Opencensus and that works.
> [tempo] Enabled the opencensus receive in the default Helm template for Tempo

- charts/grafana/Chart.yaml
- charts/grafana/README.md
- charts/grafana/values.yaml
Hi folks
The currently reference kiwigri/k8s-sidecar version 1.12.2 [contained some CVEs which were fixed in 1.12.3](https://github.com/kiwigrid/k8s-sidecar/issues/137) - this PR updates the reference to it.
This PR is very similar to https://github.com/grafana/helm-charts/pull/501, so I also bumped the grafana chart minor version.
> [grafana] bump kiwigrid/k8s-sidecar to v1.12.3, chart to 6.16.0

- charts/promtail/Chart.yaml
- charts/promtail/README.md
- charts/promtail/values.yaml
Hello grafana & loki community
I use `promtail` to scrape logs from my Kubernetes cluster which mainly used to run Spark Applications via [spark-operator](https://github.com/GoogleCloudPlatform/spark-on-k8s-operator).
So, it would be nice if loki logs stream have labels to distinguish between SparkApp. In this case is 2 lables bellow:
Up until now, the only way to do this is override the hold `scrapeConfigs` snippet, which show that is very complication.
So, with this PR, it's possible to end-users add `extraRelabelConfigs` only. For example in my case:
```yaml
config:
snippets:
extraRelabelConfigs:
- source_labels: [__meta_kubernetes_pod_label_spark_role]
target_label: spark_role
- source_labels: [__meta_kubernetes_pod_label_sparkoperator_k8s_io_app_name]
target_label: spark_app
```
And …
> [promtail] support extraRelabelConfigs in config.snippets

- charts/grafana/Chart.yaml
- charts/grafana/templates/_pod.tpl
https://github.com/grafana/helm-charts/blob/main/charts/grafana/templates/configmap.yaml#L30-L50 allows for multiple provider files to be specified, but only `datasources.yaml` `notifiers.yaml` and `dashboardproviders.yaml` were ever mounted.
Having the ability to specify several files is especially useful when using tiered values.yaml files (global, product, environment) that might want to add e.g. notifiers.
I consider this a bugfix rather than a feature as I couldn't find in the documentation that this was desired and specifying any other filenames than the ones mentioned above means they were ignored and when the ones mentioned above were missing this would lead to runtime errors.
The change is backward compatible (as long as you used the expected filenames there is no effective …
> [grafana] Enable multiple files in values.yaml for datasources / notifiers / dashboardProviders

- charts/grafana/Chart.yaml
- charts/grafana/templates/_pod.tpl
- charts/grafana/values.yaml
Adds `envFromSecrets`, allowing multiple secrets to provide environment variables, and for those secrets to be optionally loaded (instead of always required). This will enable scenarios such as optionally (and through a separate deployment) providing authentication provider settings.
Also fixes the case where `envFromSecret` and `envRenderSecret` were both defined, which would have only loaded one of them (since `envFrom` would have been defined twice).
Signed-off-by: Kyle Schouviller <kyschouv@microsoft.com>
> [grafana] Adding envFromSecrets to allow multiple optional secrets to provide environment variables

- charts/tempo/Chart.yaml
- charts/tempo/README.md
- charts/tempo/values.yaml
When you install the tempo Helm Chart, you get the following warnings:
```
coalesce.go:163: warning: skipped value for podAnnotations: Not a table.
coalesce.go:163: warning: skipped value for podAnnotations: Not a table.
coalesce.go:163: warning: skipped value for podAnnotations: Not a table.
```
This PR solves this by changing the podAnnotations from an empty list to an empty object.
> [tempo] Fix podAnnotations

- charts/enterprise-logs/CHANGELOG.md
- charts/enterprise-logs/Chart.yaml
- charts/enterprise-logs/templates/admin-api/deployment-admin-api.yaml
- charts/enterprise-logs/values.yaml
This PR contains PR #684 and therefore needs to be rebased after that is merged.
Fixes #687
> [enterprise-logs] Run GEL as non-root user `enterprise-logs`

- charts/grafana/Chart.yaml
- charts/grafana/values.yaml
Signed-off-by: Maarten De Wispelaere <maarten@bitprocessor.be>
The grafana chart isn't using the `appVersion` from the Chart.yaml as image tag. 
The previous 2 changes only changed the appVersion, not the `image.tag` in the values.yaml.
This commit fixes that.
> [grafana] Fix the image tag in the grafana chart

- charts/tempo-distributed/Chart.yaml
- charts/tempo-distributed/README.md
- charts/tempo-distributed/README.md.gotmpl
- charts/tempo-distributed/templates/NOTES.txt
- charts/tempo-distributed/templates/_helpers.tpl
- charts/tempo-distributed/templates/distributor/_helpers-distributor.tpl
- charts/tempo-distributed/templates/distributor/deployment-distributor.yaml
- charts/tempo-distributed/templates/distributor/service-distributor.yaml
- charts/tempo-distributed/templates/distributor/servicemonitor-distributor.yaml
- charts/tempo-distributed/templates/gateway/_helpers-gateway.tpl
- charts/tempo-distributed/templates/gateway/configmap-gateway.yaml
- charts/tempo-distributed/templates/gateway/deployment-gateway.yaml
- charts/tempo-distributed/templates/gateway/ingress-gateway.yaml
- charts/tempo-distributed/templates/gateway/secret-gateway.yaml
- charts/tempo-distributed/templates/gateway/service-gateway.yaml
- charts/tempo-distributed/values.yaml
Hello!
In my company we need to push jaeger traces to tempo, located in a different cluster, this is possible via gateway ingress.
I added gateway component which proxies API requests to appropriate tempo components. The configuration is pretty much the same as in loki-distributed gateway component. The changes are backwards compatible, gateway is disabled by default.
I also found an issue that suggests adding ingress for tempo components https://github.com/grafana/helm-charts/issues/551.
Please have a look if it's fine.
Thank you for the great product!
> [tempo-distributed] Add gateway component to tempo-distributed

- charts/tempo/Chart.yaml
- charts/tempo/README.md
- charts/tempo/templates/statefulset.yaml
- charts/tempo/values.yaml
Hi there!
Just did a small fix concerning `podLabels` in the `tempo` chart. Before, when using `podLabels`, rendering the chart resulted in such output:
```
Error: YAML parse error on tempo/templates/statefulset.yaml: error converting YAML to JSON: yaml: line 24: mapping values are not allowed in this context
Use --debug flag to render out invalid YAML
```
I aligned the templating to the way it is done for annotations and also added an explicit `podLabels` default value in `values.yaml`.
Signed-off-by: Joshua Mühlfort <muehlfort@gonicus.de>
> [tempo] Fix podLabels

- charts/loki-distributed/Chart.yaml
- charts/loki-distributed/README.md
- charts/loki-distributed/templates/distributor/hpa.yaml
- charts/loki-distributed/templates/gateway/hpa.yaml
- charts/loki-distributed/templates/querier/hpa.yaml
- charts/loki-distributed/templates/query-frontend/hpa.yaml
What this PR does / why we need it:
Reorders the list in `spec.metrics` for all components' HPAs in order to circumvent issue kubernetes/kubernetes#74099. Without this change, GitOps style CD tools such as Argo will consider the HPAs permanently out of sync due to the following discrepancy:
> [loki-distributed] Switch metric list order in HPAs

- charts/tempo-distributed/Chart.yaml
- charts/tempo-distributed/README.md
- charts/tempo-distributed/templates/compactor/servicemonitor-compactor.yaml
- charts/tempo-distributed/templates/distributor/servicemonitor-distributor.yaml
- charts/tempo-distributed/templates/ingester/servicemonitor-ingester.yaml
- charts/tempo-distributed/templates/memcached/servicemonitor-memcached.yaml
- charts/tempo-distributed/templates/querier/servicemonitor-querier.yaml
- charts/tempo-distributed/templates/query-frontend/servicemonitor-jaeger-query.yaml
- charts/tempo-distributed/templates/query-frontend/servicemonitor-query-frontend.yaml
- charts/tempo-distributed/values.yaml
Similar to https://github.com/grafana/helm-charts/pull/452, this adds support for configuring a ServiceMonitor's relabelling behaviour. This is especially useful for anyone who uses Grafana's various mixins for dashboards, as these expect a job dimension that includes the namespace (see https://github.com/grafana/helm-charts/pull/452 for a sample `relabelings` config that achieves this).
This also needs to be done for the Promtail chart, but there is an existing open PR for this - https://github.com/grafana/helm-charts/pull/766.
> [tempo-distributed] Add relabeling configuration to ServiceMonitors

- charts/grafana/Chart.yaml
- charts/grafana/templates/_pod.tpl
- charts/grafana/values.yaml
This PR makes the watchMethod for the datasource sidecar configurable like the dashboard sidecar.
The current default behavior is kept.
> [grafana] make datasource sidecar watchMethod configurable

- charts/tempo/Chart.yaml
- charts/tempo/README.md
- charts/tempo/templates/statefulset.yaml
Fix `<toYaml>: wrong number of args for toYaml: want 1 got 2` error when setting affinity.
> [tempo] Fix affinity toYaml call

- charts/enterprise-logs/CHANGELOG.md
- charts/enterprise-logs/Chart.yaml
- charts/enterprise-logs/templates/_helpers.tpl
- charts/enterprise-logs/templates/admin-api/deployment-admin-api.yaml
- charts/enterprise-logs/templates/compactor/statefulset-compactor.yaml
- charts/enterprise-logs/templates/gateway/deployment-gateway.yaml
- charts/enterprise-logs/templates/tokengen/job-tokengen.yaml
- charts/enterprise-logs/values.yaml
Services where incorrectly configured when using the default MinIO configuration,
which pointed to `{{ .Release.Name }}-enterprise-logs-minio` instead of `{{ .Release.Name }}-minio`.
Signed-off-by: Christian Haudum <christian.haudum@gmail.com>
> [enterprise-logs] Fix dev cluster MinIO endpoints in default configuration.

- charts/tempo/Chart.yaml
- charts/tempo/README.md
- charts/tempo/templates/configmap-tempo.yaml
- charts/tempo/values.yaml
As described in issue [#487](https://github.com/grafana/helm-charts/issues/487) it would be nice to be able to provide some custom configuration to Tempo server in the single binary chart.
In order to solve that we can use a similar approach to what is already available for other Tempo sub components (like ingester) so a `.Values.tempo.server ` could be used to provide YAML configuration to the server.
Note: to make this change consistent the previous value `httpListenPort: 3100` is modified to be set as any other server configuration.
> [tempo] Allow custom configuration of Tempo server

- charts/agent-operator/Chart.yaml
- charts/agent-operator/README.md
- charts/agent-operator/templates/tests/test-grafanaagent.yaml
Because:
* Having a null `spec:` definition in the agent-operator MetricsInstance
used for test, causes the test to fail with the following error during
the apply of the manifest: 'The MetricsInstance "primary" is invalid:
spec: Invalid value: "null": spec in body must be of type object:
"null"'
This commit:
* Sets the value to an empty object `spec: {}` rather than null
Signed-off-by: Tommaso Sardelli <lacapannadelloziotom@gmail.com>
> [agent-operator] Fix agent-operator tests setting an empty MetricsInstance spec

- charts/agent-operator/Chart.yaml
- charts/agent-operator/README.md
- charts/agent-operator/templates/operator-deployment.yaml
`podAnnotations` was not indented enough, causing validation to fail when trying to deploy with `podAnnotations`.
Signed-off-by: Anders Østhus <anders.osthus@gmail.com>
> [agent-operator] Fix indentation on podAnnotations

- charts/enterprise-logs/CHANGELOG.md
- charts/enterprise-logs/Chart.yaml
- charts/enterprise-logs/templates/_helpers.tpl
Commit d75c89a164ff96f3a1b400ab59c0d2bac67896cf introduced a bug that caused an error when MinIO was disabled. It was caused by the `"enterprise-logs.minio"` template macro, which tried to sus the service port configuration even when `minio.enabled` was set to `false`.
---
This PR includes PR #832
> [enterprise-logs] Fix template rendering bug

- charts/grafana/Chart.yaml
- charts/grafana/README.md
- charts/grafana/templates/_pod.tpl
- charts/grafana/values.yaml
This PR add the possibility to specify the SCRIPT environment variable to allow a script to be executed after a dashboard configmap got reloaded.
Link to the k8s-sidecar environment variable list: https://github.com/kiwigrid/k8s-sidecar#configuration-environment-variables
> [grafana] Add SCRIPT environment variable to grafana dashboard sidecar container

- charts/grafana/Chart.yaml
- charts/grafana/README.md
- charts/grafana/templates/_pod.tpl
- charts/grafana/values.yaml
To allow sidecars to run in environments with strict policies, for example using:
```yaml
...
sidecar:
...
securityContext:
capabilities:
drop: [ALL]
runAsNonRoot: true
allowPrivilegeEscalation: false
readOnlyRootFilesystem: true
...
```
> [grafana] Configurable Security Context for sidecars

- charts/loki-distributed/Chart.yaml
- charts/loki-distributed/README.md
- charts/loki-distributed/templates/query-frontend/service-query-frontend.yaml
Fixes #801, albeit not necessarily the right way about it...
From a maintenance perspective it's fragile to just add a duplicate port like that, and from a BC perspective we can't necessarily just rename the old one either.
There's definitely something that needs to happen, but I'm not sure this is it, even though it does the trick.
> [loki-distributed] Add 'grpclb' port to query-frontend service

- charts/grafana/Chart.yaml
- charts/grafana/README.md
- charts/grafana/templates/headless-service.yaml
- charts/grafana/values.yaml
This PR adds the possibility to create a headless service for normal deployments and adds some documentation on how to setup a cluster for unfied alerting.
fixes #747
> [grafana] Alerting: add options and documentation to deploy a HA cluster

- charts/tempo/Chart.yaml
- charts/tempo/README.md
- charts/tempo/templates/configmap-tempo-query.yaml
`tempo.server.httpListenPort` was renamed `tempo.server.http_listen_port` in #822 .
This should also use `tempo.server.http_listen_port` in backend url in tempo-query config.
> [tempo] Fix server.http_listen_port in tempo-query backend config

- charts/enterprise-logs/CHANGELOG.md
- charts/enterprise-logs/Chart.lock
- charts/enterprise-logs/Chart.yaml
fixes the issue #853 
> in GEL:v1.2.0 , WAL is enabled by default and the default WAL path is wal that makes the app to create a folder wal in working directory (/ect/enterprise-logs/) that is read-only.
the latest version of loki-distributed defines correct path for the WAL.
> [enterprise-logs] bumped version of loki-distributed chart

- charts/enterprise-metrics/CHANGELOG.md
- charts/enterprise-metrics/Chart.yaml
- charts/enterprise-metrics/values.yaml
I think these limits shouldn't be set in this way, as they are likely to
come from copy-pasting the loki helm chart.
- `enforce_metric_name: false`: Is required for Loki, but not really helpful for Metrics.
- `reject_old_samples: true`/`reject_old_samples_max_age: 168h` are not relevant for TSDB storage engine, as the limiting factor is the TSDB storage engine for ingestion older samples, rathern than these defaults.
> [enterprise-metrics] Remove non-relevant default limits

- charts/grafana/Chart.yaml
- charts/grafana/values.yaml
Update to Grafana 8.3.1 due to [high severity security fix](https://grafana.com/blog/2021/12/07/grafana-8.3.1-8.2.7-8.1.8-and-8.0.7-released-with-high-severity-security-fix/?plcmt=footer)
> [grafana] Update to Grafana 8.3.1

- charts/grafana/Chart.yaml
- charts/grafana/templates/dashboards-json-configmap.yaml
I meet side effect when I pass `.Values.dashboards`, then however, sidecar will include these [ConfigMaps](https://github.com/grafana/helm-charts/blob/main/charts/grafana/templates/dashboards-json-configmap.yaml) into grafana's folder due to side dashboard label.
But these [ConfigMaps](https://github.com/grafana/helm-charts/blob/main/charts/grafana/templates/dashboards-json-configmap.yaml) has already been mounted as volumes (see below), so it's not necessary to tell sidecar includes these files 
https://github.com/grafana/helm-charts/blob/589022e7e2680f0f6dd99ae6c9d015755fef6e5d/charts/grafana/templates/_pod.tpl#L282-L292
Previous PR: https://github.com/grafana/helm-charts/pull/746
> [grafana] Remove sidecar dashboard label on configmap

- charts/grafana/Chart.yaml
- charts/grafana/values.yaml
[Grafana 8.3.2](https://grafana.com/blog/2021/12/10/grafana-8.3.2-and-7.5.12-released-with-moderate-severity-security-fix/) is released with moderate severity security fix and updated to image tag.
> [grafana] Update to Grafana 8.3.2

- charts/loki/Chart.yaml
- charts/loki/templates/_helpers.tpl
- charts/loki/templates/ingress.yaml
When I'm installing loki helm chart to Kubernetes 1.22+, I got the error:
```
Error: UPGRADE FAILED: unable to recognize "": no matches for kind "Ingress" in version "networking.k8s.io/v1beta1"
```
This is because `apiVersion: networking.k8s.io/v1beta1` [becomes deprecated in Kubernetes 1.22+](https://kubernetes.io/docs/reference/using-api/deprecation-guide/#ingress-v122), with replacing to stable `networking.k8s.io/v1`.
Also in `path` part of the template there are some changes needed.
P.S. `grafana` chart installs succesfully on k8s 1.22.4.
_And there are several warnings about compatibility with v1.25+:_
```
W1207 15:08:07.725807 1034065 warnings.go:70] policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
```
_I can fix them in next PR._
> [loki] Update loki ingress template to support kubernetes 1.22+

- charts/grafana/Chart.yaml
- charts/grafana/templates/_pod.tpl
Since grafana chart [v6.19.0](https://github.com/grafana/helm-charts/pull/887), deployment is failing with `Error: secret "prometheus-stack-grafana" not found` when admin user is disabled (with `GF_SECURITY_DISABLE_INITIAL_ADMIN_CREATION`) and sidecar.datasources is enabled.
> [grafana] fix: dont get admin credentials from secret if admin is not enabled

- charts/loki/Chart.yaml
- charts/loki/templates/_helpers.tpl
This is an addition to https://github.com/grafana/helm-charts/pull/879 to fix problem, mentioned here https://github.com/grafana/helm-charts/commit/2127b36b286e31480f49d49f4929afe616d093f0#r62024255
Actually "networking.k8s.io/v1" is supported from 1.20, not from 1.22
https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.20/#ingressclass-v1-networking-k8s-io
> [loki] Lower version for "networking.k8s.io/v1" to 1.20

- charts/loki/Chart.yaml
- charts/loki/templates/_helpers.tpl
The helper returns "networking.k8s.io/v1" and not networking.k8s.io/v1. This fails the if comparison and always generates the else part, which is not valid for the new api.
> [loki] Fix correct ingress for >= 1.20

- charts/enterprise-metrics/CHANGELOG.md
- charts/enterprise-metrics/Chart.yaml
- charts/enterprise-metrics/templates/ingester-statefulset.yaml
This is a request for feedback, I'm curious if others in the team agree that the pros outweigh the cons.
I think we should update the ingester `podManagementPolicy` to `Parallel`.
Pros:
* This is what we use in our own clusters
* It will help to recover clusters with a broken ingester ring faster, because to do so we'll then simply have to:
* Scale down Distributors to `0` (to cut off ingestion)
* Scale down Ingesters to `0`
* Drop Ingester ring
* Scale up Ingesters to final replica count. This will now be much faster because all Ingesters will replay their WALs concurrently as opposed to sequentially 
* Scale up Distributors to final replica count
* [According to the docs the `podManagementPolicy` is on relevant when scaling the SFS up/down, not when rolling out …
> [enterprise-metrics] update ingester podManagementPolicy to Parallel

- charts/enterprise-logs/CHANGELOG.md
- charts/enterprise-logs/Chart.yaml
- charts/enterprise-logs/templates/tokengen/job-tokengen.yaml
I'm no helm expert, but I found by setting the selector to explicitly `null`, and using the `checksum/config` annotation, it made it hard to do a helm upgrade of the enterprise logs chart. Since the tokengen is a job, `spec.selector` and `spec.template` are immutable, thus updates always fail when `selector` is trying to be set to `null`, and also fail whenever theres a change to config. I think in the case of the tokenjob it is expected you will have to delete it an recreate it to make changes.
> [enterprise-logs] remove fields that make it hard to do helm updates

- charts/tempo/Chart.yaml
- charts/tempo/README.md
- charts/tempo/templates/service.yaml
`values.yaml` configures `receivers.otlp.protocols.http` to `0.0.0.0:4318`.
The service should match that config.
> [tempo] fix tempo-oltp-http ports

- charts/promtail/Chart.yaml
- charts/promtail/README.md
- charts/promtail/templates/servicemonitor.yaml
- charts/promtail/values.yaml
Similar to #452
Adds a config option to allow controlling the relabelling behaviour. 
Signed-off-by: dahei <david.heinrich@cortado.com>
> [promtail] Add relabeling configuration to ServiceMonitor

- charts/loki-stack/requirements.yaml
When enabling `prometheus` in `loki-stack` it does not work in Kubernetes v1.22.3:
```
Error: UPGRADE FAILED: [unable to recognize "": no matches for kind "ClusterRole" in version "rbac.authorization.k8s.io/v1beta1", unable to recognize "": no matches for kind "ClusterRoleBinding" in version "rbac.authorization.k8s.io/v1beta1"]
```
This upgrades to the latest available version at this time.
Can you help me get this approved @mapno?
Ref: #821
> [loki-stack] Update Prometheus to work on K8S 1.22.3

- charts/grafana/Chart.yaml
- charts/grafana/README.md
This commit updates the Grafana Helm chart documentation.
In the section about the image renderer plugin, the reference was linking to
a broken documentation in another GitHub repository.
After inspecting the changes on the `grafana-image-render` repository,
I found out that the change below updated most of the documentation,
where the content of the `remote_rendering_using_docker.md` was
moved to the main `README.md` file.
Then, this fix points towards the new reference.
Here it is the commit that changed the documentation on the remote repo.
https://github.com/grafana/grafana-image-renderer/pull/277
> [grafana] Update README.md

- charts/enterprise-metrics/CHANGELOG.md
- charts/enterprise-metrics/Chart.yaml
- charts/enterprise-metrics/templates/alertmanager-dep.yaml
- charts/enterprise-metrics/templates/alertmanager-statefulset.yaml
Alertmanager writes /tmp to validate the configuration being uploaded.
Allow RW access to a /tmp directory. Not using memory backend volume as
most functions of GEM are memory limited.
> [enterprise-metrics] alertmanager: fix readonly /tmp dir

- charts/loki-distributed/Chart.yaml
- charts/loki-distributed/README.md
- charts/loki-distributed/templates/compactor/serviceaccount-compactor.yaml
Signed-off-by: Ankit Mehta <ankit.mehta@appian.com>
Similar to https://github.com/grafana/helm-charts/pull/538, fixing the service account for compactor so it can add the automountServiceAccountToken to the SA.
> [loki-distributed] Fix automountServiceAccountToken for compactor

- charts/loki-distributed/Chart.yaml
- charts/loki-distributed/README.md
- charts/loki-distributed/templates/querier/deployment-querier.yaml
Re: #808, 
This PR removes the `/var/loki` A.K.A `data`  volume mount from the querier deployment when the index-gateway is enabled.
> [loki-distributed] Remove /var/loki volume mount from querier deployment

- charts/enterprise-logs/CHANGELOG.md
- charts/enterprise-logs/Chart.yaml
- charts/enterprise-logs/templates/admin-api/deployment-admin-api.yaml
- charts/enterprise-logs/templates/compactor/statefulset-compactor.yaml
This PR contains multiple changes and fixes:
- [BUGFIX] Use correct subPath configuration for the compactor's storage mount.
- [BUGFIX] Fixed issue that prevented users from mouting extra persistent volumes for the compactor.
- [CHANGE] Configure `securityContext.fsGroup` value for Admin API pod based on the value `adminApi.securityContext.runAsGroup`.
This PR supersedes #915 
Signed-off-by: Christian Haudum <christian.haudum@gmail.com>
> [enterprise-logs] multiple fixes

- charts/agent-operator/Chart.yaml
- charts/agent-operator/README.md
- charts/agent-operator/templates/tests/test-grafanaagent.yaml
- charts/agent-operator/values.yaml
See https://github.com/grafana/agent/releases/tag/v0.22.0 for more info
Signed-off-by: hjet <hjet@users.noreply.github.com>
Keeping a log of manual changes so we can automate this in the future:
> [agent-operator] Bump agent-operator version to v0.22.0

- charts/enterprise-logs/Chart.yaml
- charts/enterprise-logs/templates/admin-api/deployment-admin-api.yaml
- charts/enterprise-logs/templates/admin-api/service-admin-api.yaml
- charts/enterprise-logs/templates/compactor/statefulset-compactor.yaml
- charts/enterprise-logs/templates/gateway/deployment-gateway.yaml
- charts/enterprise-logs/templates/gateway/service-gateway.yaml
- charts/enterprise-logs/templates/secret-config.yaml
- charts/enterprise-logs/values.yaml
This change brings the enterprise-logs chart in line with the loki-distributed chart in terms of how the config is handled. In the loki-distributed chart, the config is a string. This has the benefit of accepting the config exactly as the user provides it, without merging in other default values that are hard to keep up to date as the software changes. It has the downside of the config no longer being structured data, so we can't access nested properties like `server.http_listen_port`.
I considered exposing the http and grpc ports as top level configs, but they are hardcoded in multiple places in the loki-distributed chart, so I'd rather force that convention here as well to reduce the configuration surface area. I would be open to hardcoding `http_listen_port` to 80 as that's what's the …
> [enterprise-logs] Convert config value from structured data to a string

- charts/grafana/Chart.yaml
- charts/grafana/values.yaml
Commit f1c0555 bumped the appVersion without bumping the image.tag in values.yaml
This PR fixes the version skew.
> [grafana] fix: Sync image tag with appVersion

- charts/tempo/Chart.yaml
- charts/tempo/README.md
- charts/tempo/templates/configmap-tempo.yaml
- charts/tempo/values.yaml
authEnabled created the auth_enabled key in the config file.
This has been renamed a while ago in
https://github.com/grafana/tempo/pull/646, so update the helm chart
accordingly.
> [tempo] authEnabled -> multitenancyEnabled

- charts/loki-distributed/Chart.yaml
- charts/loki-distributed/README.md
- charts/loki-distributed/values.yaml
Hi!
This is the second time I'll try to merge this PR, sorry for the insistence, but I think it is a very useful way to configure the backend storage without needing to rewrite the whole config, I've been using a fork for a long time and if this was finally merged it would be great. Since my first PR, another one was made and accepted but never got merged (https://github.com/grafana/helm-charts/pull/521).
The helm chart of tempo-distributed already implements a similar approach.
I've added `schemaConfig ` and `storageConfig ` to allow us to configure different storages without needing to overwrite the whole config string that is used to create the config map.
The default behaviour is still using the same values:
```
loki:
schemaConfig:
configs:
- from: 2020-09-07
store: boltdb-shipper …
```
> [loki-distributed] allow configuring storage backend with chart values

- charts/grafana/Chart.yaml
- charts/grafana/values.yaml
Signed-off-by: Marlene Pereira <wear_mar@hotmail.com>
There are a number of high severity vulnerabilities items addressed in `1.14.3`.
Please refer to [kiwigrid/k8s-sidecar/issues/148](https://github.com/kiwigrid/k8s-sidecar/issues/148).
> [grafana] bump kiwigrdi/k8s-sidecar to 1.14.3

- charts/grafana/Chart.yaml
- charts/grafana/README.md
- charts/grafana/values.yaml
Signed-off-by: Marlene Pereira <wear_mar@hotmail.com>
Updating k8s-sidecar version to `1.15.1` as more CVEs are addressed in this version, [see](https://github.com/kiwigrid/k8s-sidecar/pull/151).
> [grafana] bump kiwigrdi/k8s-sidecar to 1.15.1

- charts/grafana/Chart.yaml
- charts/grafana/templates/_helpers.tpl
- charts/grafana/templates/hpa.yaml
Signed-off-by: Loïc Fouray <loic.fouray@orange.com>
Helm lists the recommended kubernetes labels from https://helm.sh/docs/chart_best_practices/labels/
Currently two labels are missing in Grafana Chart Helm :
app.kubernetes.io/component : it will be interesting to add this label
app.kubernetes.io/part-of : my opinion is that it is a label to add by the user
> [grafana] Add app.kubernetes.io/component label

- charts/promtail/Chart.yaml
- charts/promtail/README.md
- charts/promtail/templates/extra-manifests.yaml
- charts/promtail/values.yaml
Signed-off-by: Nick Fisher <nfisher1@its.jnj.com>
Adding the ability to add extra manifests to the deployment of the chart. This will allow for better integration with secrets add-ons such as https://github.com/external-secrets/kubernetes-external-secrets or https://github.com/kubernetes-sigs/secrets-store-csi-driver
This is essentially the same change as https://github.com/grafana/helm-charts/pull/928, but for promtail.
> [promtail] Add extra (dynamic) Manifests to chart

- index.yaml
Raised from this issue: https://github.com/grafana/helm-charts/issues/996
---
It seems that chart-releaser released 6.21.2 to the gh-pages branch in 5b6a15f, but then reverted that change while releasing tempo-distributed-0.15.1 in 49073c6.
This PR manually adds grafana-6.21.2 back to the chart repository.
> Restore grafana-6.21.2

- charts/tempo/Chart.yaml
- charts/tempo/README.md
- charts/tempo/templates/service.yaml
This PR make setting service annotations works correctly and fix indent on helm template.
When I set the following value in `values.yaml`, the annotations value is not set correctly. So, I renamed `.Values.annotations` to `.Values.service.annotations` and fixed some indent issue.
```
service:
type: ClusterIP
annotations:
networking.istio.io/exportTo: "."
```
This seems related to #740.
Thank you!
Signed-off-by: Takaaki Furukawa <takaaki.frkw@gmail.com>
> [tempo] Make setting service annotations works correctly and fix indent

- charts/loki-stack/Chart.yaml
- charts/loki-stack/requirements.yaml
- charts/loki-stack/values.yaml
Signed-off-by: Akram Weheba <akram.weheba@netscout.com>
Bumped Grafana minor version to 3. 
Addresses CVE-2021-43798 vulnerability in 8.1.6 and default new Grafana alerting.
> [loki-stack] Bumped grafana 8.1.6->8.3.4

- charts/tempo-distributed/Chart.yaml
- charts/tempo-distributed/README.md
Release: https://github.com/grafana/tempo/releases/tag/v1.3.1
Signed-off-by: Mario Rodriguez <mariorvinas@gmail.com>
> [tempo-distributed] Bump Tempo to v1.3.1

- charts/grafana/Chart.yaml
- charts/grafana/templates/servicemonitor.yaml
I ran into a problem with kube-prometheus-stack setting interval to "", which gets rendered as `null`
Signed-off-by: Brian Glogower <xbglowx@gmail.com>
> [grafana] Use `with` for serviceMonitor interval and scrapeTimeout

- charts/loki-stack/Chart.yaml
- charts/loki-stack/values.yaml
Resolve medium CVEs.
https://grafana.com/blog/2022/02/08/grafana-7.5.15-and-8.3.5-released-with-moderate-severity-security-fixes/
Signed-off-by: Thomas Kooi <t.j.kooi@avisi.nl>
> [loki-stack] bumped Grafana image from 8.3.4 -> 8.3.5 in loki-stack

- charts/grafana/Chart.yaml
- charts/grafana/values.yaml
Resolve medium CVEs.
https://grafana.com/blog/2022/02/08/grafana-7.5.15-and-8.3.5-released-with-moderate-severity-security-fixes/
Signed-off-by: Thomas Kooi <t.j.kooi@avisi.nl>
> [grafana] Bumped Grafana 8.3.4 -> 8.3.5

- charts/tempo/Chart.yaml
- charts/tempo/README.md
- charts/tempo/templates/service.yaml
Istio uses port name prefixes or `appProtocol` to determine the protocol.
Currently, the names have the protocol as a suffix, but using appProtocol felt like a smaller change.
Relates to https://github.com/grafana/helm-charts/issues/104.
> [tempo] specify grpc appProtocol for tempo service

- charts/enterprise-logs/CHANGELOG.md
- charts/enterprise-logs/Chart.yaml
- charts/enterprise-logs/values.yaml
Need to add the following under the ingester section of `config: |` of the values.yaml file for enterprise-logs chart. Right now this setting is only in the loki-distributed helm chart values.yaml file 
```
wal:
dir: /var/loki/wal
```
This results in the ingester pods crash looping with an error of readonly filesystem
> [enterprise-logs] Re-add WAL dir configuration lost in 2.0.0 update

- charts/grafana/Chart.yaml
- charts/grafana/templates/_pod.tpl
- charts/grafana/values.yaml
Brings back the datasource sidecar initContainer that was removed in https://github.com/grafana/helm-charts/commit/ee0914e19e680a6cde7a5a4e9bcb43f2bef9517a
```
POST request sent to http://localhost:3000/api/admin/provisioning/datasources/reload. Response: 401 Unauthorized {"message": "Unauthorized"}
```
Users not using Basic Auth need to set `datasources.skipReload` to `true` to avoid these 401s ([Admin API only works with basic auth](https://grafana.com/docs/grafana/latest/http_api/admin/#reload-provisioning-configurations)). However, this essentially disables automatic datasource reloading, and since the `initContainer` was also removed, grafana no longer loads any cm/secret-defined datasources (even those that may already exist) when it comes up. Restarting the pod manually fails to …
> [grafana] Add back datasource sidecar initContainer

- charts/grafana/Chart.yaml
- charts/grafana/values.yaml
Sorry, I've made a mistake in #1051: just bump the `appVersion` field in Chart.yaml, not tag in values.yaml. This PR corrects it.
> [grafana] deps: Bump grafana from 8.3.5 to 8.3.6, take 2

- charts/loki/Chart.yaml
- charts/loki/README.md
- charts/loki/values.yaml
The alerting url https://grafana.com/docs/loki/latest/alerting throws a 404.
I think the document now lies under https://grafana.com/docs/loki/latest/rules/
---
Signed-off-by: Toni Tauro <toni.tauro@adfinis.com>
> [loki] docs: alerting uri goes to 404 -> /rules/

- charts/loki-distributed/Chart.yaml
- charts/loki-distributed/README.md
- charts/loki-distributed/templates/compactor/deployment-compactor.yaml
- charts/loki-distributed/templates/distributor/deployment-distributor.yaml
- charts/loki-distributed/templates/gateway/deployment-gateway.yaml
- charts/loki-distributed/templates/index-gateway/statefulset-index-gateway.yaml
- charts/loki-distributed/templates/ingester/statefulset-ingester.yaml
- charts/loki-distributed/templates/memcached-chunks/statefulset-memcached-chunks.yaml
- charts/loki-distributed/templates/memcached-frontend/statefulset-memcached-frontend.yaml
- charts/loki-distributed/templates/memcached-index-queries/statefulset-memcached-index-queries.yaml
- charts/loki-distributed/templates/memcached-index-writes/statefulset-memcached-index-writes.yaml
- charts/loki-distributed/templates/querier/deployment-querier.yaml
- charts/loki-distributed/templates/querier/statefulset-querier.yaml
- charts/loki-distributed/templates/query-frontend/deployment-query-frontend.yaml
- charts/loki-distributed/templates/ruler/deployment-ruler.yaml
- charts/loki-distributed/templates/table-manager/deployment-table-manager.yaml
- charts/loki-distributed/values.yaml
Add global and per-component `podLabels` field to the `loki-distributed` chart.
> [loki-distributed] add global and per-component pod labels

- charts/tempo/Chart.yaml
- charts/tempo/README.md
- charts/tempo/templates/serviceaccount.yaml
The tempo Helm Chart can currently not be deployed in a namespace other than default, as the ServiceAccount is not deployed to the release namespace.
> [tempo] Deploy tempo ServiceAccount in release namespace

- charts/loki/Chart.yaml
- charts/loki/templates/prometheusrule.yaml
- charts/loki/values.yaml
Adds an additional prometheusRule template for adding custom Rules which can be used by alertmanager to alert us.
It makes sure prometheusRules are only deployed if serviceMonitor is enabled
---
Signed-off-by: Toni Tauro <toni.tauro@adfinis.com>
> [loki] feat: Add optional prometheusRule value/template

- charts/tempo-distributed/Chart.yaml
- charts/tempo-distributed/README.md
- charts/tempo-distributed/templates/compactor/deployment-compactor.yaml
- charts/tempo-distributed/templates/distributor/deployment-distributor.yaml
- charts/tempo-distributed/templates/ingester/statefulset-ingester.yaml
- charts/tempo-distributed/templates/querier/deployment-querier.yaml
- charts/tempo-distributed/templates/query-frontend/deployment-query-frontend.yaml
As title, `terminationGracePeriodSeconds` are missing in templates.
> [tempo-distributed] add terminationGracePeriodSeconds

- charts/tempo-distributed/Chart.yaml
- charts/tempo-distributed/README.md
- charts/tempo-distributed/templates/podsecuritypolicy.yaml
- charts/tempo-distributed/templates/role.yaml
- charts/tempo-distributed/templates/rolebinding.yaml
- charts/tempo-distributed/values.yaml
Add possibility to enable RBAC features and create a PodSecurityPolicy.
Used the [Loki helm chart](https://github.com/grafana/helm-charts/tree/main/charts/loki) as template for the manifests and `values.yaml`.
Yes, [Pod Security Policies](https://kubernetes.io/docs/concepts/policy/pod-security-policy/) are deprecated since Kubernetes v1.21 and will be removed with v1.25, but until then they are in use nonetheless. That's why I think this PR will be a useful addition.
> [tempo-distributed] Add possibility to enable RBAC and PodSecurityPolicy

- charts/grafana/Chart.yaml
- charts/grafana/templates/secret.yaml
closes https://github.com/grafana/helm-charts/issues/817
thanks @TomyLobo for flagging
The secret can be in charge of both, either or none of admin credentials and ldap config.
If either ldap config or admin credential provisioning is applicable the secret is created, the content of the secret will vary depending on if admin credentials and/or ldap config require existence there
if neither ldap nor admin user are needed, the secret is not created
> [grafana] don't break ldap if admin is disabled

- charts/loki-distributed/Chart.yaml
- charts/loki-distributed/README.md
- charts/loki-distributed/templates/ruler/_helpers-ruler.tpl
ConfigMap names cannot be upper case. So for example `Example-Tenant` does not work in ruler configuration:
```
ruler:
directories:
Example-Tenant:
rules1.txt: |
...
```
... as the name is used in the ConfigMap name. 
This change will impact only the name of the configmap (e.g. `loki-ruler-rules-example-tenant`), the directory in filesystem be written as it should (e.g. `/etc/loki/rules/Example-Tenant`).
> [loki-distributed] loki.rulerRulesDirName should be lower case

- charts/tempo-distributed/Chart.yaml
- charts/tempo-distributed/README.md
- charts/tempo-distributed/templates/query-frontend/service-query-frontend-discovery.yaml
- charts/tempo-distributed/values.yaml
The default behavior of a headless service is to get the IP addresses of the pods backing the service. This behavior causes issue when adding annotations such as **external-dns** to expose the `query-frontend-service` . 
Adding a separate annotations for `query-frontend-discovery` will solve this issue.
> [tempo-distributed] Add annotation for query-frontend-discovery

- charts/loki-distributed/Chart.yaml
- charts/loki-distributed/README.md
- charts/loki-distributed/templates/ruler/statefulset-ruler.yaml
- charts/loki-distributed/values.yaml
Useful if using recording rules and need to scale ruler as recommended by https://grafana.com/docs/loki/latest/operations/recording-rules/#kubernetes
Inspired by the configuration of `ingester`.
Should fix https://github.com/grafana/helm-charts/issues/849
Let me know if I miss something :)
> [loki-distributed] Allow to configure ruler as statefulset

- charts/agent-operator/Chart.yaml
- charts/agent-operator/README.md
- charts/agent-operator/templates/operator-deployment.yaml
imagePullSecrets are defined on Pod spec level, not on the individual Pod containers level https://kubernetes.io/docs/concepts/containers/images/#referring-to-an-imagepullsecrets-on-a-pod
> [agent-operator] Fix image pull secrets templating

- charts/loki-distributed/Chart.yaml
- charts/loki-distributed/README.md
As 0.46.1 is not available and the github action is not redeploying it, bumping
the version to 0.46.2 to fix it.
> [loki-distributed] Bump to 0.46.2 to redeploy chart

- charts/enterprise-logs/values.yaml
Change the values.yaml file, so one can choose pspEnabled for K8s that use PodSecurityPolicy (i.e. AKS, EKS, and GKE) when pspEnbabled set to 'true'. For OpenShift, which doesn't support / use PodSecurityPolicy, but instead uses SecurityContextContraints we can just set pspEnabled to 'false' and sccEnabled to 'true' and have the role, rolebinding and serviceAccount use the proper one (i.e. PSP or SCC).
> [enterprise-logs] Update values.yaml

- charts/loki-distributed/templates/role.yaml
This adds support for OpenShift by defining the SCC policies required. This goes along with the values.yaml change for rbac.sccEnabled  and the rolebinding.yaml changes as well as the new file securitycontextconstraints.yaml
> [loki-distributed] Update role.yaml

- charts/loki-distributed/templates/rolebinding.yaml
This adds support for OpenShift by defining the SCC policies required. This goes along with the values.yaml change for rbac.sccEnabled  and the role.yaml changes (PR https://github.com/grafana/helm-charts/pull/1078) as well as the new file securitycontextconstraints.yaml file
> [loki-distributed] Update rolebinding.yaml

- charts/enterprise-metrics/CHANGELOG.md
- charts/enterprise-metrics/Chart.yaml
- charts/enterprise-metrics/values.yaml
This PR updates the helm chart to deploy GEM 1.7.0, the latest release.
> [enterprise-metrics] Update enterprise-metrics to 1.7.0

- charts/loki-distributed/Chart.yaml
- charts/loki-distributed/README.md
we have already merged [the PR with a new version](https://github.com/grafana/helm-charts/pull/1085)  but release action was not run. So, I bumped it again to re-run the action
> [loki-distributed] bumped version of helm chart to re-run release action

- charts/tempo-distributed/Chart.yaml
- charts/tempo-distributed/README.md
- charts/tempo-distributed/templates/compactor/deployment-compactor.yaml
- charts/tempo-distributed/templates/distributor/deployment-distributor.yaml
- charts/tempo-distributed/templates/gateway/deployment-gateway.yaml
- charts/tempo-distributed/templates/ingester/statefulset-ingester.yaml
- charts/tempo-distributed/templates/memcached/statefulset-memcached.yaml
- charts/tempo-distributed/templates/querier/deployment-querier.yaml
- charts/tempo-distributed/templates/query-frontend/deployment-query-frontend.yaml
- charts/tempo-distributed/values.yaml
Add global configuration for pod annotations
Follow similar way done on `loki-distributed`.
> [tempo-distributed] Add global configuration for pod annotations

- charts/loki-simple-scalable/Chart.yaml
- charts/loki-simple-scalable/README.md
- charts/loki-simple-scalable/templates/configmap.yaml
- charts/loki-simple-scalable/templates/write/statefulset-write.yaml
- charts/loki-simple-scalable/values.yaml
This makes configuration across loki helm charts more consistent.
> [loki-simple-scalable] bring config in line with loki-distributed by accepting string or structured config

- charts/promtail/Chart.yaml
- charts/promtail/README.md
- charts/promtail/values.yaml
This makes it easier to support multiple client configs in the promtail helm chart. The provided lokiAddress is used for the first client config, but I've changed is from `client:` with a single config to `clients:` to support multiple, with the rest being optionally provided as an array of client configs in the `extraClientConfigs` section.
> [promtail] make extra client configs an array of configs

- charts/loki-distributed/Chart.yaml
- charts/loki-distributed/README.md
- charts/loki-distributed/templates/index-gateway/service-index-gateway-headless.yaml
- charts/loki-distributed/templates/index-gateway/servicemonitor-index-gateway.yaml
- charts/loki-distributed/templates/ingester/service-ingester-headless.yaml
- charts/loki-distributed/templates/ingester/servicemonitor-ingester.yaml
- charts/loki-distributed/templates/querier/service-querier-headless.yaml
- charts/loki-distributed/templates/querier/servicemonitor-querier.yaml
This PR fixes the metric duplication caused by having an additional headless service for some of the Loki components by adding a label to the headless service to disable the `ServiceMonitor` using it to discover targets.
Closes #597.
> [loki-distributed] Fix metric duplication

- charts/loki-distributed/Chart.yaml
- charts/loki-distributed/README.md
- charts/loki-distributed/values.yaml
In previous versions, when using `index_gateway_client`, it was not inserted in the correct position.
This PR will set it correctly when `indexGateway.enabled: true`.
If `indexGateway.enabled: true` is set:
```yaml
storage_config:
boltdb_shipper:
active_index_directory: /var/loki/index
cache_location: /var/loki/cache
cache_ttl: 168h
index_gateway_client:
server_address: dns:///loki-distriburted-loki-distributed-index-gateway:9095
shared_store: filesystem
filesystem:
directory: /var/loki/chunks
```
If `indexGateway.enabled: true` is NOT set:
```yaml
storage_config:
boltdb_shipper:
active_index_directory: /var/loki/index
cache_location: /var/loki/cache
cache_ttl: 168h
shared_store: filesystem
filesystem:
directory: /var/loki/chunks
```
- fixes #1003 
- [community …
> [loki-distributed] Insert index_gateway_client into the correct position

- charts/grafana/Chart.yaml
- charts/grafana/README.md
- charts/grafana/templates/_pod.tpl
- charts/grafana/values.yaml
Add support for template directives at initContainers and envFrom.
Allows to use values for generation of e.g. secret names which is especially handy if chart is used within umbrella chart.
sample `values.yaml`:
```yaml
extraInitContainers:
- name: create-postgresql-db
image: bitnami/postgresql:latest
command: ["createdb"]
args: [ "mydb" ]
env:
- name: PGPASSWORD
valueFrom:
secretKeyRef:
name: '{{ include "grafana.fullname" . }}-env-secret'
key: GF_DATABASE_PASSWORD
envValueFrom:
ENV_NAME:
configMapKeyRef:
name: '{{ include "grafana.fullname" . }}-env'
key: value_key
envFromConfigMaps:
- name: '{{ include "grafana.fullname" . }}-env'
optional: true
```
Signed-off-by: Christian Lumper <c.lumper@tributech.io>
> [grafana] tpl support

- charts/loki-distributed/Chart.yaml
- charts/loki-distributed/README.md
- charts/loki-distributed/templates/ingester/deployment-ingester.yaml
All other components already have the correct container name.
Signed-off-by: Jack Baldry <jack.baldry@grafana.com>
> [loki-distributed] Ensure ingester container name matches the component name

- charts/loki-distributed/Chart.yaml
- charts/loki-distributed/README.md
- charts/loki-distributed/README.md.gotmpl
using the example documentation for s3 results in failure to parse the yaml config. this pr updates the example with the correct fields.
ref this output from the loki components when using the example config:
```
failed parsing config: /etc/loki/config/config.yaml: yaml: unmarshal errors:
line 2: field boltdb_shipper not found in type loki.ConfigWrapper
```
and then also
```
failed parsing config: /etc/loki/config/config.yaml: yaml: unmarshal errors:
line 81: field shared_storage not found in type shipper.Config
```
> [loki-distributed] fix: s3 example documentation in README.md

- charts/loki-distributed/Chart.yaml
- charts/loki-distributed/README.md
- charts/loki-distributed/templates/compactor/servicemonitor-compactor.yaml
- charts/loki-distributed/templates/distributor/servicemonitor-distributor.yaml
- charts/loki-distributed/templates/index-gateway/servicemonitor-index-gateway.yaml
- charts/loki-distributed/templates/ingester/servicemonitor-ingester.yaml
- charts/loki-distributed/templates/memcached-chunks/servicemonitor-memcached-chunks.yaml
- charts/loki-distributed/templates/memcached-frontend/servicemonitor-memcached-frontend.yaml
- charts/loki-distributed/templates/memcached-index-queries/servicemonitor-memcached-index-queries.yaml
- charts/loki-distributed/templates/memcached-index-writes/servicemonitor-memcached-index-writes.yaml
- charts/loki-distributed/templates/querier/servicemonitor-querier.yaml
- charts/loki-distributed/templates/query-frontend/servicemonitor-query-frontend.yaml
- charts/loki-distributed/templates/ruler/servicemonitor-ruler.yaml
- charts/loki-distributed/templates/table-manager/servicemonitor-table-manager.yaml
- charts/loki-distributed/values.yaml
Add possibility to define `metricRelabelings` for `ServiceMonitor` CRDs as described in the [specification](https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api.md#endpoint).
> [loki-distributed] Add metricRelabelings to ServiceMonitors

- charts/mimir-distributed/Chart.yaml
- charts/mimir-distributed/README.md
- charts/mimir-distributed/capped-large.yaml
- charts/mimir-distributed/capped-small.yaml
Removes wrong, redundant config snippet and adds affinity rules - should be the same as small and large yaml.
> [mimir-distributed] fix prod values capped-small and capped-large

- charts/mimir-distributed/Chart.yaml
- charts/mimir-distributed/README.md
- charts/mimir-distributed/values.yaml
* `/distributor`
* `/alertmanager`
* `/multitenant_alertmanager`
* `/api/v1/rules`
* `/prometheus/rules`
* `/prometheus/config/v1/rules`
are all prefixes to endpoints, so the nginx proxy rules need to reflect that
This was the source of this bug report https://grafana.slack.com/archives/C039863E8P7/p1649793055645919
> [mimir-distributed] naginx regex location blocks

- charts/loki-stack/Chart.yaml
- charts/loki-stack/templates/datasources.yaml
- charts/loki-stack/values.yaml
This PR relates to https://github.com/grafana/helm-charts/pull/966
Query limit is changed via max_entries_limit https://grafana.com/docs/loki/latest/configuration/#limits_config which default value is 5000 but not affecting here when using Dashboard sidecar as the datasource is limited by default to 1000.
This PR allows to override both values and setting default Loki and Loki Datasource default, lowest of them will apply when using sidecar.
> [loki-stack] max_entries_limit_per_query to it's current value

- charts/tempo-distributed/Chart.yaml
- charts/tempo-distributed/README.md
- charts/tempo-distributed/templates/memcached/statefulset-memcached.yaml
- charts/tempo-distributed/templates/querier/deployment-querier.yaml
- charts/tempo-distributed/templates/querier/service-querier.yaml
Hey folks. It's my first contribution. I hope I followed all the contribution guidelines.
Annotations seem to have been incorrectly rendering the templates
**statefulset-memcached.yaml**
```
Error: YAML parse error on tempo-distributed/charts/tempo-distributed/templates/memcached/statefulset-memcached.yaml: error converting YAML to JSON: yaml: line 14: did not find expected key
helm.go:84: [debug] error converting YAML to JSON: yaml: line 14: did not find expected key
```
```yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
name: tempo-tempo-distributed-memcached
namespace: default
labels:
helm.sh/chart: tempo-distributed-0.16.9
app.kubernetes.io/name: tempo-distributed
app.kubernetes.io/instance: tempo
app.kubernetes.io/version: "1.3.2" …
```
> [tempo-distributed] fix: indentation of annotations

- .github/workflows/linter.yml
- .helmdocsignore
- charts/mimir-distributed/CHANGELOG.md
- charts/mimir-distributed/Chart.yaml
- charts/mimir-distributed/README.md
Start updating charts for helm-docs 1.8.1. We can only update and release one chart at a time , so put ones that fail linting on helmdocsignore for now.
Old version renders chart dependencies differently:
old: | https://helm.min.io/ | minio | 8.0.10 |
new: | https://helm.min.io/ | minio(minio) | 8.0.10 |
Old version missing chart alias.
> [mimir-distributed] Bump helm-docs version to not force contributors on older vesion

- charts/loki-stack/Chart.yaml
- charts/loki-stack/requirements.yaml
- charts/loki-stack/values.yaml
This PR bumps the Promtail version in the `loki-stack` chart to 2.4.2.
> [loki-stack] Bump chart versions of all dependencies of Loki-stack chart

- charts/grafana/Chart.yaml
- charts/grafana/templates/tests/test.yaml
The existing Grafana helm test doesn't cleanup the test pod after success. This causes pods to linger around the cluster. This change adds the necessary annotation to delete the test pod after success. See the official helm [documentation](https://helm.sh/docs/topics/charts_hooks/#hook-deletion-policies) for more information.
> [grafana] Cleanup helm test pod after success

- charts/mimir-distributed/CHANGELOG.md
- charts/mimir-distributed/Chart.yaml
- charts/mimir-distributed/README.md
- charts/mimir-distributed/templates/nginx/ingress.yaml
Fixes the TPL crash currently preventing deploying the Chart with activated ingress object. 
Seems to be introduced with https://github.com/grafana/helm-charts/pull/1203
Signed-off-by: secustor <sebastian@poxhofer.at>
> [mimir-distributed] nginx gateway ingress use new component naming

- charts/loki-distributed/Chart.yaml
- charts/loki-distributed/README.md
- charts/loki-distributed/values.yaml
This PR add proxy rules to the gateway to allow connections to the Prometheus API endpoints of Loki. 
Source of the solution: https://github.com/grafana/loki/issues/5203#issuecomment-1050691943
Signed-off-by: secustor <sebastian@poxhofer.at>
> [loki-distributed] proxy api calls to the PromAPI

- .helmdocsignore
- charts/agent-operator/Chart.yaml
- charts/agent-operator/README.md
- charts/agent-operator/values.yaml
Use latest helm-docs 1.8.1 for README.md generation in agent-operator
> [agent-operator] Bump helm-docs use in agent-operator to 1.8.1

- charts/loki/Chart.yaml
- charts/loki/values.yaml
This PR relates to https://github.com/grafana/helm-charts/pull/966
Query limit is changed via max_entries_limit https://grafana.com/docs/loki/latest/configuration/#limits_config which default value is 5000 but not affecting here when using Dashboard sidecar as the datasource is limited by default to 1000.
This PR allows to override both values and setting default Loki and Loki Datasource default, lowest of them will apply when using sidecar.
Signed-off-by: Guillermo Caracuel <guillermo.caracuel@predictiva.io>
> [loki] max_entries_limit_per_query to it's default value

- charts/mimir-distributed/CHANGELOG.md
- charts/mimir-distributed/Chart.yaml
- charts/mimir-distributed/README.md
- charts/mimir-distributed/gem.yaml
- charts/mimir-distributed/templates/gateway/_helpers.tpl
- charts/mimir-distributed/templates/gateway/gateway-ingress.yaml
- charts/mimir-distributed/values.yaml
The GEM gateway does not come with an option to create an ingress resource. On the other hand, the nginx component comes with this option.
The config and templates were copied almost verbatim from the nginx ingress.
> [mimir-distributed] Add ingress to GEM gateway

- charts/mimir-distributed/CHANGELOG.md
- charts/mimir-distributed/Chart.yaml
- charts/mimir-distributed/README.md
- charts/mimir-distributed/templates/gateway/gateway-svc.yaml
- charts/mimir-distributed/values.yaml
The non-enterprise version of the chart has an nginx working as a
reverse proxy. That can have the exposed service port overridden in the
values.yaml. The enterprise equivalent does not allow this.
This PR changes the enterprise gateway to allow custom exposed ports.
> [mimir-distributed] Make GEM gateway svc port configurable

- charts/rollout-operator/Chart.yaml
- charts/rollout-operator/README.md
- charts/rollout-operator/templates/_helpers.tpl
- charts/rollout-operator/templates/deployment.yaml
Recalculate the chart name
Commonly the chart would be used as a subchart under the
alias rollout_operator. Making it possible to use
.Values.rollout_operator:  But that results in a Chart name that
is not a valid kubernetes resource name. Sanitize the chart name
and turn _ back into -.
Also use hardcoded fix name for container for dashboards.
> [rollout-operator] rollout op fix subchartname

- charts/grafana/Chart.yaml
Bumping Grafana Helm Chart to version `8.5.0`
> [grafana] bump chart to latest grafana version

- charts/rollout-operator/Chart.yaml
- charts/rollout-operator/README.md
There was a github outage when 0.1.1 was released. Everything is in place
except the repo is not actually updated. See helm search repo.
> [rollout-operator] Bump version to sync helm repo index

- charts/grafana/Chart.yaml
- charts/grafana/templates/_pod.tpl
- charts/grafana/values.yaml
Adding optional liveness and readiness probes to the k8s-sidecar. This is needed for deploying into environments that require the use of liveness/readiness probes for all running containers. If the probe configuration is passed, it is added to each sidecar that is enabled.
Example:
```yaml
sidecar:
livenessProbe:
exec:
command:
- /bin/true
readinessProbe:
exec:
command:
- /bin/true
```
> [grafana] add liveness and readiness probes to sidecars

- charts/mimir-distributed/CHANGELOG.md
- charts/mimir-distributed/Chart.yaml
- charts/mimir-distributed/README.md
- charts/mimir-distributed/templates/overrides-exporter/overrides-exporter-dep.yaml
- charts/mimir-distributed/templates/overrides-exporter/overrides-exporter-pdb.yaml
- charts/mimir-distributed/templates/overrides-exporter/overrides-exporter-svc.yaml
- charts/mimir-distributed/templates/ruler/ruler-dep.yaml
- charts/mimir-distributed/templates/ruler/ruler-pdb.yaml
- charts/mimir-distributed/templates/ruler/ruler-servmon.yaml
- charts/mimir-distributed/templates/ruler/ruler-svc.yaml
- charts/mimir-distributed/values.yaml
Signed-off-by: Miguel Ángel Ortuño <ortuman@gmail.com>
Turn `ruler` and `override-exporter` into optional components.
> [mimir-distributed] make ruler and override-exporter optional components

- charts/mimir-distributed/CHANGELOG.md
- charts/mimir-distributed/Chart.yaml
- charts/mimir-distributed/README.md
- charts/mimir-distributed/templates/admin-api/admin-api-dep.yaml
- charts/mimir-distributed/templates/alertmanager/alertmanager-dep.yaml
- charts/mimir-distributed/templates/alertmanager/alertmanager-statefulset.yaml
- charts/mimir-distributed/templates/compactor/compactor-statefulset.yaml
- charts/mimir-distributed/templates/distributor/distributor-dep.yaml
- charts/mimir-distributed/templates/ingester/ingester-statefulset.yaml
- charts/mimir-distributed/templates/querier/querier-dep.yaml
- charts/mimir-distributed/templates/ruler/ruler-dep.yaml
- charts/mimir-distributed/templates/store-gateway/store-gateway-statefulset.yaml
Signed-off-by: Miguel Ángel Ortuño <ortuman@gmail.com>
Add memberlist container named port to all components that depend on it.
> [mimir-distributed] add named port memberlist to pod container

- charts/mimir-distributed/CHANGELOG.md
- charts/mimir-distributed/Chart.yaml
- charts/mimir-distributed/README.md
- charts/mimir-distributed/templates/podsecuritypolicy.yaml
- charts/mimir-distributed/templates/role.yaml
- charts/mimir-distributed/templates/rolebinding.yaml
- charts/mimir-distributed/values.yaml
Signed-off-by: Miguel Ángel Ortuño <ortuman@gmail.com>
~~This PR merges `rbac.create` and `rbac.pspEnabled` options into a single `rbacEnabled` flag.~~
Removed `rbac.create` option.
fixes: #1300
> [mimir-distributed] remove rbac.create option

- charts/tempo-distributed/Chart.yaml
- charts/tempo-distributed/values.yaml
In the values, ingester.config.max_block_bytes was exposed but it was ingester.config.maxBlockBytes that was used in the configmap. Same goes for max_block_duration and complete_block_timeout.
> [tempo-distributed] Fix ingester values

- charts/loki-simple-scalable/Chart.lock
- charts/loki-simple-scalable/Chart.yaml
- charts/loki-simple-scalable/ci/default-values.yaml
- charts/loki-simple-scalable/ci/enterprise.yaml
- charts/loki-simple-scalable/ci/ingress-values.yaml
- charts/loki-simple-scalable/ci/persistence-values.yaml
- charts/loki-simple-scalable/templates/_helpers.tpl
- charts/loki-simple-scalable/templates/gateway/_helpers-gateway.tpl
- charts/loki-simple-scalable/templates/gateway/configmap-gateway.yaml
- charts/loki-simple-scalable/templates/gateway/deployment-gateway.yaml
- charts/loki-simple-scalable/templates/read/_helpers-read.tpl
- charts/loki-simple-scalable/templates/read/statefulset-read.yaml
- charts/loki-simple-scalable/templates/secret-license.yaml
- charts/loki-simple-scalable/templates/tokengen/_helpers.yaml
- charts/loki-simple-scalable/templates/tokengen/job-tokengen.yaml
- charts/loki-simple-scalable/templates/tokengen/role-tokengen.yaml
- charts/loki-simple-scalable/templates/tokengen/rolebinding-tokengen.yaml
- charts/loki-simple-scalable/templates/tokengen/serviceaccount-tokengen.yaml
- charts/loki-simple-scalable/templates/write/_helpers-write.tpl
- charts/loki-simple-scalable/templates/write/statefulset-write.yaml
- charts/loki-simple-scalable/values.yaml
This PR combines `enterprise-logs-simple` and `loki-simple-scalable` with the goal of
1. Making it easier to maintain charts by having fewer to maintain
2. Making it easier to switch between OSS Loki and GEL by simply toggling a config option
Setting `enterprise.enabled = true` will change the following:
1. Use the `enterprise-logs` image instead of the `loki` image
2. Mount a license to the pods. A license can be added via the `enterprise.license` setting
3. Add additional routes to the gateway's nginx config to include Admin endpoints exposed by GEL
This is in line with the strategy we are following for Mimir chart as well (see #1203)
> [loki-simple-scalable] Make enterprise a configurable option

- charts/mimir-distributed/CHANGELOG.md
- charts/mimir-distributed/Chart.yaml
- charts/mimir-distributed/README.md
- charts/mimir-distributed/templates/alertmanager/alertmanager-servmon.yaml
- charts/mimir-distributed/templates/alertmanager/alertmanager-svc-headless.yaml
- charts/mimir-distributed/templates/ingester/ingester-servmon.yaml
- charts/mimir-distributed/templates/ingester/ingester-svc-headless.yaml
- charts/mimir-distributed/templates/query-frontend/query-frontend-servmon.yaml
- charts/mimir-distributed/templates/query-frontend/query-frontend-svc-headless.yaml
- charts/mimir-distributed/templates/store-gateway/store-gateway-servmon.yaml
- charts/mimir-distributed/templates/store-gateway/store-gateway-svc-headless.yaml
this was how i fixed https://github.com/grafana/helm-charts/issues/1307 in our setup
I'm open to other, more elegant solutions, or a rename of the service label to something else.
Because the mimir-jsonnet only has a headless service, I was tempted to remove the non-headless service from the helm chart, but decided against that.
> [mimir-distributed] exclude headless services from ServiceMonitors to prevent duplication of prometheus scrape targets

- charts/grafana/Chart.yaml
- charts/grafana/README.md
- charts/grafana/templates/_pod.tpl
- charts/grafana/templates/image-renderer-deployment.yaml
- charts/grafana/templates/serviceaccount.yaml
- charts/grafana/templates/tests/test.yaml
- charts/grafana/values.yaml
This PR adds more possibilities for injecting templated values in the Grafana chart, when used as a dependency. This follows previous PRs such as #1167.
This enabled templates in the following parameters:
* extraConfigmapMounts
* affinity
* imageRenderer.affinity
* admin.existingSecret
* persistence.subPath
* persistence.existingClaim
* image.pullSecrets
* imageRenderer.image.pullSecrets
* serviceAccount.annotations
> [grafana] Add more support for templates in values

- charts/agent-operator/Chart.yaml
- charts/agent-operator/README.md
- charts/agent-operator/templates/operator-clusterrole.yaml
Closes https://github.com/grafana/agent/issues/1660
I just added all /finalizers resources because I don't know which are required for all usecases. Feel free to reduce them but this configuration now works on OKD 4.10 / Kubernetes v1.23.3-2003+e419edff267ffa-dirty with a GrafanaAgent and MetricsInstance resource.
> [agent-operator] Fix Grafana Agent finalizers errors on OpenShift

- charts/grafana/Chart.yaml
- charts/grafana/templates/_pod.tpl
Fix a misuse of the default filter (arguments to a pipeline method are passed last, not first). Fixes https://github.com/grafana/helm-charts/commit/469f524243cdaf4b399041243cc2357f21a2e553#commitcomment-73188288
> [grafana] Fix use of default in existingClaim template

- charts/tempo-distributed/Chart.yaml
- charts/tempo-distributed/templates/compactor/poddisruptionbudget-compactor.yaml
- charts/tempo-distributed/templates/distributor/poddisruptionbudget-distributor.yaml
- charts/tempo-distributed/templates/gateway/poddisruptionbudget-gateway.yaml
- charts/tempo-distributed/templates/ingester/poddisruptionbudget-ingester.yaml
- charts/tempo-distributed/templates/memcached/_helpers-memcached.tpl
- charts/tempo-distributed/templates/memcached/poddisruptionbudget-memcached.yaml
- charts/tempo-distributed/templates/memcached/service-memcached.yaml
- charts/tempo-distributed/templates/memcached/servicemonitor-memcached.yaml
- charts/tempo-distributed/templates/memcached/statefulset-memcached.yaml
- charts/tempo-distributed/templates/querier/poddisruptionbudget-querier.yaml
- charts/tempo-distributed/templates/query-frontend/poddisruptionbudget-query-frontend.yaml
This adds pdbs in the same manner that the loki-distributed chart does.
I've added a pdb for each resource but some could be considered up for debate - i.e. to my knowledge having 0 replicas available of memcached or queryFrontend would not cause downtime, but 0 of ingester or distributor would cause big issues.
This addresses https://github.com/grafana/helm-charts/issues/1364
Signed-off-by: AlexDHoffer <alexdchoffer@gmail.com>
> [tempo-distributed] Add pdb if resource has > 1 replicas

- charts/grafana/Chart.yaml
- charts/grafana/values.yaml
Small update to default to latest grafana version in a helm chart.
> [grafana] bump version to 8.5.2

- charts/enterprise-logs/Chart.yaml
- charts/enterprise-logs/values.yaml
This allows overwriting a config options of the default config without loosing e.g. the schema configuration.
It is required by the AWS marketplace deployment: https://grafana.com/docs/enterprise-logs/latest/setup/aws-marketplace/
> [enterprise-logs] Support additional config

- charts/loki-simple-scalable/Chart.yaml
- charts/loki-simple-scalable/templates/_helpers.tpl
- charts/loki-simple-scalable/templates/configmap.yaml
- charts/loki-simple-scalable/templates/gateway/_helpers-gateway.tpl
- charts/loki-simple-scalable/templates/podsecuritypolicy.yaml
- charts/loki-simple-scalable/templates/prometheusrule.yaml
- charts/loki-simple-scalable/templates/read/_helpers-read.tpl
- charts/loki-simple-scalable/templates/read/service-read-headless.yaml
- charts/loki-simple-scalable/templates/read/service-read.yaml
- charts/loki-simple-scalable/templates/read/statefulset-read.yaml
- charts/loki-simple-scalable/templates/role.yaml
- charts/loki-simple-scalable/templates/rolebinding.yaml
- charts/loki-simple-scalable/templates/securitycontextconstraints.yaml
- charts/loki-simple-scalable/templates/service-memberlist.yaml
- charts/loki-simple-scalable/templates/tokengen/_helpers.yaml
- charts/loki-simple-scalable/templates/tokengen/job-tokengen.yaml
- charts/loki-simple-scalable/templates/tokengen/role-tokengen.yaml
- charts/loki-simple-scalable/templates/tokengen/rolebinding-tokengen.yaml
- charts/loki-simple-scalable/templates/tokengen/serviceaccount-tokengen.yaml
- charts/loki-simple-scalable/templates/write/_helpers-write.tpl
- charts/loki-simple-scalable/templates/write/service-write-headless.yaml
- charts/loki-simple-scalable/templates/write/service-write.yaml
- charts/loki-simple-scalable/templates/write/statefulset-write.yaml
- charts/loki-simple-scalable/values.yaml
This PR represent changes made to the helm chart to make it easier to run internally at Grafana Labs.
* In order to better support this helm chart, we are spinning up an
environment at Grafana Labs that uses it. In order to do so, a few
changes were necessary.
* Also includes a few ease of use changes like:
* less verbose names
* better automatic schema config based on storage type
* ability to add extra selector labels to pods of stateful sets
> [loki-simple-scalable] Match more closely Grafana Labs deployments

- charts/grafana/Chart.yaml
- charts/grafana/README.md
- charts/grafana/templates/_pod.tpl
- charts/grafana/values.yaml
There are many cases that PR or chart release only changed `appVersion` and left `image.tag` value (may not be the whole):
* chart 6.26.6 #1289
* fixed in chart 6.26.7 #1294
* (by me) chart 6.21.7 #1051
* fixed in chart 6.21.8 #1052
* chart 6.20.3 #907
* fixed in chart 6.20.6 #975
* chart 6.16.7 #692, chart 6.16.8 #694
* fixed in chart 6.16.9 #698
It seems first-comers can make mistakes easily, so I've changed the tag used by pod image definition defaults to chart `appVersion`.
Description based on: https://github.com/argoproj/argo-helm/blob/1492575ee07aebdbdc22ff4d16da7455fe3e1b1e/charts/argo-cd/values.yaml#L16
> [grafana] feat: Defaults image.tag to chart appVersion

- .github/workflows/check-codeowners.yaml
- .github/workflows/ci.yml
- .github/workflows/lint-test.yaml
- .github/workflows/linter.yml
This PR enables storing helm charts next to their product (like we do with jsonnet), but still allows to reuse common github actions for linting and testing. Out of scope: release (will be another PR).
> Make workflows in this repository reusable from other repositories

- .github/workflows/update-helm-repo.yaml
This workflow builds a chart in a source repository and releases it
to the helm-charts repository. It tags the source repository. It creates
a PR to update the helm repo index.yaml in the helm-charts repository.
Eventually we'd want the workflow to just commit the change to the index.yaml for helm without a PR - but let's test things e2e first.
**Note** this workflow is only triggered by other workflows, not by itself.
> Reusable workflow to release a chart from a different repository

- .github/workflows/update-helm-repo.yaml
Change detection didn't work on main branch because target (main) and HEAD
were the same.
Add detection of latest tag to compare to.
Also remove running change detection twice and place changed chart path
on output of the first job.
> Fix change detection in helm repo update action

- .github/workflows/update-helm-repo.yaml
Testing of the update via pull request is finished. Enable push to
the branch so no manual action is needed.
> Enable push to gh-pages automatically from chart releaser

- charts/grafana/Chart.yaml
- charts/grafana/templates/_helpers.tpl
- charts/grafana/templates/poddisruptionbudget.yaml
- charts/grafana/templates/podsecuritypolicy.yaml
PodDisruptionBudget apiVersion policy/v1beta1 is deprecated in v1.21+. and will be unavailable in the next Kubernetes version. Nothing else needs to be changed in the yaml specs
> [grafana] Upgrade PodDisruptionBudget apiVersion

- .github/workflows/lint-test.yaml
We'd like to release the Mimir chart periodically, not on every
PR. So version check won't be needed.
> Allow to skip the version check during linting

- charts/promtail/Chart.yaml
- charts/promtail/README.md
- charts/promtail/values.yaml
Current, we have `app` label that refer to k8s's `app.kubernetes.io/name` label or helm's `app` legacy label.
In the cases there are multiple deployments/releases in the same namespace, it's very helpful if there is `instance` label that used to distinguish among them.
> [promtail] add `instance` labels

- .github/workflows/update-helm-repo.yaml
Also added some informational logging to aid debugging in the future
This is necessary for Mimir since we are moving to a weekly release instead of releasing every commit. There are potentially many commits with "changed" charts despite the version in `Chart.yaml` being unchanged. For example, this run failed when I merged some changes to main: https://github.com/grafana/mimir/actions/runs/2450081153
Signed-off-by: Patrick Oyarzun <patrick.oyarzun@grafana.com>
> Skip chart release if tag already exists

- charts/tempo/Chart.yaml
- charts/tempo/README.md
- charts/tempo/templates/configmap-tempo-query.yaml
- charts/tempo/templates/service.yaml
- charts/tempo/templates/statefulset.yaml
- charts/tempo/values.yaml
This PR
- allows adding `securityContext` to
- pod `tempo`
- container `tempo`
- container `tempo-query`
- allows for removing the container `tempo-query` for two reasons
- not needed for Grafana 7.5+ as [Grafana 7.5.x and higher can query Tempo directly](https://grafana.com/docs/tempo/latest/configuration/querying/#grafana-75x-and-higher-easy-mode)
- container `tempo-query` fails with `securityContext.readOnlyRootFilesystem: true`
Maintainers: feel free to modify, reword comments/readme.md or remove parts.
> [tempo] add securityContext & enable removing tempoQuery container 

- charts/grafana/Chart.yaml
- charts/grafana/templates/configmap.yaml
There are configs that are not an object within grafana.ini e.g. force_migration=<bool>
This commit adds these configs. With this change this will be possible in values.yml: 
grafana.ini:
force_migration: true
> [grafana] add non object grafana.ini configs

- charts/loki-canary/Chart.yaml
- charts/loki-canary/README.md
- charts/loki-canary/templates/daemonset.yaml
- charts/loki-canary/values.yaml
We are using loki-canary charts and wanted to manage pods using some custom labels on pods. Loki-Canary doesn't provide fexibility yet to use custom podLabels on Daemonset loki-canary. Added .Values.podLabels that can be applied to loki-canary daemonset.
> [loki-canary] Adding flexibility to add pod labels to loki-canary daemon set

- charts/loki-distributed/Chart.yaml
- charts/loki-distributed/README.md
- charts/loki-distributed/templates/_helpers.tpl
- charts/loki-distributed/templates/distributor/poddisruptionbudget-distributor.yaml
- charts/loki-distributed/templates/gateway/poddisruptionbudget-gateway.yaml
- charts/loki-distributed/templates/index-gateway/poddisruptionbudget-index-gateway.yaml
- charts/loki-distributed/templates/ingester/poddisruptionbudget-ingester.yaml
- charts/loki-distributed/templates/memcached-chunks/poddisruptionbudget-memcached-chunks.yaml
- charts/loki-distributed/templates/memcached-frontend/poddisruptionbudget-memcached-frontend.yaml
- charts/loki-distributed/templates/memcached-index-queries/poddisruptionbudget-memcached-index-queries.yaml
- charts/loki-distributed/templates/memcached-index-writes/poddisruptionbudget-memcached-index-writes.yaml
- charts/loki-distributed/templates/querier/poddisruptionbudget-querier.yaml
- charts/loki-distributed/templates/query-frontend/poddisruptionbudget-query-frontent.yaml
- charts/loki-distributed/templates/ruler/poddisruptionbudget-ruler.yaml
The API version for PodDisruptionBudgets changed to `policy/v1` in Kubernetes v1.21.
> [loki-distributed] Use policy/v1 API for PodDisruptionBudgets in loki-distributed

- charts/agent-operator/Chart.yaml
- charts/agent-operator/README.md
- charts/agent-operator/templates/_helpers.tpl
- charts/agent-operator/templates/operator-clusterrole.yaml
- charts/agent-operator/templates/operator-clusterrolebinding.yaml
- charts/agent-operator/templates/operator-deployment.yaml
- charts/agent-operator/templates/operator-serviceaccount.yaml
- charts/agent-operator/values.yaml
**ENHANCEMENT**
In favour of using Kubernetes [recommended labels](https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/) to `agent-operator`:
- Label `app.kubernetes.io/component` has been moved from resources to common label template;
**BUG-FIX**
Manifest `operator-deployment.yaml` contained a bug where deployment template metadata labels, were using `ga-operator.selectorLabels` instead of `ga-operator.labels`.
**FEATURE**
In addition, **optional** custom user labels can now be added to `agent-operator` resources:
```yaml
...
customLabels: {}
...
```
**FEATURE**
Chart now supports adding extra arguments for the cli using `extraArgs`:
```yaml
...
extraArgs: []
...
```
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that …
> [agent-operator] Add: Kubernetes recommended labels, custom labels and extra args

- charts/grafana/Chart.yaml
- charts/grafana/README.md
- charts/grafana/values.yaml
There are quite a couple of severe vulnerabilities in the image currently used. This bumps the k8s-sidecar version to the latest release where these vulns are fixed.
> [grafana] bump kiwigrid/k8s-sidecar to 1.19.2

- charts/grafana/Chart.yaml
- charts/grafana/templates/servicemonitor.yaml
When namespaceOverride is set, the serviceMonitor does not work anymore without this fix.
Signed-off-by: Maurice Faber <morriz@idiotz.nl>
> [grafana] Update servicemonitor.yaml

- charts/grafana/Chart.yaml
- charts/grafana/README.md
- charts/grafana/templates/networkpolicy.yaml
- charts/grafana/values.yaml
Found a need for egress to be added to the Grafana network policy. In some cases, datasources outside the cluster or namespace will need an egress to be able to connect.
Adding egress to the network policy with the ability to specify ports addresses this issue.
Signed-off-by: Wilson, Jason M <jason.wilson2@marist.edu>
> [grafana] Add egress to network policy

- charts/promtail/Chart.yaml
- charts/promtail/README.md
- charts/promtail/templates/daemonset.yaml
- charts/promtail/values.yaml
⚠ **BREAKING CHANGE** ⚠
By making `/run/promtail` mount configurable, platforms with limited `hostPath` specification (e.g. GKE Autopilot) will be able to use Helm Chart of Promtail.
Close #447
Close #644
> [promtail] Change `/run/promtail` mount to configurable with `values.yaml`

- charts/grafana/Chart.yaml
- charts/grafana/templates/deployment.yaml
- charts/grafana/templates/statefulset.yaml
- charts/grafana/values.yaml
For HA Alerting:
Would like the ability to use a StatefulSet instead of a deployment. That way I can dynamically populate the ha-peers using predetermined host names.
Example:
```
ha_peers=grafana-0:9094,grafana-1:9094,grafana-2:9094
```
> [grafana] - HA Alerting: Allow StatefulSet to be used instead of Deployment

- charts/loki-distributed/Chart.yaml
- charts/loki-distributed/README.md
- charts/loki-distributed/templates/_helpers.tpl
Hi,
This PR is to handle KubeVersion containing a platform version like `1.22.9-eks-1` appropriately.
We run loki-distributed on EKS, and tried to upgrade loki-distributed to 0.48.5 to use `policy/v1` API for PodDisruptionBudgets. But `policy/v1` api doesn't appeared in the manifest.
According to [the docs](https://helm.sh/docs/chart_template_guide/function_list/#working-with-prerelease-versions) , semverCompare function skips a such KubeVersion if the version in the condition doesn't contain the suffix `-0`. This works on my environment.
Thanks.
> [loki-distributed] Fix ignoring KubeVersion containing a platform version

- INTERNAL.md
> INTERNAL.md: add instructions on usage of PGP key as github secret

- charts/loki-simple-scalable/Chart.yaml
- charts/loki-simple-scalable/README.md
**Scope**: Simple Scalable Model Helm Chart Documentation
[This commit ](https://github.com/grafana/helm-charts/commit/cab9e61ebdda23129bd59b4a813f5dd4749fc36b) updated the simple scalable model charts' loki.config value to be a string. However the examples were broken within the README. This PR fixes those examples.
> [loki-simple-scalable] Fix: Simple Scalable Model Helm Chart README examples

- index.yaml
This was never really in use, since we switched to using actual
beta versions instead with mimir-distributed chart.
> Remove confusing mimir-distributed-beta chart from helm repo

- charts/loki/Chart.yaml
- charts/loki/templates/statefulset.yaml
- charts/loki/values.yaml
This brings `loki` into line with some of the other charts, e.g. for providing credentials to object storage
> [loki]  Support .Values.extraEnvFrom

- charts/loki-stack/Chart.yaml
- charts/loki-stack/requirements.yaml
As a follow-up to #1513, this updates `loki-stack`'s `loki` requirement to a version that includes the change
> [loki-stack] Update loki to 2.12.2

- charts/enterprise-logs/CHANGELOG.md
- charts/enterprise-logs/Chart.yaml
- charts/enterprise-logs/templates/compactor/statefulset-compactor.yaml
The /tmp directory is used to write temporary marker files and if it's not mounted, Loki will log errors about read-only file system.
This issue has already been addressed in the `loki` chart with #967, in the `loki-distributed` chart with #717, and in the `loki-simple-scalable` chart with #1146.
Signed-off-by: Christian Haudum <christian.haudum@gmail.com>
> [enterprise-logs] Mount read/write /tmp directory in Compactor

- charts/promtail/Chart.yaml
- charts/promtail/README.md
- charts/promtail/README.md.gotmpl
This PR improves the docs for promtail syslog and journal scraping configs:
- add some useful source labels
- add some additional links to docs
- fix the journal example to mount `/etc/machine-id`  as described in the docs
> [promtail] improve documentation for syslog and journal scraping

- charts/loki-distributed/Chart.yaml
- charts/loki-distributed/README.md
- charts/loki-distributed/templates/service-memberlist.yaml
- charts/loki-distributed/values.yaml
This PR references the same issue as https://github.com/grafana/helm-charts/issues/1099, but for the loki-distributed helm-chart.
Using istio protocol selection, the ports break in the memberlist service and throw the following error:
```
level=warn ts=2021-08-13T10:42:42.205933Z caller=client.go:344 component=client host=api.*.appdomain.cloud msg=“error sending batch, will retry” status=500 error="server returned HTTP status 500 Internal Server Error (500): empty ring"
```
This can be fixed by adding the `appProtocol` field in the memberlist service and setting it to `tcp` for loki-distributed. If appProtocol is left empty, then it will be ignored and not included in the service.
> [loki-distributed] Add optional appProtocol to memberlist svc

- charts/promtail/Chart.yaml
- charts/promtail/README.md
- charts/promtail/values.yaml
Similar to `extraClientConfigs`, `config.snippets.extraServerConfigs` is added to the config file's 'server' block.
I would like to use this change to add `health_check_target` setting to the config file.
> [promtail]  Add config.snippets.extraServerConfigs

- charts/loki/Chart.yaml
- charts/loki/README.md
- charts/loki/templates/service-headless.yaml
- charts/loki/templates/statefulset.yaml
- charts/loki/values.yaml
Hi team,
The admission controller in our multi-tenant K8s cluster requests all services and PVCs must have compliant labels. Loki service has custom labels, but not Loki service-headless and PVC created by the statefulset.
This PR allows to add extra labels to the `volumeClaimTemplates` section in the Statefulset and the Loki service-headless.
Signed-off-by: Canh Ngo <canhnt@gmail.com>
> [loki] Allowed to add labels to service-headless and PVC

- charts/tempo-distributed/Chart.yaml
- charts/tempo-distributed/README.md
- charts/tempo-distributed/values.yaml
This is suboptimal since promtail uses HTTP/1.1 and can cause issues with Istio which , by default, will reject anything lower than HTTP/1.1
Slack conversation for reference: https://grafana.slack.com/archives/CEPJRLQNL/p1651595415595109
Signed-off-by: Francesco Ciocchetti <primeroznl@gmail.com>
> [tempo-distributed] gateway: Set the HTTP version for proxying to HTTP/1.1

- charts/loki-simple-scalable/Chart.yaml
- charts/loki-simple-scalable/README.md
- charts/loki-simple-scalable/values.yaml
This PR exposes a few additional configs we found we needed to tweak in our own GL ops deployment.
* Added configuration options for using an external memcache cache
* Added configuration options for specifying additional storage and
query_frontend configuration options
> [loki-simple-scalable] Add additional configs needed for GL ops deploy

- charts/loki-simple-scalable/CHANGELOG.md
- charts/loki-simple-scalable/Chart.yaml
- charts/loki-simple-scalable/README.md
- charts/loki-simple-scalable/templates/_helpers.tpl
- charts/loki-simple-scalable/values.yaml
This is needed to fix a bug in the generated config that always assumed S3 for ruler storage. Fixes #1552.
> [loki-simple-scalable] Ssd ruler config

- charts/loki-canary/Chart.yaml
- charts/loki-canary/README.md
- charts/loki-canary/templates/daemonset.yaml
- charts/loki-canary/values.yaml
Added podSecurityContext and containerSecurityContext as a helm chart configurable value to loki-canary helm chart.
> [loki-canary] add SecurityContext

- charts/loki-distributed/Chart.yaml
- charts/loki-distributed/README.md
updated loki release version to 2.6.1 and bumped version of the chart
> [loki-distributed] updated loki release version to 2.6.1 and bumped version of the chart

- charts/loki-simple-scalable/Chart.yaml
- charts/loki-simple-scalable/README.md
updated loki release version to 2.6.1 and bumped version of the chart
> [loki-simple-scalable] updated loki release version to 2.6.1 and bumped version of the chart

- charts/loki-canary/Chart.yaml
- charts/loki-canary/README.md
updated loki release version to 2.6.1 and bumped version of the chart
> [loki-canary] updated loki release version to 2.6.1 and bumped version of the chart

- charts/loki/Chart.yaml
- charts/loki/values.yaml
updated loki release version to 2.6.1 and bumped version of the chart
> [loki] updated loki release version to 2.6.1 and bumped version of the chart

- charts/grafana/Chart.yaml
- charts/grafana/templates/_pod.tpl
- charts/grafana/values.yaml
By default, sidecar image is very noisy. Recently they've added the functionality to set LOG_LEVEL in the upstream
(https://github.com/kiwigrid/k8s-sidecar/pull/190), let's have it available in Grafana's chart.
Signed-off-by: Bartek Stalewski <ftpd@insomniac.pl>
> [grafana] Set LOG_LEVEL in the sidecar container.

- charts/grafana/Chart.yaml
- charts/grafana/templates/_pod.tpl
In https://github.com/grafana/helm-charts/pull/1624 I've made a mistake and used two different paths in two places. This PR fixes it.
Sorry for breaking it!
Signed-off-by: Bartek Stalewski <ftpd@insomniac.pl>
> [grafana] Fix logLevel in chart.

- charts/grafana/Chart.yaml
Update Grafana due to the latest release and quick smoke test locally in our setup.
> [grafana] Upgrade Grafana to 9.0.4 and bump chart

- charts/enterprise-logs-simple/Chart.yaml
- charts/enterprise-logs-simple/values.yaml
Related to: https://github.com/grafana/helm-charts/pull/1339
By default nginx uses HTTP/1.0 for proxied requests : https://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_http_version
This is suboptimal since promtail uses HTTP/1.1 and can cause issues with Istio which , by default, will reject anything lower than HTTP/1.1
Signed-off-by: Francesco Ciocchetti <primeroznl@gmail.com>
> [enterprise-logs-simple] - gateway: Set the HTTP version for proxying to HTTP/1.1 

- charts/grafana/Chart.yaml
- charts/grafana/templates/image-renderer-network-policy.yaml
fixes https://github.com/grafana/helm-charts/issues/795
removing the `namespaceSelector` from the network policy
effectively only allows pods from the same namespace to access 
the image renderer. there is no need to manually specify the
namespace, and the label previously used to match on a namespace
isn't the default K8s namespace label (that would be 
kubernetes.io/metadata.name )
> [grafana] image-renderer: fix namespace selector issue

- charts/loki-simple-scalable/Chart.yaml
- charts/loki-simple-scalable/README.md
- charts/loki-simple-scalable/templates/service-memberlist.yaml
We had made this change to our helm-charts we re-host a while ago and upon upgrade to latest version we left the port name as `http` and encountered nothing but issues, think a PR is necessary since this breaks istio injected loki-simple-scalable deployments.
For issue https://github.com/grafana/helm-charts/issues/1099
> [loki-simple-scalable] Service Memberlist tcp prefix fix

- charts/loki-distributed/Chart.yaml
- charts/loki-distributed/README.md
- charts/loki-distributed/templates/memcached-chunks/service-memcached-chunks.yaml
- charts/loki-distributed/templates/memcached-frontend/service-memcached-frontend.yaml
- charts/loki-distributed/templates/memcached-index-queries/service-memcached-index-queries.yaml
- charts/loki-distributed/templates/memcached-index-writes/service-memcached-index-writes.yaml
- charts/loki-distributed/values.yaml
This PR addresses the same issue that was resolved in https://github.com/grafana/helm-charts/pull/1549, but for memcached instead.
With istio protocol selection, loki components are unable to communicate with the memcached services and throw the following error: 
```
level=error ts=2022-07-07T18:25:48.762006363Z caller=memcached.go:144 org_id=fake msg="Failed to get keys from memcached" keysrequested=1 err="memcache: unexpected line in get response: \"HTTP/1.1 400 Bad Request\\r\\n\""
level=error ts=2022-07-07T18:25:48.949472733Z caller=memcached.go:220 msg="failed to put to memcached" name=chunks err=null
level=warn ts=2022-07-07T18:25:48.949510324Z caller=background.go:127 msg="backgroundCache writeBackLoop Cache.Store fail" err="server=100.80.71.54:11211: memcache: unexpected response …
```
> [loki-distributed] Add optional appProtocol to memcached services

- charts/tempo-distributed/Chart.yaml
- charts/tempo-distributed/README.md
- charts/tempo-distributed/templates/ingester/pdb.yaml
- charts/tempo-distributed/templates/ingester/statefulset-ingester.yaml
This change amends the podManagementPolicy that was introduced in #1057 to include a PodDisruptionBudget.  This will help ensure that the Ingesters won't take an outage during a deployment.
> [tempo-distributed] Include PodDisruptionBudget for the Ingester

- charts/tempo/Chart.yaml
- charts/tempo/README.md
- charts/tempo/templates/statefulset.yaml
- charts/tempo/values.yaml
This extends the tempo chart such that it allows setting the priorityClassName at the pod spec level. I don't know why this is missing, and we actually need it when deploying tempo via this chart. 
I did not figure out how to regenerate the README, maybe somebody can tell me? Also, I didn't know if I was supposed to bump the chart version. I can remove this from this PR if that's something happening on release only.
Let me know if there's something else missing! Hope you can merge and release this soon.
> [tempo] allow setting priorityClassName

- charts/enterprise-logs/CHANGELOG.md
- charts/enterprise-logs/Chart.yaml
- charts/enterprise-logs/templates/compactor/statefulset-compactor.yaml
- charts/enterprise-logs/templates/gateway/deployment-gateway.yaml
- charts/enterprise-logs/values.yaml
Signed-off-by: JordanRushing <rushing.jordan@gmail.com>
> [enterprise-logs] Support configuring `containerSecurityContext` for compactor and gateway targets in the enterprise-logs chart

- charts/enterprise-logs/CHANGELOG.md
- charts/enterprise-logs/Chart.lock
- charts/enterprise-logs/Chart.yaml
- charts/enterprise-logs/templates/admin-api/deployment-admin-api.yaml
- charts/enterprise-logs/templates/compactor/statefulset-compactor.yaml
- charts/enterprise-logs/templates/gateway/deployment-gateway.yaml
- charts/enterprise-logs/templates/tokengen/job-tokengen.yaml
- charts/enterprise-logs/values.yaml
* Update loki-distributed to 0.55.0
* Harmonize `securityContext` configs with loki-distributed:
- Rename `adminApi.securityContext` option to `adminApi.podSecurityContext`
- Add `adminApi.securityContext` option
- Rename `tokengen.securityContext` option to `tokengen.podSecurityContext`
- Add `tokengen.securityContext` option
- Rename `compactor.securityContext` to `compactor.podSecurityContext`
- Rename `gateway.securityContext` to `gateway.podSecurityContext`
> [enterprise-logs] Harmonize securityContext for all pods

- charts/loki-simple-scalable/Chart.yaml
- charts/loki-simple-scalable/README.md
- charts/loki-simple-scalable/src/dashboards/loki-operational.json
- charts/loki-simple-scalable/src/dashboards/loki-reads-resources.json
- charts/loki-simple-scalable/src/dashboards/loki-writes-resources.json
- charts/loki-simple-scalable/src/dashboards/loki-writes.json
There are other issues with the current dashboards as well, but I think it's better to fix them one PR at a time.
Job names were changed in the same PR that added them dashboards: https://github.com/grafana/helm-charts/pull/1514
> [loki-simple-scalable] src/dashboards: fix expressions to match new job name

- charts/grafana/Chart.yaml
- charts/grafana/templates/configmap.yaml
- charts/grafana/values.yaml
Current chart cannot download dashboard.json from gitlab repository from this line
https://github.com/grafana/helm-charts/blob/main/charts/grafana/templates/configmap.yaml#L87
In order to make this compatible with gitlab token we need to set header as PRIVATE-TOKEN: xxx instead
This PR will make it able to.
To test just simple create 1 token in gitlab and curl to some file in a repo with that token
> [grafana] allow download dashboard from gitlab

- charts/loki-simple-scalable/CHANGELOG.md
- charts/loki-simple-scalable/Chart.yaml
- charts/loki-simple-scalable/README.md
- charts/loki-simple-scalable/values.yaml
> [loki-simple-scalable] GEL release 1.5.1

- charts/loki/Chart.yaml
- charts/loki/templates/statefulset.yaml
- charts/loki/values.yaml
Introduces the topologySpreadConstraint for the cluster default
of `zone` in soft-enforcement for compatibility. Setting the chart
default of whenUnsatisfiable: ScheduleAnyway will mean this has no
impact on chart users. Those who wish to alter this value to
DoNotSchedule will enable strict enforcement of Loki pods being
Distributed evenly among cluster zones.
> [loki] implement topology spread constraints

- charts/loki-stack/Chart.yaml
- charts/loki-stack/requirements.yaml
- charts/loki-stack/values.yaml
The promtail version included in loki-stack is currently pretty old. This updates it to the same version as loki itself.
This would supersede #1605 and #925.
> [loki-stack] Update promtail dependency to ^6.2.3

- charts/tempo-distributed/Chart.yaml
- charts/tempo-distributed/README.md
- charts/tempo-distributed/templates/ingester/statefulset-ingester.yaml
- charts/tempo-distributed/values.yaml
same as https://github.com/grafana/helm-charts/pull/1703 but for tempo.
> [tempo-distributed] allow using inmemory emptyDir with tempo-ingester

- charts/grafana/Chart.yaml
- charts/grafana/values.yaml
Fixes #1685
At the moment if you enable ingress on the Grafana chart you also have to remember to specify the hostname again in the grafana.ini file to make sure redirects work properly. This update defaults the ini value to the first hostname in the ingress object to save repeating information.
> [grafana] Make grafana server domain default to ingress host

- charts/loki-simple-scalable/CHANGELOG.md
- charts/loki-simple-scalable/Chart.yaml
- charts/loki-simple-scalable/README.md
- charts/loki-simple-scalable/values.yaml
Fixes https://github.com/grafana/helm-charts/issues/1695
- This will allow users of the chart to configure the server block as documented here https://grafana.com/docs/loki/latest/configuration/#server through values.
Signed-off-by: cebidhem <cebidhem@pm.me>
> [loki-simple-scalable] Allow loki server block to be configured

- charts/grafana/Chart.yaml
- charts/grafana/templates/_pod.tpl
Add support for templates in the `extraContainerVolumes` value for the Grafana chart, to align with the rest of the values that support it.
> [grafana] Support tpl in extraContainerVolumes

- charts/loki-distributed/Chart.yaml
- charts/loki-distributed/README.md
- charts/loki-distributed/templates/NOTES.txt
- charts/loki-distributed/templates/query-scheduler/_helpers-query-scheduler.tpl
- charts/loki-distributed/templates/query-scheduler/deployment-query-scheduler.yaml
- charts/loki-distributed/templates/query-scheduler/poddisruptionbudget-query-scheduler.yaml
- charts/loki-distributed/templates/query-scheduler/service-query-scheduler.yaml
- charts/loki-distributed/templates/query-scheduler/servicemonitor-query-scheduler.yaml
- charts/loki-distributed/values.yaml
Linked to #1574, the recommended approach for the _read-path_ is to deploy the `query-scheduler` as an independent component which allows us to scale `query-frontend` regardless of restriction imposed by `-querier.max-concurrent`.
If you want to learn more about this limitation I invite you to check the [Why Query Frontend Scalability is Limited](https://grafana.com/docs/mimir/latest/operators-guide/architecture/components/query-frontend/#why-query-frontend-scalability-is-limited) article from _Mimir_.
Among other benefits, it allows users to benefit from more metrics in the frontend as well as metrics from the scheduler components; which, in turn, allow users to follow the new [operational guide to auto-scale the queriers](https://github.com/grafana/loki/pull/6801) by @salvacorts.
I …
> [loki-distributed] Feature: Deploy query-scheduler as an independent component

- charts/loki-distributed/Chart.yaml
- charts/loki-distributed/README.md
- charts/loki-distributed/templates/index-gateway/statefulset-index-gateway.yaml
- charts/loki-distributed/templates/ingester/deployment-ingester.yaml
- charts/loki-distributed/templates/ingester/statefulset-ingester.yaml
- charts/loki-distributed/values.yaml
Allows to use emptyDir in ingester and indexGateway with medium: Memory. Useful in certain cases.
Allows setting limit as well, uses same variable as ordinary persistence block.
For ingester, supports both Deployment and StatefulSet.
> [loki-distributed] add support for in-memory disk in ingester and indexGateway

- charts/tempo-distributed/Chart.yaml
- charts/tempo-distributed/README.md
- charts/tempo-distributed/values.yaml
The feature https://github.com/grafana/tempo/pull/1465 was added to Tempo v1.5.0 which made `log_received_traces` deprecated and replaced with `log_received_spans` with extra options.
> [tempo-distributed] Add log_received_spans option

- charts/loki-distributed/Chart.yaml
- charts/loki-distributed/README.md
- charts/loki-distributed/templates/_helpers.tpl
- charts/loki-distributed/templates/ingester/statefulset-ingester.yaml
- charts/loki-distributed/values.yaml
now the readiness and liveness probe configs are for every component. I want to be able to customize these configs for Ingester only. 
Signed-off-by: Youhua Li <webcraft@gmail.com>
> [loki-distributed] enable customization of readiness and liveness probe configuration for Loki Ingester

- charts/loki-distributed/Chart.yaml
- charts/loki-distributed/README.md
- charts/loki-distributed/templates/compactor/deployment-compactor.yaml
- charts/loki-distributed/templates/distributor/service-distributor.yaml
- charts/loki-distributed/templates/ingester/service-ingester-headless.yaml
- charts/loki-distributed/templates/ingester/service-ingester.yaml
- charts/loki-distributed/templates/querier/service-querier-headless.yaml
- charts/loki-distributed/templates/querier/service-querier.yaml
- charts/loki-distributed/templates/query-frontend/service-query-frontend.yaml
- charts/loki-distributed/values.yaml
When Istio is configured with `PeerAuthentication`-[policy](https://istio.io/latest/docs/concepts/security/#authentication-policies) mode set to `STRICT`, mutual TLS is enforced by default. Istio is relying on [protocol selection](https://istio.io/latest/docs/ops/configuration/traffic-management/protocol-selection/) to proxy traffic. This pull request will introduce an optional `appProtocol.grpc`-option for the ingester-, distributor-, querier- and query-frontend-service.
Feedback on the field name, `x.appProtocol.grpc`,  and documentation are welcome.
This merge request will also add the compactor to the memberlist as stated in the [loki documentation](https://grafana.com/docs/loki/latest/fundamentals/architecture/rings/). There is an ongoing merge request, …
> [loki-distributed] add appProtocol grpc field and add compactor to memberlist

- charts/loki/Chart.yaml
- charts/loki/templates/_helpers.tpl
- charts/loki/templates/podsecuritypolicy.yaml
@zanhsieh This PR fixes a bug in the resource naming for PodDisruptionBudgets. The resource ends in `s` and is plural.
Secondly, PodSecurityPolicy resource was removed in 1.25 according to the documentation and replaced with Pod Security Admission which would be a major update to the way it handles pod security policies as its a feature now of k8s. I added a check before enabling that when `pspEnabled` is set which should only deploy it if the legacy `PodSecurityPolicy` is available.
See deprecation notices and more [HERE](https://kubernetes.io/blog/2021/04/06/podsecuritypolicy-deprecation-past-present-and-future/)
Also, I created an [issue (1735)](https://github.com/grafana/helm-charts/pull/1735) to track the deprecation and some work/resolution as the fix I apply here is really a patch …
> [loki] Fix bug in poddisruptionbudget(s) & remove pod-sec

- charts/grafana/Chart.yaml
- charts/grafana/README.md
- charts/grafana/templates/_pod.tpl
- charts/grafana/templates/configmap.yaml
- charts/grafana/templates/tests/test-configmap.yaml
- charts/grafana/values.yaml
This should allow provisioning of files via the [grafana provisioning support](https://grafana.com/docs/grafana/latest/administration/provisioning/#alerting) and should address #1710.
This will only work when using the chart with Grafana 9.1
Example usage:
```yaml
alerting:
rules.yaml:
apiVersion: 1
groups:
....
contactpoints.yaml:
apiVersion: 1
contactPoints:
....
```
> [grafana] Add support for alerting provisioning present in grafana 9.1

- charts/grafana/Chart.yaml
- charts/grafana/templates/service.yaml
- charts/grafana/values.yaml
Currently, there is a bug where user-provided service annotations
are not passed through the templating engine, even though the docs suggest
that they are. This patch applies the same strategy as the serviceAccount
annotations to the service annotations.
Signed-off-by: Michael Bauer <mbauer@relativityspace.com>
Testing is run with an `overrides.yaml` file containing the following:
```
service:
annotations:
something.io/test: "{{ .Release.Name }}-test"
```
The expected outcome is that the result of `helm template . -f overrides.yaml` will produce a service with the annotation:
```
something.io/test: release-name-test
```
```
~/rs/ext/helm-charts/charts/grafana grafana-service-annotation-templating*
❯ helm template -f overrides.yaml . | grep "something.io/test" --context=1
annotations: …
```
> [grafana] fix: Respect templating in service.annotations as specified in documentation

- charts/loki-stack/Chart.yaml
- charts/loki-stack/requirements.yaml
This is mostly an attempt to get a k8s v1.25 compatible install.  I hope it's really this easy, but this PR mostly exists to see if CI passes ;)
The "contributing guidelines" suggest bumping the version number for each change.  I don't know if that's actually the procedure, but I did it.  It seems like there were no breaking changes mentioned in the Loki README since 2.13.0 (i.e. not from 2.14 to 2.15 which this PR updates), so I just did a patch number bump here.
> [loki-stack] update loki chart dependency

- charts/loki-distributed/Chart.yaml
- charts/loki-distributed/README.md
- charts/loki-distributed/templates/ingester/deployment-ingester.yaml
- charts/loki-distributed/templates/ingester/hpa.yaml
- charts/loki-distributed/templates/ingester/statefulset-ingester.yaml
- charts/loki-distributed/values.yaml
I believe if you set replication_factor: 3, you can autoscale the ingester up and down. memory load seems to be evenly distributed to all of my replicas with a max of 6. mostly copied from https://github.com/grafana/helm-charts/pull/667
> [loki-distributed] fix - add support for autoscaling ingester

- charts/tempo-distributed/Chart.yaml
- charts/tempo-distributed/README.md
- charts/tempo-distributed/README.md.gotmpl
- charts/tempo-distributed/values.yaml
Adds support for the entire [metrics_generator config](https://grafana.com/docs/tempo/latest/configuration/#metrics-generator) in the `tempo-distributed` chart, matching the config structure. It looks like the `tempo` chart has a bit more of a bespoke configuration so I did not update that but I can if needed.
Addresses https://github.com/grafana/helm-charts/issues/1621
Important breaking change note:
- Moves `metricsGenerator.config.storage_remote_write` to `metricsGenerator.config.storage.remote_write`
- Moves `metricsGenerator.config.service_graphs_max_items` to `metricsGenerator.config.processor.service_graphs.max_items`
I can add these back to make things backwards compatible if needed. I only bumped a minor version but will bump a major if it's more appropriate, given the breaking …
> [tempo-distributed] chore: support full metrics_generator config in tempo-distributed

- charts/tempo-distributed/Chart.yaml
- charts/tempo-distributed/README.md
- charts/tempo-distributed/templates/ingester/statefulset-ingester.yaml
- charts/tempo-distributed/values.yaml
Allow annotations in ingestor's PVC. So that project like [pvc-autoresizer](https://github.com/topolvm/pvc-autoresizer) can be used to auto resize ingestor's PVC size.
For testing, enable persistence and update annotations
```
persistence:
-    enabled: false
+    enabled: true
inMemory: false
@@ -148,7 +148,8 @@ ingester:
storageClass: null
-    annotations: {}
+    annotations:
+      test.com/size: 10Gi
```
Run helm template command helm template test . -f values.yaml to render templates.
Inspect ingester StatefulSet to ensure annotations are added.
```
volumeClaimTemplates:
- metadata:
annotations:
test.com/size: 10Gi
name: data
spec:
accessModes:
- ReadWriteOnce
resources:
requests:
storage: "10Gi"
```
> [tempo-distributed] Add annotations to ingester's pvc

- .github/workflows/update-helm-repo.yaml
Add optional tag prefix for publishing helm charts. Useful for when this workflow is invoked from another repository.
> Add optional helm tag prefix to release job

- .github/workflows/update-helm-repo.yaml
Better separation of package name from git tag name. I think this was the intention of PR 1779
I don't know if we want to keep the git tag in the source repository and the helm-charts repo in sync or not. This PR does not keep them in sync.
> Fix update-helm-repo.yaml

- charts/tempo-distributed/Chart.yaml
- charts/tempo-distributed/README.md
- charts/tempo-distributed/templates/ingester/poddisruptionbudget-ingester.yaml
The ingester pdb should specify a maxUnavailable equal to (total number of desired replicas) - (number of replicas in the ring required to ACK a write). Currently in main the calculation is incorrect.
> [tempo-distributed] Fix ingester pdb to use rep. factor properly

- charts/loki-distributed/Chart.yaml
- charts/loki-distributed/README.md
- charts/loki-distributed/templates/distributor/poddisruptionbudget-distributor.yaml
- charts/loki-distributed/templates/gateway/poddisruptionbudget-gateway.yaml
- charts/loki-distributed/templates/index-gateway/poddisruptionbudget-index-gateway.yaml
- charts/loki-distributed/templates/ingester/poddisruptionbudget-ingester.yaml
- charts/loki-distributed/templates/memcached-chunks/poddisruptionbudget-memcached-chunks.yaml
- charts/loki-distributed/templates/memcached-frontend/poddisruptionbudget-memcached-frontend.yaml
- charts/loki-distributed/templates/memcached-index-queries/poddisruptionbudget-memcached-index-queries.yaml
- charts/loki-distributed/templates/memcached-index-writes/poddisruptionbudget-memcached-index-writes.yaml
- charts/loki-distributed/templates/querier/poddisruptionbudget-querier.yaml
- charts/loki-distributed/templates/query-frontend/poddisruptionbudget-query-frontent.yaml
- charts/loki-distributed/templates/query-scheduler/poddisruptionbudget-query-scheduler.yaml
- charts/loki-distributed/templates/ruler/poddisruptionbudget-ruler.yaml
- charts/loki-distributed/values.yaml
Almost all Loki distributed PDBs takes them values from the `distributor` configuration. 
Also, PDBs are deployed for services that are not enabled.
This PR fixes these two issues.
> [loki-distributed] fix: pdbs should take the right value

- charts/tempo-distributed/Chart.yaml
- charts/tempo-distributed/README.md
- charts/tempo-distributed/templates/query-frontend/service-query-frontend-discovery.yaml
This PR ensures service ports related to the optional `tempo-query` component are only configured when `tempo-query` is enabled. This is consistent with the existing `query-frontend` service configuration.
Additionally, the `grpclb` port has been moved immediately below `grpc`, so that all the ports are listed in order.
> [tempo-distributed] fix: remove extraneous ports from query-frontend-discovery service

- charts/promtail/Chart.yaml
- charts/promtail/README.md
- charts/promtail/templates/_pod.tpl
- charts/promtail/values.yaml
Closes #1805 (see there for motivation) #1727 (didn't realise this existed before)
I am not a Helm templating expert. Typically I see this sort of extra being done as a List, but I couldn't get it to render with the necessary - at the beginning of the extra containers in the overall list, so I went with the name: values hash approach. Feel free to improve that.
Signed-off-by: Conor Evans <coevans@tcd.ie>
redo of #1806 which i messed up spectacularly
> [promtail] feat: support extraContainers for Promtail Deployments

- charts/grafana/Chart.yaml
Straight forward hotfix update of the `appVersion` in the `grafana/Chart.yaml` from 9.1.4 to 9.1.5.
See: https://github.com/grafana/grafana/releases/tag/v9.1.5
> [grafana] upgrade to 9.1.5

- charts/grafana/Chart.yaml
- charts/grafana/templates/_pod.tpl
This allows for users to use `"{{ .Release.Namespace }}"` in values.yaml
> [grafana] - Add support for templating in searchNamespace

- charts/grafana/Chart.yaml
- charts/grafana/templates/hpa.yaml
This pull request will add the **namespace** field to the Grafana horizontal pod autoscaling metadata. 
Both [deployment.yaml](https://github.com/grafana/helm-charts/blob/main/charts/grafana/templates/deployment.yaml#L6) and [service.yaml](https://github.com/grafana/helm-charts/blob/main/charts/grafana/templates/service.yaml#L6) use the [namespaceOverride](https://github.com/grafana/helm-charts/blob/main/charts/grafana/templates/_helpers.tpl#L56)-value from [values.yaml ](https://github.com/grafana/helm-charts/blob/main/charts/grafana/values.yaml#L924) file. The [hpa.yaml](https://github.com/grafana/helm-charts/blob/main/charts/grafana/templates/hpa.yaml) doesn't. This can cause a situation where the horizontal pod autoscaling and the deployment are on two different namespaces.
> [grafana] add namespace to horizontal pod autoscaling

- charts/grafana/Chart.yaml
- charts/grafana/values.yaml
If not using the ingress feature the domain value would be empty. This resulted in the template producing an ini file with a line like this:
`domain = \n`
This would cause issues when passing the resource through a tool like kustomize, which would turn the multiline block into an encoded single line string in order to preserve trailing whitespace, resulting in kubectl diffs that are very hard to review.
> [grafana] Fix whitespace issue due to empty value

- charts/tempo-distributed/Chart.yaml
- charts/tempo-distributed/README.md
- charts/tempo-distributed/templates/query-frontend/service-query-frontend.yaml
- charts/tempo-distributed/values.yaml
Query frontend supports `type: loadbalancer`, but lacks loadbalancer specs. This MR adds two common load balancer specs:
* loadBalancerIP
* loadBalancerSourceRanges
Signed-off-by: Anthony Lazam <xlzm.tech@gmail.com>
> [tempo-distributed] Service LB specs for query-frontend

- charts/loki-distributed/Chart.yaml
- charts/loki-distributed/README.md
- charts/loki-distributed/templates/compactor/deployment-compactor.yaml
- charts/loki-distributed/templates/distributor/deployment-distributor.yaml
- charts/loki-distributed/templates/index-gateway/statefulset-index-gateway.yaml
- charts/loki-distributed/templates/ingester/deployment-ingester.yaml
- charts/loki-distributed/templates/ingester/statefulset-ingester.yaml
- charts/loki-distributed/templates/querier/deployment-querier.yaml
- charts/loki-distributed/templates/querier/statefulset-querier.yaml
- charts/loki-distributed/templates/query-frontend/deployment-query-frontend.yaml
- charts/loki-distributed/templates/query-scheduler/deployment-query-scheduler.yaml
- charts/loki-distributed/templates/ruler/deployment-ruler.yaml
- charts/loki-distributed/templates/ruler/statefulset-ruler.yaml
- charts/loki-distributed/templates/runtime-configmap.yaml
- charts/loki-distributed/templates/table-manager/deployment-table-manager.yaml
- charts/loki-distributed/values.yaml
This is largely inspired by similar value available in [mimir-distributed](https://github.com/grafana/mimir/tree/main/operations/helm/charts/mimir-distributed) helm chart.
The idea is to have a dedicated configmap to handle [runtime_config](https://grafana.com/docs/loki/latest/configuration/#runtime-configuration-file), alway present even if empty. This way, having it seperately from main config, components pods are guaranteed not to restart for any changes.
```yaml
runtimeConfig:
overrides:
tenant1:
ingestion_rate_mb: 10
max_streams_per_user: 100000
max_chunks_per_query: 100000
tenant2:
max_streams_per_user: 1000000
max_chunks_per_query: 1000000
multi_kv_config:
mirror-enabled: false
primary: consul
```
Some questionable details:
1. Like in `mimir-distributed`, `runtimeConfig` is …
> [loki-distributed] Introduce runtimeConfig

- charts/grafana/Chart.yaml
Straight forward hotfix update of the appVersion in the grafana/Chart.yaml from 9.1.5 to 9.1.6.
See: https://github.com/grafana/grafana/releases/tag/v9.1.6
> [grafana] upgrade to 9.1.6

- charts/loki-stack/Chart.yaml
- charts/loki-stack/templates/tests/loki-test-configmap.yaml
- charts/loki-stack/templates/tests/loki-test-pod.yaml
Chart does not allow loki to be disabled in values, because of some variables used i tests templates (like  here https://github.com/grafana/helm-charts/blob/main/charts/loki-stack/templates/tests/loki-test-pod.yaml#L23)
This pr just make such resources optionals by testing if loki is enabled.
Same as https://github.com/grafana/helm-charts/pull/481 but without any lawyers involved ;)
> [loki-stack] Disable tests is loki is disabled

- charts/agent-operator/Chart.yaml
- charts/agent-operator/README.md
- charts/agent-operator/templates/operator-clusterrole.yaml
- charts/agent-operator/values.yaml
This is useful when the agent-operator is being used as a subchart and
the parent chart is using a PodSecurityPolicy. This new value will allow
the user of the parent chart to configure the agent to use the same
PSP as the parent chart.
> [agent-operator] Allow using PodSecurityPolicy

- charts/agent-operator/Chart.yaml
- charts/agent-operator/README.md
- charts/agent-operator/templates/operator-deployment.yaml
- charts/agent-operator/values.yaml
This is useful for when running in a restricted environment. For example when running in a namespace using the [Restricted policy](https://kubernetes.io/docs/concepts/security/pod-security-standards/#restricted) (either via a [PodSecurityPolicy](https://v1-24.docs.kubernetes.io/docs/concepts/security/pod-security-policy/) or via the new [namespace labels](https://kubernetes.io/docs/tasks/configure-pod-container/enforce-standards-namespace-labels/)), the agent-operator container should not be allowed privilege escalation and should only have access to a read-only root filesystem.
These are already configurable in the CRDs for the Grafana Agent pods that the operator creates, but the operator doesn't have them.
> [agent-operator] Add container SecurityContext

- charts/grafana/Chart.yaml
- charts/grafana/README.md
- charts/grafana/templates/_pod.tpl
- charts/grafana/values.yaml
This is a continuation of [PR 1756](https://github.com/grafana/helm-charts/pull/1756) after a wrong manipulation there.
Previous description:
This PR adds the capacity to use Grafana 9.1 file provisioning for unified alerting through the same sidecar mechanism already in place for dashboards, datasources or notifiers.
This should help for https://github.com/grafana/helm-charts/issues/1710
> [grafana] load alerts through sidecar

- charts/grafana/Chart.yaml
- charts/grafana/templates/configmap-dashboard-provider.yaml
- Add an additional condition for creating the ConfigMap defining the provider for the dashboards sidecar, that `.Values.sidecar.dashboards.SCProvider` is true. This doesn't affect the default behavior, but allows for a cleaner deployment when not using SCProvider
> [grafana] Fix sidecar dashboard configmap creation

- charts/loki-canary/Chart.yaml
- charts/loki-canary/README.md
- charts/loki-canary/templates/daemonset.yaml
- charts/loki-canary/values.yaml
This change introduces templating for volume mounts and volumes
Tested with 
```
helm  template --dry-run --debug -f ci/without-basic-auth-values.yaml .
helm  template --dry-run --debug -f ci/with-basic-auth-values.yaml .
```
Also created a file with the additional values and ran `helm  template --dry-run --debug -f tmp/with-basic-volume-values.yaml`
```
lokiAddress: loki:3100
basicAuth:
enabled: true
username: user
password: pass
extraVolumes:
- name: tmp-test
emptyDir: {}
extraVolumeMounts:
- name: tmp-test
mountPath: /tmp-test
```
Output
```
---
apiVersion: v1
kind: ServiceAccount
metadata:
name: release-name-loki-canary
labels:
helm.sh/chart: loki-canary-0.9.2
app.kubernetes.io/name: loki-canary
app.kubernetes.io/instance: release-name
app.kubernetes.io/version: "2.6.1" …
```
> [loki-canary] Introduce volumes and volume mounts to containers

- charts/promtail/Chart.yaml
- charts/promtail/README.md
- charts/promtail/values.yaml
This PR add the possibility to configure the [new `limits_config` stanza](https://grafana.com/docs/loki/latest/clients/promtail/configuration/#limits_config) of Promtail without having to directly override `config.file`.
> [promtail] add 'limits_config' stanza

- charts/loki-distributed/Chart.yaml
- charts/loki-distributed/README.md
- charts/loki-distributed/README.md.gotmpl
Hello dear Grafana helm chart maintainers
This PR updates the loki-distributed README.md to reflect the latest changes in memcached configuration introduced in https://github.com/grafana/helm-charts/pull/1765
> [loki-distributed] update memcached usage documentation

- charts/grafana/Chart.yaml
Signed-off-by: Roman Verenich <roman.verenich@gmail.com>
> [grafana] bump default grafana image tag to 9.2.0

- charts/grafana/Chart.yaml
- charts/grafana/templates/image-renderer-deployment.yaml
- charts/grafana/values.yaml
Signed-off-by: ybelMekk <youssef.bel.mekki@nav.no>
Stumbled in to this then configuring kyverno and Pod security standard: [restricted](https://kubernetes.io/docs/concepts/security/pod-security-standards/)
I found that i could not control the container security context in values.yaml
added this PR to add that.
Cheers.
> [grafana] ability to set container security context for image-renderer

- charts/fluent-bit/Chart.yaml
- charts/fluent-bit/templates/podsecuritypolicy.yaml
Try to fix PodSecurityPolicy being removed after Kubernetes 1.25+. 
- This PR just simply removes PSP (same as disable PSP).
- PSP before 1.25+ only reaches `policy/v1beta1`
- `policy/v1` does `NOT` contain PodSecurityPolicy. Please don't mix with PodDisruptionBudget.
> [fluent-bit] Fix PSP deprecation after k8s 1.25+

- charts/loki-distributed/Chart.yaml
- charts/loki-distributed/README.md
- charts/loki-distributed/templates/podsecuritypolicy.yaml
Try to fix PodSecurityPolicy being removed after Kubernetes 1.25+.
- This PR just simply removes PSP (same as disable PSP).
- PSP before 1.25+ only reaches `policy/v1beta1`
- `policy/v1` does `NOT` contain PodSecurityPolicy. Please don't mix with PodDisruptionBudget.
> [loki-distributed] Fix PSP deprecation after k8s 1.25+

- charts/promtail/Chart.yaml
- charts/promtail/README.md
- charts/promtail/templates/podsecuritypolicy.yaml
Try to fix PodSecurityPolicy being removed after Kubernetes 1.25+.
- This PR just simply removes PSP (same as disable PSP).
- PSP before 1.25+ only reaches `policy/v1beta1`
- `policy/v1` does `NOT` contain PodSecurityPolicy. Please don't mix with PodDisruptionBudget.
> [promtail] Fix PSP deprecation after k8s 1.25+

- charts/tempo-distributed/Chart.yaml
- charts/tempo-distributed/README.md
- charts/tempo-distributed/templates/podsecuritypolicy.yaml
Try to fix PodSecurityPolicy being removed after Kubernetes 1.25+.
- This PR just simply removes PSP (same as disable PSP).
- PSP before 1.25+ only reaches `policy/v1beta1`
- `policy/v1` does `NOT` contain PodSecurityPolicy. Please don't mix with PodDisruptionBudget.
> [tempo-distributed] Fix PSP deprecation after k8s 1.25+

- charts/tempo-distributed/Chart.yaml
- charts/tempo-distributed/README.md
- charts/tempo-distributed/values.yaml
Signed-off-by: David <davidcalvertfr@gmail.com>
Just a missing comma in the `values.yaml` file of `tempo-distributed`
> [tempo-distributed] missing comma in values.yaml

- charts/grafana/Chart.yaml
- charts/grafana/values.yaml
This chart is for Grafana but the comment says prometheus.
Looks like a copy-paste issue. Fixing to avoid confusion.
> [grafana] typo in the comment for initChownData in Grafana helm values

- charts/grafana/Chart.yaml
See: https://github.com/grafana/grafana/releases/tag/v9.2.1
> [grafana] bump default grafana image tag to 9.2.1

- charts/grafana/Chart.yaml
- charts/grafana/README.md
- charts/grafana/templates/serviceaccount.yaml
- charts/grafana/values.yaml
This PR adds support for adding labels to the Grafana Service Account which is required for the new [Azure Workload Identity](https://learn.microsoft.com/en-us/azure/aks/workload-identity-overview) functionality.
> [grafana] Added support for ServiceAccount labels

- charts/tempo-distributed/Chart.yaml
- charts/tempo-distributed/README.md
- charts/tempo-distributed/templates/metrics-generator/deployment-metrics-generator.yaml
- charts/tempo-distributed/values.yaml
The default of using local disk for scratch space is still kept in values so this should be a no-op change for people upgrading.
> [tempo-distributed] Add value for changing metrics-generator wal volume to be able to mount it in memory

- charts/promtail/Chart.yaml
- charts/promtail/README.md
- charts/promtail/templates/_pod.tpl
- charts/promtail/templates/configmap.yaml
- charts/promtail/templates/servicemonitor.yaml
- charts/promtail/values.yaml
This pull request solves issues #1915 and #1916.
- The Promtail config can now optionally be generated as a ConfigMap instead of a secret. This makes hacking with `kubectl` much less of a chore. If you still need secrets in your config, consider injecting them through environment variables using `extraEnvFrom` chart value and setting `extraArgs: ["-config.expand-env=true"]`.
- ServiceMonitor was missing some crucial settings, in particular `tlsConfig`. The ServiceMonitor template has now been updated to match that used for the `loki-distributed` chart.
> [promtail] Update ServiceMonitor template and introduce config as ConfigMap option

- charts/grafana/Chart.yaml
See: https://github.com/grafana/grafana/releases/tag/v9.2.2
> [grafana] bump default grafana image tag to 9.2.2

- charts/tempo-distributed/Chart.yaml
- charts/tempo-distributed/README.md
- charts/tempo-distributed/templates/gateway/ingress-gateway.yaml
- charts/tempo-distributed/templates/memcached/statefulset-memcached.yaml
- charts/tempo-distributed/templates/prometheusrule.yaml
Re-procedure the issues:
```
$ helm pull grafana/tempo-distributed --untar --version 0.27.0
```
```
$ helm template --set memcachedExporter.enabled=true tempo-distributed
Error: template: tempo-distributed/templates/memcached/statefulset-memcached.yaml:78:20: executing "tempo-distributed/templates/memcached/statefulset-memcached.yaml" at <include "tempo.memcachedExporterImage" (dict "ctx" . "component" "memcached-exporter")>: error calling include: template: no template "tempo.memcachedExporterImage" associated with template "gotpl"
```
```
$ helm template --set gateway.enabled=true --set gateway.ingress.enabled=true tempo-distributed
Error: template: tempo-distributed/templates/gateway/ingress-gateway.yaml:45:25: executing "tempo-distributed/templates/gateway/ingress-gateway.yaml" at …
```
> [tempo-distributed] Fix issue when render chart templates

- charts/loki-stack/Chart.yaml
- charts/loki-stack/requirements.yaml
To address 2 points:
a) Grafana has UI issues with latest Chrome like https://github.com/grafana/grafana/issues/54722
b) Need to specify appProtocol for loki-grafna service and this is available in Grafana helm chart since https://github.com/grafana/helm-charts/commit/ce087048ecc833876c63826b9ec2157083ce55be
> [loki-stack] Bumb Grafana to 9.2

- charts/grafana/Chart.yaml
- charts/grafana/values.yaml
Changes:
* drop `ALL` (caps) instead of `all` to match spec, k8s implementation, and kyverno policy implementation.
* bump chart patch version
Fixes #1938
> [grafana] Fix drop ALL capitalization

- charts/loki-distributed/Chart.yaml
- charts/loki-distributed/README.md
- charts/loki-distributed/templates/memcached-chunks/statefulset-memcached-chunks.yaml
- charts/loki-distributed/templates/memcached-frontend/statefulset-memcached-frontend.yaml
- charts/loki-distributed/templates/memcached-index-queries/statefulset-memcached-index-queries.yaml
- charts/loki-distributed/templates/memcached-index-writes/statefulset-memcached-index-writes.yaml
- charts/loki-distributed/values.yaml
Currently if memcached is enabled through the `memcachedXXX` values, the infrastructure will be deployed, but Loki is not configured to use the created resources.
This PR adds new entries to the default `loki.config` value, which minimally configures each memcached component when enabled (solving #1386).
Additionally cache configuration can still be injected and overwritten using the `structuredConfig` value.
This PR also adds the ability to configure optional persistence for the memcached stateful sets, meaning cache data will not be lost upon pod restart. This solves issue #1936.
> [loki-distributed] wire-in memcached automatically when enabled, introduce memcached persistence

- charts/grafana/Chart.yaml
See: [https://github.com/grafana/grafana/releases/tag/v9.2.3](https://github.com/grafana/grafana/releases/tag/v9.2.3)
> [grafana] bump default grafana image tag to 9.2.3

- charts/tempo-distributed/Chart.yaml
- charts/tempo-distributed/README.md
- charts/tempo-distributed/templates/distributor/service-distributor.yaml
- charts/tempo-distributed/templates/gossip-ring/service-gossip-ring.yaml
- charts/tempo-distributed/templates/ingester/service-ingester.yaml
- charts/tempo-distributed/templates/metrics-generator/service-metrics-generator.yaml
- charts/tempo-distributed/templates/querier/service-querier.yaml
- charts/tempo-distributed/templates/query-frontend/service-query-frontend-discovery.yaml
- charts/tempo-distributed/templates/query-frontend/service-query-frontend.yaml
- charts/tempo-distributed/values.yaml
When Istio is configured with `PeerAuthentication`-[policy](https://istio.io/latest/docs/concepts/security/#authentication-policies) mode set to STRICT, mutual TLS is enforced by default. Istio is relying on [protocol selection](https://istio.io/latest/docs/ops/configuration/traffic-management/protocol-selection/) to proxy traffic. This pull request will introduce an optional `appProtocol`- and `appProtocol.grpc`-option for the memberlist-, ingester-, distributor-, querier-, metrics-generator- and query-frontend-service.
Feedback on the field names, `tempo.memberlist.appProtocol`, `<service>.appProtocol.grpc`, and documentation are welcome.
Istio doesn't work well when the gossip-ring / memberlist is of type `http`, I have to use `tcp`. That is why the optional …
> [tempo-distributed] add appProtocol field to the memberlist, distributor, ingester, metricsGenerator, querier and the queryFrontend

- charts/grafana/Chart.yaml
- charts/grafana/templates/hpa.yaml
The helm chart used to break if hpa was enabled with statefulset. This adds autoscaling support in conjunction with statefulset.
> [grafana] feat: add ability for sts autoscaling

- charts/tempo-distributed/Chart.yaml
- charts/tempo-distributed/README.md
- charts/tempo-distributed/templates/ingester/service-ingester-discovery.yaml
- charts/tempo-distributed/templates/ingester/service-ingester.yaml
- charts/tempo-distributed/templates/metrics-generator/service-metrics-generator-discovery.yaml
- charts/tempo-distributed/templates/metrics-generator/service-metrics-generator.yaml
This pull request will add [headless services](https://kubernetes.io/docs/concepts/services-networking/service/#headless-services) for the `ingester` and `metrics-generator`. The `query-frontend` already has a headless service. Tried to follow the same name convention as the `query-frontend` and named the new headless services with the suffix *-discovery*.
Headless services for the `ingester` and the `metrics-generator` are required when used with service-mesh solutions such as [Istio](https://istio.io/). The gRPC connections are established with internal Kubernetes endpoint IP's which Istio are not aware of and will therefore block those connections. Adding headless services will resolve this Istio issue.
**This pull request include the optional `appProtocol` option and should therefore …
> [tempo-distributed] add headless services for ingester and metrics-generator

- charts/loki-distributed/Chart.yaml
- charts/loki-distributed/README.md
- charts/loki-distributed/templates/query-frontend/service-query-frontend.yaml
Use standard k8s service type for query-frontend to have some kind of load-balancing without relying on any external mechanism.
Closes https://github.com/grafana/helm-charts/issues/405
Signed-off-by: Thomas Belian <thomas.belian@deutschebahn.com>
> [loki-distributed] feat: switch to standard k8s service for query-frontend

- charts/grafana/Chart.yaml
A new version of Grafana has been released [fixing a critical vulnerability](https://grafana.com/blog/2022/11/08/security-release-new-versions-of-grafana-with-critical-and-moderate-fixes-for-cve-2022-39328-cve-2022-39307-and-cve-2022-39306/) and more. This fix should be available to everyone installing Grafana via Helm Chart quickly.
> [grafana] bump default grafana image tag to 9.2.4 for critical security update

- charts/grafana/Chart.yaml
- charts/grafana/templates/configmap.yaml
The Grafana ConfigMap cannot be rendered when an alerting value object is provided.
> [grafana] fix alerting configmap

- charts/loki-stack/Chart.yaml
- charts/loki-stack/templates/datasources.yaml
When using multiple releases of the loki-stack chart, the datasources of the wrong release can be imported into grafana by the sidecar as the grafana_datasource label is the same.
the datasource configmap should instead use the key/value pair defined in the values of the grafana sub-chart if specified: https://github.com/grafana/helm-charts/blob/d7d211d3b8e5d134afcdbbd40d6cd36be73443f2/charts/grafana/values.yaml#L873 and https://github.com/grafana/helm-charts/blob/d7d211d3b8e5d134afcdbbd40d6cd36be73443f2/charts/grafana/values.yaml#L875
Any feedback or suggestions are appreciated :)
> [loki-stack] Use grafana.sidecar.datasources.{label,labelValue} for datasources cm metadata

- charts/loki-distributed/Chart.yaml
- charts/loki-distributed/README.md
- charts/loki-distributed/values.yaml
Just a small fix in a comment for enabling autoscaling in querier.
> [loki-distributed] Fix typo in querier values

- charts/tempo/Chart.yaml
- charts/tempo/README.md
- charts/tempo/values.yaml
Tempo chart uses `compacted_block_retention` for the retention and tempo-distributed uses `block_retention`. I am updating the tempo chart to match the tempo-distributed.
We probably shouldn't update the `compacted_block_retention` as @joe-elliott mentioned here
https://github.com/grafana/tempo/issues/1884#issuecomment-1310295822
Fixes #1970
> [tempo] block_retention instead of compacted_block_retention

- charts/tempo-distributed/Chart.yaml
- charts/tempo-distributed/README.md
- charts/tempo-distributed/templates/gateway/_helpers-gateway.tpl
- charts/tempo-distributed/templates/gateway/secret-gateway.yaml
The following template fails on the latest version of tempo-distributed.
```sh
$ helm template tempo grafana/tempo-distributed \
--set gateway.enabled=true \
--set gateway.ingress.enabled=true \
--set fullnameOverride=tempo \
--set gateway.basicAuth.enabled=true \
--version 0.27.7 >/dev/null
Error: template: tempo-distributed/templates/gateway/secret-gateway.yaml:6:11: executing "tempo-distributed/templates/gateway/secret-gateway.yaml" at <include "tempo.resourceName" (dict "ctx" . "component" "gateway")>: error calling include: template: tempo-distributed/templates/_helpers.tpl:153:3: executing "tempo.resourceName" at <include "tempo.fullname" .ctx>: error calling include: template: tempo-distributed/templates/_helpers.tpl:15:14: executing "tempo.fullname" at <.Values.fullnameOverride>: …
```
> [tempo-distributed] fix wrong context on gateway with basicAuth enabled

- charts/grafana/Chart.yaml
See: [https://github.com/grafana/grafana/releases/tag/v9.2.5](https://github.com/grafana/grafana/releases/tag/v9.2.5)
> [grafana] bump default grafana image tag to 9.2.5

- charts/tempo-distributed/Chart.yaml
- charts/tempo-distributed/README.md
Tempo-distributed helm chart version needs update in order to be released.
See @mhoyer [comment](https://github.com/grafana/helm-charts/pull/1980#issuecomment-1318724727).
> [tempo-distributed] Bump tempo-distributed chart version

- charts/grafana/Chart.yaml
Due to https://github.com/grafana/helm-charts/pull/1980#issuecomment-1318724727 to trigger a new release build.
> [grafana] bump grafana chart version

- charts/grafana/Chart.yaml
- charts/grafana/templates/ingress.yaml
In a recent refactor (45f71da2c9055f6de23761434a8fc2472559ca53), `path` based `Ingress` manifests [were broken](https://github.com/grafana/helm-charts/commit/45f71da2c9055f6de23761434a8fc2472559ca53#diff-3cc6b406041b4e16cbcfce60566d7931bd50051cd73290333657b94865ecca72L74-L75) in that they started providing boolean values for a string field. This PR reverts the broken refactor.
> [grafana] fix boolean pathType value

- charts/loki-distributed/Chart.yaml
- charts/loki-distributed/README.md
- charts/loki-distributed/templates/ingester/deployment-ingester.yaml
- charts/loki-distributed/templates/ingester/statefulset-ingester.yaml
- charts/loki-distributed/templates/querier/deployment-querier.yaml
- charts/loki-distributed/templates/querier/statefulset-querier.yaml
Signed-off-by: Srinivas Boga <bseenu@gmail.com>
Below i tried to show the problem with a simple chart just having the configmap resource in its templates
```
bash-5.1$ cat capability/Chart.yaml
apiVersion: v2
name: capability
description: A Helm chart for testing kube version capability
version: 0.0.1
bash-5.1$ cat capability/templates/cm.yaml
apiVersion: v1
kind: ConfigMap
metadata:
name: capability
data:
stringVersion: {{ .Capabilities.KubeVersion.Minor | quote }}
intVersion: {{ .Capabilities.KubeVersion.Minor | int | quote }}
bash-5.1$ helm upgrade --install capability ./capability
Release "capability" does not exist. Installing it now.
NAME: capability
LAST DEPLOYED: Tue Nov  1 19:37:02 2022
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
bash-5.1$ kubectl get cm …
```
> [loki-distributed] Handling the eks minor versions which has plus sign

- charts/grafana/Chart.yaml
- charts/grafana/templates/_helpers.tpl
Signed-off-by: toVersus <toversus2357@gmail.com>
Fixes: #2003
After this patch, we can properly render the manifests:
```console
❯ helm template grafana -n monitoring .
---
apiVersion: v1
kind: ServiceAccount
metadata:
labels:
helm.sh/chart: grafana-6.44.7
app.kubernetes.io/name: grafana
app.kubernetes.io/instance: grafana
app.kubernetes.io/version: "9.2.5"
foo: bar
name: grafana
namespace: monitoring
(...)
```
> [grafana] Fix broken extraLabels parameter due to missing line break

- charts/loki-distributed/Chart.yaml
- charts/loki-distributed/README.md
- charts/loki-distributed/values.yaml
This PR bump memcached from  1.6.7 to 1.6.17. The main advantage is that latest memcached has better support for large object in memcache. This makes memcache much more effective and reduce the amount error logs `SERVER_ERROR out of memory storing object`.
This discussion is quite interesting on this subject : https://groups.google.com/g/memcached/c/h-m9S7wODBs
> [loki-distributed] bump memcached from 1.6.7-alpine to 1.6.17-alpine

- charts/loki-distributed/Chart.yaml
- charts/loki-distributed/README.md
- charts/loki-distributed/values.yaml
This PR fix the error below from ingester `topologySpreadContraints.topologyKey` label mantaining the same default config from querier.
```
W1125 13:02:22.763074 2592274 warnings.go:70] spec.template.spec.topologySpreadConstraints[0].topologyKey: failure-domain.beta.kubernetes.io/zone is deprecated since v1.17; use "topology.kubernetes.io/zone" instead
```
> [loki-distributed] Fix ingester topology spread constraints

- charts/loki-distributed/Chart.yaml
- charts/loki-distributed/README.md
- charts/loki-distributed/values.yaml
Before:
```
kubectl logs -n loki loki-loki-distributed-gateway-86d46d55f7-hcsmv
/docker-entrypoint.sh: No files found in /docker-entrypoint.d/, skipping configuration
10.112.128.1 - - [28/Nov/2022:05:15:09 +0000]  200 "GET / HTTP/1.1" 2 "-" "kube-probe/1.22" "-"
10.112.128.1 - - [28/Nov/2022:05:15:19 +0000]  200 "GET / HTTP/1.1" 2 "-" "kube-probe/1.22" "-"
10.112.128.1 - - [28/Nov/2022:05:15:29 +0000]  200 "GET / HTTP/1.1" 2 "-" "kube-probe/1.22" "-"
10.112.128.1 - - [28/Nov/2022:05:15:29 +0000]  200 "GET / HTTP/1.1" 2 "-" "kube-probe/1.22" "-"
10.112.128.1 - - [28/Nov/2022:05:15:39 +0000]  200 "GET / HTTP/1.1" 2 "-" "kube-probe/1.22" "-"
10.112.128.1 - - [28/Nov/2022:05:15:39 +0000]  200 "GET / HTTP/1.1" 2 "-" "kube-probe/1.22" "-"
10.112.128.1 - - [28/Nov/2022:05:15:49 +0000]  200 "GET …
```
> [loki-distributed] Disable access_log for readinessProbe and livenessProbe in gateway

- charts/loki-distributed/Chart.yaml
- charts/loki-distributed/README.md
- charts/loki-distributed/values.yaml
1.20.x stable branch.
Security Scan: 1.19-alpine:
nginxinc/nginx-unprivileged:1.19-alpine (alpine 3.13.5) Total: 96 (UNKNOWN: 0, LOW: 6, MEDIUM: 29, HIGH: 52, CRITICAL: 9) Security Scan: 1.20.2-alpine:
nginxinc/nginx-unprivileged:1.20.2-alpine (alpine 3.14.6) Total: 22 (UNKNOWN: 0, LOW: 2, MEDIUM: 8, HIGH: 9, CRITICAL: 3)
> [loki-distributed] Update image gateway to 1.20.2-alpine.

- charts/tempo-distributed/Chart.yaml
- charts/tempo-distributed/README.md
- charts/tempo-distributed/values.yaml
Need to use discovery address (headless service) to make it work for multiple frontend replicas.
It will fix an issue when requests will fail if multiple `query-frontend` replicas: requests will succeed on only one replica.
Full discussion and troubleshooting steps: https://grafana.slack.com/archives/C01D981PEE5/p1669658595868349
> [tempo-distributed] Fix query frontend address

- charts/grafana/Chart.yaml
In light of [CVE-2022-31097](https://grafana.com/blog/2022/11/29/grafana-security-release-new-versions-with-high-severity-security-fix-for-cve-2022-31097/) please can we bump the Grafana appVersion to 9.3.0
> [grafana] Bump Grafana Version to 9.3.0

- charts/loki-distributed/Chart.yaml
- charts/loki-distributed/README.md
- charts/loki-distributed/templates/distributor/poddisruptionbudget-distributor.yaml
- charts/loki-distributed/templates/gateway/poddisruptionbudget-gateway.yaml
- charts/loki-distributed/templates/index-gateway/poddisruptionbudget-index-gateway.yaml
- charts/loki-distributed/templates/ingester/poddisruptionbudget-ingester.yaml
- charts/loki-distributed/templates/memcached-chunks/poddisruptionbudget-memcached-chunks.yaml
- charts/loki-distributed/templates/memcached-frontend/poddisruptionbudget-memcached-frontend.yaml
- charts/loki-distributed/templates/memcached-index-queries/poddisruptionbudget-memcached-index-queries.yaml
- charts/loki-distributed/templates/memcached-index-writes/poddisruptionbudget-memcached-index-writes.yaml
- charts/loki-distributed/templates/querier/poddisruptionbudget-querier.yaml
- charts/loki-distributed/templates/query-frontend/poddisruptionbudget-query-frontent.yaml
- charts/loki-distributed/templates/query-scheduler/poddisruptionbudget-query-scheduler.yaml
- charts/loki-distributed/templates/ruler/poddisruptionbudget-ruler.yaml
Currently the chart creates `PodDisruptionBudget` for enabled components even if `maxUnavailable` value is not set. This results in resources which look like this:
```yaml
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
name: dimunech-loki-loki-distributed-distributor
labels:
helm.sh/chart: loki-distributed-0.66.2
app.kubernetes.io/name: loki-distributed
app.kubernetes.io/instance: dimunech-loki
app.kubernetes.io/version: "2.6.1"
app.kubernetes.io/component: distributor
spec:
selector:
matchLabels:
app.kubernetes.io/name: loki-distributed
app.kubernetes.io/instance: dimunech-loki
app.kubernetes.io/component: distributor
```
Such PDBs have neither `minAvailable` nor `maxUnavailable` defined, effectively functioning as if no disruptions are …
> [loki-distributed] Do not create PDBs if maxUnavailable value is not set

- charts/rollout-operator/Chart.yaml
- charts/rollout-operator/README.md
Updating the helm chart given the new release: [version cut PR](https://github.com/grafana/rollout-operator/pull/27)
There's no diff for the image tag specifically because by default it uses the `appVersion` as can be seen in this section from `values.yaml`:
```
image:
repository: grafana/rollout-operator
pullPolicy: IfNotPresent
tag: ""
```
> [rollout-operator] Update for v0.2.0 image

- charts/loki-distributed/Chart.yaml
- charts/loki-distributed/README.md
- charts/loki-distributed/templates/_helpers.tpl
- charts/loki-distributed/templates/distributor/hpa.yaml
- charts/loki-distributed/templates/gateway/hpa.yaml
- charts/loki-distributed/templates/ingester/hpa.yaml
- charts/loki-distributed/templates/querier/hpa.yaml
- charts/loki-distributed/templates/query-frontend/hpa.yaml
Hi, we migraded from loki-stack to loki-distributed helm chart, but our k8s cluster is running on 1.25.x version already. 
I ran into an issue with an unsupported apiVersion for HorizontalPodAutoscaler in loki-distributed helm chart, so I decided to add support for the autoscaling/v2 apiVersion.
Signed-off-by: Tomáš Novák <tomas.novak@bcas.cz>
> [loki-distributed] Add HPA support for k8s >=1.25-0

- charts/grafana/Chart.yaml
- charts/grafana/README.md
- charts/grafana/templates/_helpers.tpl
- charts/grafana/templates/_pod.tpl
- charts/grafana/templates/tests/test.yaml
- charts/grafana/values.yaml
Some parent charts of grafana have global values. As a user it is confusing when global values aren't consistently used across charts.
This PR adds support for global `imagePullSecrets`. This makes it easier for users of charts such as kube-prometheus-stack to configure custom pull secrets.
This is my first PR to Grafana. Any feedback is greatly appreciated.
> [grafana] Add support for global imagePullSecrets values

- charts/loki-distributed/Chart.yaml
- charts/loki-distributed/README.md
- charts/loki-distributed/templates/_helpers.tpl
- charts/loki-distributed/templates/compactor/deployment-compactor.yaml
- charts/loki-distributed/templates/distributor/deployment-distributor.yaml
- charts/loki-distributed/templates/gateway/_helpers-gateway.tpl
- charts/loki-distributed/templates/gateway/deployment-gateway.yaml
- charts/loki-distributed/templates/index-gateway/statefulset-index-gateway.yaml
- charts/loki-distributed/templates/ingester/deployment-ingester.yaml
- charts/loki-distributed/templates/ingester/statefulset-ingester.yaml
- charts/loki-distributed/templates/querier/deployment-querier.yaml
- charts/loki-distributed/templates/querier/statefulset-querier.yaml
- charts/loki-distributed/templates/query-frontend/deployment-query-frontend.yaml
- charts/loki-distributed/templates/query-scheduler/deployment-query-scheduler.yaml
- charts/loki-distributed/templates/ruler/deployment-ruler.yaml
- charts/loki-distributed/templates/ruler/statefulset-ruler.yaml
- charts/loki-distributed/templates/table-manager/deployment-table-manager.yaml
Fixes https://github.com/grafana/helm-charts/issues/1948 by running `sha256sum` against the template data in the configmaps instead of the configmap files.
Templating the configmap files causes the checksum to change during upgrades that only touch labels, which causes all pods to roll over. While the pod rolling is graceful, it should be avoided to prevent having to waste resources reloading caches and reading back WALs.
> [loki-distributed] Checksum the contents of configmaps instead of the resources

- charts/loki-distributed/Chart.yaml
- charts/loki-distributed/README.md
- charts/loki-distributed/templates/_helpers.tpl
Allow to use up-to-date api version for HPA, when it's already available in cluster. Don't wait for deprecated API to be removed.
Followup to https://github.com/grafana/helm-charts/pull/1956
> [loki-distributed] Relax autoscaling/v2 compatibility to 1.23

- charts/grafana/Chart.yaml
- charts/grafana/templates/_pod.tpl
- charts/grafana/templates/headless-service.yaml
- charts/grafana/templates/hpa.yaml
- charts/grafana/templates/statefulset.yaml
- charts/grafana/values.yaml
In PR https://github.com/grafana/helm-charts/pull/1971 a change was made that converted "statefulset" to a list of "sts" and "StatefulSet". This was a breaking change, since if you supplied "statefulset" it was no longer recognized. 
This PR also fixes a nil pointer when supplying a `global.imagePullSecrets`, but not a `image.pullSecrets` that was introduced in https://github.com/grafana/helm-charts/pull/2035
> [grafana] Fix image.pullSecret nil pointer and fix persistence.type missing "statefulset" type

- charts/grafana/Chart.yaml
- charts/grafana/templates/_pod.tpl
- fixes #2019 
- fixes #2044 
the condition for the `searchNamespaces` interpolation when enabling the `notifiers` sidecar was incorrect after the 6.44.0 migration.
hence, the  interpolation `{{ tpl (. | join ",") $root }}` did not succeed as `.` was the entire pod context.
> [grafana] fix broken interpolation for notifier searchNamespace in grafana chart

- charts/grafana/Chart.yaml
- charts/grafana/values.yaml
Fixes #18
Apparently the mysterious hangups of the sidecar process have vanished using the most recent version.
> [grafana] Bump sidecar image version

- charts/promtail/Chart.yaml
- charts/promtail/README.md
- charts/promtail/templates/_pod.tpl
I have changed the condition for extraContainers, because previously it was working only if deployment type was enabled, usually promtail use daemonset instead of deployment.
> [promtail] changed condition for extraContainers

- charts/grafana/Chart.yaml
- charts/grafana/README.md
- charts/grafana/templates/_pod.tpl
- charts/grafana/values.yaml
I noticed that when using the dashboards sidecar to provision dashboards no automatic reload is configured. Meanwhile the alerts and datasources sidecars are configured with the automatic reload.
> [grafana] Add ability to reload dashboard provisioning

- charts/tempo/Chart.yaml
- charts/tempo/README.md
- charts/tempo/templates/serviceaccount.yaml
- charts/tempo/values.yaml
I need to add additional labels to the service account so I can use Azure Workload Identity
Signed-off-by: Archie Lamb <git@archielamb.uk>
> [tempo] Allow adding additional ServiceAccount labels

- charts/loki-distributed/Chart.yaml
- charts/loki-distributed/README.md
- charts/loki-distributed/templates/distributor/hpa.yaml
- charts/loki-distributed/templates/gateway/hpa.yaml
- charts/loki-distributed/templates/ingester/hpa.yaml
- charts/loki-distributed/templates/querier/hpa.yaml
- charts/loki-distributed/templates/query-frontend/hpa.yaml
Followup to https://github.com/grafana/helm-charts/pull/2038
I forgot that there were schema changes between `autoscaling/v2beta1` and `autoscaling/v2`. Updated HPA templates to support old and new API version. Otherwise rendering of chart with any `...autoscaling.enabled=true` will fail with
```
Failed to render chart: exit status 1: Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: [ValidationError(HorizontalPodAutoscaler.spec.metrics[0].resource): unknown field "targetAverageUtilization" in io.k8s.api.autoscaling.v2.ResourceMetricSource, ValidationError(HorizontalPodAutoscaler.spec.metrics[0].resource): missing required field "target" in io.k8s.api.autoscaling.v2.ResourceMetricSource]
```
Signed-off-by: Ihor Urazov …
> [loki-distributed] Update HPAs to support autoscaling/v2 schema

- .github/workflows/release.yaml
- .github/workflows/sync-readme.yaml
This PR adds explicit [permissions section](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions) to workflows. This is a security best practice because by default workflows run with [extended set of permissions](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token) (except from `on: pull_request` [from external forks](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)). By specifying any permission explicitly all others are set to none. By using the principle of least privilege the damage a compromised workflow can do (because of an [injection](https://securitylab.github.com/research/github-actions-untrusted-input/) or compromised third party tool or …
> GitHub Workflows security hardening

- charts/grafana/Chart.yaml
- charts/grafana/templates/_helpers.tpl
When using SHA hashes in image tags, kubernetes rejects the resource with the following error message:
`<resource> is invalid: [metadata.labels: Invalid value: "<version@hash>": must be no more than 63 characters, metadata.labels: Invalid value: "<version@hash>": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue', or 'my_value', or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')]`
> [grafana] Fix for invalid labels

- charts/grafana/Chart.yaml
- charts/grafana/templates/image-renderer-deployment.yaml
- charts/grafana/templates/image-renderer-network-policy.yaml
- charts/grafana/templates/image-renderer-servicemonitor.yaml
- charts/grafana/values.yaml
* Add a ServiceMonitor for `grafana-image-renderer`
* Allow adding extra selectors to the `grafana-image-renderer` ingress network policy so that the Prometheus Operator can be allowed to query the metrics
> [grafana] Add a ServiceMonitor for grafana-image-renderer

- charts/promtail/Chart.yaml
- charts/promtail/README.md
- charts/promtail/templates/_helpers.tpl
- charts/promtail/templates/clusterrolebinding.yaml
- charts/promtail/templates/configmap.yaml
- charts/promtail/templates/daemonset.yaml
- charts/promtail/templates/deployment.yaml
- charts/promtail/templates/hpa.yaml
- charts/promtail/templates/networkpolicy.yaml
- charts/promtail/templates/role.yaml
- charts/promtail/templates/rolebinding.yaml
- charts/promtail/templates/secret.yaml
- charts/promtail/templates/service-extra.yaml
- charts/promtail/templates/service-metrics.yaml
- charts/promtail/templates/serviceaccount.yaml
- charts/promtail/values.yaml
This pull request makes it possible to configure the namespace the promtail to deploy outsides `.Release.Namespace`. It is useful if the user wrap all logging helm charts as an umbrella chart and want to deploy promtail into a different namespace.
Signed-off-by: Kirchen99 <latias_latios@126.com>
> [promtail] Allow to Configure Promtail Namespace

- charts/tempo-distributed/Chart.yaml
- charts/tempo-distributed/README.md
- charts/tempo-distributed/templates/querier/deployment-querier.yaml
- charts/tempo-distributed/templates/querier/hpa.yaml
- charts/tempo-distributed/values.yaml
Autoscaling support in the tempo-distributed helm chart was added in the following PR https://github.com/grafana/helm-charts/pull/1057, however it did not include autoscaling for the querier.
The tempo querier should be auto-scalable (https://github.com/grafana/helm-charts/pull/1057#issuecomment-1048858650), so this PR is adding the HPA for the querier, similar to the other tempo components.
> [tempo-distributed] add hpa for tempo querier

- charts/tempo-distributed/Chart.yaml
- charts/tempo-distributed/README.md
- charts/tempo-distributed/values.yaml
The Tempo compactor offers several flags to customize the compactor's behavior: https://grafana.com/docs/tempo/latest/configuration/#compactor
This PR allows us to pass these flags into the `values.yaml` file so that we can override the flags as needed.
Checklist
> [tempo-distributed] feat: add flags for compaction configs

- charts/tempo-distributed/Chart.yaml
- charts/tempo-distributed/README.md
- charts/tempo-distributed/templates/gateway/service-gateway.yaml
- charts/tempo-distributed/values.yaml
This creates a way to use the gateway for more complex scenarios in combination with .Values.gateway.nginxConfig.httpSnippet.
> [tempo-distributed] Add capability to define additional ports on gateway service

- charts/loki-distributed/Chart.yaml
- charts/loki-distributed/README.md
- charts/loki-distributed/templates/ingester/statefulset-ingester.yaml
Currently, if ingester is deployed in StatefulSet mode and HPA is enabled, pods are constantly being created and immediately terminated due to conflicts between StatfulSet `replicas` and HPA `desiredReplicas`. This PR fixes this issue.
> [loki-distributed] Do not set ingester StatefulSet replicas when HPA enabled

- charts/tempo-distributed/Chart.yaml
- charts/tempo-distributed/README.md
- charts/tempo-distributed/values.yaml
This is a followup from my earlier MR: https://github.com/grafana/helm-charts/pull/2086
I accidentally omitted part of the documentation for the `compactor.config.compaction.max_time_per_tenant` flag
Checklist
> [tempo-distributed] fix(docs): typo on compactor.config.compaction.max_time_per_tenant flag

- charts/grafana/Chart.yaml
- charts/grafana/templates/_helpers.tpl
- charts/grafana/templates/hpa.yaml
- charts/grafana/templates/image-renderer-deployment.yaml
- charts/grafana/templates/image-renderer-hpa.yaml
- charts/grafana/values.yaml
* Update the `grafana.hpa.apiVersion` helper to support the `autoscaling/v2beta2` API
* Update the Grafana HPA to allow configuring scaling behavior
* Add optional autoscaling for the `grafana-image-renderer`deployment
> [grafana] Allow to configure HPA scaling behavior and add autoscaling for grafana-image-renderer

- charts/tempo-distributed/Chart.yaml
- charts/tempo-distributed/README.md
- charts/tempo-distributed/templates/_helpers.tpl
- charts/tempo-distributed/templates/compactor/_helpers-compactor.tpl
- charts/tempo-distributed/templates/compactor/deployment-compactor.yaml
- charts/tempo-distributed/templates/distributor/_helpers-distributor.tpl
- charts/tempo-distributed/templates/distributor/deployment-distributor.yaml
- charts/tempo-distributed/templates/gateway/_helpers-gateway.tpl
- charts/tempo-distributed/templates/gateway/deployment-gateway.yaml
- charts/tempo-distributed/templates/ingester/_helpers-ingester.tpl
- charts/tempo-distributed/templates/ingester/statefulset-ingester.yaml
- charts/tempo-distributed/templates/memcached/_helpers-memcached.tpl
- charts/tempo-distributed/templates/memcached/statefulset-memcached.yaml
- charts/tempo-distributed/templates/metrics-generator/_helpers-metrics-generator.tpl
- charts/tempo-distributed/templates/metrics-generator/deployment-metrics-generator.yaml
- charts/tempo-distributed/templates/querier/_helpers-querier.tpl
- charts/tempo-distributed/templates/querier/deployment-querier.yaml
- charts/tempo-distributed/templates/query-frontend/_helpers-query-frontend.tpl
- charts/tempo-distributed/templates/query-frontend/deployment-query-frontend.yaml
- charts/tempo-distributed/values.yaml
There are many reasons to not use docker.io public registry, e.g.:
- docker.io pull rate limit is really low and this release usually pulls 10 or more images. Ref: https://www.docker.com/increase-rate-limits/
- to use modified images from private registry
This can be enabled by simply adding imagePullSecrets
ref: https://kubernetes.io/docs/concepts/containers/images/#specifying-imagepullsecrets-on-a-pod
> [tempo-distributed] feat: Enable usage of private docker registry

- .github/workflows/release.yaml
- cr.yaml
There are a few reasons for this:
* The GPG key being used was potentially compromised related to a recent security incident in another CI tool which had this GPG private key as a secret
* We consider these "public" helm charts, we don't want the existence of a signature to indicate a level of scrutiny or security that doesn't exist.
* The public key was never published to a key server as far as we can tell and as such we doubt anyone is actually using this as it it's extremely difficult right now to find the public key
* You should always verify changes made when updating a chart as both good operational and security practice.
In short: at best this signing provides little value, at worst a false sense of security.
> Disable helm chart signing and provenance

- charts/tempo-distributed/Chart.yaml
- charts/tempo-distributed/README.md
- charts/tempo-distributed/values.yaml
This PR allows us to customize all of the flags under the `compactor.compaction` configs: https://grafana.com/docs/tempo/latest/configuration/#compactor
Related to a [previous PR](https://github.com/grafana/helm-charts/pull/2086) which added a few of these flags, but not all of them.
Checklist:
> [tempo-distributed] feat(tempo-distributes/values.yaml): add remaining tempo compaction flags

- charts/tempo-distributed/Chart.yaml
- charts/tempo-distributed/README.md
- charts/tempo-distributed/values.yaml
@joe-elliott: Second attempt at this. New fork, new branch, with essentially the same changes.  Hopefully this time we got it right. The other PR (https://github.com/grafana/helm-charts/pull/2070) can be deleted if all is well with this one.
> [tempo-distributed] add metrics_generator_processors when metrics generator is enabled

- charts/grafana/Chart.yaml
- charts/grafana/README.md
- charts/grafana/values.yaml
There is a new sidecar upgrade which respects changes to destination folders:
* https://github.com/kiwigrid/k8s-sidecar/releases/tag/1.22.0
This PR updates the tag and updates the README.md.
> [grafana] Bump sidecar version to 1.22.0

- charts/grafana/Chart.yaml
- charts/grafana/templates/image-renderer-network-policy.yaml
- charts/grafana/templates/image-renderer-servicemonitor.yaml
* Fix the grafana-image-renderer network policies
* The namespace and pods selectors need to be in the same rule to really match only the Grafana pods and nothing else from the same namespace
* The egress policy needs to target the target port of the Grafana service
* Use the proper target labels value for the `grafana-image-renderer` ServiceMonitor (see https://github.com/grafana/helm-charts/pull/2130#pullrequestreview-1263011569)
> [grafana] Fix grafana-image-renderer network policies and service monitor

- charts/tempo-distributed/Chart.yaml
- charts/tempo-distributed/README.md
- charts/tempo-distributed/templates/distributor/service-distributor-discovery.yaml
This merge request will add a [headless service](https://kubernetes.io/docs/concepts/services-networking/service/#headless-services) for the tempo-distributor.
When the OpenTelemetry Collector is using the [Load Balancing Exporter](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/exporter/loadbalancingexporter/README.md), and the load balancing exporter is configured to used the `dns` resolver, a headless service for the tempo-distributor is required for the dns resolver to get all endpoints. Without a headless service, the load balancing exporter will only see the Kubernetes service IP, and not the endpoints.
If you have suggestions, improvements or questions, feel free to ask or enlighten me.
> [tempo-distributed] add headless service for tempo-distributor

- charts/grafana/Chart.yaml
- charts/grafana/README.md
- charts/grafana/templates/_pod.tpl
- charts/grafana/templates/headless-service.yaml
- charts/grafana/values.yaml
* The guide for H/A defines ha_peers port as 9094
* https://github.com/grafana/helm-charts/tree/main/charts/grafana#high-availability-for-unified-alerting
ISSUE:
* When i set the ha_peers value as {{ Name }}-headless:9094, i get a lookup error. 
* I also get an (failed to join)error when i set it to port 3000 
* I've made changes to my helm-generated-yaml and i don't get the error log anymore, and is working as intended. I applied the changes i made to the chart. please review! thanks
> [grafana] H/A gossip port bug fix

- charts/grafana/Chart.yaml
See:
https://github.com/grafana/helm-charts/pull/2146
Fixing release doesn't get thru because the chart version didn't get bumped.
> [grafana] fix PR 2146 release

- charts/loki-distributed/Chart.yaml
- charts/loki-distributed/README.md
- charts/loki-distributed/templates/query-frontend/service-query-frontend.yaml
Revert [loki-distributed] Update query-fronted service to set clusterIP #2110 
Fixes https://github.com/grafana/helm-charts/issues/2127
Signed-off-by: Siebren Zwerver siebren@siebjee.nl
> [loki-distributed] Revert: Update query-fronted service to set clusterIP #2110

- charts/grafana/Chart.yaml
See details about included hotfixes (since 9.3.1):
- https://github.com/grafana/grafana/releases/tag/v9.3.2
- https://github.com/grafana/grafana/releases/tag/v9.3.4
- https://github.com/grafana/grafana/releases/tag/v9.3.6
> [grafana] bump default grafana image tag to 9.3.6

- charts/loki-distributed/Chart.yaml
- charts/loki-distributed/README.md
- charts/loki-distributed/values.yaml
The previous version of loki [included](https://github.com/grafana/helm-charts/blob/5ec00d6923c3045e3c387f8367ed90193998a70c/charts/loki-distributed/values.yaml#L86) a wrong compactor address, which caused the following errors from other components:
```
level=error ts=2023-01-13T09:47:29.06565832Z caller=http.go:131 msg="error getting cache gen numbers from the store" err="Get \"loki-distributed-qa-compactor:3100\": unsupported protocol scheme \"loki-distributed-qa-compactor\""
```
This changes fix compactor address by adding `http://` protocol schema.
Related comment: https://github.com/grafana/loki/pull/3109#discussion_r551354841
Signed-off-by: junwei.liang <junwei.liang@mintegral.com>
> [loki-distributed] Fix compactor address without protocol schema

- charts/grafana/Chart.yaml
- charts/grafana/templates/_pod.tpl
- charts/grafana/templates/headless-service.yaml
- charts/grafana/values.yaml
This change will expose the UDP port needed by the gossip protocol. It also changes the name of the gossip port, as the old one was too long (15 chars limit on port names in Kubernetes).
> [grafana] Alerting: expose UDP port

- charts/promtail/Chart.yaml
- charts/promtail/README.md
Just the patch update for promtail from 2.7.1 → 2.7.2
See: https://github.com/grafana/loki/releases/tag/v2.7.2
> [promtail] bump default Promtail image tag to 2.7.2

- charts/grafana/Chart.yaml
- charts/grafana/README.md
- charts/grafana/templates/_pod.tpl
- charts/grafana/values.yaml
when its possible to set a alternative `command` for the grafana container, it should also be possible to set `args` for this command.
would be useful when using hashicorp/envconsul.
Signed-off-by: gietschess <49275246+gietschess@users.noreply.github.com>
> [grafana] option to allow optional args

- charts/loki-stack/Chart.yaml
- charts/loki-stack/templates/tests/loki-test-configmap.yaml
- charts/loki-stack/templates/tests/loki-test-pod.yaml
- charts/loki-stack/values.yaml
In some enterprise environments it's forbidden to let everything communicate with the internet. In such cases we need an option to disable components that want to do that to not have a broken pod in the cluster. That's why I added the option to disable the test_pod even if loki itself is enabled, expanding [#1835](https://github.com/grafana/helm-charts/pull/1835).
> [loki-stack] Make it possible to disable the loki test_pod.

- charts/tempo-distributed/Chart.yaml
- charts/tempo-distributed/README.md
- charts/tempo-distributed/values.yaml
**What this PR does:**
Previously, the Admin Client section of the chart for Grafana
Enterprise Traces was only configured should MinIO be enabled.
These changes:
* Add a new `storage.admin` section for configuring the client
backend storage type and bucket details.
* Finally, the README has been updated to document the new
admin storage configuration section.
This commit fixes https://github.com/grafana/helm-charts/issues/2112.
Signed-off-by: Heds Simons <hedley.simons@grafana.com>
**Checklist**
[ ] Tests updated
[x] Documentation added
> [tempo-distributed] Ensure that Admin Client is configured with relevant details.

- charts/tempo-distributed/Chart.yaml
- charts/tempo-distributed/README.md
- charts/tempo-distributed/values.yaml
This PR enables a user to configure the options under `query.search.*`: https://grafana.com/docs/tempo/latest/configuration/#querier
I came across this need while trying to set up a serverless backend for the tempo-querier deployment, and described in this guide: https://grafana.com/docs/tempo/latest/operations/serverless_gcp/
Checklist
> [tempo-distributed] feat: add configs for querier.search.* to values.yaml

- charts/tempo-distributed/Chart.yaml
- charts/tempo-distributed/README.md
- charts/tempo-distributed/values.yaml
I added a config option for `querier.config.search.external_endpoints` in a previous PR: https://github.com/grafana/helm-charts/pull/2195 but I forgot to call `toYaml` on it. I believe it needs the `toYaml` call because it is a `list` type.
While this doesn't cause an issue for regular strings:
```
querier:
config:
search:
external_endpoints:
- https://my-serverless-endpoint-asdf-uw.a.run.app
```
when we pass in an env var:
```
querier:
config:
search:
external_endpoints:
- ${MY_SERVERLESS_ENDPOINT}
```
we get the following error:
```
Error: 'error converting YAML to JSON: yaml: line 87: did not find expected '','' or '']'''
```
This PR fixes the bug.
I tested locally and can confirm the fix using both a single item and multi-item list.
Checklist:
> [tempo-distributed] call toYaml on list data type

- charts/promtail/Chart.yaml
- charts/promtail/README.md
See also: https://github.com/grafana/loki/releases/tag/v2.7.3
> [promtail] bump default promtail image tag to 2.7.3

- charts/tempo-distributed/Chart.yaml
- charts/tempo-distributed/README.md
- charts/tempo-distributed/values.yaml
This PR adds several configuration parameters for the querier and querier_frontend deployments.
For context, I've been following this guide to optimize the performance of TraceQL on my queriers, so having access to these configurations is required:
https://github.com/grafana/tempo/blob/9ad992451a657a2a221dc8e526295bc5e347e62a/docs/sources/operations/backend_search.md#L67
Checklist:
> [tempo-distributed] Add support to optimize TraceQL queries

- charts/promtail/Chart.yaml
- charts/promtail/README.md
- charts/promtail/templates/_pod.tpl
- charts/promtail/templates/servicemonitor.yaml
- charts/promtail/values.yaml
Hi,
on large clusters, the rollout of promtail could take some time. This PR extends the current helm chart by an config reloader sidecar. It depends on https://github.com/grafana/loki/pull/7247.
I used the config-reloader images from prometheus helm chart. config-reloader implements inotify to detect changes instantly.
> [promtail] Implement config-reloader

- charts/grafana/Chart.yaml
- charts/grafana/templates/configmap.yaml
- charts/grafana/values.yaml
Hey everyone,
Tried to import a dashboard from a private Azure Repos but this needs an authorization header which is currently not supported by the chart.
See the [documentation](https://learn.microsoft.com/en-us/azure/devops/organizations/accounts/use-personal-access-tokens-to-authenticate?view=azure-devops&tabs=Windows#use-a-pat).
> [grafana] Basic auth for dashboard downloader

- charts/grafana/Chart.yaml
- charts/grafana/README.md
- charts/grafana/templates/configmap.yaml
Hello everyone,
our team is migrating all our alert rules to the new provisioning mechanism and we were having trouble with the current Helm chart because the contents of each `rules.yaml` file must be inlined, making the `values.yaml` files extremely long.
I added the possibility of importing a YAML using the `file:` key similar to the mechanism for the dashboards. The configuration in `values.yaml` looks like this:
```yaml
alerting:
team1-alert-rules.yaml:
file: alerting/team1/rules.yaml
team2-alert-rules.yaml:
file: alerting/team2/rules.yaml
team3-alert-rules.yaml:
file: alerting/team3/rules.yaml
``` 
I hope this helps other users of the Helm chart. Thank you!
> [grafana] Support including YAML files with alert rules using the `file` subkey.

- charts/grafana/Chart.yaml
- charts/grafana/templates/image-renderer-network-policy.yaml
The currently defined network policy only works when the image renderer
is matching the authorized namespace based on the `name` label, which is
not a label all kubernetes namespace have, but instead a widely used but
nevertheless not universal label.
The default label for all namespace, added by the API server, is
`kubernetes.io/metadata.name`, as documented here:
https://kubernetes.io/docs/reference/labels-annotations-taints/#kubernetes-io-metadata-name
By changing this labelSelector for the `namespaceSelector` clause, we
permit users of kubernetes distribution where no `name` label is
set on namespaces to use the image renderer without issue,
and we don't impact the usability of other users.
> [grafana] fix image-renderer network policy

- charts/tempo-distributed/Chart.yaml
- charts/tempo-distributed/README.md
- charts/tempo-distributed/templates/_helpers.tpl
- charts/tempo-distributed/templates/distributor/hpa.yaml
- charts/tempo-distributed/templates/gateway/hpa.yaml
- charts/tempo-distributed/templates/ingester/hpa.yaml
- charts/tempo-distributed/templates/querier/hpa.yaml
- charts/tempo-distributed/templates/query-frontend/hpa.yaml
> autoscaling/v2beta1 HorizontalPodAutoscaler is deprecated in v1.22+, unavailable in v1.25+; use autoscaling/v2 HorizontalPodAutoscaler
Taken [inspiration](https://github.com/grafana/helm-charts/blob/main/charts/loki-distributed/templates/_helpers.tpl#L144-L153) from [loki-distributed Helm chart](https://github.com/grafana/helm-charts/blob/main/charts/loki-distributed/).
This Pull Request will make the Horizontal Pod Autoscaling resources toggle between `autoscaling/v2beta1` and `autoscaling/v2` depending on whether the the cluster can support the `apiVersion` or not.
I noticed the issue https://github.com/grafana/helm-charts/issues/1944 to avoid `apiVersion` toggling, but perhaps this can be merged and then adjusted later when / if a cleanup is happening?
> [tempo-distributed] use appropriate HorizontalPodAutoscaling apiVersion

- charts/grafana/Chart.yaml
See details about included hotfixes (since 9.3.6):
- v9.3.7 was never released → but the changes are listed as 9.3.7 here: https://github.com/grafana/grafana/blob/main/CHANGELOG.md#938-2023-02-28
- https://github.com/grafana/grafana/releases/tag/v9.3.8
> [grafana] bump default grafana image tag to 9.3.8

- charts/tempo-distributed/Chart.yaml
- charts/tempo-distributed/README.md
- charts/tempo-distributed/values.yaml
after https://github.com/grafana/helm-charts/pull/1759 was merged, the tempo-distributed chart unexpectedly installed minio in our k8s cluster which resulted in a bunch of new pods crash looping and setting off prom alerts. as a side note, something about the way the minio chart generates resources causes a bunch of merge conflicts in our gitops CI commitback logic. because of this, the helm principal that charts should always be installable using only default values, and the below linked commit, it seems best to disable minio by default
ref: https://github.com/grafana/helm-charts/pull/1759#issuecomment-1448460904
> [tempo-distributed] fix: disable minio by default

- charts/grafana/Chart.yaml
- charts/grafana/templates/clusterrole.yaml
- charts/grafana/templates/clusterrolebinding.yaml
as long as .Values.rbac.extraClusterRoleRules is explicitly defined the cluster-scoped rbac resources (clusterrole and its binding) should be created.
> [grafana] rbac cluster-scoped resource creation conditions

- charts/fluent-bit/Chart.yaml
- charts/fluent-bit/README.md
- charts/fluent-bit/templates/daemonset.yaml
- charts/fluent-bit/values.yaml
In order to comply with certain audit policies I'd like to set a securityContext on the fluent-bit pod.
It seems in the past a podSecurityPolicy was supplied, but that mechanism is deprecated now.
Would it be possible to add this support?
Sorry for opening the PR twice,  I'm new to contributing and I got lost in the whole signing procedure.
Kind regards,
Robin
> [fluent-bit] Add securityContext support

- charts/loki-canary/Chart.yaml
- charts/loki-canary/README.md
- charts/loki-canary/templates/_helpers.tpl
- charts/loki-canary/templates/daemonset.yaml
- charts/loki-canary/templates/secret.yaml
- charts/loki-canary/templates/service.yaml
- charts/loki-canary/templates/serviceaccount.yaml
- charts/loki-canary/values.yaml
As it was done for promtail https://github.com/grafana/helm-charts/pull/2064, now for loki-canary.
> [loki-canary] Allow to configure canary namespace and update to latest app version (2.7.4)

- charts/tempo/Chart.yaml
- charts/tempo/README.md
- charts/tempo/templates/statefulset.yaml
I got an error when I enabled metricsGenerator:
```
/tmp/tempo: read-only file system
```
To fix this, this PR makes /tmp mounted to emptyDir
> [tempo] Make tmp directory read/write when using metricsGenerator

- charts/grafana/Chart.yaml
bumped Grafana to the latest version `9.4.3` released on the 2nd of March, 2023 (https://github.com/grafana/grafana/blob/main/CHANGELOG.md)
> [grafana] bumped grafana version to 9.4.3

- charts/grafana/Chart.yaml
- charts/grafana/templates/configmap.yaml
- charts/grafana/values.yaml
Hey,
The cURL Accept header needs to be different from the default _"application/json"_ in order to download from Azure repos.
You won't receive the actual file content in the response if the default one is used.
> [grafana] Possibility to change Accept header for dashboard downloader

- charts/tempo-distributed/Chart.yaml
- charts/tempo-distributed/README.md
- charts/tempo-distributed/values.yaml
Update the default enterprise traces image to the newly released 2.0.1.
> [tempo-distributed] Update default enterprise traces image

- charts/grafana/Chart.yaml
- charts/grafana/README.md
- charts/grafana/templates/pvc.yaml
- charts/grafana/values.yaml
In the default configuration (using deployment instead of statefulset), a pod eviction can delete the persistent volume. Using StatefulSet helps somewhat, but I can sleep better at night if I know that my grafana persistent volume is not easily accidentally deleted. (This keeps the kubernetes default of `Delete` but can be set to e.g. `Retain`)
> [grafana] Allow setting persistentVolumeReclaimPolicy for persistent volume

- charts/rollout-operator/Chart.yaml
- charts/rollout-operator/README.md
Updating the helm chart to correspond with the new [release](https://github.com/grafana/rollout-operator/releases/tag/v0.4.0) and [image](https://hub.docker.com/layers/grafana/rollout-operator/v0.4.0/images/sha256-f4c1cd20f97e6ca2248ed3c2e50d8d221a0ea2e7b431d9c56a9c001bcfd1984d?context=explore)
> [rollout-operator] Update for v0.4.0

- charts/loki-distributed/Chart.yaml
- charts/loki-distributed/README.md
- charts/loki-distributed/templates/ruler/statefulset-ruler.yaml
Permits running sidecars in the Loki ruler pods. This is possible with the deployments, just not the statefulset.
> [loki-distributed] Add extraContainers to loki distributed ruler statefulset

- charts/fluent-bit/Chart.yaml
- charts/fluent-bit/README.md
- charts/fluent-bit/templates/daemonset.yaml
- charts/fluent-bit/templates/serviceaccount.yaml
- charts/fluent-bit/values.yaml
This PR adds the option to disable automounting serviceaccount tokens, both on the serviceaccount level and on the pods. 
This option is important as a best practice, because pods that don't make calls to the Kubernetes API should not have a Kubernetes API token in the first place.
> [fluent-bit] Add automountServiceAccountToken variable

- charts/promtail/Chart.yaml
- charts/promtail/README.md
- charts/promtail/templates/hpa.yaml
`autoscaling/v2beta1` is deprecated and is removed in Kubernetes v1.25+.
> [promtail] support HPA in k8s v1.25+

- charts/grafana/Chart.yaml
- charts/grafana/README.md
`ingressClassName` info is available in other helm charts but was missing in Grafana chart
> [grafana] add ingressClassName information

- charts/grafana/Chart.yaml
- charts/grafana/README.md
I've added an example of k8 secret to make it easier for new users to complete the datasource configuration.
> [grafana] docs: Add example of datasource secret to README

- charts/grafana/Chart.yaml
- charts/grafana/values.yaml
This adds the missing controls to permit the `grafana` container to run under https://kubernetes.io/docs/concepts/security/pod-security-standards/#restricted
> [grafana] set security controls for pod-security-standards restricted

- charts/grafana/Chart.yaml
- charts/grafana/values.yaml
My auditors want fully qualified container images, I figured others would probably benefit from this as well.
> [grafana] use fully qualified container names

- charts/loki-distributed/Chart.yaml
- charts/loki-distributed/README.md
- charts/loki-distributed/values.yaml
Fixes https://github.com/grafana/helm-charts/issues/2348 by using the headless service instead of the regular. This causes the config to work properly for multiple instances of query frontend
> [loki-distributed] fix: querry-frontend url

- charts/promtail/Chart.yaml
- charts/promtail/README.md
- charts/promtail/templates/_helpers.tpl
loki.serviceName is no longer used anywhere.
The dependency on loki.serviceName was removed in commit 9b576e19 ([promtail] Refactor chart).
> [promtail] remove definition of loki.serviceName

- charts/grafana/Chart.yaml
- charts/grafana/templates/deployment.yaml
- charts/grafana/templates/statefulset.yaml
This change introduces the `kubectl.kubernetes.io/default-container` annotations to the `grafana` pod to make kubectl default to this container when running `kubectl exec` or `kubectl logs`.
> [grafana] add default-container annotation to default to grafana container

- charts/grafana/Chart.yaml
let's move forward and use new and shiny grafana 9.5 by default
> [grafana] update chart to use grafana 9.5.1 by default

- charts/grafana/Chart.yaml
- charts/grafana/templates/_pod.tpl
This PR corrects templating in `extraConfigmapMounts.subPath` which is currently failing even with the included default. As a result, a value must be supplied in the field.
Fixes #1446
> [grafana] Correct subPath in extraConfigmapMounts

- charts/tempo/Chart.yaml
- charts/tempo/README.md
- charts/tempo/values.yaml
tempo-query was required for Grafana version <7.5 for compatibility with jaeger-ui. grafana version <7.5 didn't have Tempo datasource, and we used jaeger datasource to query tempo via tempo-query.
Grafana 7.5 was released on Mar 25, 2021, which was 2+ year ago.
> [tempo] Disable tempo-query by default

- charts/promtail/Chart.yaml
- charts/promtail/README.md
- charts/promtail/values.yaml
As promtail helm template working with annotation, level, it should be moved to root level of ports in example values.yaml
> [promtail] fix: extraPort metadata placement

- charts/grafana/Chart.yaml
- charts/grafana/README.md
- charts/grafana/templates/image-renderer-deployment.yaml
- charts/grafana/values.yaml
This allows using secrets or configmaps in-cluster to configure options for the image-renderer.
This is useful for setting the renderer token via an in-cluster secret.
From grafana/grafana-image-renderer#420
> [grafana] Add envValueFrom to image-renderer

- charts/promtail/Chart.yaml
- charts/promtail/README.md
As it seems there are no breaking changes concerning promtail between 2.7.4 and 2.8.2, 
this PR aim to bump promtail version (resolves #2379).
> [promtail] bump promtail version to 2.8.2

- charts/grafana/Chart.yaml
See also https://github.com/grafana/grafana/releases/tag/v9.5.2
> [grafana] bump default grafana image tag to 9.5.2

- charts/tempo-distributed/Chart.yaml
- charts/tempo-distributed/README.md
- charts/tempo-distributed/values.yaml
- Updates tempo-distributed to use GET 2.1.0
- Removes deprecated config in Tempo 2.1
> [tempo-distributed] Update for GET 2.1.0

- charts/tempo/Chart.yaml
- charts/tempo/README.md
- charts/tempo/templates/statefulset.yaml
- charts/tempo/values.yaml
The appversion was updated in the chart, but the actual images use these tags for some reason.
> [tempo] Correctly sets the Tempo version for 2.1.1

- charts/tempo-distributed/Chart.yaml
- charts/tempo-distributed/README.md
- charts/tempo-distributed/templates/query-frontend/service-query-frontend-discovery.yaml
The `publishNotReadyAddresses` flag seems to be set in the jsonnet version of the deployment but is missing in the helm chart and prevents the `query-frontend-discovery` service to expose its underlying pods. 
fixes: https://github.com/grafana/helm-charts/issues/2404
> [tempo-distributed] fix missing `publishNotReadyAddresses` in  query-frontend-discovery service

- charts/grafana/Chart.yaml
- charts/grafana/values.yaml
This adds another security control on the grafana container.  It shouldn't be user visible as no properly functioning grafana container should try to escalate its privileges.
> [grafana] default allowPrivilegeEscalation=false

- charts/grafana/Chart.yaml
This adds a link in artifacthub.io to the chart source.  Which is handy sometimes...
> [grafana] Add links to chart source

- charts/grafana/Chart.yaml
- charts/grafana/README.md
- charts/grafana/values.yaml
There is a new sidecar upgrade which fixes some regressions introduced in 1.22.0:
- https://github.com/kiwigrid/k8s-sidecar/releases/tag/1.24.3
This PR updates the tag, updates the README.md, and bumps the grafana chart version 6.56.6.
> [grafana] bump sidecar version to 1.24.3

- charts/grafana/Chart.yaml
- charts/grafana/README.md
- charts/grafana/templates/secret-env.yaml
- charts/grafana/values.yaml
All .Values.env values are already pass through tpl. I would like to have the same behavior for secrets, too.
https://github.com/grafana/helm-charts/blob/eb55960453f49814d3234fd4417ffb2d5b127b80/charts/grafana/templates/_pod.tpl#L950-L953
> [grafana] Use tpl in envSecrets

- charts/rollout-operator/Chart.yaml
- charts/rollout-operator/README.md
[New release](https://github.com/grafana/rollout-operator/releases/tag/v0.6.0)
> [rollout-operator] Bump rollout-operator version to 0.6.0

- charts/grafana/Chart.yaml
[Grafana security release](https://grafana.com/blog/2023/06/06/grafana-security-release-new-grafana-versions-with-security-fixes-for-cve-2023-2183-and-cve-2023-2801/)
See also: https://github.com/grafana/grafana/releases/tag/v9.5.3
> [grafana] bump default grafana image tag to 9.5.3

- charts/promtail/Chart.yaml
- charts/promtail/README.md
- charts/promtail/values.yaml
This saves the enduser from having to copy and modify the entire `config.file` block, just to update the `positions` block. As that might be required, as the default of `/run/promtail/positions.yaml` will not work everywhere, as `/run` might be a tmpfs.
> [promtail] make config positions block more easily configurable

- .github/workflows/release.yaml
- cr.yaml
* Enables release note generation via an [option](https://github.com/helm/chart-releaser#create-github-releases-from-helm-chart-packages) provided by chart-releaser. chart-releaser uses GitHub's feature for automatic release note generation ([docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes](https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes)).
* Current release notes provided in the release are unusable with tools like [Renovate](https://github.com/renovatebot/renovate).
* Closes #1034
> chore(github): Generate release notes

- charts/promtail/Chart.yaml
- charts/promtail/README.md
- charts/promtail/templates/deployment.yaml
- charts/promtail/values.yaml
Hey folks 👋 ,
Little PR here to add that capability to set the update strategy to the deployment object of Promtail
It is especially useful when we deploy a promtail agent in "Push API" mode as a kubernetes deployment object and that we want to control the way the update is performed
Don't hesitate to ask me if you have any questions
Cheers 😉
> [promtail] add update strategy to deployment

- charts/promtail/Chart.yaml
- charts/promtail/README.md
- charts/promtail/templates/_pod.tpl
When using the configuration `.Values.configmap.enabled` to use a Configmap instead of Secret for storing the configuration,
the checksum annotation used to force a pod re-roll is missing.
> [promtail] bugfix: Checksum annotation

- .github/workflows/release.yaml
Fixes #2395
This PR start to publish OCI helm charts to ghcr.io/grafana/charts/, e.g. : `ghcr.io/grafana/charts/grafana`
Bitnami recently switches to OCI as default source for helm charts
* https://blog.bitnami.com/2023/04/httpsblog.bitnami.com202304bitnami-helm-charts-now-oci.html
and prometheus-community enable OCI based helm charts, too:
* https://github.com/prometheus-community/helm-charts/pull/3433
Fetch charts over OCI has multiple benefits:
* It's not longer necessary to download the 1.6M chart [index.yaml](https://grafana.github.io/helm-charts/index.yaml) each time.
* Mirroring to air-gapped environments would much easier, since existing service like Azure Container Registry, Elastic Container Registry and GoHarbor can be used to store/cache the helm charts.
I'm aware that this PR …
> Enable OCI chart push

- charts/tempo-distributed/Chart.yaml
- charts/tempo-distributed/README.md
- charts/tempo-distributed/templates/distributor/hpa.yaml
- charts/tempo-distributed/templates/gateway/hpa.yaml
- charts/tempo-distributed/templates/ingester/hpa.yaml
- charts/tempo-distributed/templates/querier/hpa.yaml
- charts/tempo-distributed/templates/query-frontend/hpa.yaml
- charts/tempo-distributed/values.yaml
We ran into a use case where it would have been helpful to fine tune a little bit HPA behaviour.
This PR will allow to optionally define a behaviour on the HorizontalPodAutoscaler resource. See https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/ and https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.24/#horizontalpodautoscalerspec-v2-autoscaling for reference.
> [tempo-distributed] Add support for HPA behavior customization

- .github/workflows/release.yaml
Reverts grafana/helm-charts#2443
@zanhsieh Here is the rollback. 
This PR set the error to an warning which give the time to do the correct config while the workflow is not blocked.
In https://github.com/prometheus-community/helm-charts/blob/8b91a619e9407c0e830df7071ee73cd160937b6b/.github/workflows/release.yaml#L52-L60, we are using the same workflow, it seems like that packages are not configured yet to allow an push from actions.
An Grafana org admin has to set this in order to allow helm push from the pipeline: https://docs.github.com/en/packages/managing-github-packages-using-github-actions-workflows/publishing-and-installing-a-package-with-github-actions#upgrading-a-workflow-that-accesses-a-registry-using-a-personal-access-token
The documentations also describe that a Personal …
> Revert "Enable OCI chart push"

- charts/tempo-distributed/Chart.yaml
- charts/tempo-distributed/README.md
Changes from https://github.com/grafana/helm-charts/pull/2462 were not propagated, so bumping chart version to have new release should help fix it.
> [tempo-distributed] Bump chart version to 1.4.5

- charts/grafana/Chart.yaml
There are no breaking changes in this update. See the Grafana [changelog](https://github.com/grafana/grafana/blob/main/CHANGELOG.md#955-2023-06-22) for details.
> [grafana] Update Grafana to v9.5.5

- charts/grafana/Chart.yaml
update grafana default version to `v10.0.1`
[grafana v10.0.1 changelog](https://github.com/grafana/grafana/blob/main/CHANGELOG.md#1001-2023-06-22)
> [grafana] bump default grafana version 10.0.1

- charts/grafana/Chart.yaml
- charts/grafana/README.md
- charts/grafana/values.yaml
There is a new sidecar upgrade which fixes some vulns:
- https://github.com/kiwigrid/k8s-sidecar/releases/tag/1.24.6
> [grafana] bump kiwigrid/k8s-sidecar version to 1.24.6

- charts/grafana/Chart.yaml
- fixes #2487
- fix Chart.yaml
- Add [license annotations](https://artifacthub.io/docs/topics/annotations/helm/#supported-annotations)
- Improved searchability
- Add keywords
- Improved searchability
- Remove `engine: gotpl`
- [helm v3](https://helm.sh/docs/topics/charts/#the-chartyaml-file) not allows `engine: gotpl`
> [grafana] fix Chart.yaml - add license and keywords, remove gotpl

- charts/grafana/Chart.yaml
Just bumping up the Grafana tag to `v10.0.2` (from `v10.0.1`).
> [grafana] Update Grafana to v10.0.2

- charts/tempo-distributed/Chart.yaml
- charts/tempo-distributed/README.md
- charts/tempo-distributed/values.yaml
Replace deprecated `failure-domain.beta.kubernetes.io/zone` by `topology.kubernetes.io/zone` in `TopologySpreadConstraints`
> [tempo-distributed] Replace deprecated failure-domain topology

- charts/grafana/Chart.yaml
- charts/grafana/README.md
- charts/grafana/templates/_pod.tpl
Currently the k8s-sidecar container will always use basic authentication when REQ_USERNAME and REQ_PASSWORD are set. This can cause issues when attempting to use any configmaps/secrets with `*.url` key configured.
There is an open bug issue here: https://github.com/kiwigrid/k8s-sidecar/issues/290
However when `sidecar.dashboards.skipReload` is **true** there doesn't seem to be a need/reason to set the REQ_USERNAME and REQ_PASSWORD environment variables. This PR allow omitting them to prevent triggering the current bug in the k8s-sidecar.
This issue was triggered by the following commit inside this repository: https://github.com/grafana/helm-charts/commit/3bcfc47221007e5f7f53830eec17c66d97fcd62f
> [grafana] Enabling the ability to omit the REQ_USERNAME and REQ_PASSWORD variables when sidecar.dashboards.skipReload is true

- charts/tempo-distributed/Chart.yaml
- charts/tempo-distributed/README.md
- charts/tempo-distributed/templates/distributor/service-distributor-discovery.yaml
- charts/tempo-distributed/templates/distributor/service-distributor.yaml
- charts/tempo-distributed/templates/query-frontend/service-query-frontend-discovery.yaml
- charts/tempo-distributed/templates/query-frontend/service-query-frontend.yaml
- charts/tempo-distributed/values.yaml
We have a need to add service labels to support some service mesh configuration specifically for the distributor and query-frontend. These are added following the pattern that is already used for other services that have labels for the main services.
For the existing services with user-settable labels, there aren't any that also have paired *discovery* services, so I wasn't sure what to do here. Looking at related annotations, there is inconsistency in how they are named across the distributor and queryFrontend:
- distributor.service.annotations
- queryFrontend.service.annotations
- queryFrontend.serviceDiscovery.annotations (the separate serviceDiscovery annotation was added by #1104)
The approach that I took was to add labels for the discovery services following the existing naming …
> [tempo-distributed] Service labels for distributor and query-frontend

- charts/loki-distributed/Chart.yaml
- charts/loki-distributed/README.md
- charts/loki-distributed/templates/serviceaccount.yaml
- charts/loki-distributed/values.yaml
This change adds the option to add labels to the serviceAccount created by the helm chart.
> [loki-distributed] option for additional serviceAccount labels

- charts/promtail/Chart.yaml
- charts/promtail/README.md
- charts/promtail/values.yaml
This PR allows to configure the Promtail log format to json and logfmt.
> [promtail] allowing to configure Promtail log format

- charts/promtail/Chart.yaml
- charts/promtail/README.md
- charts/promtail/templates/_pod.tpl
- charts/promtail/values.yaml
Reworked PR #2219 with a rebase and incremented minor version.
Add support for optionally overriding the registry hostname and credentials from a parent chart.
This is important for air-gapped installations which do not have direct access to the public internet and must use a private, internal container registry.
It also avoids having to modify the Promtail Helm chart directly.
FAO: @unguiculus and @Whyeasy
> [promtail] Allow parent charts to override registry hostname and credentials

- charts/loki-distributed/Chart.yaml
- charts/loki-distributed/README.md
- charts/loki-distributed/values.yaml
The affinity value is expected to be passed as a string. The default values for querier and compactor were empty maps. This meant that helm would complain with the following message:
```
warning: cannot overwrite table with non table ...
```
which is basically telling the user that the type of the value in the values.yaml file is an empty map, but the value you're overriding it with is a string.
This commit fixes that issue by using the default affinity that is set for all other components (hard node and soft zone anti affinity).
> [loki-distributed] fix helm warning: cannot overwrite table with non table

- charts/loki-distributed/Chart.yaml
- charts/loki-distributed/README.md
- charts/loki-distributed/templates/distributor/hpa.yaml
- charts/loki-distributed/templates/gateway/hpa.yaml
- charts/loki-distributed/templates/ingester/hpa.yaml
- charts/loki-distributed/templates/querier/hpa.yaml
- charts/loki-distributed/templates/query-frontend/hpa.yaml
- charts/loki-distributed/values.yaml
Adds the possibility to include behaviour definitions for autoscalers
> [loki-distributed] Add behaviours to hpa

- charts/loki-canary/Chart.yaml
- charts/loki-canary/README.md
https://github.com/grafana/loki/releases/tag/v2.8.3
> [loki-canary] bump loki version to 2.8.3

- charts/loki-distributed/Chart.yaml
- charts/loki-distributed/README.md
https://github.com/grafana/loki/releases/tag/v2.8.3
> [loki-distributed] bump loki version to 2.8.3

- charts/loki-distributed/Chart.yaml
- charts/loki-distributed/README.md
- charts/loki-distributed/templates/compactor/deployment-compactor.yaml
The compactor affinity rules in the deployment template didn't use the tpl function which was producing wrong configs at the end
> [loki-distributed] fixed an issue with the compactor affinity

- charts/loki-distributed/Chart.yaml
- charts/loki-distributed/README.md
- charts/loki-distributed/templates/ingester/service-ingester-headless.yaml
Adds annotations for `loki-ingester-headless` service if provided in `.Values.loki.serviceAnnotations`
> [loki-distributed] annotations for ingester-headless service

- charts/grafana/Chart.yaml
- charts/grafana/values.yaml
Nothing special. Just adds a `deleteDatasources` reference, so users know where to place their entries, when they want to delete existing datasources. Addresses #1125.
> [grafana] add deleteDatasources reference

- charts/loki-distributed/Chart.yaml
- charts/loki-distributed/README.md
- charts/loki-distributed/templates/distributor/deployment-distributor.yaml
- charts/loki-distributed/templates/ingester/deployment-ingester.yaml
- charts/loki-distributed/templates/querier/deployment-querier.yaml
- charts/loki-distributed/values.yaml
Adding maxSurge as a configurable value for ingester, querier, and distributor.  Rollouts with these components can take a long time if they are set to high replicas.  This will allow a user to configure the maxSurge to whatever they want.
> [loki-distributed] Templatizing maxSurge for deployments

- charts/tempo-vulture/Chart.yaml
- charts/tempo-vulture/README.md
- charts/tempo-vulture/templates/deployment.yaml
- charts/tempo-vulture/values.yaml
> [tempo-vulture] Host aliases for tempo vulture

- charts/loki-distributed/Chart.yaml
- charts/loki-distributed/README.md
- charts/loki-distributed/templates/ingester/deployment-ingester.yaml
- charts/loki-distributed/templates/ingester/statefulset-ingester.yaml
- charts/loki-distributed/values.yaml
This adds support for configuring lifecycle hooks on the ingester deployment/daemonset, as it's possible already in the [loki simple scalable chart](https://github.com/grafana/loki/pull/8010/files#diff-63fce4804a7a1326e58b3c5ab9bf8efed2fb8407de8280a170e1f74979a4b394), also addressing #1963.
> [loki-distributed] support custom lifecycle hooks on ingester

- charts/tempo-distributed/Chart.yaml
- charts/tempo-distributed/README.md
- charts/tempo-distributed/values.yaml
In #2552, the port was not included and resulted in distributors not connecting to the ring.  Here we include the port and reference the `memberlist.bind_port` value.
fixes: #2559
related: #2552
> [tempo-distributed] include memberlist port in join_members

- charts/tempo-distributed/Chart.yaml
- charts/tempo-distributed/README.md
- charts/tempo-distributed/values.yaml
- Update tempo-distributed to 2.2
- Remove deprecated config option `tolerate_failed_blocks`
> [tempo-distributed] Updated to 2.2

- charts/tempo-distributed/Chart.yaml
- charts/tempo-distributed/README.md
- charts/tempo-distributed/values.yaml
- Make block version null and rely on Tempo defaults.
- Add a note to not auto scale ingesters unless you're a wizard
> [tempo-distributed] make block version default to Tempo

- charts/tempo-distributed/Chart.yaml
- charts/tempo-distributed/README.md
- charts/tempo-distributed/README.md.gotmpl
- charts/tempo-distributed/values.yaml
This PR does the following:
~~1. Updates the tempo-distributed helm chart to the latest v2.2 Tempo release~~
~~2. Removes the now-incompatible `tolerate_failed_blocks` config, as announced in the Tempo v2.2.x release: https://github.com/grafana/tempo/releases/tag/v2.2.0-rc.0~~
3. Adds support for the `external_backend` and `google_cloud_run` configs, to leverage the new RBAC feature
I tested a local build of this helm chart, and can confirm that it works correctly with the new 2.2 release.
Checklist:
> [tempo-distributed] Add support for querier.config.search.external_backend

- charts/tempo-distributed/Chart.yaml
- charts/tempo-distributed/README.md
My last PR was just merged recently: https://github.com/grafana/helm-charts/pull/2553
which bumped the chart version to `1.5.1`, but those changes are not actually in the `1.5.1` chart because another PR was merged slightly earlier, which also bumped the chart version to `1.5.1`: https://github.com/grafana/helm-charts/pull/2563/files
So this PR bumps the version to `1.5.2` so that my changes will be available in the most recent chart version.
Maybe this will motivate me to start using the Tempo operator... :smile:
> [tempo-distributed] Bump to 1.5.2

- charts/loki-canary/Chart.yaml
- charts/loki-canary/README.md
- charts/loki-canary/templates/daemonset.yaml
- charts/loki-canary/values.yaml
> [loki-canary] add host aliases

- charts/tempo-distributed/Chart.yaml
- charts/tempo-distributed/README.md
- charts/tempo-distributed/templates/admin-api/admin-api-dep.yaml
- charts/tempo-distributed/templates/compactor/deployment-compactor.yaml
- charts/tempo-distributed/templates/distributor/deployment-distributor.yaml
- charts/tempo-distributed/templates/enterprise-federation-frontend/deployment-federation-frontend.yaml
- charts/tempo-distributed/templates/enterprise-gateway/gateway-dep.yaml
- charts/tempo-distributed/templates/gateway/deployment-gateway.yaml
- charts/tempo-distributed/templates/ingester/statefulset-ingester.yaml
- charts/tempo-distributed/templates/memcached/statefulset-memcached.yaml
- charts/tempo-distributed/templates/metrics-generator/deployment-metrics-generator.yaml
- charts/tempo-distributed/templates/querier/deployment-querier.yaml
- charts/tempo-distributed/templates/query-frontend/deployment-query-frontend.yaml
- charts/tempo-distributed/templates/tokengen/tokengen-job.yaml
- charts/tempo-distributed/values.yaml
> [tempo-distributed] Add host aliases

- charts/synthetic-monitoring-agent/Chart.yaml
- charts/synthetic-monitoring-agent/README.md
- charts/synthetic-monitoring-agent/templates/deployment.yaml
- charts/synthetic-monitoring-agent/values.yaml
> [synthetic-monitoring-agent] Host aliases for synthetic monitoring agent

- charts/promtail/Chart.yaml
- charts/promtail/README.md
- charts/promtail/templates/configmap.yaml
- charts/promtail/values.yaml
I would like to be able to control my Promtail config from outside the Helm chart. The proposed change does not change default behaviour.
I use the Helm chart with Kustomize `HelmChartInflatorGenerator` and this would let me use my own ConfigMap for the Promtail config file which I can then e.g. use `ConfigMapGenerator` to restart my Promtail DaemonSet one config change.
> [promtail] Add control to disable Promtail config in Helm chart

- charts/tempo/Chart.yaml
- charts/tempo/README.md
- charts/tempo/templates/statefulset.yaml
- charts/tempo/values.yaml
You may want to clean up old replicasets so that these don't appear in metrics, OPA violations, ArgoCD UI and so on.
Therefore you want to overwrite the Kubernetes default revision history limit.
See [Kubernetes Clean up Policy](https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#clean-up-policy).
_(also available for StatefulSets but not yet documented [here](https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/), instead please see [openapi-spec](https://raw.githubusercontent.com/kubernetes/kubernetes/master/api/openapi-spec/swagger.json))_
> [tempo] feat: allow changing the default revisionHistoryLimit

- charts/promtail/Chart.yaml
- charts/promtail/README.md
- charts/promtail/templates/daemonset.yaml
- charts/promtail/templates/deployment.yaml
- charts/promtail/values.yaml
You may want to clean up old replicasets so that these don't appear in metrics, OPA violations, ArgoCD UI and so on.
Therefore you want to overwrite the Kubernetes default revision history limit.
See [Kubernetes Clean up Policy](https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#clean-up-policy).
(also available for DaemonSets but not yet documented [here](https://kubernetes.io/docs/concepts/workloads/controllers/daemonset/), instead please see [openapi-spec](https://raw.githubusercontent.com/kubernetes/kubernetes/master/api/openapi-spec/swagger.json))
> [promtail] feat: allow changing the default revisionHistoryLimit

- charts/tempo-distributed/Chart.yaml
- charts/tempo-distributed/README.md
- charts/tempo-distributed/README.md.gotmpl
- charts/tempo-distributed/values.yaml
Without this change, metrics-generator is disabled by default, but processors are enabled by default.  This misalignment means that users who never enable metrics-generator have an unnecessary amount of log noise on the distributor.  Here we set the default processors to empty.   Users who have not configured the metrics-generator processors and have relied the previous default processors will **need to set the processors you desire**.
> [tempo-distributed] Use default empty values for metrics-generator processors

- charts/tempo-distributed/Chart.yaml
- charts/tempo-distributed/README.md
- charts/tempo-distributed/templates/serviceaccount.yaml
- charts/tempo-distributed/values.yaml
The `automountServiceAccountToken` is configurable in the mono-tempo helm chart, but not in the distributed version.
https://github.com/grafana/helm-charts/blob/main/charts/tempo/templates/serviceaccount.yaml#L20
We want to set the field to be true in our tempo deployment, but we can't overwrite it easily right now.
> [tempo-distributed] fix: make auto mount sa token configurable

- charts/tempo-distributed/Chart.yaml
- charts/tempo-distributed/README.md
- charts/tempo-distributed/values.yaml
The option is in the documentation but missing in the helm chart. https://grafana.com/docs/tempo/latest/configuration/#ingester
> [tempo-distributed] fix: add flush all on shutdown for ingestors

- charts/promtail/Chart.yaml
- charts/promtail/README.md
- charts/promtail/values.yaml
Revert of #2575
Also see discussion at #2428 - the change to `tpl` lead to the conflict with all Go template definitions inside of `pipelineStages`. As it turns out this is also a typical use case in `pipelineStages`, e.g. by using promtail's [template](https://grafana.com/docs/loki/latest/clients/promtail/stages/template/) stage. In this context the `tpl` makes more problems than it is useful.
> [promtail] Render pipelineStages with tpl function revert

- charts/grafana/Chart.yaml
- charts/grafana/README.md
- charts/grafana/templates/servicemonitor.yaml
- charts/grafana/values.yaml
To actually allow filtering out metrics pre-ingestion.
The readme is erroneously using the [upstream docs](https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api.md#endpoint) docs for `metricRelabelings` on the `relabelings` field, which is wrong. Have copied the lines from the corresponding docs in the linked `ServiceMonitor.spec.endpoint` docs.
> [grafana] allow configuring serviceMonitor.metricRelabelings

- charts/rollout-operator/Chart.yaml
- charts/rollout-operator/README.md
Updates the rollout-operator chart to correspond with the new [v0.7.0 release](https://github.com/grafana/rollout-operator/releases/tag/v0.7.0)
> [rollout-operator] Update for v0.7.0

- .github/workflows/release.yaml
From the issue:
The release process fails in https://github.com/grafana/helm-charts/issues/2588 because chart-releaser discovers changes in promtail and tempo-distributed with tempo-distributed [existing already](https://github.com/grafana/helm-charts/actions/runs/5804536484/job/15734243055).
Chart-releaser lists this as a [common error](https://github.com/helm/chart-releaser#common-error-messages). I assume this can be fixed by adding the CR_SKIP_EXISTING=true to the [environment variables](https://github.com/helm/chart-releaser#environment-variables) section in the documentation.
closes #2591
> [promtail, ci] fix: skip existing releases

- charts/loki-canary/Chart.yaml
- charts/loki-canary/README.md
Looks like some CVE fixes that would be good to get in here: https://github.com/grafana/loki/releases/tag/v2.8.4
> [loki-canary] bump loki version to 2.8.4

- charts/loki-distributed/Chart.yaml
- charts/loki-distributed/README.md
Looks like some CVE fixes that would be good to get in here: https://github.com/grafana/loki/releases/tag/v2.8.4
> [loki-distributed] bump loki version to 2.8.4

- charts/grafana/Chart.yaml
There are breaking changes. Take a look into the [release notes](https://github.com/grafana/grafana/releases/tag/v10.1.0).
> [grafana] Update Grafana to v10.1.0

- .github/workflows/lint-test.yaml
The recent update broke the mimir-distributed helm chart because it was relying on the default kubectl version in the kind-action. When kind-action was updated from 1.2.0 to 1.8.0 the kubectl version went from 1.20.8 to 1.26.4
This PR exposes the version of the version of kubernetes that kind-action should use.
> lint-test CI: make kubernetes version configurable

- .github/workflows/lint-test.yaml
In addition to configuring kubectl as #2618 did we should also be able to configure the kubernetes node image. This PR does this and introduces some consistency in input naming.
It also removes the default values so the one from the kind-action are used by default and updating the kind action is sufficient to update the kubernetes version too.
> lint-test CI: make kind node image configurable

- charts/loki-distributed/Chart.yaml
- charts/loki-distributed/README.md
- charts/loki-distributed/templates/memcached-chunks/statefulset-memcached-chunks.yaml
- charts/loki-distributed/values.yaml
Adding the ability to add additional volumeClaimTemplates and volumeMounts to the memcached-chunks statefulset. 
This is needed for use cases where adding and mounting another PVC to memcached is required, such as implementing the extstore. This use case was explored in this blog https://grafana.com/blog/2023/08/23/how-we-scaled-grafana-cloud-logs-memcached-cluster-to-50tb-and-improved-reliability/.
Example of configuring these new fields:
```
memcachedChunks:
volumeClaimTemplates:
- metadata:
name: data-extstore
spec:
accessModes:
- ReadWriteOnce
storageClassName: null
resources:
requests:
storage: 100Gi
extraVolumeMounts:
- name: data-extstore
mountPath: /extstore
```
> [loki-distributed] Add support for additional PVCs in the memcached-chunks statefulset

- charts/promtail/Chart.yaml
- charts/promtail/README.md
CVE updates: https://github.com/grafana/loki/releases/tag/v2.8.4
> [promtail] bump promtail version to 2.8.4

- charts/tempo/Chart.yaml
- charts/tempo/README.md
Bug fixes: https://github.com/grafana/tempo/releases/tag/v2.2.2
> [tempo] bump tempo version to 2.2.2

- charts/tempo-distributed/Chart.yaml
- charts/tempo-distributed/README.md
bug fixes: https://github.com/grafana/tempo/releases/tag/v2.2.2
> [tempo-distributed] bump tempo version to 2.2.2

- charts/loki-distributed/Chart.yaml
- charts/loki-distributed/README.md
- charts/loki-distributed/templates/compactor/deployment-compactor.yaml
- charts/loki-distributed/templates/config-secret.yaml
- charts/loki-distributed/templates/configmap.yaml
- charts/loki-distributed/templates/distributor/deployment-distributor.yaml
- charts/loki-distributed/templates/index-gateway/statefulset-index-gateway.yaml
- charts/loki-distributed/templates/ingester/deployment-ingester.yaml
- charts/loki-distributed/templates/ingester/statefulset-ingester.yaml
- charts/loki-distributed/templates/querier/deployment-querier.yaml
- charts/loki-distributed/templates/querier/statefulset-querier.yaml
- charts/loki-distributed/templates/query-frontend/deployment-query-frontend.yaml
- charts/loki-distributed/templates/query-scheduler/deployment-query-scheduler.yaml
- charts/loki-distributed/templates/ruler/deployment-ruler.yaml
- charts/loki-distributed/templates/ruler/statefulset-ruler.yaml
- charts/loki-distributed/templates/table-manager/deployment-table-manager.yaml
- charts/loki-distributed/values.yaml
Add possibility to store Loki config in a secret instead of configmap.
For example: When using `loki.structuredConfig.common.storage.azure` you don't want to store the storage account accessKey in a configMap.
I found it more comfortable as creating a secret on my own and using `loki.existingSecretForConfig` and it's more stable for upcoming updates.
> [loki-distributed] config as secret

- charts/loki-distributed/Chart.yaml
- charts/loki-distributed/README.md
- charts/loki-distributed/values.yaml
I am a loki beginner and when I deployed `loki-distributed` in my production environment, it caused a cluster outage. The reason was because the bandwidth was hit full, causing packet loss.
> [loki-distributed] enable grpc compression by default

- charts/tempo-distributed/Chart.yaml
- charts/tempo-distributed/README.md
- charts/tempo-distributed/templates/admin-api/admin-api-dep.yaml
- charts/tempo-distributed/templates/compactor/deployment-compactor.yaml
- charts/tempo-distributed/templates/distributor/deployment-distributor.yaml
- charts/tempo-distributed/templates/enterprise-gateway/gateway-dep.yaml
- charts/tempo-distributed/templates/gateway/deployment-gateway.yaml
- charts/tempo-distributed/templates/ingester/statefulset-ingester.yaml
- charts/tempo-distributed/templates/memcached/statefulset-memcached.yaml
- charts/tempo-distributed/templates/metrics-generator/deployment-metrics-generator.yaml
- charts/tempo-distributed/templates/querier/deployment-querier.yaml
- charts/tempo-distributed/templates/query-frontend/deployment-query-frontend.yaml
In EKS the KubeVersion looks like `v1.26.2-eks-a59e1f0`, `.Capabilities.KubeVersion.Minor` returns `26+` for this which is then casted to an int value of 0 causing `topologySpreadConstraints` config not to be applied.
> [tempo-distributed] fix KubeVersion check for topologySpreadConstraints

- charts/rollout-operator/Chart.yaml
- charts/rollout-operator/README.md
Updates the rollout-operator chart to correspond with the new [v0.8.0 release](https://github.com/grafana/rollout-operator/releases/tag/v0.8.0)
> [rollout-operator] Update for v0.8.0

- charts/promtail/Chart.yaml
- charts/promtail/README.md
Reference: https://github.com/grafana/loki/releases/tag/v2.9.1
> [promtail] bump promtail version to 2.9.1

- charts/tempo-distributed/Chart.yaml
- charts/tempo-distributed/README.md
- charts/tempo-distributed/values.yaml
If autoscaling is turned for the ingester, the distributor component permanently fails.
```
ingester:
autoscaling:
enabled: true
```
This will result in the following Go error in the distributor component:
`level=error ts=2023-09-21T07:26:44.537318884Z caller=rate_limited_logger.go:27 msg="pusher failed to consume trace data" err="at least 2 live replicas required, could only find 1"`
Therefor I propose to change the minReplicas default value for the ingester component:
```
ingester:
autoscaling:
minReplicas: 2
```
> [tempo-distributed] adjust minReplicas for ingester

- charts/loki-distributed/Chart.yaml
- charts/loki-distributed/README.md
- charts/loki-distributed/templates/index-gateway/statefulset-index-gateway.yaml
- charts/loki-distributed/values.yaml
I followed a similar implementation for `loki-distributed` https://github.com/grafana/helm-charts/pull/2649 to enable [PersistentVolumeClaim retention policy](https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#persistentvolumeclaim-retention).
> [loki-distributed] Enable StatefulSetAutoDeletePVC feature for indexGateway

- charts/tempo-distributed/Chart.yaml
- charts/tempo-distributed/README.md
bumping the tempo version. Bug fix https://github.com/grafana/tempo/releases/tag/v2.2.3
> [tempo-distributed] bump tempo version to 2.2.3

- charts/tempo-distributed/Chart.lock
- charts/tempo-distributed/Chart.yaml
- charts/tempo-distributed/README.md
- charts/tempo-distributed/values.yaml
- ct.yaml
This primarly fixes a breaking change where the MinIO chart dependency had been reset to the prior, deprecated Chart, which broke the installation of this Chart from source.
This occured as part of this PR: https://github.com/grafana/helm-charts/pull/2384 presumably due to a failure to rebase between initial raising and merging.
Have also updated the GET version from 2.1.0 to 2.2.1, inline with latest release.
Fully E2E tested via GET k8s cluster, with Grafana and GrAgent setup.
> [tempo-distributed] Moves to GET 2.2.1, reverts MinIO dependency.

- .github/workflows/release.yaml
Minio hosts its charts at a new repo location now, so the release.yaml GH workflow needs to reflect that.
This adds it as a separate repo to not break anything existing.
> Add new Minio repo to release workflow

- charts/grafana/Chart.yaml
New version supports Azure AD workload identity: 
https://grafana.com/blog/2023/09/29/new-grafana-releases-to-support-transition-to-azure-ad-workload-identity-authentication-in-microsoft-azure/
> [grafana] Upgrade grafana to 10.1.4

- charts/grafana/Chart.yaml
- charts/grafana/templates/dashboards-json-configmap.yaml
Otherwise problems such as https://github.com/prometheus-community/helm-charts/issues/3866 happen
I tried adding a test;
```yaml
sidecar:
dashboards:
enabled: true
labelValue: "1"
dashboards:
my-provider:
my-awesome-dashboard:
gnetId: 10000
revision: 1
datasource: Prometheus
```
but this mistake doesn't get detected via `ct lint`
> [grafana] fix: add missing `| quote` for `sidecar.dashboards.labelValue`

- charts/loki-distributed/Chart.yaml
- charts/loki-distributed/README.md
- charts/loki-distributed/templates/index-gateway/service-index-gateway-headless.yaml
- charts/loki-distributed/templates/index-gateway/service-index-gateway.yaml
- charts/loki-distributed/templates/index-gateway/statefulset-index-gateway.yaml
- charts/loki-distributed/templates/query-scheduler/deployment-query-scheduler.yaml
- charts/loki-distributed/templates/query-scheduler/service-query-scheduler.yaml
- charts/loki-distributed/templates/ruler/service-ruler.yaml
- charts/loki-distributed/values.yaml
According to the Grafana Loki [documentation](https://grafana.com/docs/loki/latest/get-started/hash-rings/):
* the query scheduler must be part of a hashring
* the index gateway may optionally be part of a hashring
This PR updates the chart such that the query scheduler and index gateway pods will expose the memberlist container port 7946, and include the member list selector label. 
The index gateway may optionally be prevented from joining the memberlist by setting `.Values.indexGateway.joinMemberlist` to false (default true), reflecting the current state of the documentation.
In addition, the `appProtocol` field may be optionally configured for the ruler, query scheduler, and index gateway.
> [loki-distributed] Query scheduler and index gateway join the memberlist

- charts/tempo-distributed/Chart.yaml
- charts/tempo-distributed/README.md
- charts/tempo-distributed/values.yaml
I want to fix [Too many jobs in the queue](https://grafana.com/docs/tempo/latest/troubleshooting/too-many-jobs-in-queue/#too-many-jobs-in-the-queue) issue in my tempo setting.
> [tempo-distributed] storage.trace.pool.max_workers & storage.trace.pool.queue_depth config support

- charts/tempo-distributed/Chart.yaml
- charts/tempo-distributed/README.md
- charts/tempo-distributed/templates/gateway/configmap-gateway.yaml
- charts/tempo-distributed/templates/gateway/deployment-gateway.yaml
- charts/tempo-distributed/templates/gateway/hpa.yaml
- charts/tempo-distributed/templates/gateway/ingress-gateway.yaml
- charts/tempo-distributed/templates/gateway/poddisruptionbudget-gateway.yaml
- charts/tempo-distributed/templates/gateway/secret-gateway.yaml
- charts/tempo-distributed/templates/gateway/service-gateway.yaml
Realized this when installing with `helm template ... ` followed by `kubectl apply`. 
If that is intended I'm happy to change it. Please let me know if I did something wrong w.r.t. contributing :)
> [tempo-distributed] add missing namespaces to gateway resource

- charts/loki-distributed/Chart.yaml
- charts/loki-distributed/README.md
- charts/loki-distributed/README.md.gotmpl
- charts/loki-distributed/templates/distributor/hpa.yaml
- charts/loki-distributed/templates/gateway/hpa.yaml
- charts/loki-distributed/templates/ingester/hpa.yaml
- charts/loki-distributed/templates/querier/hpa.yaml
- charts/loki-distributed/templates/query-frontend/hpa.yaml
- charts/loki-distributed/values.test.yaml
- charts/loki-distributed/values.yaml
To implement autoscaling based on custom metrics (as described in the [documentation](https://grafana.com/docs/loki/latest/operations/autoscaling_queriers/)) _without_ using KEDA, we need more options for configuring the HPAs. This introduces a `customMetrics` stanza which allows additional metrics stanzas to be used in the HPA manifest.
I also updated the README with some missing documentation that is required for #2700
As a bonus: update Loki to `2.9.2` which was just released.
> [loki-distributed] Enable custom metrics for HPA and update Loki to 2.9.2

- charts/promtail/Chart.yaml
- charts/promtail/README.md
Reference: https://github.com/grafana/loki/releases/tag/v2.9.2
> [promtail] bump promtail version to 2.9.2

- charts/grafana/Chart.yaml
- charts/grafana/README.md
- charts/grafana/templates/service.yaml
In some cases, the externalTrafficPolicy value should also be configured. The default value of externalTrafficPolicy is 'Cluster' which needs to change for example if you use an internal LoadBalancer type service in Microsoft Azure environment.
> [grafana] add externalTrafficPolicy support

- charts/tempo-distributed/Chart.yaml
- charts/tempo-distributed/README.md
- charts/tempo-distributed/values.yaml
Fixes #2701 
Updated the default location as mentioned in the issue.
> [tempo-distributed] Corrected Default trace API location of gateway.nginxConfig.file in tempo-distributed

- .github/workflows/update-helm-repo.yaml
Authentication with Github App requires two vars being set in input (APP ID and PEM) and additional step to generate a temporary token. This PR adds support for such authentication in `update-helm-release` workflow.
It is implemented with conditionals in order to remain backwards compatible to setups of other projects that are using just one token at the moment.
It was tested with k6-operator:
- example CI workflow: https://github.com/grafana/k6-operator/blob/main/.github/workflows/helm-release.yaml
- successful run: https://github.com/grafana/k6-operator/actions/runs/6586421178
> Adding support for workflow with Github App authentication

- charts/grafana/Chart.yaml
- charts/grafana/templates/_pod.tpl
Previously, this was ranging over extraVolumeClaims instead of extraVolumes, which meant extraVolumes was never read. This caused volumes mounted as extraVolumes to be mounted as emptyDirs.
This also correctly inserts all data from hostPath volumes, and allows configMaps to be used as an extraVolume.
This should fix https://github.com/prometheus-community/helm-charts/issues/3851
> [grafana] Range over extraVolumes 

- charts/grafana/Chart.yaml
- charts/grafana/README.md
- charts/grafana/templates/_pod.tpl
- charts/grafana/templates/image-renderer-deployment.yaml
- charts/grafana/templates/tests/test.yaml
- charts/grafana/values.yaml
Many popular Helm charts, such as those provided by [Bitnami](https://github.com/bitnami/charts/tree/main/bitnami) ([1](https://github.com/bitnami/charts/blob/3f08ec6ab4335af812b8625ef0f1c41b7659206a/bitnami/mongodb/values.yaml#L16C1-L16C20), [2](https://github.com/bitnami/charts/blob/3f08ec6ab4335af812b8625ef0f1c41b7659206a/bitnami/grafana/values.yaml#L14), [3](https://github.com/bitnami/charts/blob/3f08ec6ab4335af812b8625ef0f1c41b7659206a/bitnami/redis/values.yaml#L16), plus 105 other charts) and [Prometheus](https://github.com/prometheus-community/helm-charts/tree/main/charts) ([1](https://github.com/prometheus-community/helm-charts/blob/1d917846c4f9dc3157d1ae8fc5511d63c3813aa3/charts/kube-state-metrics/values.yaml#L29), [2](https://github.com/prometheus-community/helm-charts/blob/1d917 …
> [grafana] Rename global.image.registry to global.imageRegistry

- charts/grafana/Chart.yaml
- charts/grafana/README.md
- charts/grafana/values.yaml
For a moment, I needed to set `podAnnotation` for the `image-renderer` pod, and upon a quick review of the `values.yaml` and the `readme`, I realized that it did not contain the information. For a brief moment, I thought the chart wouldn't support it, but upon examining the template, I found that it does support it; only the `values.yaml` did not have the information. So, I'm adding it now. Thanks!
> [grafana] fix: include podAnnotation in grafana values for imagerenderer

- charts/grafana/Chart.yaml
- charts/grafana/templates/_pod.tpl
If a client sets `global.imageRegistry`, that registry should override whatever registries are specified in `extraInitContainers`.
> [grafana] Add global image registry support for extraInitContainers

- charts/tempo/Chart.yaml
- charts/tempo/README.md
- charts/tempo/templates/_helpers.tpl
- charts/tempo/values.yaml
When using SHA hashes in image tags, kubernetes rejects the resource with the following error message:
<resource> is invalid: [metadata.labels: Invalid value: "<version@hash>": must be no more than 63 characters, metadata.labels: Invalid value: "<version@hash>": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue', or 'my_value', or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')]
[related pr for grafana](https://github.com/grafana/helm-charts/pull/2067)
> [tempo] fix metadata labels exceeding k8s character limit while using tag's digest

- charts/rollout-operator/Chart.yaml
- charts/rollout-operator/README.md
Updating to use the new [v0.9.0 release](https://github.com/grafana/rollout-operator/releases/tag/v0.9.0)
> [rollout-operator] update for v0.9.0

- charts/tempo-distributed/Chart.yaml
- charts/tempo-distributed/README.md
- charts/tempo-distributed/templates/extra-manifests.yaml
- charts/tempo-distributed/values.yaml
Add the ability to create extraObjects in helm chart.
> [tempo-distributed] Add the ability to add extraObjects

- .github/workflows/update-helm-repo.yaml
The old min.io helm is no longer available. This is blocking Loki Helm chart releases: see https://github.com/grafana/loki/actions/runs/7059033470/job/19281713160 for an example.
> Remove the deprecated minio chart from the call-update-helm-repo GH action

- charts/grafana/Chart.yaml
- charts/grafana/templates/_pod.tpl
- charts/grafana/values.yaml
This PR adds setting the [DNS policy and config](https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pod-s-dns-policy) for the pod template.
Since the image is based on alpine, certain clusters continue to have issues with dns resolution due to `ndots: 5`. Allowing this to be set to `ndots: 1` usually fixes the issue.
Ref: #2826
> [grafana] Allow setting dns config for pod template

- charts/loki-distributed/Chart.yaml
- charts/loki-distributed/README.md
- charts/loki-distributed/templates/compactor/_helpers-compactor.tpl
- charts/loki-distributed/templates/compactor/persistentvolumeclaim-compactor.yaml
- charts/loki-distributed/templates/compactor/statefulset-compactor.yaml
- charts/loki-distributed/values.yaml
Hey there !
Small contribution here to allow users of the chart to manage the compactor as a statefulset
:warning: Also I draw you attention on the fact that in the `values.yaml` I set the compactor field `Kind` as `Statefulset` starting now : this might break existing setup. I did that since Statefulset is kind of the default way to manage stateful software in k8s IMHO, but let me know what you think about it :wink:
If you have any question, do not hesitate to reach me :wink:
Cheers :sunny:
> [loki-distributed] manage compactor as statefulset

- charts/grafana/Chart.yaml
- charts/grafana/templates/ingress.yaml
Ingress supports host starts with asterisk(*), but it has to be quoted.
With this PR adding quotes to host.
Use this override values yaml to reproduce the issue.
helm template --values override.yaml . --debug
```
ingress:
enabled: true
hosts:
- "*.test.com"
``` 
Error: YAML parse error on grafana/templates/ingress.yaml: error converting YAML to JSON: yaml: line 14: did not find expected alphabetic or numeric character
helm.go:84: [debug] error converting YAML to JSON: yaml: line 14: did not find expected alphabetic or numeric character
> [grafana] Quote hostname in ingress.yaml

- charts/rollout-operator/Chart.yaml
- charts/rollout-operator/README.md
- charts/rollout-operator/values.yaml
This PR removes the CPU limit for rollout-operator pods.
This limit is not needed and unnecessarily limits the CPU utilisation of the rollout-operator under load.
Related: https://github.com/grafana/mimir/pull/7066
> [rollout-operator] Remove default CPU limit for rollout-operator pod

- charts/grafana/Chart.yaml
- charts/grafana/templates/_config.tpl
- charts/grafana/templates/_helpers.tpl
- charts/grafana/values.yaml
- There are numerous properties within `grafana.ini` that should be secret. 
- Users might try to provide these properties by setting them in helm `values`. This would result in secrets being leaked, since the contents of `grafana.ini` is stored as a configmap.
- This PR adds assertions that users do not provide explicit secrets into the `grafana.ini` configmap.
- We could "pluck" these values out of the configmap and store them in a secret.  We could then use `envFrom` or some other mechanism to inject them into `grafana.ini`. However, this might lead to confusion on the part of users, who may expect all the values to be put into the `grafana.ini` verbatim.
> [grafana] feat: fail when users store secrets in plaintext

- charts/grafana/Chart.yaml
- charts/grafana/templates/_pod.tpl
- charts/grafana/values.yaml
This PR enables adding environment values from Secrets or ConfigMaps into the datasources sidecar, which is quite useful for registering datasources with ServiceAccount tokens, specially for OpenShift environments
> [grafana] Support Datasource sidecar having envValueFrom

- charts/grafana/Chart.yaml
- charts/grafana/templates/configSecret.yaml
My current values to test this scenario is the following one to be able to generate my datasources inside a secret instead of a configmap:
```
datasources:
datasources.yaml:
secret:
apiVersion: 1
datasources:
- name: xxx
```
Before this commit I was rendering this kind of secret:
```
apiVersion: v1
kind: Secret
metadata:
name: "grafana-config-secret"
namespace: xxx
labels:
helm.sh/chart: grafana-xxx
app.kubernetes.io/name: grafana
app.kubernetes.io/instance: grafana
app.kubernetes.io/version: "xxx"
data:
stringData:
datasources.yaml: |
secret:
apiVersion: 1
datasources:
```
We can see the `secret:` is inside the datasources.yaml and on the grafana log i've had this error:
```
"[Deprecated] the datasource provisioning config is outdated. please upgrade" …
```
> [grafana] fix secret datasources/notifiers rendering 

- charts/rollout-operator/Chart.yaml
- charts/rollout-operator/README.md
Helm chart for rollout-operator v.0.10.1
Note: there's another [open (conflicting) PR](https://github.com/grafana/helm-charts/pull/2903) which upgrades to rollout-operator v0.11.0, but we don't have an Helm chart for v0.10.1. I think we can get this PR (v0.10) merged and then rebase https://github.com/grafana/helm-charts/pull/2903, updating the Helm Chart version there.
> [rollout-operator] update for v0.10.1

- charts/rollout-operator/Chart.yaml
- charts/rollout-operator/README.md
rollout-operator [v0.11.0](https://github.com/grafana/rollout-operator/releases/tag/v0.11.0) has been released, this updates the chart to use it
> [rollout-operator] update for v0.11.0

- charts/tempo-distributed/Chart.yaml
- charts/tempo-distributed/README.md
- charts/tempo-distributed/values.yaml
Current tempo-distributed chart allows to configure vParquet3 but not [dedicated attribute columns](https://grafana.com/docs/tempo/latest/operations/dedicated_columns/#dedicated-attribute-columns) that it allows.
> [tempo-distributed] Allow for attribute columns to be configured

- charts/grafana/Chart.yaml
- charts/grafana/templates/_helpers.tpl
Checks for the presence of the following syntax anywhere in the setting (based on the documentation here: https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/#variable-expansion):
`${whatever}` or `$__<provider>{whatever}`
If these are found, validation passes.
Fixes #2899
> [grafana] Don't fail assertNoLeakedSecrets check if a variable expansion operator is found

- charts/grafana/Chart.yaml
- charts/grafana/templates/_pod.tpl
Template should support custom properties for emptyDir
```
extraVolumes:
- name: ephemeral-tmp
emptyDir:
sizeLimit: 50Mi
```
Before this PR, volume properties was ignored, now =>
Values
```
extraVolumes:
- name: ephemeral-tmp
```
Generate 
```
- name: ephemeral-tmp
emptyDir: {}
```
Values
```
extraVolumes:
- name: ephemeral-tmp
emptyDir:
sizeLimit: 50Mi
```
Generate 
```
- name: ephemeral-tmp
emptyDir:
sizeLimit: 50Mi
```
> [grafana] Allow to customize empty dir volume

- charts/grafana/Chart.yaml
- fix Chart.yaml - incorrect license
- chart license is Apache-2.0
- relates #2810 
- fixes #2882
> [grafana] fix Chart.yaml - fix incorrect license #2882

- charts/promtail/Chart.yaml
- charts/promtail/README.md
Fix bugs/CVEs: https://github.com/grafana/loki/releases/tag/v2.9.3
> [promtail] bump promtail version to 2.9.3

- charts/loki-distributed/Chart.yaml
- charts/loki-distributed/README.md
- charts/loki-distributed/templates/distributor/poddisruptionbudget-distributor.yaml
- charts/loki-distributed/templates/gateway/poddisruptionbudget-gateway.yaml
- charts/loki-distributed/templates/index-gateway/poddisruptionbudget-index-gateway.yaml
- charts/loki-distributed/templates/ingester/poddisruptionbudget-ingester.yaml
- charts/loki-distributed/templates/memcached-chunks/poddisruptionbudget-memcached-chunks.yaml
- charts/loki-distributed/templates/memcached-frontend/poddisruptionbudget-memcached-frontend.yaml
- charts/loki-distributed/templates/memcached-index-queries/poddisruptionbudget-memcached-index-queries.yaml
- charts/loki-distributed/templates/memcached-index-writes/poddisruptionbudget-memcached-index-writes.yaml
- charts/loki-distributed/templates/querier/poddisruptionbudget-querier.yaml
- charts/loki-distributed/templates/query-frontend/poddisruptionbudget-query-frontent.yaml
- charts/loki-distributed/templates/query-scheduler/poddisruptionbudget-query-scheduler.yaml
- charts/loki-distributed/templates/ruler/poddisruptionbudget-ruler.yaml
Fixes: #2848
Whenever the PDB maxUnavailable is set to 0, the following condition fails (i.e. for indexGateway):
```
{{- if not .Values.indexGateway.maxUnavailable }}
```
---
To fix it, I used [one of the solutions](https://github.com/helm/helm/issues/3164#issuecomment-709537506) given by the helm issue that seems to be backwards compatible.
Note: I believe this issue might be happening in more implementations of this chart or other charts.
> [loki-distributed] Allow maxUnavailable to be set as 0

- charts/grafana/Chart.yaml
- charts/grafana/templates/_pod.tpl
- charts/grafana/values.yaml
I wanted to do something like this:
```
envFromSecrets:
- name: grafana-internal-creds
prefix: PGINT_
optional: false
- name: grafana-payload-creds
prefix: PGPL_
optional: false
```
prefix is a valid but optional field according to https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.26/#envfromsource-v1-core.
> [grafana] Allow prefix field in envFrom entries

- charts/grafana/Chart.yaml
- charts/grafana/values.yaml
> [grafana] autoMount set to false in values.yaml

- charts/rollout-operator/Chart.yaml
- charts/rollout-operator/README.md
Similarly to https://github.com/grafana/helm-charts/pull/2903, I'm updating the helm chart to get rollout-operaotr v0.13.0. I think we can skip v0.12.0 because it's a version we've have never rolled out at Grafana Labs.
> [rollout-operator] update for v0.13.0

- charts/agent-operator/Chart.yaml
- charts/agent-operator/README.md
- charts/agent-operator/values.yaml
This is pending the v0.40.2 release to finish, but given how it's close to EOD I'm preparing the PR now so we can merge as soon as the release is out there
> [agent-operator] Bump version of Grafana Agent to v0.40.2

- charts/grafana/Chart.yaml
- charts/grafana/README.md
- charts/grafana/templates/serviceaccount.yaml
- charts/grafana/values.yaml
Follow-up PR from #2991 
* Document `automountServiceAccountToken`
* Replace `serviceAccount.autoMount` by `serviceAccount.automountServiceAccountToken` - other charts using the same naming, too (https://github.com/grafana/helm-charts/blob/df7ae36c21bce12712c04a91115c165a04b7cdbf/charts/tempo/templates/serviceaccount.yaml#L20) - `serviceAccount.autoMount` is still supported and preferred to avoid a breaking change here.
> [grafana] Add `serviceAccount.automountServiceAccountToken` and document `automountServiceAccountToken`

- charts/grafana/Chart.yaml
- charts/grafana/values.yaml
https://github.com/kiwigrid/k8s-sidecar/compare/1.26.0...1.26.1
> [grafana] bump kiwigrid/k8s-sidecar to 1.26.1

- charts/tempo-distributed/Chart.yaml
- charts/tempo-distributed/README.md
- charts/tempo-distributed/values.yaml
Upgrade Tempo to 2.4.0 and use the new multi-cache config. 
I have assigned the following roles to the memcache:
```yaml
- roles:
- parquet-footer
- parquet-column-idx
- parquet-offset-idx
- bloom
- frontend-search
```
> [tempo-distributed] Upgrade to Tempo 2.4.0

- charts/tempo-distributed/Chart.yaml
- charts/tempo-distributed/README.md
- charts/tempo-distributed/values.yaml
Latest GET release moves to Tempo base v2.4.1 and includes Arm builds.
> [tempo-distributed] Update GET to v2.4.0, bump Tempo to v2.4.1.

- charts/agent-operator/Chart.yaml
- charts/agent-operator/README.md
- charts/agent-operator/templates/tests/test-grafanaagent.yaml
- charts/agent-operator/values.yaml
This PR adds the ability to override the default busybox image used in the test probe. This is useful in air-gapped environments where docker.io might not be accessible
> [agent-operator] Add override for test image

- .github/workflows/release.yaml
Resolves #2481
OCI chart push was introduced by @jkroepke here:
- https://github.com/grafana/helm-charts/issues/2395
- https://github.com/grafana/helm-charts/pull/2443
- https://github.com/grafana/helm-charts/pull/2474
But it fails due to missing docker login to GHCR.
I am a Argo helm maintainer and we use almost the identical code:
https://github.com/argoproj/argo-helm/blob/fa85e824f014ef7bf19163d4ecf7e9b8eb01f6b9/.github/workflows/publish.yml#L67C15-L82
/cc: @zanhsieh as you merged @jkroepke PRs in the past
> fix: Push charts to GHCR requires login

- charts/rollout-operator/Chart.yaml
- charts/rollout-operator/README.md
Update rollout-operator to v0.14.0 in corresponding chart, which gets bumped to v0.15.0.
> [rollout-operator] Update to v0.14.0

- .github/CODEOWNERS
If there are no codeowners, then approval will be up to a core group of default reviewers, neither of whom is part of the Agent group.
> Make Grafana Agent maintainers to be owners of the agent operator chart

- charts/tempo-distributed/Chart.yaml
- charts/tempo-distributed/README.md
- charts/tempo-distributed/templates/enterprise-gateway/gateway-svc.yaml
- charts/tempo-distributed/values.yaml
Namely:
* Service type
* Service port
* Cluster IP address (if type is ClusterIP)
* Loadbalancer IP address (if type is LoadBalancer)
The gateway component already supports these, inline with similar config options in Mimir and Loki. The enterprise gateway component does not.
Can help in situations where specific cluster/loadbalancer port mappings are required for external IPs for a cluster.
> [tempo-distributed] Adds service specific features for enterprise gateway inline with gateway.

- charts/tempo-distributed/Chart.yaml
- charts/tempo-distributed/README.md
- charts/tempo-distributed/templates/ingester/statefulset-ingester.yaml
- charts/tempo-distributed/templates/metrics-generator/statefulset-metrics-generator.yaml
- charts/tempo-distributed/values.yaml
In preparation for a future release, here we keep up with the tempo UID change of the container.
https://github.com/grafana/tempo/pull/2265
This change will allow an example values to be produced to chown the stateful data for both the ingesters and the metrics-generator in an init container.
> [tempo-distributed] add initContainers to generator and ingester STS

- charts/tempo-distributed/Chart.yaml
- charts/tempo-distributed/README.md
- charts/tempo-distributed/templates/tokengen/tokengen-job.yaml
I've run into an error when trying to deploy the helm chart via ArgoCD which is getting stuck on trying to execute the `tokengen-job`.
The error is as follows:
```
PostSync  Job.batch "tempo-tokengen-job" is invalid: [spec.selector: Required value, spec.template.metadata.labels: Invalid value: map[string]string{"app.kubernetes.io/component":"tokengen-job", "app.kubernetes.io/instance":"tempo", "app.kubernetes.io/managed-by":"Helm", "app.kubernetes.io/name":"tempo", "app.kubernetes.io/version":"2.4.1", "batch.kubernetes.io/controller-uid":"1aef82a1-1901-4360-a92d-bfd2b8ac568c", "batch.kubernetes.io/job-name":"tempo-tokengen-job", "controller-uid":"1aef82a1-1901-4360-a92d-bfd2b8ac568c", "helm.sh/chart":"tempo-distributed-1.9.5", "job-name":"tempo-tokengen-job"}: `selector` does not match …
```
> [tempo-distributed] fix invalid selector configuration for tokengenjob

- charts/tempo-distributed/Chart.yaml
- charts/tempo-distributed/README.md
- charts/tempo-distributed/values.yaml
Fixes braking change introduced in PR #2729. 
This should fix a previously introduced breaking change, and make the gateway `/v1/traces` path backwards compatible with `/otlp/v1/traces`. It could otherwise break a lot of production environments (like it did for us).
> [tempo-distributed] fixed broken gateway path

- charts/tempo-distributed/Chart.yaml
- charts/tempo-distributed/README.md
- charts/tempo-distributed/templates/tokengen/tokengen-job.yaml
Many apologies! This is on me for not properly verifying the [Jobs](https://kubernetes.io/docs/concepts/workloads/controllers/job/) prior to raising my previous PR.
Templating with a config like the following 
```
selector:
template:
metadata:
labels:
app.kubernetes.io/component: tokengen-job-2
```
will throw the error: 
```
selector` does not match template `labels`, spec.selector: Invalid value: "null": field is immutable
```
On the other hand, adding in the selector labels will also fail as Kubernetes will throw the following error:
```
`selector` not auto-generated
```
I've given this a much more rigorous test, and apologies for my previous bad change 🙏 
The Selector should not be manually specified unless otherwise configured in spec. Removing the selector altogether ensures the job …
> [tempo-distributed] Removing Job Selector Config

- .github/workflows/update-helm-repo.yaml
Fixes #1534
This PR updates the `update-helm-repo` workflow, replacing the hardcoded list of dependencies with a step that adds the dependencies from the output of the chart's `helm dependency list`.
> Don't hardcode helm charts dependencies in shared release workflow

- charts/tempo-distributed/Chart.yaml
- charts/tempo-distributed/README.md
- charts/tempo-distributed/values.yaml
Upgrading to Tempo v2.5.0
Tempo v2.5.0 [Changelog](https://github.com/grafana/tempo/releases/tag/v2.5.0)
> [tempo-distributed] Update for v2.5.0 release

- charts/tempo/Chart.yaml
- charts/tempo/README.md
Upgrading to Tempo v2.5.0
Tempo v2.5.0 [Changelog](https://github.com/grafana/tempo/releases/tag/v2.5.0)
> [tempo] Update for v2.5.0 release

- charts/grafana/Chart.yaml
This PR updates the helm version to the lastest Grafana version.
I have tested this changes inside kube-prometheus-stack which als deploy dashboards and datasources through sidecars.
Everything works here.
Note: I bumped the helm chart version to make end-users fully aware of the potential breaking changes (Grafana 11 itself has some)
> [grafana] Update Grafana to 11.0.0

- charts/lgtm-distributed/Chart.yaml
- charts/lgtm-distributed/README.md
> [lgtm-distributed] issue/2980 upgraded lgtm-distributed dependencies

- charts/grafana/Chart.yaml
- charts/grafana/README.md
- charts/grafana/templates/_config.tpl
- charts/grafana/values.yaml
My first PR 🎉 !
This simple PR should allow users to be able to set a `folderUid` which may help solve issues in some deployments, see referencing ticket for more info.
TICKET: Fix #2955
> [grafana] conf(grafana): Add `folderUid` option

- charts/grafana/Chart.yaml
- charts/grafana/templates/configmap.yaml
- charts/grafana/values.yaml
fixes https://github.com/grafana/helm-charts/issues/1811
Adding configmap annotation with example in values file how to use it with ArgoCD in case configmap is too big.
> [grafana] Adding configmap annotation

- .github/CODEOWNERS
- charts/grafana/Chart.yaml
I'm offering help as maintainer for the Grafana helm chart.
I contribute a lot to this [repository](https://github.com/grafana/helm-charts/pulls?q=is%3Apr+author%3Ajkroepke) and the [loki](https://github.com/grafana/loki/pulls?q=is%3Apr+author%3Ajkroepke) repository. 
Additionally, I'm kube-prometheus-stack chart maintainers and using the grafana helm chart in production.
In case the helm chart maintainer (@zanhsieh, @rtluckie, @maorfr, @Xtigyro, @torstenwalter) agree, I need a invite for that repository.
> [grafana] Adding jkroepke as maintainer

- charts/grafana/Chart.yaml
- charts/grafana/templates/pvc.yaml
- charts/grafana/values.yaml
Fixes #3125
#3041 was introduced without a real problem to mention. 
However, with the lookup function, helm-diff shows always an diff, since the lookup function does not work together with `helm template`.
Since the change is merged, it's very to cut out. In conclusion, I add an toggle to turn off that feature. The toggle is enabled by default to avoid any breaking changes. Power users can decided to turn off that feature if they wish.
> [grafana] Introduce toggle for volumeName lookup

- charts/tempo-distributed/Chart.yaml
- charts/tempo-distributed/README.md
- charts/tempo-distributed/README.md.gotmpl
- charts/tempo-distributed/templates/ingester/_helpers-ingester.tpl
- charts/tempo-distributed/templates/ingester/statefulset-ingester.yaml
- charts/tempo-distributed/values.yaml
@z0rc, please test upgrade againts this PR, i forgot to add an else clause that adds the default zone if zone aware replication is set to false (weird it only happens during an upgrade
> [tempo-distributed] Fix zone aware replication upgrade and rollout operator 

- charts/promtail/Chart.yaml
- charts/promtail/README.md
- charts/promtail/templates/_helpers.tpl
- charts/promtail/values.yaml
For example, when I set `image.tag=2.9.8`, I'd like the resulting annotation to be `app.kubernetes.io/version: 2.9.8` instead of the current `app.kubernets.io/version: 2.9.3` which uses the `.Chart.AppVersion`. I've copied from the grafana chart, which already has the correct behaviour.
> [promtail] prefer image.tag for app.kubernetes.io/version

- charts/grafana/Chart.yaml
- charts/grafana/values.yaml
This PR aims to clarify the documentation of the `serviceMonitor.enabled` setting which does not create a `CustomResourceDefinition` (CRD) but a `CustomResource` (CR) instead,
The CRD is like a class definition, the CR is an instance of that class.
I stumbled upon this and thought that this clarification might resolve some confusion for other users :)
> [grafana] Clarify documentation for serviceMonitor.enabled

- charts/tempo-distributed/Chart.yaml
- charts/tempo-distributed/README.md
- charts/tempo-distributed/templates/compactor/deployment-compactor.yaml
- charts/tempo-distributed/templates/distributor/deployment-distributor.yaml
- charts/tempo-distributed/templates/gossip-ring/service-gossip-ring.yaml
- charts/tempo-distributed/templates/ingester/statefulset-ingester.yaml
- charts/tempo-distributed/templates/querier/deployment-querier.yaml
We needed an easy way to set a different memberlist bind_port for Tempo to prevent gossip-ring collusion between our prod and stage deployment in k8s, because setting cluster_label didn't completely work for us.
```
memberlist:
abort_if_cluster_join_fails: false
bind_addr: []
bind_port: 7947
cluster_label: tempo-stage
cluster_label_verification_disabled: false
gossip_interval: 1s
gossip_nodes: 2
gossip_to_dead_nodes_time: 30s
join_members:
- dns+tempo-stage-deployment-gossip-ring:7947
leave_timeout: 5s
left_ingesters_timeout: 5m
max_join_backoff: 1m
max_join_retries: 10
min_join_backoff: 1s
node_name: ""
packet_dial_timeout: 5s
packet_write_timeout: 5s
pull_push_interval: 30s
randomize_node_name: true
rejoin_interval: 0s
retransmit_factor: 2
stream_timeout: 10s
```
> [tempo-distributed] Use memberlistBindPort instead of hardcoded values

- charts/tempo-distributed/Chart.yaml
- charts/tempo-distributed/README.md
- charts/tempo-distributed/README.md.gotmpl
- charts/tempo-distributed/templates/_helpers.tpl
- charts/tempo-distributed/values.yaml
Fixes a bug with runtime overrides that prevented using the new override format. Still works with legacy overrides.
Fixes https://github.com/grafana/tempo/issues/3795.
> [tempo-distributed] New overrides format bugfix

- charts/grafana/Chart.yaml
- charts/grafana/templates/pvc.yaml
when deploying grafana as stateful workload, it's unnecessary to create pvc manually since we use `statefulset.spec.volumeClaimTemplates` instead.
> [grafana] fix: do not create pvc manually when useStatefulSet

- charts/grafana/Chart.yaml
- charts/grafana/templates/_pod.tpl
- charts/grafana/values.yaml
Hi there, we are using that feature a lot but recently ran into some kind of race condition because a referenced ConfigMap wasn't existing yet. I noticed that there is now also an alerting sidecar which will probably improve our situation, but I still wanted to contribute this small changes which gives one the option to make the extraConfigmapMounts optional.
> [grafana] add value to make extraConfigmapMounts and extraSecretMounts optional

- charts/tempo/Chart.yaml
- charts/tempo/README.md
- charts/tempo/templates/networkpolicy.yaml
This PR addresses the user's comment https://github.com/grafana/helm-charts/pull/2922#issuecomment-2188167417 to remove multiple - (dash) entries under from in ingress to perform AND operation making the Network Policy more secure.
> [tempo] Remove multiple - (dash) entries under from within ingress

- charts/grafana/Chart.yaml
- charts/grafana/templates/dashboards-json-configmap.yaml
Remove the dashboard labels from dashboard-json-configmaps, as these are loaded seperately. 
This fixes: #3072
> [grafana] Removed dashboard labels from dashboard-json-configmap

- charts/grafana/Chart.yaml
- charts/grafana/templates/_helpers.tpl
When specifying .image.tag value that's longer than 64 chars you'd fail deploying Grafana.
> [grafana] Truncate label values - max 64 characters 

- charts/grafana/Chart.yaml
- charts/grafana/ci/with-nondefault-values.yaml
- charts/grafana/values.yaml
Fix issue https://github.com/grafana/helm-charts/issues/2343
> [grafana] tpl for host in grafana.ini

- charts/tempo-distributed/Chart.yaml
- charts/tempo-distributed/README.md
- charts/tempo-distributed/values.yaml
In order to force nginx to resolve hostnames in proxy_pass directive, we
need to set a variable and use it in proxy_pass. Otherswise nginx only
resolves hostnames at boot time.
> [tempo-distributed] fix: force nginx gateway to resolve upstream hostname

- charts/loki-distributed/Chart.yaml
- charts/loki-distributed/README.md
- charts/loki-distributed/values.yaml
In order to force nginx to resolve hostnames in proxy_pass directive, we
need to set a variable and use it in proxy_pass. Otherswise nginx only
resolves hostnames at boot time.
> [loki-distributed] fix: force nginx gateway to resolve upstream hostname on missing locations

- charts/tempo/Chart.yaml
- charts/tempo/README.md
- charts/tempo/values.yaml
Tempo [v2.5.0-rc.0](https://github.com/grafana/tempo/releases/tag/v2.5.0-rc.0) is now being run as non-root, see https://github.com/grafana/tempo/pull/2265. Change default values.yaml to avoid having every user apply this to their configuration.
> [tempo] Fix tempo permissions after update to v1.9.0

- charts/grafana-sampling/Chart.lock
- charts/grafana-sampling/Chart.yaml
- charts/grafana-sampling/README.md
- charts/grafana-sampling/README.md.gotmpl
- charts/grafana-sampling/templates/_alloy_config_deployment.alloy.txt
- charts/grafana-sampling/templates/_alloy_config_statefulset.alloy.txt
- charts/grafana-sampling/templates/_helpers.tpl
- charts/grafana-sampling/templates/_otelcol_auth_basic.alloy.txt
- charts/grafana-sampling/templates/_otelcol_connector_servicegraph.alloy.txt
- charts/grafana-sampling/templates/_otelcol_connector_spanmetrics.alloy.txt
- charts/grafana-sampling/templates/_otelcol_exporter_loadbalancing.alloy.txt
- charts/grafana-sampling/templates/_otelcol_exporter_otlp.alloy.txt
- charts/grafana-sampling/templates/_otelcol_exporter_prometheus.alloy.txt
- charts/grafana-sampling/templates/_otelcol_processor_batch.alloy.txt
- charts/grafana-sampling/templates/_otelcol_processor_filter.alloy.txt
- charts/grafana-sampling/templates/_otelcol_processor_tail_sampling.alloy.txt
- charts/grafana-sampling/templates/_otelcol_processor_transform.alloy.txt
- charts/grafana-sampling/templates/_otelcol_receiver_otlp.alloy.txt
- charts/grafana-sampling/templates/_prometheus_remote_write.alloy.txt
- charts/grafana-sampling/templates/configmap_deployment.yaml
- charts/grafana-sampling/templates/configmap_statefulset.yaml
- charts/grafana-sampling/values.yaml
This PR upgrades the tail sampling helm chart to use Grafana Alloy. This introduces breaking changes. See the README.md file.
In addition, it introduces a `metricsGeneration.legacy` configuration option set to `true` by default. In future releases, this will default to `false`. Using legacy metric names will align the spanmetrics generated by the `otelcol.spanmetrics.connector` component to match the metric names generated by the Tempo metrics generator. Setting  `metricsGeneration.legacy` set to `false` will use the default metric names. See https://grafana.com/docs/agent/latest/flow/reference/components/otelcol.connector.spanmetrics/#otelcolconnectorspanmetrics for more info.
> [grafana-sampling] upgrade to grafana alloy

- charts/tempo-distributed/Chart.yaml
- charts/tempo-distributed/README.md
- charts/tempo-distributed/templates/compactor/poddisruptionbudget-compactor.yaml
- charts/tempo-distributed/templates/distributor/poddisruptionbudget-distributor.yaml
- charts/tempo-distributed/templates/enterprise-federation-frontend/poddisruptionbudget-federation-frontend.yaml
- charts/tempo-distributed/templates/gateway/poddisruptionbudget-gateway.yaml
- charts/tempo-distributed/templates/ingester/poddisruptionbudget-ingester.yaml
- charts/tempo-distributed/templates/memcached/poddisruptionbudget-memcached.yaml
- charts/tempo-distributed/templates/metrics-generator/poddisruptionbudget-metrics-generator.yaml
- charts/tempo-distributed/templates/querier/poddisruptionbudget-querier.yaml
- charts/tempo-distributed/templates/query-frontend/poddisruptionbudget-query-frontend.yaml
- charts/tempo-distributed/values.yaml
At the moment PDBs created as part of Tempo installation has their `maxUnavailable` statically set to 1 (except for `ingester`). This PR makes this value configurable with defaults set as before.
The change is backwards compatible as it has default values set to 1 and for the `ingester` is set to the template expression as before.
> [tempo-distributed] added configuration option to set `maxUnavailable` for PDBs

- charts/grafana/Chart.yaml
- charts/grafana/README.md
- charts/grafana/templates/_pod.tpl
- charts/grafana/values.yaml
I'm making a PR related to this [issue](https://github.com/grafana/helm-charts/issues/3291).
This feature allows for running Grafana and remote image renderer in  different namespaces. It is especially useful when you have multiple grafana instances in different clusters and namespaces and you want  them to use same remote image renderer.
> [grafana] Support for overriding the server and call back urls

- charts/tempo-distributed/Chart.yaml
- charts/tempo-distributed/README.md
- charts/tempo-distributed/README.md.gotmpl
- charts/tempo-distributed/ci/parquet-dedicated-columns.yaml
Upgrading to Tempo v2.6.0
Tempo v2.6.0 [Changelog](https://github.com/grafana/tempo/releases/tag/v2.6.0)
> [tempo-distributed] Upgrade to v2.6.0

- charts/promtail/Chart.yaml
- charts/promtail/README.md
- charts/promtail/templates/_pod.tpl
In this PR the `extraVolumes` and `initContainers` can be filled in with templates in a parent chart.
For the `initContainers` it allows to for example inject a container that waits until kafka is ready. From the context of a parent chart, a service would be created where the name for example is `{{ .Release.Name }}-kafka`. This could for example be injected in `kcat` to check if kafka is ready.
It's also possible now to include a secret that's created in a parent chart (with the release name included in the name). This could be useful to inject a password using `password_file` with a file coming from a volume made with that secret.
This could for example look like the following in a values file of a parent chart.
Note that `{{ $.Release.Name }}-loki-gateway-auth` is a secret here with …
> [promtail] allow to inject templates

- charts/tempo-distributed/Chart.yaml
- charts/tempo-distributed/README.md
- charts/tempo-distributed/templates/ingester/_helpers-ingester.tpl
`name` label is required on pods that should be managed by the rollout-operator this pr ensure that it is added.
https://github.com/grafana/rollout-operator/issues/15
> [tempo-distributed] Add required name label to ingesters

- charts/rollout-operator/Chart.yaml
- charts/rollout-operator/README.md
Updates rollout operator Helm chart.
> [rollout-operator] Update rollout-operator Helm chart to v0.18.0, using rollout-operator v0.19.1

- charts/grafana-sampling/Chart.yaml
- charts/grafana-sampling/README.md
- charts/grafana-sampling/templates/_otelcol_processor_batch.alloy.txt
- charts/grafana-sampling/values.yaml
This PR makes batch processing options configurable for the deployment and statefulset batch processors. Additionally, k8s.pod.name is added to the set of default dimensions to avoid issue with faulty target_info metric generation.
> [grafana-sampling] add batch config options and k8s.pod.name to metrics dimensions

- charts/tempo-distributed/Chart.yaml
- charts/tempo-distributed/README.md
- charts/tempo-distributed/templates/admin-api/admin-api-dep.yaml
- charts/tempo-distributed/templates/compactor/deployment-compactor.yaml
- charts/tempo-distributed/templates/distributor/deployment-distributor.yaml
- charts/tempo-distributed/templates/enterprise-federation-frontend/deployment-federation-frontend.yaml
- charts/tempo-distributed/templates/gateway/deployment-gateway.yaml
- charts/tempo-distributed/templates/ingester/statefulset-ingester.yaml
- charts/tempo-distributed/templates/memcached/statefulset-memcached.yaml
- charts/tempo-distributed/templates/metrics-generator/deployment-metrics-generator.yaml
- charts/tempo-distributed/templates/querier/deployment-querier.yaml
- charts/tempo-distributed/templates/query-frontend/deployment-query-frontend.yaml
- charts/tempo-distributed/values.yaml
Most of the deployed components did not apply the global extraEnv in the deployment templates.  This resulted in having to duplicate extraEnv vars in the values/overrides files.  This change uses the pattern from mimir to create an env: for a deployment if the .Values.global.extraEnv or .Values.<component>.extraEnv exists.  It also adds the global extraEnv section to the values.yaml file.
Closes #3332
> [tempo-distributed] Adds global extraEnv support to deployed components

- .github/workflows/check-codeowners.yaml
- .github/workflows/lint-test.yaml
- .github/workflows/linter.yml
- .github/workflows/release.yaml
- .github/workflows/sync-readme.yaml
- .github/workflows/update-helm-repo.yaml
- .github/workflows/validate-pr.yaml
This PR:
* upgrades a number of [deprecated](https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/) actions to their latest versions
* fixes the use of the [deprecated](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/) `::set-output` command
* bumps the version of Python used to the latest available to resolve `Version 3.7 was not found in the local cache` errors when running on the latest Ubuntu 24.04 runners
> Fix use of deprecated GitHub Actions actions and commands, and bump Python version

- charts/tempo-distributed/Chart.yaml
- charts/tempo-distributed/README.md
- charts/tempo-distributed/templates/metrics-generator/statefulset-metrics-generator.yaml
Fixes global.extraEnv key support for metrics-generator when it is deployed as kind: StatefulSet
Resolves: #3346
> [tempo-distributed] Fix global.extraEnv key support for metrics-generator statefulset

- charts/tempo-distributed/Chart.yaml
- charts/tempo-distributed/README.md
- charts/tempo-distributed/templates/compactor/deployment-compactor.yaml
A recent change to add a global extraEnv (https://github.com/grafana/helm-charts/commit/2126cb60a0974de3369ad210ebce8be786d4ccaa) made a small typo for the compactor component, so that it was looking at `compactor.env` instead of `compactor.extraEnv` (in the case `global.extraEnv` is not set). 
This PR just fixes that.
> [tempo-distributed] Fixes minor regression in tempo-distributed compactor extraEnv

- charts/tempo-distributed/Chart.yaml
- charts/tempo-distributed/README.md
- charts/tempo-distributed/values.yaml
Fixes #3307 
This PR adds tolerations for memcached.
> [tempo-distributed] Add support for tolerations in memcached

- charts/grafana/Chart.yaml
- charts/grafana/templates/_config.tpl
fixes array format in configmap grafana.ini.
previously produced: `org_mapping = ["a" "b" "c"]`, which grafana did not apply correctly
now produces: `org_mapping = ["a", "b", "c"]`, which grafana applies correctly
of note:
for some reason this only seems to work when applied as TOML style array lists `["a", "b", "c"]`, even though the file type is nominally ini, which would suggest the following would actually be appropriate:
```
org_mapping[] = "a"
org_mapping[] = "b"
org_mapping[] = "c"
```
🤷
> [grafana] correct array formatting for grafana.ini

- .github/workflows/update-helm-repo.yaml
Some Helm charts, such as Loki, are not being pushed to an OCI registry because OCI support is missing in the `update-helm-repo.yaml` workflow, which is used for external releases.
Solution: This PR introduces a step that ensures Helm charts are also pushed to the GitHub Container Registry (GHCR) as part of the release process, providing OCI support for charts that were previously excluded.
> Add OCI registry support for all Helm charts

- charts/grafana/Chart.yaml
- charts/grafana/templates/tests/test-configmap.yaml
- charts/grafana/templates/tests/test-podsecuritypolicy.yaml
- charts/grafana/templates/tests/test-role.yaml
- charts/grafana/templates/tests/test-rolebinding.yaml
- charts/grafana/templates/tests/test-serviceaccount.yaml
- charts/grafana/templates/tests/test.yaml
- charts/grafana/values.yaml
As a user of the testFramework, I'd like to be able to run it automatically `post-install` and `post-upgrade` to check the health endpoint of my Grafana instance any time it is altered. Additionally, upon failure of this test, I'd like it to rollback which happens automatically when using the previously mentioned hook types.
> [grafana] Make the Helm hook type for the testFramework configurable

- charts/tempo-distributed/Chart.yaml
- charts/tempo-distributed/README.md
- charts/tempo-distributed/templates/ingester/service-ingester.yaml
- charts/tempo-distributed/templates/ingester/statefulset-ingester.yaml
like in mimir, we need to pass `ingester.ring.instance-availability-zone` when enabled zone aware ingestion 
FYI @zalegrala
> [tempo-distributed] feat: add cli flag for zone aware ingestion

- charts/agent-operator/Chart.yaml
- charts/agent-operator/README.md
- charts/agent-operator/templates/_helpers.tpl
- charts/agent-operator/values.yaml
Every object created by the chart can have custom labels.
Fixes https://github.com/grafana/helm-charts/issues/3319
I edited Rollour operator Charts using the same logic used for https://github.com/grafana/mimir/issues/9067
> [agent-operator] Add commonLabels (#3319)

- charts/synthetic-monitoring-agent/Chart.yaml
- charts/synthetic-monitoring-agent/README.md
- charts/synthetic-monitoring-agent/templates/deployment.yaml
- charts/synthetic-monitoring-agent/values.yaml
Added a deploymentStrategy for the synthetic-monitoring-agent helm.
This allows more controle on how the pods will be deployed.
Used the same syntax as other helm charts already do.
> [synthetic-monitoring-agent] Add deployment strategy

- charts/rollout-operator/Chart.yaml
- charts/rollout-operator/README.md
- charts/rollout-operator/templates/_helpers.tpl
- charts/rollout-operator/templates/role.yaml
- charts/rollout-operator/templates/rolebinding.yaml
- charts/rollout-operator/values.yaml
Every object created by the chart can have custom labels.
Fixes https://github.com/grafana/helm-charts/issues/3319
I edited  Rollour operator Charts using the same logic used for https://github.com/grafana/mimir/issues/9067
> [rollout-operator] Add commonLabels (#3319)

- charts/tempo-distributed/Chart.yaml
- charts/tempo-distributed/README.md
- charts/tempo-distributed/README.md.gotmpl
- charts/tempo-distributed/values.yaml
Addressing https://github.com/grafana/tempo/issues/2766 where Loki/Tempo ingesters can join each other's ring because cluster_label seems to be defaulted to something common to both components. This change should mitigate the issue in the future.
> [tempo-distributed] set unique cluster_label for tempo-distributed memberlist

- charts/tempo/Chart.yaml
- charts/tempo/README.md
- charts/tempo/README.md.gotmpl
- charts/tempo/values.yaml
Addressing https://github.com/grafana/tempo/issues/2766 where Loki/Tempo ingesters can join each other's ring because cluster_label seems to be defaulted to something common to both components. This change should mitigate the issue in the future.
> [tempo] set unique cluster_label for tempo memberlist

- charts/tempo/Chart.yaml
- charts/tempo/README.md
The chart seems to lag behind the releases now. I've manually bumped the image and it seems to work just fine with the rest of the chart.
> [tempo] Update to 2.6.1

- .github/workflows/lint-test.yaml
- charts/grafana/Chart.yaml
- charts/grafana/ci/with-nondefault-values.yaml
- charts/grafana/templates/route.yaml
- charts/grafana/values.yaml
This PR offer a implementation of the Gateway API in BETA state.
It based on https://github.com/prometheus-community/helm-charts/pull/4646 where the current design was identified as simple and complete.
> [grafana] Implement Gateway API

- .github/workflows/lint-test.yaml
Follow-up of #3400
The gateway CRDs installed use `x-kubernetes-validations` which is only [available as of 1.23](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.23/#jsonschemaprops-v1-apiextensions-k8s-io).
This breaks CI when the kubectl version is lower than 1.23. We use these CI actions for grafana/mimir-distributed [with 1.20 for example](https://github.com/grafana/mimir/blob/a7f1e3f79fe0a72f64d2f60c6ce65afa03e2dd8c/.github/workflows/helm-ci.yml#L11-L18)
> CI: only install gateway CRDs if k8s version >= 1.23

- charts/synthetic-monitoring-agent/Chart.yaml
- charts/synthetic-monitoring-agent/README.md
A user brought the existence of this helm chart to my knowledge, and figured I could bump the version. Perhaps we could set up some automation for this, e.g. renovate?
> [synthetic-monitoring-agent] bump version to v0.29.3

- .github/workflows/update-helm-repo.yaml
This is a fixup to #3366 #3418
In #3383 I'd already added these permissions, but I removed them later in #3418 — removing them was wrong.
That is, the workflow uses `GITHUB_TOKEN` to push the tag to the **source** repository. This is indicated by the error (note `github-actions[bot]`):
```
Pushing tag mimir-distributed-5.6.0-weekly.314
remote: Permission to grafana/mimir.git denied to github-actions[bot].
fatal: unable to access 'https://github.com/grafana/mimir/': The requested URL returned error: 403
```
This was the part I've missed. My thinking was that the tags are always created by the GitHub App install token (ref. to what I _wrongly_ mentioned in this comment https://github.com/grafana/helm-charts/pull/3418#discussion_r1836710790).
This PR should fix the workflow.
> workflows: bring back missing permissions to update-helm-repo

- charts/rollout-operator/Chart.yaml
- charts/rollout-operator/README.md
- charts/rollout-operator/templates/servicemonitor.yaml
Rollout operator always creates `relabelings` when serviceMonitor is enabled, which produces invalid yaml 
```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
name: release-name-rollout-operator
labels:
helm.sh/chart: rollout-operator-0.18.1
app.kubernetes.io/name: rollout-operator
app.kubernetes.io/instance: release-name
app.kubernetes.io/version: "v0.19.1"
spec:
selector:
matchLabels:
app.kubernetes.io/name: rollout-operator
app.kubernetes.io/instance: release-name
endpoints:
- port: http-metrics
relabelings:  < --- here
scheme: http
```
> [rollout-operator] make relabelings optional for rollout operator

- charts/tempo-distributed/Chart.yaml
- charts/tempo-distributed/README.md
- charts/tempo-distributed/templates/distributor/service-distributor.yaml
- charts/tempo-distributed/templates/ingester/service-ingester.yaml
- charts/tempo-distributed/values.yaml
Added the following features to the helm chart of tempo-distributed:
- users can set service type on the ingester service
- users can set internalTrafficPolicy on both ingester/distributor services
> [tempo-distributed] Service type and internalTrafficPolicy settings to Ingress/Distributor

- charts/loki-distributed/Chart.yaml
- charts/loki-distributed/README.md
- charts/loki-distributed/README.md.gotmpl
- charts/loki-distributed/values.yaml
Addressing https://github.com/grafana/tempo/issues/2766 where Loki/Tempo ingesters can join each other's ring because cluster_label seems to be defaulted to something common to both components. This change should mitigate the issue in the future.
> [loki-distributed] set unique cluster_label for loki-distributed memberlist

- charts/tempo-distributed/Chart.yaml
- charts/tempo-distributed/README.md
- charts/tempo-distributed/templates/memcached/statefulset-memcached.yaml
- charts/tempo-distributed/values.yaml
This will allow additional volumes, mounts and args related to the memcached statefulset and its exporter.
> [tempo-distributed] allow extra memcached configurations

- charts/grafana/Chart.yaml
- charts/grafana/values.yaml
Add missing configuration sections from grafana alerting block. Without these, it's unclear how to get alerts properly working via provisioning.
> [grafana] values.yaml: update alerting examples and ref

- charts/tempo-distributed/Chart.yaml
- charts/tempo-distributed/README.md
- charts/tempo-distributed/values.yaml
Added missing query frontend metrics config. Closes [#3323](https://github.com/grafana/helm-charts/issues/3323).
> [tempo-distributed] add query frontend metrics config

- charts/tempo-distributed/Chart.yaml
- charts/tempo-distributed/README.md
- charts/tempo-distributed/templates/ingester/statefulset-ingester.yaml
Closes https://github.com/grafana/helm-charts/issues/3237
Ran into an issue when trying to add `podLabels` into our deploy of tempo. 
```
RUNTIME ERROR: Parsing Helm output: yaml: unmarshal errors:
line 1752: mapping key "name" already defined at line 1751
```
Tracking back to the rendering here, it seems like the `.Values.ingester.podLabels` are duplicated between the statefulset definition and the `_helpers.tpl` function : https://github.com/grafana/helm-charts/blob/main/charts/tempo-distributed/templates/ingester/_helpers-ingester.tpl#L172-L174
> [tempo-distributed] Remove duplicated ingester podLabels

- charts/grafana/Chart.yaml
- charts/grafana/templates/_pod.tpl
- charts/grafana/values.yaml
We faced an number of situation where the default retries were not sufficient.
These are:
- Cluster restart, at that moment the Kubernetes API is very busy and did not reply in time. Multiple retries were done, in most cases the default 5 retries are enough, but in some cases that was not enough.
- New pod creation, at that moment Grafana is busy initialising itself and is not accepting requests on the reload endpoint.
During startup phase some more time might be needed to complete the actions.
Example log
```
2024-11-20T09:57:40.446956500Z {"time": "2024-11-20T09:57:40.446215+00:00", "taskName": null, "msg": "Writing /etc/grafana/provisioning/datasources/datasource.yaml (ascii)", "level": "INFO"}
2024-11-20T09:57:40.451282471Z {"time": "2024-11-20T09:57:40.450890+00:00", "taskName": …
```
> [grafana] Add configuration options for the number of retries done by the sidecar

- charts/rollout-operator/Chart.yaml
- charts/rollout-operator/README.md
rollout-operator v0.21.0 has been released, this PR updates the Helm chart to use it.
> [rollout-operator] Update rollout-operator chart with version v0.21.0

- charts/tempo-distributed/Chart.yaml
- charts/tempo-distributed/README.md
- charts/tempo-distributed/README.md.gotmpl
- charts/tempo-distributed/values.yaml
There's been recent confusion over the use of the `global_overrides` and `overrides` objects. This PR aims to make it clearer.
> [tempo-distributed] Clarifies use of `global_overrides` and `overrides` objects.

- charts/tempo-distributed/Chart.yaml
- charts/tempo-distributed/README.md
- charts/tempo-distributed/values.yaml
Updated and tested Memcached from 1.6.29 to 1.6.33
Below is the link for the changes:
https://github.com/memcached/memcached/compare/1.6.29...1.6.33
> [tempo-distributed] Updated memcached image

- charts/grafana/Chart.yaml
- charts/grafana/templates/_pod.tpl
In order to enable profiling using Grafana Alloy and Grafana Pyroscope
currently you would need to abuse another container port or insert a
dummy container to facitilitate profile collection.
This is because a containerPort is matched with the annotations to
enable profiling. As a workaround I am "abusing" the port :9094, as for
the example I am working on it is unused. This change will make it
possible to coexist with gossip-tcp and you would be able to enable
profiling like this:
```
helm upgrade -n pyroscope-test --install grafana grafana/grafana \
--set env.GF_DIAGNOSTICS_PROFILING_ENABLED=true \
--set env.GF_DIAGNOSTICS_PROFILING_ADDR=0.0.0.0 \
--set env.GF_DIAGNOSTICS_PROFILING_PORT=6060 \
--set-string 'podAnnotations.profiles\.grafana\.com/cpu\.scrape=true' \
--set-string …
```
> [grafana] feat(grafana): Introduce profiling container port

- charts/grafana-sampling/Chart.yaml
- charts/grafana-sampling/README.md
- charts/grafana-sampling/templates/_otelcol_receiver_otlp.alloy.txt
- charts/grafana-sampling/values.yaml
Add max message receive size config param for otlp receivers used in sampling chart. Defaults to 4MB. 
Resolves #3483 
Example configuration:
```yaml
deployment:
otlp:
receiver:
grpc:
max_recv_msg_size: 4MB
statefulset:
otlp:
receiver:
grpc:
max_recv_msg_size: 16MB
```
> [grafana-sampling] add max message receive size config param 

- charts/tempo-distributed/Chart.yaml
- charts/tempo-distributed/README.md
- charts/tempo-distributed/templates/metrics-generator/statefulset-metrics-generator.yaml
- charts/tempo-distributed/values.yaml
Hi,
Added volume reclaim policy parameters to metrics-generator.
Cheers
> [tempo-distributed] Added Volume reclaim policy to metrics-generator

- charts/rollout-operator/Chart.yaml
- charts/rollout-operator/README.md
Updates the version to correspond with https://github.com/grafana/rollout-operator/releases/tag/v0.23.0
> [rollout-operator] update rollout-operator version to 0.23.0

- charts/tempo-distributed/Chart.yaml
- charts/tempo-distributed/README.md
- charts/tempo-distributed/templates/ingester/statefulset-ingester.yaml
- charts/tempo-distributed/templates/metrics-generator/statefulset-metrics-generator.yaml
- charts/tempo-distributed/values.yaml
Added global storage class.
Generally, people do not set different storageClasses for different components.
So having a global variable would be quite convenient.
Cheers
> [tempo-distributed] Added global storage class

- charts/tempo-distributed/Chart.lock
- charts/tempo-distributed/Chart.yaml
- charts/tempo-distributed/README.md
- charts/tempo-distributed/README.md.gotmpl
> [tempo-distributed] bump tempo to 2.7.0 and rollout operator 

- charts/tempo/Chart.yaml
- charts/tempo/README.md
- charts/tempo/templates/service.yaml
- charts/tempo/templates/servicemonitor.yaml
- charts/tempo/values.yaml
The ServiceMonitor does not have a namespace specified, need to define namespace.
Add tempo values comments and document link can help users configure better.
> [tempo] Add servicemonitor namespace and values note

- charts/grafana/Chart.yaml
- charts/grafana/README.md
- charts/grafana/values.yaml
This reduces the CVE count to 0
> [grafana] Update downloadDashboards image to latest curl release

- charts/loki-distributed/Chart.yaml
- charts/loki-distributed/README.md
- charts/loki-distributed/values.yaml
Updating loki-distributed image tag from 1.20.2-alpine to 1.27.3-alpine
Signed-off-by:  Marcelo Sanchez <marcelo.sanchez@priverion.dev>
> [loki-distributed] Update image gateway to 1.27.3-alpine.

- charts/grafana/Chart.yaml
- charts/grafana/templates/_pod.tpl
- charts/grafana/values.yaml
This parameter is added because the ldap reload api is not working https://grafana.com/docs/grafana/latest/developers/http_api/admin/#reload-ldap-configuration
To allow an extraContainer to restart the Grafana container
> [grafana] feat: add shareProcessNamespace option to restart Grafana on LDAP config changes

- charts/rollout-operator/Chart.yaml
- charts/rollout-operator/README.md
Updates rollout-operator corresponding to its new release: https://github.com/grafana/rollout-operator/releases/tag/v0.24.0
> [rollout-operator] update to v0.24.0

- charts/tempo-distributed/Chart.yaml
- charts/tempo-distributed/README.md
- charts/tempo-distributed/templates/memcached/statefulset-memcached.yaml
In using this chart, I came across a formatting error. The conditional for disabling memcached-exporter does not wrap all of its possible settings. If you use volumeMounts and disable memcached-exporter, it still adds the volumeMounts and results in adding a second duplicate section to the memcached container config.
This change fixes that. 
I also wonder if we should set the memcached-exporter extraVolumeMounts to be configured via:
`.Values.memcachedExporter.extraVolumeMounts` rather than the current `.Values.memcached.extraVolumeMounts` so that it is possible to mount different things into each container in the case you may need to rather than them both getting the same thing.
> [tempo-distributed] Fix Memcached StatefulSet volumeMounts formatting issue

- charts/grafana-sampling/Chart.yaml
- charts/grafana-sampling/README.md
- charts/grafana-sampling/templates/_otelcol_connector_servicegraph.alloy.txt
- charts/grafana-sampling/values.yaml
Fixes https://github.com/grafana/helm-charts/issues/3588
The default flush interval is 0s which generates a lot of metrics. This change will set it to 60s by default, which will eventually be the default upstream. As part of this change it is also made available in the values so it can be customised.
> [grafana-sampling] Update default servicegraph metrics_flush_interval

- charts/grafana/Chart.yaml
- charts/grafana/templates/hpa.yaml
This PR modifies the HorizontalPodAutoscaler (HPA) `scaleTargetRef` condition logic to use the same `if` statement as used by the [charts/grafana/templates/statefulset.yaml](https://github.com/grafana/helm-charts/blob/2049e69629b1f9d8bfda37852de393ee6f403005/charts/grafana/templates/statefulset.yaml#L2) template, allowing for the correct target kind to be generated.
Fixes: [\[grafana\] Incorrect HPA scaleTargetRef creation for StatefulSets #3586](https://github.com/grafana/helm-charts/issues/3586)
> [grafana] Fix HPA scaleTargetRef condition logic

- charts/tempo-distributed/Chart.yaml
- charts/tempo-distributed/README.md
- charts/tempo-distributed/templates/tokengen/tokengen-job.yaml
- charts/tempo-distributed/templates/tokengen/tokengen-rbac.yaml
- charts/tempo-distributed/templates/tokengen/tokengen-serviceaccount.yaml
- charts/tempo-distributed/values.yaml
This PR adds conditional capability to enterprise-traces to store tokengen output in a kubernetes secret to provide parity with Loki and Mimir.  This allows other helm jobs to access the admin token for additional operations such as tenant provisioning.
Fixes: #deployment_tools/217968
> [tempo-distributed] adds conditional ability to store tokengen output into k8s secret.

- charts/tempo-distributed/Chart.yaml
- charts/tempo-distributed/README.md
- charts/tempo-distributed/templates/provisioner/provisioner-job.yaml
- charts/tempo-distributed/templates/provisioner/provisioner-rbac.yaml
- charts/tempo-distributed/templates/provisioner/provisioner-serviceaccount.yaml
- charts/tempo-distributed/values.yaml
What this PR does
Grafana's Federal Cloud offering needs to utilize [enterprise provisioner](https://github.com/grafana/enterprise-provisioner) via configuration to ensure tenants are created properly in a security constrained environment. This change provides consistent tenant management across Grafana products (aligning with Loki and Mimir).
This PR adds an optional job that runs via helm post-install hook that calls the Grafana Enterprise Provisioner app to create tenants, access policies and tokens via the admin api based on configuration in the helm values.
Which issue(s) this PR fixes or relates to
Fixes #3596
Fixes #deployment_tools/2110675
> [tempo-distributed] Add optional provisioner job to provision tenants from configuration

- .github/workflows/linter.yml
- charts/loki-distributed/Chart.yaml
- charts/loki-distributed/README.md
- charts/loki-distributed/templates/distributor/poddisruptionbudget-distributor.yaml
- charts/loki-distributed/templates/gateway/poddisruptionbudget-gateway.yaml
- charts/loki-distributed/templates/index-gateway/poddisruptionbudget-index-gateway.yaml
- charts/loki-distributed/templates/ingester/poddisruptionbudget-ingester.yaml
- charts/loki-distributed/templates/memcached-chunks/poddisruptionbudget-memcached-chunks.yaml
- charts/loki-distributed/templates/memcached-frontend/poddisruptionbudget-memcached-frontend.yaml
- charts/loki-distributed/templates/memcached-index-queries/poddisruptionbudget-memcached-index-queries.yaml
- charts/loki-distributed/templates/memcached-index-writes/poddisruptionbudget-memcached-index-writes.yaml
- charts/loki-distributed/templates/querier/poddisruptionbudget-querier.yaml
- charts/loki-distributed/templates/query-frontend/poddisruptionbudget-query-frontent.yaml
- charts/loki-distributed/templates/query-scheduler/poddisruptionbudget-query-scheduler.yaml
- charts/loki-distributed/templates/ruler/poddisruptionbudget-ruler.yaml
- charts/loki-distributed/values.yaml
**Reasoning:** 
In our use case we need to be able to customize `minAvailable` value in podDisruptionBudgets.
> [loki-distributed]  Add minAvailable poddisruptionbudget

- charts/grafana-sampling/Chart.lock
- charts/grafana-sampling/Chart.yaml
- charts/grafana-sampling/README.md
- charts/grafana-sampling/templates/_alloy_config_deployment.alloy.txt
- charts/grafana-sampling/templates/_alloy_config_statefulset.alloy.txt
- charts/grafana-sampling/templates/_live_debugging.alloy.txt
- charts/grafana-sampling/values.yaml
- This feature has been recently graduated to GA and is very useful during troubleshooting.
- Upgrades alloy to v1.7.5
- See [official doc](https://grafana.com/docs/alloy/latest/troubleshoot/debug/#live-debugging-page)
> [grafana-sampling] Add support for live debugging

- charts/rollout-operator/Chart.yaml
- charts/rollout-operator/README.md
Update corresponding to the new release: https://github.com/grafana/rollout-operator/releases/tag/v0.25.0
> [rollout-operator] update to v0.25.0

- charts/grafana/Chart.yaml
- charts/grafana/README.md
- charts/grafana/values.yaml
I think we should at least document or enable by default the `rule_version_record_limit` setting. We had 10 millions of versions on our side because of alert changes via API. 
Related:
- https://github.com/grafana/grafana-operator/pull/1763
- https://github.com/grafana/grafana/blob/4f19995bef97a6a6b9816b6f5ab7363b0339b5f8/conf/defaults.ini#L1413-L1416
- https://community.grafana.com/t/alert-rule-version-table-in-database-too-large/137270/2
> [grafana] Document limitation of alert's rule_version_record_limit to avoid DB saturation

- charts/grafana/Chart.yaml
- charts/grafana/templates/extra-manifests.yaml
This pull request fixes some extra spaces on the grafana chart extra-manifests.yaml that breaks templating. Basically, those objects are in the helm templates but not déployed in clusters
> [grafana] fix extra spaces in extra objects to fix templating

- charts/tempo-distributed/Chart.yaml
- charts/tempo-distributed/README.md
- charts/tempo-distributed/templates/querier/deployment-querier.yaml
- charts/tempo-distributed/values.yaml
- allow setting `spec.strategy.rollingUpdate.maxUnavailable` for the querier deployment by setting `querier.rollingUpdate.maxUnavailable`
- add the default value of `1` to the values, which is the currently hardcoded value, to maintain backward compatibility
- bump version to `1.33.0`
- update readme via helm-docs
> [tempo-distributed] allow setting spec.strategy.rollingUpdate.maxUnavailable for the querier deployment

- charts/rollout-operator/Chart.yaml
- charts/rollout-operator/README.md
- charts/rollout-operator/templates/deployment.yaml
After seeing that https://github.com/grafana/helm-charts/pull/3638 merged (to address https://github.com/grafana/helm-charts/issues/3632) I realized I missed the inner template metadata section within the Deployment. Apologies!
> [rollout-operator] add missing namespace

- charts/cloudcost-exporter/Chart.yaml
- charts/cloudcost-exporter/README.md
- charts/cloudcost-exporter/templates/deployment.yaml
Part of https://github.com/grafana/cloudcost-exporter/pull/464
Use the port name configured for the Service for the liveness and readiness probes.
> [cloudcost-exporter] use service portName for liveness and readiness probes

- charts/tempo-distributed/Chart.yaml
- charts/tempo-distributed/README.md
- charts/tempo-distributed/values.yaml
Hey folks 👋 
Following Tempo 2.7 release note, this PR will add the query-frontend parameter called `max_spans_per_span_set`
Description of the parameter: https://grafana.com/docs/tempo/latest/configuration/#limit-the-spans-per-spanset
Mention in the release note: https://grafana.com/docs/tempo/latest/setup/upgrade/#maximum-spans-per-span-set
Don't hesitate to reach me if you any remark/questions 😉 
Cheers ☀️
> [tempo-distributed] add max_spans_per_span_set param for query-frontend

- charts/tempo/Chart.yaml
- charts/tempo/README.md
- charts/tempo/values.yaml
Trace WAL files are required for enabling `local-blocks` processor. This setting's default is `""` rather than a default path, which should be set to a sensible default when enabling the metrics-generator.
Here is the relevant documentation concerning the `metrics_generator` config:
https://grafana.com/docs/tempo/latest/configuration/#metrics-generator
> [tempo] Add traces_storage option for spans metrics

- charts/grafana/Chart.yaml
- charts/grafana/README.md
- charts/grafana/templates/image-renderer-deployment.yaml
- charts/grafana/values.yaml
Addresses both remediations in the linked issue.
Closes #3652 
Included:
1. If 'global.imagePullSecrets' is set, then this will be also propagated to the Image Renderer component and will overwrite '.Values.imageRenderer.image.pullSecrets' if specified.
2. The sequence 'imageRenderer.image.pullSecrets' is specified with an empty default value in the values.yaml
> [grafana] Image Pull Secrets for the Image Renderer deployment not set in values.yaml

- .github/workflows/check-codeowners.yaml
It previously explicitly used ubuntu-20.04 which is EOL.
Related #3656
> chore(github): Update codeowners check to run on latest ubuntu

- charts/rollout-operator/Chart.yaml
- charts/rollout-operator/README.md
- charts/rollout-operator/templates/role.yaml
Based on tests, I think the `patch` permission to `apps/statefulsets` is missing.
```
level=warn ts=2025-04-17T09:02:31.196597988Z msg="unable to adjust desired replicas of StatefulSet" group=ingester err="statefulsets.apps \"loki-general-ingester-zone-b\" is forbidden: User \"system:serviceaccount:loki:loki-general-rollout-operator\" cannot patch resource \"statefulsets\" in API group \"apps\" in the namespace \"loki\""
level=debug ts=2025-04-17T09:02:31.196748498Z msg="reconciling StatefulSet" statefulset=loki-general-ingester-zone-a
level=debug ts=2025-04-17T09:02:31.196812368Z msg="reconciling StatefulSet" statefulset=loki-general-ingester-zone-b
level=debug ts=2025-04-17T09:02:31.196850638Z msg="reconciling StatefulSet" statefulset=loki-general-ingester-zone-c
level=info …
```
> [rollout-operator] fix: add missing patch permission to apps/statefulsets

- charts/grafana/Chart.yaml
Update `appVersion` to the final release version of the container image `11.6.1`.
> [grafana] Update Grafana to 11.6.1

- charts/grafana/Chart.yaml
- charts/grafana/templates/_pod.tpl
- charts/grafana/values.yaml
- Grafana's chart uses [kiwigrid/k8s-sidecar](https://github.com/kiwigrid/k8s-sidecar) as default container image for sidecar and init containers.
- The lifecycle execution of the "script" is after the file has been written and before executing the HTTP call.
- There are some cases where the script is used for variable or string substitution for dynamic content.
- Using the approach with an init container, the script should only run once at initialization, otherwise the watch will always detect a difference in the file and rewrite perpetually
- Allow using the script functionality from the Grafana init container (before only conf in the side container section)
- Allow using the "extraMounts" also in the init container configuration
> [grafana] Add support for custom script and extra mounts in Grafana sidecar

- charts/grafana/Chart.yaml
- charts/grafana/templates/statefulset.yaml
- charts/grafana/values.yaml
- Add `volumeName` field to statefulset template
- Update chart templates for better volume management
- Bump Chart version to 8.13.2
Why is this needed
Currently, when using Grafana as a StatefulSet, we may need to delete the existing Grafana and reinstall it. Even if the PV's Reclaim Policy is set to 'Retain' and we manually restore the PV, we cannot reuse the recovered PV because the volumeName field is missing in the statefulset.yaml
What would you like to be added
I worked around the issue and solved it as follows.
```yaml
volumeClaimTemplates:
- apiVersion: v1
kind: PersistentVolumeClaim
metadata:
name: storage
spec:
accessModes: {{ .Values.persistence.accessModes }}
storageClassName: {{ .Values.persistence.storageClassName }}
volumeName: {{ .Values.persistence.volumeName | quote }} …
```
> [grafana] Add volumeName field to statefulset template

- charts/loki-distributed/Chart.yaml
- charts/loki-distributed/README.md
- charts/loki-distributed/templates/ingester/statefulset-ingester.yaml
- charts/loki-distributed/values.yaml
In our LGTM project we want to be able to set the 'updateStrategy' of the Loki Ingester StatefulSet to 'onDelete'.
Currently, this is not possible while using the Loki Distributed helm chart.
With the changes in this PR, the Loki Ingester StatefulSet should default to updateStrategy 'rollingUpdate' with partition set to '0' and override the updateStrategy depending on the statefulStrategy value.
> [loki-distributed] adds ability to set updateStrategy in the Loki Ingester StatefulSet

- charts/cloudcost-exporter/Chart.yaml
- charts/cloudcost-exporter/README.md
use 0.8.1 instead since 0.8.0 contains a bug
> [cloudcost-exporter] Use cloudcost-exporter patch v0.8.1

- charts/rollout-operator/Chart.yaml
- charts/rollout-operator/README.md
- charts/rollout-operator/templates/deployment.yaml
- charts/rollout-operator/values.yaml
This PR is an update of https://github.com/grafana/helm-charts/pull/3473
I came across this while attempting to deploy the [Loki Helm chart](https://github.com/grafana/loki/tree/main/production/helm/loki) and found that I needed to set `args` for deploying with Mimir.
This will enable users to specify additional arguments while preserving the existing default.
> [rollout-operator] Enable setting containers.extraArgs

- .github/workflows/update-helm-repo.yaml
It's defined in the env, but it's possible this syntax for env expansion only works inside bash/run statements, and is not done by the normal processor. Let's just try setting it, to see if it fixes: https://raintank-corp.slack.com/archives/C08Q3NB2VL3/p1746043218511839 (I don't know of another way to test changes here)
I double checked and the same potential issue doesn't appear in any other steps.
> update-helm-repo: Test a different format for expanding app ID

- charts/grafana/Chart.yaml
- charts/grafana/README.md
- charts/grafana/values.yaml
The trivy scanner recommends explicitly dropping all capabilities. The explicit `add` ensures `CHOWN` is still permitted.
Similarly, readonlyRootFilesystem is recommended.
> [grafana] Explicitly drop all unused capabilities for init-chown-data and set readonlyRootFilesystem

- charts/grafana/Chart.yaml
- charts/grafana/README.md
- charts/grafana/values.yaml
Revert readOnlyRootFilesystem per https://github.com/grafana/helm-charts/issues/3690
Fixes https://github.com/grafana/helm-charts/issues/3690
> [grafana] Revert initChownData readOnlyRootFilesystem - 6cd0753

- .github/workflows/update-helm-repo.yaml
I originally updated the wrong job, the `setup` job was fine, it was `release` that was failing:
> ci: fix `update-helm-repo.yaml` github actions workflow

- charts/grafana/Chart.yaml
- charts/grafana/README.md
- charts/grafana/templates/_config.tpl
- charts/grafana/values.yaml
With the following `values.yaml` snippet:
```yaml
dashboardProviders:
dashboardproviders.yaml:
apiVersion: 1
providers:
- name: default
orgId: 1
folder: ''
type: file
disableDeletion: true
editable: false
options:
path: "/var/lib/grafana/dashboards/default"
dashboards:
default:
"cert-manager":
url: "https://github.com/monitoring-mixins/website/raw/refs/heads/master/assets/cert-manager/dashboards/overview.json"
"cloudnative-pg":
url: "https://github.com/cloudnative-pg/grafana-dashboards/raw/refs/heads/main/charts/cluster/grafana-dashboard.json"
"nginx":
url: "https://github.com/kubernetes/ingress-nginx/raw/refs/heads/main/deploy/grafana/dashboards/nginx.json"
"request-handling-performance":
url: "https://github.com/kubernetes/ingress-nginx/raw/refs/heads/main/deploy/grafana/dashboards/reque …
```
> [grafana] Allow users to override curl short options

- charts/tempo-distributed/Chart.yaml
- charts/tempo-distributed/README.md
- charts/tempo-distributed/templates/gateway/deployment-gateway.yaml
- charts/tempo-distributed/values.yaml
This PR adds an annotations map (default empty) as part of the values for the gateway that allows for specifying annotations specific to the Tempo gateway deployment.
In order to comply with certain internal security standards it would be great to be able to specify annotations for the Tempo gateway deployment (now this is only possible for gateway pods). This functionality seems present for most other components (e.g.: distributor, compactor, querier) but seems left out for the gateway.
> [tempo-distributed] Add support to set specific Tempo gateway annotations

- charts/tempo-distributed/Chart.yaml
- charts/tempo-distributed/README.md
- charts/tempo-distributed/templates/provisioner/provisioner-job.yaml
- charts/tempo-distributed/values.yaml
This PR adds extraVolumes to the provisioner definition to ensure it can properly mount TLS certificates. This PR also corrects the initContainer to use a single container with a call to /usr/bin/provisioner for each tenant, instead of an initContainer per tenant.
Fixes: #3701
> [tempo-distributed] Add extraVolumes to support mTLS for provisioner job

- charts/rollout-operator/Chart.yaml
- charts/rollout-operator/README.md
Updates the rollout-operator helm chart to correspond with the new rollout-operator release: https://github.com/grafana/rollout-operator/releases/tag/v0.27.0
> [rollout-operator] update to v0.27.0

- charts/tempo-distributed/Chart.yaml
- charts/tempo-distributed/README.md
- charts/tempo-distributed/templates/compactor/deployment-compactor.yaml
This MR removes the `replicas` field from the compactor deployment when autoscaling is enabled. This prevents the deployment from being scaled back to the fixed replica count during rollouts, before the HPA/KEDA takes over again.
> [tempo-distributed] Remove replicas when autoscaling is enabled for compactor

- charts/tempo-distributed/Chart.yaml
- charts/tempo-distributed/README.md
- charts/tempo-distributed/values.yaml
https://github.com/grafana/helm-charts/pull/3491 made `minReadySeconds` configurable but didn't add a default for `querier.minReadySeconds` value, which causes the existing setups relying on the previous hard-coded default to get a `null`. That leads to diffs like this:
```diff
-   minReadySeconds: 10
+   minReadySeconds: null
```
This PR adds a default for `querier.minReadySeconds`.
> [tempo-distributed] add missing minReadySeconds value for querier

- charts/tempo-distributed/Chart.yaml
- charts/tempo-distributed/README.md
- charts/tempo-distributed/templates/metrics-generator/statefulset-metrics-generator.yaml
revisionHistoryLimit is not part of the statefulset spec
> [tempo-distributed] remove revisionHistoryLimit from metrics generator statefulset

- charts/tempo/Chart.yaml
- charts/tempo/README.md
- charts/tempo/templates/_ports.tpl
- charts/tempo/values.yaml
in https://github.com/grafana/helm-charts/pull/3745 i forgot that port 3100 is set also in the k8s service and the tempo config itself, this PR fixes it
> [tempo] fix port 3200 alignment

- charts/grafana/Chart.yaml
- charts/grafana/values.yaml
The latest change causes issues to sidecars running kiwigrid. downgrading kiwigrid to 1.30.3 will fix the issue.
- Kiwigrid has an issue with SSL, which deletes all dashboards from grafana.
- Downgrading to a working version (from 1.30.5 to 1.30.3)
- Link of the bug: https://github.com/kiwigrid/k8s-sidecar/issues/400
> [grafana] SSL issue with dashboard/datasource sidecards caused by bug on kiwigrid

- charts/tempo-distributed/Chart.yaml
- charts/tempo-distributed/README.md
- charts/tempo-distributed/templates/metrics-generator/statefulset-metrics-generator.yaml
When running helm validation it is expected that each statefulset contains a serviceName as an identifier [as having none is known to cause issues with validation](https://github.com/helm/helm/issues/7207). Other statefulset components such as ingesters [have this field](https://github.com/grafana/helm-charts/blob/main/charts/tempo-distributed/templates/ingester/statefulset-ingester.yaml#L31) and thus pass validation when enabled. 
This change simply adds `serviceName: metrics-generator` to the spec field of the metrics generator statefulset template. 
All other component statefulsets in tempo-distributed have a serviceName which meets this requirement, this change brings all existing statefulset components in line.
Signed-off-by: Stephen Black sjb4634@gmail.com
> [tempo-distributed] Add serviceName to the metrics-generator statefulset

- charts/tempo-distributed/Chart.yaml
- charts/tempo-distributed/README.md
- charts/tempo-distributed/templates/compactor/poddisruptionbudget-compactor.yaml
- charts/tempo-distributed/templates/compactor/service-compactor.yaml
- charts/tempo-distributed/templates/distributor/hpa.yaml
- charts/tempo-distributed/templates/distributor/poddisruptionbudget-distributor.yaml
- charts/tempo-distributed/templates/ingester/hpa.yaml
- charts/tempo-distributed/templates/ingester/poddisruptionbudget-ingester.yaml
- charts/tempo-distributed/templates/memcached/poddisruptionbudget-memcached.yaml
- charts/tempo-distributed/templates/querier/hpa.yaml
- charts/tempo-distributed/templates/querier/poddisruptionbudget-querier.yaml
- charts/tempo-distributed/templates/query-frontend/hpa.yaml
- charts/tempo-distributed/templates/query-frontend/ingress-query-frontend.yaml
- charts/tempo-distributed/templates/query-frontend/poddisruptionbudget-query-frontend.yaml
fix namespace field missing issue when helm release is managed by ArgoCD.
> [tempo-distributed] fix missing namespace field

- charts/grafana-sampling/Chart.lock
- charts/grafana-sampling/Chart.yaml
- charts/grafana-sampling/README.md
- charts/grafana-sampling/templates/_otelcol_receiver_otlp.alloy.txt
- charts/grafana-sampling/values.yaml
This adds the ability to set grpc server keepalive parameters to otlp receivers used in the sampling chart.
> [grafana-sampling] add receiver parameters

- charts/grafana/Chart.yaml
- charts/grafana/templates/_pod.tpl
Closes #3861
Quick fix to standardize the naming of the primary container within the grafana pod using the `grafana.name` named template
> [grafana] Update _pod.tpl to override container name 

- charts/tempo-distributed/Chart.yaml
- charts/tempo-distributed/README.md
- charts/tempo-distributed/templates/provisioner/provisioner-job.yaml
- charts/tempo-distributed/values.yaml
The current image does not provide a suitable shell. Therefore, switching to the same image as the [mimir](https://github.com/grafana/mimir/pull/12498)
> [tempo-distributed] replace kubectl default image with alpine/kubectl

- charts/tempo-distributed/Chart.yaml
- charts/tempo-distributed/README.md
- charts/tempo-distributed/templates/admin-api/admin-api-dep.yaml
- charts/tempo-distributed/templates/compactor/deployment-compactor.yaml
- charts/tempo-distributed/templates/distributor/deployment-distributor.yaml
- charts/tempo-distributed/templates/enterprise-federation-frontend/deployment-federation-frontend.yaml
- charts/tempo-distributed/templates/enterprise-gateway/gateway-dep.yaml
- charts/tempo-distributed/templates/gateway/deployment-gateway.yaml
- charts/tempo-distributed/templates/ingester/statefulset-ingester.yaml
- charts/tempo-distributed/templates/memcached/statefulset-memcached.yaml
- charts/tempo-distributed/templates/metrics-generator/statefulset-metrics-generator.yaml
- charts/tempo-distributed/templates/querier/deployment-querier.yaml
- charts/tempo-distributed/templates/query-frontend/deployment-query-frontend.yaml
- charts/tempo-distributed/templates/tokengen/tokengen-job.yaml
- charts/tempo-distributed/values.yaml
> [tempo-distributed] align usage of globa.extraArgs and globa.extraEnvFrom across.

- charts/rollout-operator/Chart.yaml
- charts/rollout-operator/README.md
Updating the chart to correspond to the new release: https://github.com/grafana/rollout-operator/releases/tag/v0.29.0
> [rollout-operator] update for v0.29.0 release

- charts/grafana/Chart.yaml
- charts/grafana/templates/_pod.tpl
Set ~~`GOMAXPROCS` and~~ `GOMEMLIMIT` environment variables based on container resources. This should reduce potential CPU throttling and OOMKills on containers.
The [`resourceFieldRef`](https://kubernetes.io/docs/concepts/workloads/pods/downward-api/#downwardapi-resourceFieldRef) is a very specific Kubernetes directive that is created specifically for passing resource-related values, which rounds up the CPU value to the nearest whole number (e.g. 250m to 1) and passes the memory as a numeric value; so `64Mi` would result in the environment variable being set to `67108864`. This by design makes it completely compatible with Go's API.
An example is documented within Kubernetes documentation itself: https://kubernetes.io/docs/tasks/inject-data-application/environment-variable-expose-pod-info …
> [grafana] Set `GOMEMLIMIT` environment variable based on container resources

- charts/grafana/Chart.yaml
- charts/grafana/templates/statefulset.yaml
I want to run a scheduled backup of the Grafana database and for that I need to be able to mount the PVC to the backup runner pod in readonly mode, however the default ReadWriteOnce mode prevents this. Adding ReadOnlyMany accessMode in `values.yaml` results in
```yaml
accessModes:
- ReadWriteOnce ReadOnlyMany
```
Instead of
```yaml
accessModes:
- ReadWriteOnce
- ReadOnlyMany
```
I reused the template from `pvc.yaml`
> [grafana] fix print statefulset pvc claim accessmode as list

- charts/grafana/Chart.yaml
bump Grafana to version [12.1.1](https://github.com/grafana/grafana/releases/tag/v12.1.1), released two weeks ago, as version 12.1.0 has a bug that prevents creating alerts as it shows no contact points
> [grafana] - bump to version 12.1.1

- charts/rollout-operator/Chart.yaml
- charts/rollout-operator/README.md
- charts/rollout-operator/README.md.gotmpl
- charts/rollout-operator/crds/replica-templates-custom-resource-definition.yaml
- charts/rollout-operator/crds/zone-aware-pod-disruption-budget-custom-resource-definition.yaml
- charts/rollout-operator/templates/deployment.yaml
- charts/rollout-operator/templates/no-downscale-webhook.yaml
- charts/rollout-operator/templates/pod-eviction-webhook.yaml
- charts/rollout-operator/templates/prepare-downscale-webhook.yaml
- charts/rollout-operator/templates/role.yaml
- charts/rollout-operator/templates/service.yaml
- charts/rollout-operator/templates/webhook-clusterrole-binding.yaml
- charts/rollout-operator/templates/webhook-clusterrole.yaml
- charts/rollout-operator/templates/webhook-role-binding.yaml
- charts/rollout-operator/templates/webhook-role.yaml
- charts/rollout-operator/templates/zone-aware-pod-disruption-budget-validating-webhook.yaml
- charts/rollout-operator/values.yaml
This PR relates to https://github.com/grafana/mimir-squad/issues/2365
This PR adds support to the helm rollout-operator chart for enabling the rollout-operator webhooks. This includes;
* no-downscale validating webhook configuration
* prepare-downscale mutating webhook configuration
* pod-eviction validating webhook configuration
* zpdb-validation validating webhook configuration
* zpdb custom resource definition
* replica templates custom resource definition
Note - this PR is also related to https://github.com/grafana/mimir-squad/issues/3179 - where by the jsonnet specific to the rollout-operator will be moved from mimir to the rollout-operator repo. 
This is a new version of https://github.com/grafana/helm-charts/pull/3859
> [rollout-operator] Enable webhooks for rollout-operator

- charts/grafana-mcp/Chart.yaml
- charts/grafana-mcp/templates/deployment.yaml
It should be possible to leave authentication part exclusively on the client side using `X-Grafana-API-Key` header. Also renaming env var as `GRAFANA_API_KEY` is deprecated.
> [grafana-mcp] Set api token env conditionally

- charts/cloudcost-exporter/Chart.yaml
- charts/cloudcost-exporter/README.md
Updated with https://github.com/grafana/cloudcost-exporter/releases/tag/v0.10.0
> [cloudcost-exporter] Update cloudcost exporter helm version
