- charts/grafana/Chart.yaml
- charts/grafana/values.yaml
Update grafana to 7.1.5
See - https://hub.docker.com/r/grafana/grafana/tags
Signed-off-by: S.Cavallo <smcavallo@hotmail.com>
> Update grafana to 7.1.5

- charts/grafana/Chart.yaml
- charts/grafana/templates/_pod.tpl
> Support templating in `env` values

- charts/grafana/Chart.yaml
- charts/grafana/values.yaml
Signed-off-by: Yury Vidineev <adeptg@gmail.com>
> Update grafana to 7.2.0

- charts/grafana/Chart.yaml
- charts/grafana/templates/_pod.tpl
Convert env values to string before templating
> Resolves #23

- charts/grafana/Chart.yaml
- charts/grafana/templates/deployment.yaml
- charts/grafana/templates/statefulset.yaml
Signed-off-by: Isa Tokunaga <isa.tokunaga@thoughtworks.com>
> Fix condition for secret checksum to match that in secret.yaml

- charts/grafana/Chart.yaml
- charts/grafana/OWNERS
- charts/grafana/README.md
Fixes #6
Signed-off-by: Torsten Walter <mail@torstenwalter.de>
> Document helm repo add in chart README

- .github/workflows/sync-readme.yaml
- README.md
> Sync README to gh-pages branch

- charts/grafana/Chart.yaml
- charts/grafana/templates/image-renderer-deployment.yaml
Signed-off-by: codehimanshu <himanshuagrawal1998@gmail.com>
> fix: image renderer security context space fix

- charts/grafana/Chart.yaml
- charts/grafana/README.md
This moves the README alignement part out of #39
> Align README of Grafana Chart

- charts/grafana/Chart.yaml
- charts/grafana/templates/image-renderer-deployment.yaml
- charts/grafana/values.yaml
Signed-off-by: odavid <ohad.david@gmail.com>
> Added resources for imageRenderer

- charts/grafana/Chart.yaml
- charts/grafana/templates/image-renderer-deployment.yaml
Thank you for merging #45, however, I found a bug in the resource indentation.
This PR fixes it.
Sorry for the bug
> Fix indentation of #45

- charts/grafana/Chart.yaml
- charts/grafana/values.yaml
Signed-off-by: Calvin Bui <3604363+calvinbui@users.noreply.github.com>
> Update Grafana to 7.2.1

- charts/grafana/Chart.yaml
- charts/grafana/README.md
- charts/grafana/values.yaml
Updates the sidecar container version
> [grafana] Update k8s-sidecar to 1.1.0

- charts/grafana/Chart.yaml
- charts/grafana/README.md
- charts/grafana/values.yaml
Reverts grafana/helm-charts#64
> Revert "[grafana] Update k8s-sidecar to 1.1.0"

- charts/grafana/Chart.yaml
- charts/grafana/README.md
- charts/grafana/values.yaml
Due to https://curl.haxx.se/docs/vuln-7.70.0.html
@zanhsieh  please merge after #66 (due to chart version)
> [grafana] Update curl to 7.73.0

- charts/grafana/Chart.yaml
Author and owner of the [Puppet Server Helm chart](https://github.com/puppetlabs/puppetserver-helm-chart).
Maintainer of the [Prometheus](https://github.com/prometheus-community/helm-charts/tree/main/charts/prometheus) and [Kube-Prometheus Stack](https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack) Helm charts.
CC: @zanhsieh
> Add Xtigyro As a Maintainer

- charts/grafana/Chart.yaml
- charts/grafana/README.md
- charts/grafana/values.yaml
```
$ kubectl get po
NAME                      READY   STATUS    RESTARTS   AGE
grafana-6c5596bb7-bg2sg   1/1     Running   0          16m
$ helm list
NAME   	NAMESPACE	REVISION	UPDATED                             	STATUS  	CHART        	APP VERSION
grafana	default  	1       	2020-10-28 12:03:10.848532 +0800 HKT	deployed	grafana-5.9.0	7.2.1
$ helm version
version.BuildInfo{Version:"v3.4.0", GitCommit:"7090a89efc8a18f3d8178bf47d2462450349a004", GitTreeState:"dirty", GoVersion:"go1.15.3"}
```
> Helm3 support

- charts/grafana/Chart.yaml
- charts/grafana/README.md
- charts/grafana/templates/servicemonitor.yaml
- charts/grafana/values.yaml
Adding support for scraping of TLS endpoints.
> Adding HTTPS support for the ServiceMonitor

- charts/grafana/Chart.yaml
- charts/grafana/values.yaml
Bumps the app and the image version to Grafana 7.3.3
> Bump Grafana to 7.3.3

- charts/grafana/Chart.yaml
- charts/grafana/templates/_helpers.tpl
- charts/grafana/templates/role.yaml
- charts/grafana/templates/rolebinding.yaml
Signed-off-by: zanhsieh <zanhsieh@gmail.com>
> Fix deprecated role APIs

- charts/grafana/Chart.yaml
- charts/grafana/templates/configmap-dashboard-provider.yaml
fix: no folder if foldersFromFilesStructure
fix: add default updateIntervalSeconds + allow configuration override
> chore: side car config improvements

- .github/workflows/release.yaml
- charts/grafana/Chart.yaml
- cr.yaml
In order to be able to test it, the Grafana chart version is bumped.
> Turn on GPG signing

- .github/CODEOWNERS
- charts/loki-canary/.helmignore
- charts/loki-canary/Chart.yaml
- charts/loki-canary/README.md
- charts/loki-canary/README.md.gotmpl
- charts/loki-canary/ci/with-basic-auth-values.yaml
- charts/loki-canary/ci/without-basic-auth-values.yaml
- charts/loki-canary/templates/NOTES.txt
- charts/loki-canary/templates/_helpers.tpl
- charts/loki-canary/templates/daemonset.yaml
- charts/loki-canary/templates/secret.yaml
- charts/loki-canary/templates/service.yaml
- charts/loki-canary/templates/serviceaccount.yaml
- charts/loki-canary/templates/servicemonitor.yaml
- charts/loki-canary/values.yaml
This adds the loki-canary chart from
https://github.com/unguiculus/loki-helm-chart including its history.
I added myself as CODEOWNER for the chart.
> Add loki-canary chart

- charts/loki-distributed/Chart.yaml
- charts/loki-distributed/README.md
- charts/loki-distributed/README.md.gotmpl
Signed-off-by: Reinhard Nägele <unguiculus@gmail.com>
> [loki-distributed] Remove homepage line from readme template

- charts/loki-canary/Chart.yaml
- charts/loki-canary/README.md
- charts/loki-canary/README.md.gotmpl
Signed-off-by: Reinhard Nägele <unguiculus@gmail.com>
> [loki-canary] Remove homepage line from readme template

- charts/grafana/Chart.yaml
- charts/grafana/values.yaml
7.3.5 has an important important regarding AWS' Sigv4 Signing.
> Bump the app and the image version to Grafana 7.3.5

- charts/fluent-bit/Chart.yaml
- charts/fluent-bit/values.yaml
- charts/loki-canary/Chart.yaml
- charts/loki-canary/README.md
- charts/loki-distributed/Chart.yaml
- charts/loki-distributed/README.md
- charts/loki-stack/Chart.yaml
- charts/loki/Chart.yaml
- charts/loki/values.yaml
- charts/promtail/Chart.yaml
- charts/promtail/values.yaml
This should update everything to the latest Loki release
> Update charts for Loki 2.1.0

- charts/loki-stack/Chart.yaml
- charts/loki-stack/requirements.yaml
Signed-off-by: ohdearaugustin <j-reindl@live.at>
Closes #131
> [loki-stack] Fix requirements

- charts/promtail/Chart.yaml
- charts/promtail/README.md
- charts/promtail/values.yaml
Log level was accidentally set to debug. This reverts
it back to info.
> [promtail] Set log level to info

- charts/loki-distributed/Chart.yaml
- charts/loki-distributed/README.md
- charts/loki-distributed/templates/gateway/deployment-gateway.yaml
- charts/loki-distributed/values.yaml
Mount custom volumes in gateway such as ssl certs
> [loki-distributed] Add extraVolumes and extraVolumeMounts to gateway

- charts/grafana/Chart.yaml
- charts/grafana/README.md
- charts/grafana/templates/image-renderer-deployment.yaml
- charts/grafana/values.yaml
Signed-off-by: Feliksas <computershik@gmail.com>
> [grafana] Add an option to set the serviceAccountName for image-renderer

- charts/loki-distributed/Chart.yaml
- charts/loki-distributed/README.md
- charts/loki-distributed/templates/podsecuritypolicy.yaml
- charts/loki-distributed/templates/role.yaml
- charts/loki-distributed/templates/rolebinding.yaml
- charts/loki-distributed/values.yaml
Loki-distributed is missing PSP (which is present in non-distributed loki).
> [loki-distributed] Add support for PSP

- charts/grafana/Chart.yaml
- charts/grafana/values.yaml
Bump app and image to Grafana v7.4.0
> [grafana] Bump Grafana to v7.4.0

- charts/grafana/Chart.yaml
- charts/grafana/README.md
- charts/grafana/values.yaml
updates k8s sidecar image to version 1.10.0
> [grafana] update k8s sidecar to 1.10.0

- charts/grafana/Chart.yaml
- charts/grafana/values.yaml
Bump app and image to Grafana v7.4.1
> [grafana] Bump Grafana to v7.4.1

- charts/tempo/Chart.yaml
- charts/tempo/README.md
- charts/tempo/templates/statefulset.yaml
- charts/tempo/values.yaml
Add `extraArgs` `extraEnvs` and `extraVolumeMounts` to tempo
Signed-off-by: swartz-k <9215868@gmail.com>
> [tempo] add extra args envs volumeMounts

- charts/tempo-distributed/Chart.yaml
- charts/tempo-distributed/README.md
- charts/tempo-distributed/templates/memcached/statefulset-memcached.yaml
** Description
Image of memcached exporter is not set properly.
> [tempo-distributed] Fix memcached exporter image.

- charts/tempo/Chart.yaml
- charts/tempo/README.md
- charts/tempo/templates/_helpers.tpl
- charts/tempo/templates/serviceaccount.yaml
- charts/tempo/templates/statefulset.yaml
- charts/tempo/values.yaml
This PR fix following issues:
* https://github.com/grafana/helm-charts/issues/235
* https://github.com/grafana/helm-charts/issues/251
> [tempo] Add Service account. Fix persistence enabled

- charts/tempo-distributed/Chart.yaml
- charts/tempo-distributed/README.md
- charts/tempo-distributed/templates/compactor/deployment-compactor.yaml
- charts/tempo-distributed/templates/distributor/deployment-distributor.yaml
- charts/tempo-distributed/templates/ingester/statefulset-ingester.yaml
- charts/tempo-distributed/templates/memcached/statefulset-memcached.yaml
- charts/tempo-distributed/templates/querier/deployment-querier.yaml
- charts/tempo-distributed/templates/query-frontend/deployment-query-frontend.yaml
This PR fix following issues:
* https://github.com/grafana/helm-charts/issues/251
> [tempo-distributed] Fix Service Account 

- charts/promtail/Chart.yaml
- charts/promtail/README.md
- charts/promtail/values.yaml
Run the lokiAddress through the `tpl` function.. this allows us to do things like this:
```yaml
promtail:
config:
lokiAddress: https://{{ .Release.Name }}-loki-gateway/loki/api/v1/push
```
> [promtail] Run config.lokiAddress through the tpl function

- .github/workflows/release.yaml
Signed-off-by: Reinhard Nägele <unguiculus@gmail.com>
> Add missing charts repos to release workflow

- charts/grafana/Chart.yaml
- charts/grafana/README.md
- charts/grafana/templates/_helpers.tpl
- charts/grafana/templates/ingress.yaml
- charts/grafana/values.yaml
Add support to new ingress API.
> [grafana] Modify ingress template to be compatible with new api version

- charts/grafana/Chart.yaml
- charts/grafana/templates/ingress.yaml
- charts/grafana/values.yaml
Fixes [this](https://github.com/grafana/helm-charts/issues/271#issuecomment-790840360)
Signed-off-by: Yurii Matsiuk <ymatsiuk@users.noreply.github.com>
> [grafana] Fix pathType missing for grafana ingress

- .github/CODEOWNERS
mapno is a new member of our team and will be helping with the helm-charts
> [tempo] Make mapno a tempo code owner

- charts/tempo-distributed/Chart.yaml
- charts/tempo-distributed/README.md
- charts/tempo-distributed/templates/compactor/deployment-compactor.yaml
Compactor was not part of the memberlist/ring yet. Added the containerPort and the gossip ring selector labels.
**Added Benefits**
- Compactor starts working as intended.
> [tempo-distributed] Add compactor to ring.

- charts/tempo/Chart.yaml
- charts/tempo/README.md
- charts/tempo/templates/statefulset.yaml
This PR is adding missing ports for the Tempo `StatefulSet`. Without this, the Service cannot receive messages from any application.
> [tempo] Adding missing STS ports

- charts/promtail/Chart.yaml
- charts/promtail/README.md
> [promtail] updating for loki release 2.2.0

- charts/loki-canary/Chart.yaml
- charts/loki-canary/README.md
> [loki-canary] updating for loki release 2.2.0

- charts/loki-distributed/Chart.yaml
- charts/loki-distributed/README.md
> [loki-distributed] updating for loki release 2.2.0

- charts/loki/Chart.yaml
> [loki] Last release didn't seem to publish, trying again

- charts/grafana/Chart.yaml
- charts/grafana/README.md
- charts/grafana/templates/_pod.tpl
- charts/grafana/values.yaml
fixes #294
Signed-off-by: Roger Steneteg <rsteneteg@ea.com>
> [grafana] add ability to specify subPath for the callback url for image renderer

- charts/grafana/Chart.yaml
- charts/grafana/README.md
- charts/grafana/values.yaml
Update image tag in chart.  It is actually 7.4.3
> [grafana] Update image tag

- charts/tempo-distributed/Chart.yaml
- charts/tempo-distributed/README.md
- charts/tempo-distributed/templates/compactor/deployment-compactor.yaml
- charts/tempo-distributed/templates/distributor/deployment-distributor.yaml
- charts/tempo-distributed/templates/ingester/statefulset-ingester.yaml
- charts/tempo-distributed/templates/querier/deployment-querier.yaml
- charts/tempo-distributed/templates/query-frontend/deployment-query-frontend.yaml
Signed-off-by: adam.strawson <adam.strawson@imaginecurve.com>
Fixed #314 
_Apologies for the noise on the duplicate PR, had issues with DCO passing, so closed and created a new PR_
> [tempo-distributed] Added podAnnotations into tempo-distributed templates

- charts/loki-distributed/Chart.yaml
- charts/loki-distributed/README.md
- charts/loki-distributed/README.md.gotmpl
- charts/loki-distributed/ci/persistence-values.yaml
- charts/loki-distributed/templates/NOTES.txt
- charts/loki-distributed/templates/gateway/configmap-gateway.yaml
- charts/loki-distributed/templates/gateway/deployment-gateway.yaml
- charts/loki-distributed/templates/gateway/ingress-gateway.yaml
- charts/loki-distributed/templates/gateway/poddisruptionbudget-gateway.yaml
- charts/loki-distributed/templates/gateway/secret-gateway.yaml
- charts/loki-distributed/templates/gateway/service-gateway.yaml
- charts/loki-distributed/templates/networkpolicy.yaml
- charts/loki-distributed/values.yaml
* Make gateway optional
* Enable `htpasswd` customization
* Make NGINX log format configurable
* Allow adding custom snippets to http and server blocks
in NGINX configuration
Fixes: #243
Fixes: #244
Fixes: #319
> [loki-distributed] Improve Gateway configurability

- charts/grafana/Chart.yaml
- charts/grafana/values.yaml
Bump app and image to Grafana v7.5.1
> [grafana] Bump Grafana to v7.5.1

- charts/grafana/Chart.yaml
- charts/grafana/values.yaml
Bump app and image to Grafana v7.5.2
> [grafana] Bump Grafana to v7.5.2

- charts/grafana/Chart.yaml
- charts/grafana/README.md
- charts/grafana/templates/_pod.tpl
- charts/grafana/values.yaml
Add possibility to declare extraVolumeMounts with hostPath
> [grafana] Add possibility to declare extraVolumeMounts with hostPath

- charts/grafana/Chart.yaml
- charts/grafana/templates/configmap.yaml
Resolves: #378
Signed-off-by: Christian Zenker <christian.zenker@aoe.com>
> [grafana] bugfix: long lines in grafana.ini no longer get line break

- charts/tempo-distributed/Chart.yaml
- charts/tempo-distributed/README.md
> [tempo-distributed] Upgraded to 0.7.0

- charts/tempo/Chart.yaml
- charts/tempo/README.md
- charts/tempo/values.yaml
> [tempo] Upgraded to 0.7.0

- charts/loki-stack/Chart.yaml
- charts/loki-stack/values.yaml
Bump Grafana version to v7.5.0
> [loki-stack] Bump Grafana version

- charts/grafana/Chart.yaml
- charts/grafana/templates/_pod.tpl
let alone from a secret that is not created (pod will not start)
> [grafana] do not set admin user/pass if disabled

- charts/promtail/Chart.yaml
- charts/promtail/README.md
Signed-off-by: 1Psy <41047934+1Psy@users.noreply.github.com>
> [promtail] updating for loki release 2.2.1.

- charts/loki-distributed/Chart.yaml
- charts/loki-distributed/README.md
- charts/loki-distributed/values.yaml
This solves: https://github.com/grafana/helm-charts/issues/439
> [loki-distributed] Add option to specify dns namespace

- charts/loki-distributed/Chart.yaml
- charts/loki-distributed/README.md
Signed-off-by: Nicolas Vanheuverzwijn <nicolas.vanheu@gmail.com>
> [loki-distributed] updating for loki release 2.2.1

- charts/loki-distributed/Chart.yaml
- charts/loki-distributed/README.md
- charts/loki-distributed/README.md.gotmpl
- charts/loki-distributed/values.yaml
Signed-off-by: Sherif Ayad <sherif.k.ayad@gmail.com>
> [loki-distributed] added the live tailing property to the query frontend

- charts/tempo/Chart.yaml
- charts/tempo/README.md
- charts/tempo/values.yaml
Signed-off-by: Martin Disibio <mdisibio@gmail.com>
> [tempo] Bump default appversion to 1.0.0

- charts/tempo-distributed/Chart.yaml
- charts/tempo-distributed/README.md
Signed-off-by: Martin Disibio <mdisibio@gmail.com>
> [tempo-distributed] Bump default appversion to 1.0.0

- charts/tempo-distributed/Chart.yaml
- charts/tempo-distributed/README.md
> [tempo-distributed] Tempo 1.0.1

- charts/tempo/Chart.yaml
- charts/tempo/README.md
- charts/tempo/values.yaml
> [tempo] Tempo 1.0.1

- charts/tempo-distributed/Chart.yaml
- charts/tempo-distributed/README.md
> [tempo-distributed] Bump version to force rebuild of index.yaml

- charts/grafana/Chart.yaml
- charts/grafana/README.md
- charts/grafana/values.yaml
> [grafana] Bump Grafana to 8.0.2

- charts/loki-distributed/Chart.yaml
- charts/loki-distributed/README.md
- charts/loki-distributed/README.md.gotmpl
- charts/loki-distributed/templates/gateway/ingress-gateway.yaml
- charts/loki-distributed/values.yaml
Signed-off-by: Sherif Ayad <sherif.k.ayad@gmail.com>
> [loki-distributed] Added support for newer Ingress versions (v1) for the Gateway component

- charts/grafana/Chart.yaml
- charts/grafana/templates/_pod.tpl
fixes #530 
Signed-off-by: Laurent Demailly <ldemailly@gmail.com>
> [grafana] use sh -x for download script

- .github/workflows/lint-test.yaml
- charts/grafana/Chart.yaml
- charts/grafana/templates/podsecuritypolicy.yaml
- charts/grafana/templates/tests/test-podsecuritypolicy.yaml
@zanhsieh This is just to try out if updating helm/kind-action solves the issue identified in #545
closes #545 as it adds those changes and also updates github actions.
> [grafana] Update GitHub action

- charts/loki-canary/Chart.yaml
- charts/loki-canary/README.md
- charts/loki-canary/templates/serviceaccount.yaml
Signed-off-by: Christian Zunker <christian.zunker@codecentric.cloud>
> [loki-canary] Fix automountServiceAccountToken

- charts/enterprise-metrics/CHANGELOG.md
- charts/enterprise-metrics/Chart.yaml
- charts/enterprise-metrics/values.yaml
> [enterprise-metrics] Fix DNS address in config for self-monitoring

- charts/loki-distributed/Chart.yaml
- charts/loki-distributed/templates/_helpers.tpl
- charts/loki-distributed/templates/gateway/ingress-gateway.yaml
Fixes https://github.com/grafana/helm-charts/issues/574.
> [loki-distributed] Fix ingress behaviour

- charts/grafana/Chart.yaml
- charts/grafana/templates/_helpers.tpl
This PR improves the logic in #505.
> [grafana] Improve ingress API logic

- charts/grafana/Chart.yaml
- charts/grafana/values.yaml
Signed-off-by: Jeroen Landheer <jlandheer@bintelligence.nl>
Simple version bump of Grafana and the chart.
> [grafana] Grafana upgrade to v8.1.0

- charts/grafana/Chart.yaml
- charts/grafana/values.yaml
Signed-off-by: Sherif Ayad <sherif.k.ayad@gmail.com>
Fixes #638
> [grafana] bumped the chart version to 6.16.1 and the Grafana version to 8.1.2

- charts/grafana/Chart.yaml
- charts/grafana/README.md
- charts/grafana/values.yaml
Signed-off-by: Alejandro Germain <alexpg258@gmail.com>
> [grafana] Fix extraContainers docs and improve example

- charts/tempo-distributed/Chart.yaml
- charts/tempo-distributed/README.md
> [tempo-distributed] Updated to 1.1

- charts/tempo/Chart.yaml
- charts/tempo/README.md
- charts/tempo/values.yaml
> [tempo] Update to 1.1

- charts/loki-distributed/Chart.yaml
- charts/loki-distributed/README.md
- charts/loki-distributed/README.md.gotmpl
- charts/loki-distributed/templates/distributor/deployment-distributor.yaml
- charts/loki-distributed/templates/distributor/hpa.yaml
- charts/loki-distributed/templates/gateway/deployment-gateway.yaml
- charts/loki-distributed/templates/gateway/hpa.yaml
- charts/loki-distributed/templates/querier/deployment-querier.yaml
- charts/loki-distributed/templates/querier/hpa.yaml
- charts/loki-distributed/templates/query-frontend/deployment-query-frontend.yaml
- charts/loki-distributed/templates/query-frontend/hpa.yaml
- charts/loki-distributed/values.yaml
Fixes https://github.com/grafana/helm-charts/issues/664.
> [loki-distributed] Add autoscaling support

- .github/CODEOWNERS
- .github/workflows/lint-test.yaml
- .helmdocsignore
- charts/enterprise-logs/CHANGELOG.md
- charts/enterprise-logs/Chart.lock
- charts/enterprise-logs/Chart.yaml
- charts/enterprise-logs/README.md
- charts/enterprise-logs/ci/test-values.yaml
- charts/enterprise-logs/small.yaml
- charts/enterprise-logs/templates/_helpers.tpl
- charts/enterprise-logs/templates/admin-api/_helpers.yaml
- charts/enterprise-logs/templates/admin-api/deployment-admin-api.yaml
- charts/enterprise-logs/templates/admin-api/service-admin-api.yaml
- charts/enterprise-logs/templates/compactor/_helpers.yaml
- charts/enterprise-logs/templates/compactor/statefulset-compactor.yaml
- charts/enterprise-logs/templates/gateway/_helpers.yaml
- charts/enterprise-logs/templates/gateway/deployment-gateway.yaml
- charts/enterprise-logs/templates/gateway/service-gateway.yaml
- charts/enterprise-logs/templates/secret-config.yaml
- charts/enterprise-logs/templates/secret-license.yaml
- charts/enterprise-logs/templates/tokengen/_helpers.yaml
- charts/enterprise-logs/templates/tokengen/job-tokengen.yaml
- charts/enterprise-logs/templates/tokengen/role-tokengen.yaml
- charts/enterprise-logs/templates/tokengen/rolebinding-tokengen.yaml
- charts/enterprise-logs/templates/tokengen/serviceaccount-tokengen.yaml
- charts/enterprise-logs/values.yaml
This is the initial version of the Grafana Enterprise Logs (GEL) Helm chart.
It is based on `loki-distributed` and extends it with additional services, configuration and license.
> [enterprise-logs] Initial version of the GEL Helm chart

- charts/enterprise-logs/CHANGELOG.md
- charts/enterprise-logs/Chart.lock
- charts/enterprise-logs/Chart.yaml
- charts/enterprise-logs/ci/test-values.yaml
- charts/enterprise-logs/small.yaml
- charts/enterprise-logs/values.yaml
Fixes #682
Fixes #683 
Fixes #685
> [enterprise-logs] Remove table-manager and deploy index-gateway

- charts/grafana/Chart.yaml
Signed-off-by: Maarten De Wispelaere <maarten@bitprocessor.be>
> [grafana] Update chart with grafana 8.1.5

- charts/grafana/Chart.yaml
- charts/grafana/templates/image-renderer-deployment.yaml
Signed-off-by: butlerx <butlerx@notthe.cloud>
> [grafana] Add `livenessProbe` to grafana image renderer

- charts/agent-operator/Chart.yaml
- charts/agent-operator/README.md
- charts/agent-operator/README.md.gotmpl
Signed-off-by: hjet <hjet@users.noreply.github.com>
> [agent-operator] Add warning to README

- charts/grafana/Chart.yaml
- charts/grafana/values.yaml
Signed-off-by: Maarten De Wispelaere <maarten@bitprocessor.be>
> [grafana] Update grafana to 8.1.6

- charts/agent-operator/Chart.yaml
- charts/agent-operator/README.md
- charts/agent-operator/templates/operator-clusterrole.yaml
- charts/agent-operator/templates/operator-deployment.yaml
- charts/agent-operator/values.yaml
Closes https://github.com/grafana/agent/issues/1024
- Update operator images
- Add toggle to `values.yaml` for `kubelet-service`
> [agent-operator] Update Agent Operator to v0.20.0

- charts/grafana/Chart.yaml
- charts/grafana/README.md
- charts/grafana/values.yaml
Signed-off-by: Roman Verenich <r.verenich@melsoft-games.com>
> [grafana] CVE-2021-41174: update helm chart for grafana to comply with

- charts/loki/Chart.yaml
- charts/loki/values.yaml
Signed-off-by: Owen Diehl <ow.diehl@gmail.com>
> [loki] release 2.8.0

- charts/loki-distributed/Chart.yaml
- charts/loki-distributed/README.md
- charts/loki-distributed/ci/cache-values.yaml
- charts/loki-distributed/values.yaml
Signed-off-by: Owen Diehl <ow.diehl@gmail.com>
> [loki-distributed] release 0.39.0

- charts/promtail/Chart.yaml
- charts/promtail/README.md
> [promtail] promtail 2.4.1

- charts/loki/Chart.yaml
- charts/loki/values.yaml
> [loki] Loki 2.4.1

- charts/loki-canary/Chart.yaml
- charts/loki-canary/README.md
> [loki-canary] Loki canary 2.4.1

- charts/tempo/Chart.yaml
- charts/tempo/README.md
- charts/tempo/templates/configmap-tempo.yaml
- charts/tempo/values.yaml
I'm excited to try out the new native search: https://grafana.com/docs/tempo/latest/configuration/#search 🔍
> [tempo] add possibility to enable Tempo's native search

- charts/tempo-distributed/Chart.yaml
- charts/tempo-distributed/README.md
Signed-off-by: Martin Disibio <mdisibio@gmail.com>
> [tempo-distributed] Update tempo to 1.2.1

- charts/grafana/Chart.yaml
- charts/grafana/README.md
- charts/grafana/values.yaml
Signed-off-by: Roman Verenich <r.verenich@melsoft-games.com>
> [grafana] update chart to use image 8.2.5 by default

- charts/enterprise-logs/CHANGELOG.md
- charts/enterprise-logs/Chart.yaml
- charts/enterprise-logs/README.md
- charts/enterprise-logs/values.yaml
> [enterprise-logs] Update GEL version in child chart templates

- charts/enterprise-metrics/CHANGELOG.md
- charts/enterprise-metrics/Chart.yaml
- charts/enterprise-metrics/templates/query-frontend-dep.yaml
- charts/enterprise-metrics/values.yaml
Signed-off-by: Patrick Oyarzun <patrick.oyarzun@grafana.com>
> [enterprise-metrics] Upgrade to GEM 1.6.1

- charts/grafana/Chart.yaml
- charts/grafana/README.md
- charts/grafana/templates/_pod.tpl
- charts/grafana/values.yaml
This PR adds the possibility to mount extra volumes in the dashboard sidecar container.
> [grafana] Add additional extra volume mounts to dashboard sidecar container

- charts/tempo/Chart.yaml
- charts/tempo/README.md
- charts/tempo/templates/configmap-tempo.yaml
- charts/tempo/values.yaml
Follow up of #871
Signed-off-by: Annanay Agarwal <annanay.agarwal@grafana.com>
> [tempo] Add overrides to Tempo

- charts/grafana/Chart.yaml
- charts/grafana/values.yaml
Signed-off-by: Maarten De Wispelaere <maarten@bitprocessor.be>
> [grafana] Update to Grafana 8.3.0

- charts/grafana/Chart.yaml
- charts/grafana/README.md
Signed-off-by: Philippe <philippe.burgisser@camptocamp.com>
> [grafana] Missing documentation for new backward compatibility option

- charts/grafana/Chart.yaml
- charts/grafana/templates/extra-manifests.yaml
- charts/grafana/values.yaml
Signed-off-by: Ofir Shtrull <ofirs@tikalk.com>
> [grafana] Add extra (dynamic) Manifests to chart

- charts/loki-stack/Chart.yaml
- charts/loki-stack/requirements.yaml
This is a fix for #877 because PR #878 seems to "hang".
> [loki-stack] fix for PR: Update Prometheus to work on K8S 1.22.3 #878 

- charts/loki/Chart.yaml
- charts/loki/templates/statefulset.yaml
See https://github.com/grafana/loki/issues/3005#issuecomment-770401967 for issue detail.
> [loki] Fix double rule evaluation

- charts/loki/Chart.yaml
- charts/loki/templates/ingress.yaml
- charts/loki/values.yaml
* loki: support IngressClass
* loki: bump chart version
> [loki] Support ingress class in loki

- charts/loki-distributed/Chart.yaml
- charts/loki-distributed/README.md
> [loki-distributed] update to Loki 2.4.2

- charts/promtail/Chart.yaml
- charts/promtail/README.md
> [promtail] update to Loki 2.4.2

- charts/loki-simple-scalable/Chart.yaml
- charts/loki-simple-scalable/README.md
> [loki-simple-scalable] update to Loki 2.4.2

- charts/loki-canary/Chart.yaml
- charts/loki-canary/README.md
> [loki-canary] update to Loki 2.4.2

- charts/loki/Chart.yaml
- charts/loki/values.yaml
> [loki] update to Loki 2.4.2

- charts/enterprise-logs/CHANGELOG.md
- charts/enterprise-logs/Chart.yaml
- charts/enterprise-logs/values.yaml
> [enterprise-logs] update to gel 1.3.0

- charts/grafana/Chart.yaml
- charts/grafana/README.md
- charts/grafana/templates/_pod.tpl
- charts/grafana/values.yaml
Relates to this https://github.com/grafana/helm-charts/issues/981.
Signed-off-by: Mihail Ivanov <mihail.ivanov@sky.uk>
> [grafana] Add skipReload variable

- charts/tempo/Chart.yaml
- charts/tempo/README.md
- charts/tempo/values.yaml
> [tempo] Tempo 1.3.0

- charts/grafana/Chart.yaml
- charts/grafana/templates/_helpers.tpl
- charts/grafana/templates/hpa.yaml
Reverts grafana/helm-charts#994
The version: 6.21.2 is setted
> [grafana] Revert "Add app.kubernetes.io/component label"

- charts/loki-distributed/Chart.yaml
- charts/loki-distributed/README.md
- charts/loki-distributed/templates/ingester/deployment-ingester.yaml
- charts/loki-distributed/values.yaml
This implements the issue stated in #952.
While it works, we are actually aiming for a different solution.
> [loki-distributed] added option to use replicaset for ingesters

- charts/loki-distributed/Chart.yaml
- charts/loki-distributed/README.md
- charts/loki-distributed/README.md.gotmpl
- charts/loki-distributed/templates/configmap.yaml
- charts/loki-distributed/values.yaml
@stevehipwell 
fixes: https://github.com/grafana/helm-charts/issues/978
> [loki-distributed] add loki.structuredConfig for structured config overrides

- charts/grafana/Chart.yaml
- charts/grafana/templates/servicemonitor.yaml
Introduced via https://github.com/grafana/helm-charts/pull/1026
Signed-off-by: Brian Glogower <xbglowx@gmail.com>
> [grafana] Remove extra port in grafana's service monitor

- charts/tempo-distributed/Chart.yaml
- charts/tempo-distributed/README.md
- charts/tempo-distributed/templates/prometheusrule.yaml
- charts/tempo-distributed/values.yaml
Subj, trivial change. Ported from loki-distributed.
> [tempo-distributed] add prometheusrule

- charts/loki/Chart.yaml
- charts/loki/README.md
- charts/loki/templates/statefulset.yaml
> [loki] Make /tmp R/W to fix compactor retention

- charts/tempo-distributed/Chart.yaml
- charts/tempo-distributed/README.md
- charts/tempo-distributed/templates/compactor/deployment-compactor.yaml
- charts/tempo-distributed/templates/distributor/deployment-distributor.yaml
- charts/tempo-distributed/templates/gateway/deployment-gateway.yaml
- charts/tempo-distributed/templates/ingester/statefulset-ingester.yaml
- charts/tempo-distributed/templates/memcached/statefulset-memcached.yaml
- charts/tempo-distributed/templates/querier/deployment-querier.yaml
- charts/tempo-distributed/templates/query-frontend/deployment-query-frontend.yaml
- charts/tempo-distributed/values.yaml
Add possibility to define `securityContext` for all tempo pods. Fixes issue #837.
> [tempo-distributed] Add possiblity to define securityContext

- charts/tempo/Chart.yaml
- charts/tempo/README.md
- charts/tempo/values.yaml
> [tempo] 1.3.2

- charts/grafana/Chart.yaml
- charts/grafana/values.yaml
Bump Grafana from 8.3.6 to 8.4.2, chart version from 6.22.0 to 6.23.0
Signed-off-by: Lawrence Temple <lawrence@transit.app>
> [grafana] Bump Grafana from 8.3.6 to 8.4.2

- charts/grafana/Chart.yaml
- charts/grafana/values.yaml
Signed-off-by: Zahar Pecherichny <zfrhv2010@gmail.com>
fixed documentation link + added example
> [grafana] fixes the envValueFrom in values.yaml documentation link + added example

- charts/grafana/Chart.yaml
- charts/grafana/templates/_pod.tpl
- charts/grafana/values.yaml
Hello,
I added sidecar that supports plugins.
It is almost the same like datasource sidecar excepting the reloadURL and label.
> [grafana] add sidecar that supports plugins

- charts/loki-distributed/Chart.yaml
- charts/loki-distributed/README.md
- charts/loki-distributed/templates/ruler/persistentvolumeclaim-ruler.yaml
- charts/loki-distributed/templates/ruler/statefulset-ruler.yaml
Forgot some changes, it should fix the previous PR https://github.com/grafana/helm-charts/pull/1109
> [loki-distributed] Fixing statefulset configuration for Ruler

- charts/enterprise-logs/CHANGELOG.md
- charts/enterprise-logs/Chart.lock
- charts/enterprise-logs/Chart.yaml
- charts/enterprise-logs/values.yaml
changed version of loki-distributed chart to 0.46.4 that adds OpenShift support
> [enterprise-logs] Openshift support for GEL.

- .github/workflows/lint-test.yaml
- charts/mimir-distributed/Chart.yaml
- charts/mimir-distributed/README.md
- charts/mimir-distributed/ci/test-values.yaml
- charts/mimir-distributed/values.yaml
> [mimir-distributed] Enable mimir CI tests.

- charts/mimir-distributed/Chart.yaml
- charts/mimir-distributed/README.md
- charts/mimir-distributed/templates/minio/create-bucket-job.yaml
> [mimir-distributed] Fix the naming of minio configmap and secret in the parent chart.

- charts/loki-distributed/Chart.yaml
- charts/loki-distributed/README.md
- charts/loki-distributed/templates/compactor/deployment-compactor.yaml
- charts/loki-distributed/templates/distributor/deployment-distributor.yaml
- charts/loki-distributed/templates/gateway/deployment-gateway.yaml
- charts/loki-distributed/templates/index-gateway/statefulset-index-gateway.yaml
- charts/loki-distributed/templates/ingester/deployment-ingester.yaml
- charts/loki-distributed/templates/ingester/statefulset-ingester.yaml
- charts/loki-distributed/templates/memcached-chunks/statefulset-memcached-chunks.yaml
- charts/loki-distributed/templates/memcached-frontend/statefulset-memcached-frontend.yaml
- charts/loki-distributed/templates/memcached-index-queries/statefulset-memcached-index-queries.yaml
- charts/loki-distributed/templates/memcached-index-writes/statefulset-memcached-index-writes.yaml
- charts/loki-distributed/templates/querier/deployment-querier.yaml
- charts/loki-distributed/templates/querier/statefulset-querier.yaml
- charts/loki-distributed/templates/query-frontend/deployment-query-frontend.yaml
- charts/loki-distributed/templates/ruler/deployment-ruler.yaml
- charts/loki-distributed/templates/table-manager/deployment-table-manager.yaml
- charts/loki-distributed/values.yaml
This merge request allows for additional containers to be specified using values, allowing for manually inserting sidecars.
> [loki-distributed] Add support for extraContainers

- charts/loki-simple-scalable/Chart.yaml
- charts/loki-simple-scalable/README.md
bump loki simple scalable version to fix [CI](https://github.com/grafana/helm-charts/runs/5746878892?check_suite_focus=true)
> [loki-simple-scalable] bump loki simple scalable version

- charts/grafana/Chart.yaml
- charts/grafana/templates/_pod.tpl
#1135 
Signed-off-by: Krzyszof Dziegielewski <dziegielewski.krzysztof@gmail.com>
> [grafana] Fix initContainers when initDatasources provided

- charts/loki-distributed/Chart.yaml
- charts/loki-distributed/README.md
Based on the request at https://github.com/grafana/helm-charts/pull/1131#issuecomment-1086354061 , I submitted a PR to make a new version.
> [loki-distributed] bump new version for #1131

- charts/mimir-distributed/Chart.yaml
- charts/mimir-distributed/README.md
- charts/mimir-distributed/README.md.gotmpl
> [mimir-distributed] Fix documentation link missing slash

- charts/enterprise-logs/Chart.yaml
- charts/enterprise-logs/templates/admin-api/deployment-admin-api.yaml
- charts/enterprise-logs/templates/compactor/statefulset-compactor.yaml
- charts/enterprise-logs/templates/gateway/deployment-gateway.yaml
- charts/enterprise-logs/templates/tokengen/job-tokengen.yaml
This is useful to ensure monitoring mixins work.
> [enterprise-logs] Ensure each container name matches the component name

- charts/grafana/Chart.yaml
- charts/grafana/values.yaml
> [grafana] Bump Grafana from 8.4.2 to 8.4.5, chart version from 6.25.1 to 6.26.0

- charts/mimir-distributed/Chart.yaml
- charts/mimir-distributed/README.md
- charts/mimir-distributed/templates/alertmanager/alertmanager-dep.yaml
- charts/mimir-distributed/templates/alertmanager/alertmanager-pdb.yaml
- charts/mimir-distributed/templates/alertmanager/alertmanager-servmon.yaml
- charts/mimir-distributed/templates/alertmanager/alertmanager-statefulset.yaml
- charts/mimir-distributed/templates/alertmanager/alertmanager-svc-headless.yaml
- charts/mimir-distributed/templates/alertmanager/alertmanager-svc.yaml
- charts/mimir-distributed/templates/compactor/compactor-pdb.yaml
- charts/mimir-distributed/templates/compactor/compactor-servmon.yaml
- charts/mimir-distributed/templates/compactor/compactor-statefulset.yaml
- charts/mimir-distributed/templates/compactor/compactor-svc.yaml
- charts/mimir-distributed/values.yaml
Fix missing if compactor.enabled
Add alertmanager.enabled flag for the use case of having an external alertmanager
Implements #1178
> [mimir-distributed] mimir service flags

- charts/mimir-distributed/Chart.yaml
- charts/mimir-distributed/README.md
- charts/mimir-distributed/scripts/create-servmon
- charts/mimir-distributed/templates/_helpers.tpl
- charts/mimir-distributed/templates/alertmanager/alertmanager-servmon.yaml
- charts/mimir-distributed/templates/compactor/compactor-servmon.yaml
- charts/mimir-distributed/templates/distributor/distributor-servmon.yaml
- charts/mimir-distributed/templates/ingester/ingester-servmon.yaml
- charts/mimir-distributed/templates/querier/querier-servmon.yaml
- charts/mimir-distributed/templates/query-frontend/query-frontend-servmon.yaml
- charts/mimir-distributed/templates/ruler/ruler-servmon.yaml
- charts/mimir-distributed/templates/store-gateway/store-gateway-servmon.yaml
ServiceMonitor needs to set job and cluster labels correctly for monitoring
dashboards to work.
> [mimir-distributed] Fix labels for Mimir dashboards

- charts/mimir-distributed/Chart.yaml
- charts/mimir-distributed/README.md
> [mimir-distributed] bump mimir-distributed to 0.1.6 to fix build

- charts/promtail/Chart.yaml
- charts/promtail/README.md
> [promtail] Bump version to force gh-pages republish

- charts/loki-canary/Chart.yaml
- charts/loki-canary/README.md
> [loki-canary] Bump version to force gh-pages republish

- charts/fluent-bit/Chart.yaml
- charts/fluent-bit/templates/configmap.yaml
- charts/fluent-bit/values.yaml
Add `Buffer_Chunk_size` & `Buffer_Max_size` to Tail input section setting to default values.
This might help to situations like this https://github.com/fluent/fluent-bit/issues/354
Signed-off-by: Guillermo Caracuel <gcaracuel@gmail.com>
> [fluent-bit] Add Tail buffer size

- charts/grafana/Chart.yaml
- charts/grafana/values.yaml
> [grafana] High severity security fix version bump on charts

- charts/enterprise-metrics/CHANGELOG.md
- charts/enterprise-metrics/Chart.yaml
- charts/enterprise-metrics/README.md
- charts/enterprise-metrics/values.yaml
To be merged after #1203 
Procedure followed: https://github.com/helm/charts/blob/master/PROCESSES.md
> [enterprise-metrics] Version bump and deprecation in favour of mimir-distributed.

- charts/agent-operator/Chart.yaml
- charts/agent-operator/README.md
- charts/agent-operator/values.yaml
> [agent-operator] bump to version to 0.1.8, appVersion to v0.24.0

- charts/mimir-distributed/CHANGELOG.md
- charts/mimir-distributed/Chart.yaml
- charts/mimir-distributed/README.md
- charts/mimir-distributed/values.yaml
> [mimir-distributed] Update GEM image version

- .helmdocsignore
- charts/loki-distributed/Chart.yaml
- charts/loki-distributed/README.md
- charts/loki-distributed/values.yaml
Fix missing/wrong docstring of ingressClassName in README.
> [loki-distributed] Bump helm-docs version to 1.8.1

- charts/grafana/Chart.yaml
- charts/grafana/README.md
- charts/grafana/values.yaml
Adds affinity/nodeselector/tolerations in README and in values ( empty ) for image renderer.  
The deployment already support this options.
> [grafana] Add affinity/node selector / tolerations docs for renderer

- charts/grafana/Chart.yaml
- charts/grafana/values.yaml
It was not correct set by me since the Chart uses not the appVersion as default also the values.yaml
> [grafana] fix grafana version in values.yaml

- charts/mimir-distributed/CHANGELOG.md
- charts/mimir-distributed/Chart.yaml
- charts/mimir-distributed/README.md
- charts/mimir-distributed/templates/nginx/_helpers.tpl
- charts/mimir-distributed/templates/validate.yaml
- charts/mimir-distributed/values.yaml
Activity tracker path validation.
http_listen_port and grpc_listen_port validation #1221 
Missing extraVolumeMounts #1285 
Wrong template called in nginx helper #1278
> [mimir-distributed] Additional validations and bugfixes

- charts/grafana/Chart.yaml
- charts/grafana/templates/configmap.yaml
Signed-off-by: Cristian Chiru <cristian.chiru@revomatico.com>
Sorry for this third attempt, just realised I need to create a separate branch to avoid conflicts from other merges with the signoff thing...
> [grafana] Set dashboardProvider path in dashboard init container

- charts/mimir-distributed/CHANGELOG.md
- charts/mimir-distributed/Chart.yaml
- charts/mimir-distributed/README.md
- charts/mimir-distributed/templates/gateway/gateway-ingress.yaml
- charts/mimir-distributed/values.yaml
Set defaults for gateway ingress service ports.
> [mimir-distributed] fix null port at gateway ingress

- charts/mimir-distributed/CHANGELOG.md
- charts/mimir-distributed/Chart.yaml
- charts/mimir-distributed/README.md
- charts/mimir-distributed/values.yaml
* [ENHANCEMENT] Reorder some values for consistency.
* [BUGFIX] Add missing `admin_api.env`, `gateway.env` and `overrides_exporter.env` values.
* [BUGFIX] Remove `<service>.extraPorts` from values as it has no effect.
Fixes #1301
> [mimir-distributed] small values fixes

- charts/tempo/Chart.yaml
- charts/tempo/README.md
- charts/tempo/values.yaml
> [tempo] 1.4.0

- charts/tempo-distributed/Chart.yaml
- charts/tempo-distributed/README.md
> [tempo-distributed] v1.4.0

- charts/grafana/Chart.yaml
- charts/grafana/ci/with-affinity-values.yaml
- charts/grafana/ci/with-extraconfigmapmounts-values.yaml
- charts/grafana/ci/with-persistence.yaml
- charts/grafana/templates/_pod.tpl
This is a follow-up to MR #1333 which adds tests to catch some issues with the templating introduced in that version.
> [grafana] Fix templating issues

- charts/agent-operator/Chart.yaml
- charts/agent-operator/README.md
- charts/agent-operator/values.yaml
Similar to https://github.com/grafana/helm-charts/pull/1243
cc @rfratto @rlankfo 
Related: https://github.com/grafana/agent/issues/1609
> [agent-operator] bump appVersion to v0.24.2

- charts/grafana/Chart.yaml
- charts/grafana/values.yaml
Upgrade Grafana version to 8.5.3
Signed-off-by: pbrissaud <pbrissaud.pro@gmail.com>
> [grafana] Upgrade Grafana to 8.5.3

- charts/enterprise-logs/Chart.lock
- charts/enterprise-logs/Chart.yaml
- charts/enterprise-logs/values.yaml
Update GEL version to v1.4.1 and loki-distributed chart to latest v0.48.4
This fixes some problem when deploying to AWS Marketplace.
> [enterprise-logs] Update GEL version to v1.4.1 and update loki-distributed chart

- charts/tempo/Chart.yaml
- charts/tempo/README.md
- charts/tempo/templates/configmap-tempo.yaml
- charts/tempo/values.yaml
Issue described here https://github.com/grafana/helm-charts/issues/1077
> [tempo] Fix Tempo overrides

- charts/loki/Chart.yaml
- charts/loki/README.md
- charts/loki/templates/_helpers.tpl
- charts/loki/templates/configmap-alert.yaml
- charts/loki/templates/ingress.yaml
- charts/loki/templates/networkpolicy.yaml
- charts/loki/templates/pdb.yaml
- charts/loki/templates/podsecuritypolicy.yaml
- charts/loki/templates/prometheusrule.yaml
- charts/loki/templates/role.yaml
- charts/loki/templates/rolebinding.yaml
- charts/loki/templates/secret.yaml
- charts/loki/templates/service-memberlist.yaml
- charts/loki/templates/service.yaml
- charts/loki/templates/serviceaccount.yaml
- charts/loki/templates/servicemonitor.yaml
- charts/loki/templates/statefulset.yaml
- charts/loki/values.yaml
enabled memberlist by default and added support of memberlist( kubernetes service and exposed port on the pod)
> [loki] supported memberlist

- charts/mimir-distributed/README.md
The relocation notice failed to mention where its previous content
was moved to.
> Mimir: make a link to the new README.md

- charts/grafana/Chart.yaml
- charts/grafana/templates/configmap-dashboard-provider.yaml
- charts/grafana/templates/configmap.yaml
> [grafana] fix cve-2021-25742

- charts/grafana/Chart.yaml
- charts/grafana/templates/podsecuritypolicy.yaml
> [grafana] fix psp deprecated since k8s 1.21

- charts/grafana/Chart.yaml
- charts/grafana/templates/podsecuritypolicy.yaml
> [grafana] hotfix fix psp deprecated since k8s 1.21

- charts/loki-simple-scalable/Chart.yaml
- charts/loki-simple-scalable/templates/gateway/deployment-gateway.yaml
> [loki-simple-scalable] fixes #1467

- charts/loki/Chart.yaml
- charts/loki/values.yaml
add missing field `storageClassName` in values.yaml, corresponding comment
https://github.com/grafana/helm-charts/blob/288a3503ee91ba9be0d762e5865cd1415865b23b/charts/loki/values.yaml#L149
> [loki] : add missing field in values.yaml

- charts/grafana/Chart.yaml
- charts/grafana/templates/_helpers.tpl
- charts/grafana/templates/poddisruptionbudget.yaml
- charts/grafana/templates/podsecuritypolicy.yaml
> [grafana] fix psp pdb deprecated in k8s 1.21

- .github/workflows/lint-test.yaml
> Bump helm version in lint-test, make it configurable

- charts/grafana/Chart.yaml
- charts/grafana/templates/configmap-dashboard-provider.yaml
- charts/grafana/templates/configmap.yaml
The change in #1481 is not applicable to this repository
/fixes #1542
> [grafana] Revert #1481

- charts/loki-simple-scalable/Chart.yaml
- charts/loki-simple-scalable/values.yaml
M  charts/loki-simple-scalable/Chart.yaml
M  charts/loki-simple-scalable/values.yaml
-- This message was automatically generated by 'prepare-commit-msg'
Signed-off-by: parera10 <parera10@gmail.com>
> [loki-simple-scalable] Adding alert proxy_pass for ruler

- charts/loki-simple-scalable/CHANGELOG.md
- charts/loki-simple-scalable/Chart.yaml
- charts/loki-simple-scalable/templates/read/statefulset-read.yaml
> [loki-simple-scalable] Change default volume retention policies

- charts/promtail/Chart.yaml
- charts/promtail/README.md
- charts/promtail/values.yaml
> [promtail] use tpl function for client urls

- charts/grafana/Chart.yaml
Signed-off-by: Martin Norrsken <martin.norrsken@gmail.com>
> [grafana] Bump version to 9.0.2

- charts/grafana/Chart.yaml
- charts/grafana/templates/_pod.tpl
See:
https://github.com/grafana/helm-charts/issues/1457
> [grafana] fix sidecar dashboards labelvalue

- charts/grafana/Chart.yaml
- charts/grafana/README.md
- charts/grafana/templates/_pod.tpl
- charts/grafana/values.yaml
See:
https://github.com/grafana/helm-charts/issues/1568
> [grafana] Revert sidecar dashboard labelvalue

- charts/loki-canary/Chart.yaml
- charts/loki-canary/README.md
updated loki release version to 2.6.0 and bumped version of the chart
> [loki-canary] updated loki version to 2.6.0

- charts/loki-simple-scalable/Chart.yaml
- charts/loki-simple-scalable/README.md
Signed-off-by: Susana Ferreira <susana.ferreira@grafana.com>
> [loki-simple-scalable] Release loki-simple-scalable helm-charts version 2.6.0

- charts/loki/Chart.yaml
- charts/loki/values.yaml
Signed-off-by: Susana Ferreira <susana.ferreira@grafana.com>
> [loki] Release loki helm-charts version 2.6.0

- charts/promtail/Chart.yaml
- charts/promtail/README.md
Signed-off-by: Susana Ferreira <susana.ferreira@grafana.com>
> [promtail] Release promtail helm-charts version 2.6.0

- charts/loki-distributed/Chart.yaml
- charts/loki-distributed/README.md
> [loki-distributed] updated loki release version to 2.6.0 

- .github/CODEOWNERS
- charts/tempo-distributed/Chart.yaml
- charts/tempo-distributed/README.md
- charts/tempo/Chart.yaml
Proposing new Tempo Helm Chart maintainers based on contributions to this repository and the community slack channel `#tempo`:
- Maarten De Wispelaere @BitProcessor 
- Fausto David Suarez Rosario @faustodavid
Each approval on this PR counts as a vote - PR to be merged after 3 approvals!
Signed-off-by: Annanay Agarwal <annanay.agarwal@grafana.com>
> [tempo-distributed] Add new Tempo Helm Chart maintainers

- charts/tempo-distributed/Chart.yaml
- charts/tempo-distributed/README.md
- charts/tempo-distributed/README.md.gotmpl
- charts/tempo-distributed/templates/configmap-tempo.yaml
- charts/tempo-distributed/values.yaml
Add tempo structuredconfig override
> [tempo-distributed] structuredConfig support

- charts/loki-simple-scalable/Chart.yaml
- charts/loki-simple-scalable/README.md
- charts/loki-simple-scalable/values.yaml
See:
https://github.com/grafana/helm-charts/issues/1395
> [loki-simple-scalable] fix type error in README.md

- charts/loki-simple-scalable/CHANGELOG.md
- charts/loki-simple-scalable/Chart.yaml
- charts/loki-simple-scalable/README.md
- charts/loki-simple-scalable/templates/_helpers.tpl
- charts/loki-simple-scalable/values.yaml
Fixes: #1550 
* this is better as often they will not be overriden, for example if
leveraging env vars or IRSA
> [loki-simple-scalable] Change s3 defaults to null

- charts/grafana/Chart.yaml
Update Grafana due to the latest release.
> [grafana] Upgrade Grafana to 9.0.3 and bump chart

- charts/promtail/Chart.yaml
- charts/promtail/README.md
updated promtail release version to 2.6.1 and bumped version of the chart
> [promtail] updated promtail release version to 2.6.1 and bumped version of the chart

- charts/enterprise-logs/CHANGELOG.md
- charts/enterprise-logs/Chart.yaml
- charts/enterprise-logs/values.yaml
> [enterprise-logs] updated image version to use GEL 1.5

- charts/loki-simple-scalable/Chart.yaml
- charts/loki-simple-scalable/README.md
- charts/loki-simple-scalable/values.yaml
> [loki-simple-scalable] updated image version to use GEL 1.5

- .github/workflows/update-helm-repo.yaml
For https://github.com/grafana/mimir/pull/2427
> release-workflow: add new minio chart repo dependency

- charts/grafana/Chart.yaml
- charts/grafana/README.md
- charts/grafana/templates/configmap.yaml
- charts/grafana/values.yaml
Fixes https://github.com/grafana/helm-charts/issues/1638
> [grafana] Allow suppression of the grafana configmap

- charts/loki-simple-scalable/Chart.yaml
- charts/loki-simple-scalable/README.md
- charts/loki-simple-scalable/templates/monitoring/dashboards/configmap-1.yaml
- charts/loki-simple-scalable/templates/monitoring/dashboards/configmap-2.yaml
See:
https://github.com/grafana/helm-charts/issues/1607
> [loki-simple-scalable] add annotation to dashboard

- charts/loki-distributed/Chart.yaml
- charts/loki-distributed/README.md
- charts/loki-distributed/templates/memcached-chunks/statefulset-memcached-chunks.yaml
- charts/loki-distributed/templates/memcached-frontend/statefulset-memcached-frontend.yaml
- charts/loki-distributed/templates/memcached-index-queries/statefulset-memcached-index-queries.yaml
- charts/loki-distributed/templates/memcached-index-writes/statefulset-memcached-index-writes.yaml
- charts/loki-distributed/values.yaml
Allow to set a container securityContext for memcached-exporter
> [loki-distributed] Allow to set a container securityContext for memcached-exporter

- CONTRIBUTING.md
As suggested here, my first-time contribution, I struggled how to re-generate the readme. I've added documentation to help future first-time contributors.
> document how to re-generate the chart readme

- charts/tempo/Chart.yaml
- charts/tempo/README.md
- charts/tempo/templates/statefulset.yaml
Fixes #1670 
Signed-off-by: Hagai Barel <hagaibarel@gmail.com>
> [tempo] optional query volume

- charts/enterprise-logs/CHANGELOG.md
- charts/enterprise-logs/Chart.yaml
- charts/enterprise-logs/values.yaml
> [enterprise-logs] GEL release 1.5.1

- charts/tempo/Chart.yaml
- charts/tempo/README.md
- charts/tempo/values.yaml
Fixes #1678
Signed-off-by: Hagai Barel <hagaibarel@gmail.com>
> [tempo] Add values section for querier and query-frontend

- charts/promtail/Chart.yaml
- charts/promtail/README.md
- charts/promtail/templates/service-extra.yaml
Signed-off-by: Jorik Seldeslachts <jorselutions@gmail.com>
> [promtail] Made extraPorts protocol variable in service template

- charts/tempo/Chart.yaml
- charts/tempo/README.md
- charts/tempo/templates/statefulset.yaml
Fixes #1679 
Signed-off-by: Hagai Barel <hagaibarel@gmail.com>
> [tempo] Automatically restart pods on config changes

- charts/tempo-distributed/Chart.yaml
- charts/tempo-distributed/README.md
> [tempo-distributed] v1.5.0

- charts/tempo/Chart.yaml
- charts/tempo/README.md
- charts/tempo/values.yaml
> [tempo] v1.5.0

- charts/grafana/Chart.yaml
- charts/grafana/templates/_pod.tpl
There was a  indentation typo in the **_pod.tpl** to cause this error  when adding custom env variables 
`YAML parse error on grafana/templates/deployment.yaml: error converting YAML to JSON`
Test locally to add  custom env variables for the dashboard sidecar , it should work now
Signed-off-by: hwu-talendbj <hwu@talend.com>
> [grafana] update pod.tpl to fix yaml parse error

- charts/grafana/Chart.yaml
- charts/grafana/README.md
Signed-off-by: Amir Alavi <amiralavi7@gmail.com>
> [grafana] fix backtick for appProtocol

- charts/grafana/Chart.yaml
Signed-off-by: Armin Gerten <armin@gerten.de>
> [grafana] bump appVersion to 9.1.1 and version to 6.33.1

- charts/grafana/Chart.yaml
- charts/grafana/templates/service.yaml
See:
https://github.com/grafana/helm-charts/issues/1690
> [grafana] Hopefully this should fix Issue #1690

- charts/loki/Chart.yaml
- charts/loki/templates/servicemonitor.yaml
- charts/loki/values.yaml
Added arguments to set up tls configuration for loki service monitor.
> [loki] Add tls optional arguments for loki service monitor

- charts/agent-operator/Chart.yaml
- charts/agent-operator/README.md
- charts/agent-operator/values.yaml
Signed-off-by: rbnis <5955614+rbnis@users.noreply.github.com>
> [agent-operator] bump appVersion to 0.26.1 and version to 0.2.4

- charts/grafana/Chart.yaml
- charts/grafana/templates/_pod.tpl
- charts/grafana/values.yaml
See:
https://github.com/grafana/helm-charts/issues/1749
Signed-off-by: MH <zanhsieh@gmail.com>
> [grafana] add topologySpreadConstraints

- charts/grafana/Chart.yaml
- charts/grafana/templates/_helpers.tpl
- charts/grafana/templates/podsecuritypolicy.yaml
- charts/grafana/templates/tests/test-podsecuritypolicy.yaml
> [grafana] Fix for k8s v1.25 psp deprecation

- charts/loki-simple-scalable/Chart.yaml
- charts/loki-simple-scalable/README.md
- charts/loki-simple-scalable/templates/tokengen/job-tokengen.yaml
- charts/loki-simple-scalable/values.yaml
Signed-off-by: garcia.ryan <garcia.ryan@solute.us>
For issue https://github.com/grafana/helm-charts/issues/1766
> [loki-simple-scalable] Adding image value for tokengen job container

- charts/grafana/Chart.yaml
- charts/grafana/templates/configmap.yaml
- charts/grafana/values.yaml
This would help downloading Grafana dashboards from Bitbucket private repo. 
Signed-off-by: Milos Curuvija <curuvija@live.com>
> [grafana] Use bearer token to download grafana dashboards

- .github/workflows/update-helm-repo.yaml
> Fix syntax error in release process.

- charts/grafana/Chart.yaml
- charts/grafana/templates/_pod.tpl
- charts/grafana/values.yaml
See:
https://github.com/grafana/helm-charts/issues/1785
> [grafana] add csi type extraVolumeMount

- charts/tempo-distributed/Chart.yaml
- charts/tempo-distributed/README.md
- charts/tempo-distributed/templates/_helpers.tpl
- charts/tempo-distributed/templates/compactor/poddisruptionbudget-compactor.yaml
- charts/tempo-distributed/templates/distributor/poddisruptionbudget-distributor.yaml
- charts/tempo-distributed/templates/gateway/poddisruptionbudget-gateway.yaml
- charts/tempo-distributed/templates/ingester/pdb.yaml
- charts/tempo-distributed/templates/ingester/poddisruptionbudget-ingester.yaml
- charts/tempo-distributed/templates/memcached/poddisruptionbudget-memcached.yaml
- charts/tempo-distributed/templates/metrics-generator/poddisruptionbudget-metrics-generator.yaml
- charts/tempo-distributed/templates/querier/poddisruptionbudget-querier.yaml
- charts/tempo-distributed/templates/query-frontend/poddisruptionbudget-query-frontend.yaml
- Add helper tempo.pdb.apiVersion
- Update all PodDisruptionBudgetresourcesapiVersionto usetempo.pdb.apiVersion`
Fixes issue #1782
Signed-off-by: Andy McGrath <upon-pave0d@icloud.com>
> [tempo-distributed] Add helper for PodDisruptionBudget API Version

- charts/grafana/Chart.yaml
See:
https://github.com/grafana/helm-charts/issues/1775
> [grafana] fix cve-2022-31176

- charts/grafana/Chart.yaml
- charts/grafana/templates/_pod.tpl
- charts/grafana/templates/deployment.yaml
- charts/grafana/values.yaml
just a simple change to make securityContext Settings on download-dashboard Container
> [grafana] add securityContext Settings for DownloadDashboard Container

- charts/loki-distributed/Chart.yaml
- charts/loki-distributed/README.md
- charts/loki-distributed/templates/compactor/service-compactor.yaml
- charts/loki-distributed/templates/distributor/poddisruptionbudget-distributor.yaml
- charts/loki-distributed/templates/ingester/poddisruptionbudget-ingester.yaml
- charts/loki-distributed/templates/querier/poddisruptionbudget-querier.yaml
- charts/loki-distributed/templates/query-frontend/poddisruptionbudget-query-frontent.yaml
Addressing https://github.com/grafana/helm-charts/pull/1793#issuecomment-1241866919
> [loki-distributed] fix: pdb conditional deployment 

- charts/promtail/Chart.yaml
- charts/promtail/README.md
- charts/promtail/README.md.gotmpl
Signed-off-by: Conor Evans <coevans@tcd.ie>
https://grafana.com/docs/loki/latest/clients/promtail/configuration/#clients
> [promtail] fix: use correct syntax for clients in HTTP Push API example

- charts/grafana/Chart.yaml
Signed-off-by: rasta-rocket <bruno.fernandos@yahoo.com>
Hey folks 👋 
Little contribution to use the latest release of grafana 🎉 
Thanks
> [grafana] feat: upgrade appVersion to 9.1.4

- charts/grafana/Chart.yaml
- charts/grafana/templates/_pod.tpl
- charts/grafana/values.yaml
> [grafana] PET-1760 - Synchronise grafana sidecar envvars, add IGNORE_ALREADY_PROCESSED

- charts/tempo/Chart.yaml
- charts/tempo/README.md
- charts/tempo/templates/serviceaccount.yaml
- charts/tempo/templates/statefulset.yaml
- charts/tempo/values.yaml
just a simple change to make tempo automountServiceAccountToken configurable
> [tempo] make tempo automountServiceAccountToken configurable

- charts/loki-distributed/Chart.yaml
- charts/loki-distributed/README.md
- charts/loki-distributed/templates/compactor/deployment-compactor.yaml
- charts/loki-distributed/templates/index-gateway/statefulset-index-gateway.yaml
- charts/loki-distributed/templates/ingester/deployment-ingester.yaml
- charts/loki-distributed/templates/ingester/statefulset-ingester.yaml
- charts/loki-distributed/templates/querier/deployment-querier.yaml
- charts/loki-distributed/templates/querier/statefulset-querier.yaml
- charts/loki-distributed/templates/ruler/deployment-ruler.yaml
- charts/loki-distributed/templates/ruler/statefulset-ruler.yaml
- charts/loki-distributed/values.yaml
Add some initContainers values to all persisted services, as a standardized work around volume permission issues
> [loki-distributed] Add initContainers

- charts/grafana/Chart.yaml
- charts/grafana/values.yaml
Signed-off-by: Julien Francoz <julien@les-tilleuls.coop>
> [grafana] upgrade curl

- charts/grafana/Chart.yaml
- charts/grafana/templates/configmap.yaml
- charts/grafana/values.yaml
Use the same templating pattern found in datasource provisioning for alerting. Should fix this issue: https://github.com/grafana/helm-charts/issues/1776
> [grafana] Fix grafana alert provisioning

- charts/enterprise-logs/CHANGELOG.md
- charts/enterprise-logs/Chart.yaml
- charts/enterprise-logs/values.yaml
> [enterprise-logs] bumped GEL version to 1.5.2

- charts/loki-distributed/Chart.yaml
- charts/loki-distributed/README.md
- charts/loki-distributed/templates/gateway/service-gateway.yaml
- charts/loki-distributed/values.yaml
> [loki-distributed] Introduce appProtocol field for gateway service

- charts/grafana/Chart.yaml
- charts/grafana/README.md
- charts/grafana/templates/configmap.yaml
Fix https://github.com/grafana/helm-charts/issues/313
Signed-off-by: Julien Francoz <julien-github@francoz.net>
> [grafana] allow multiple datasource per dashboard

- charts/grafana/Chart.yaml
- charts/grafana/templates/tests/test-configmap.yaml
- charts/grafana/templates/tests/test-podsecuritypolicy.yaml
- charts/grafana/templates/tests/test-role.yaml
- charts/grafana/templates/tests/test-rolebinding.yaml
- charts/grafana/templates/tests/test-serviceaccount.yaml
See:
https://github.com/grafana/helm-charts/issues/1882
> [grafana] add helm.sh/hook: test annotation to test templates

- charts/grafana/Chart.yaml
- charts/grafana/values.yaml
See:
https://github.com/grafana/helm-charts/commit/088109da5f183599739c66ca8500d829619e52d3
> [grafana] fix imagerender enabled

- charts/agent-operator/Chart.yaml
- charts/agent-operator/README.md
- charts/agent-operator/values.yaml
Signed-off-by: rbnis <5955614+rbnis@users.noreply.github.com>
> [agent-operator] bump appVersion to 0.28.0 and version to 0.2.8

- charts/loki-simple-scalable/README.md
Signed-off-by: Greg C Krause <gregckrause@gmail.com>
> Typo loki-simple-scalable in readme deprecation notice

- charts/loki-distributed/Chart.yaml
- charts/loki-distributed/README.md
- charts/loki-distributed/templates/compactor/deployment-compactor.yaml
- charts/loki-distributed/templates/ingester/deployment-ingester.yaml
- charts/loki-distributed/templates/memcached-chunks/statefulset-memcached-chunks.yaml
https://github.com/grafana/helm-charts/issues/1905
> [loki-distributed] apply loki.annotations to more controller obj

- charts/grafana/Chart.yaml
- charts/grafana/README.md
- charts/grafana/templates/pvc.yaml
- charts/grafana/values.yaml
> [grafana] feat: allow configuring custom labels for PVCs

- charts/tempo-vulture/Chart.yaml
- charts/tempo-vulture/README.md
- charts/tempo-vulture/README.md.gotmpl
Signed-off-by: ydissen <yonahdissen@gmail.com>
> [tempo-vulture] add installation guide to tempo chart

- charts/tempo/Chart.yaml
- charts/tempo/README.md
- charts/tempo/README.md.gotmpl
Signed-off-by: ydissen <yonahdissen@gmail.com>
> [tempo]  add installation guide to tempo chart

- INTERNAL.md
This prevents other private keys to leak
> Update gpg key instructions

- charts/tempo-distributed/Chart.yaml
- charts/tempo-distributed/README.md
- charts/tempo-distributed/templates/gateway/service-gateway.yaml
> [tempo-distributed] fix gateway targetPort

- charts/tempo-distributed/Chart.yaml
- charts/tempo-distributed/README.md
- charts/tempo-distributed/templates/role.yaml
- charts/tempo-distributed/templates/rolebinding.yaml
Fixes: #1935
Signed-off-by: Zach Leslie <zach.leslie@grafana.com>
> [tempo-distributed] fix context reference for rolebinding and role

- charts/tempo-distributed/Chart.yaml
- charts/tempo-distributed/README.md
- charts/tempo-distributed/templates/gateway/ingress-gateway.yaml
Signed-off-by: Zach Leslie <zach.leslie@grafana.com>
> [tempo-distributed] fix context reference in ingress-gateway

- charts/tempo-distributed/Chart.yaml
- charts/tempo-distributed/README.md
- charts/tempo-distributed/templates/gateway/ingress-gateway.yaml
Signed-off-by: Zach Leslie <zach.leslie@grafana.com>
> [tempo-distributed] move dictionary handling to avoid nil pointer

- charts/grafana/Chart.yaml
- charts/grafana/templates/serviceaccount.yaml
> [grafana] refactor hotfix issue 1975

- charts/tempo-distributed/Chart.yaml
- charts/tempo-distributed/README.md
- charts/tempo-distributed/README.md.gotmpl
The distributed chart readme pointed to the wrong chart for installation
Signed-off-by: Nicholas Blott <blottn@tcd.ie>
> [tempo-distributed] Fix install chart example

- charts/loki-stack/Chart.yaml
- charts/loki-stack/values.yaml
See:
https://github.com/grafana/helm-charts/pull/1955#issuecomment-1316654380
> [loki-stack] fix #1955

- charts/grafana/Chart.yaml
- charts/grafana/templates/ingress.yaml
See:
https://github.com/grafana/helm-charts/issues/1996
> [grafana] refactor hotfix #1996

- charts/loki-distributed/Chart.yaml
- charts/loki-distributed/README.md
- charts/loki-distributed/templates/table-manager/deployment-table-manager.yaml
Fix issue:
https://github.com/grafana/helm-charts/issues/737
> [loki-distributed] Mount /var/loki to emptyDir in tableManager

- charts/loki-distributed/Chart.yaml
- charts/loki-distributed/README.md
> [loki-distributed] Fix PR #1968 release failed

- charts/grafana/Chart.yaml
- charts/grafana/templates/_pod.tpl
- charts/grafana/templates/headless-service.yaml
- charts/grafana/values.yaml
Please accept my contribution.
I put the possibility of configuring envValueFrom for downloadDashboards container.
The same logic that exists in grafana container, only included in the initContainers of downloadDashboards
Signed-off-by: PauloFerreira25 <pauloaugustodealmeidaferreira@gmail.com>
> [grafana] Add envValueFrom in downloadDashboards

- charts/promtail/Chart.yaml
- charts/promtail/README.md
- charts/promtail/templates/secret.yaml
- charts/promtail/values.yaml
Resolves https://github.com/grafana/helm-charts/issues/699
> [promtail] Allow setting labels and annotations in secret

- charts/promtail/Chart.yaml
- charts/promtail/README.md
Updating the helm chart given the new release
> [promtail] update to promtail version 2.7.0

- charts/promtail/Chart.yaml
- charts/promtail/README.md
- charts/promtail/templates/_helpers.tpl
- charts/promtail/templates/_pod.tpl
- charts/promtail/templates/daemonset.yaml
- charts/promtail/templates/deployment.yaml
- charts/promtail/templates/networkpolicy.yaml
- charts/promtail/templates/podsecuritypolicy.yaml
- charts/promtail/templates/role.yaml
- charts/promtail/templates/rolebinding.yaml
- charts/promtail/templates/service-extra.yaml
- charts/promtail/templates/servicemonitor.yaml
Refactor following:
- Fix indention
- Reformat `templates/_helper.tpl` to close to the code similar to the one thru `helm create promtail`
No change to values.yaml, which means backward compatible.
> [promtail] Refactor

- charts/promtail/Chart.yaml
- charts/promtail/README.md
- charts/promtail/templates/prometheus-rules.yaml
- charts/promtail/values.yaml
add the functionality to deploy PrometheusRules with promtail
Signed-off-by: Toni Tauro <toni.tauro@adfinis.com>
> [promtail] Add PrometheusRules functionality

- charts/grafana/Chart.yaml
- charts/grafana/templates/tests/test-podsecuritypolicy.yaml
- charts/grafana/templates/tests/test-role.yaml
- charts/grafana/templates/tests/test-rolebinding.yaml
Refactor following:
See:
https://github.com/grafana/helm-charts/issues/2040
> [grafana] fix grafana test 2040

- charts/grafana/Chart.yaml
Signed-off-by: Roman Verenich <roman.verenich@gmail.com>
update Chart with grafana 9.3.1 by default
> [grafana] 9.3.1 by default

- charts/grafana/Chart.yaml
- charts/grafana/templates/_pod.tpl
> [grafana] Remove unneeded data block in csi volume mount spec

- charts/loki-stack/Chart.yaml
Fix PR version not get bumped:
https://github.com/grafana/helm-charts/pull/1858/files
> [loki-stack] fix version

- charts/tempo-distributed/Chart.yaml
- charts/tempo-distributed/README.md
- charts/tempo-distributed/values.yaml
> [tempo-distributed] Allow to override nginx resolver

- charts/promtail/Chart.yaml
- charts/promtail/README.md
Signed-off-by: gasmick <33287410+gasmick@users.noreply.github.com>
> [promtail] update to promtail version 2.7.1

- charts/tempo/Chart.yaml
- charts/tempo/README.md
- charts/tempo/values.yaml
Signed-off-by: ydissen <yonahdissen@gmail.com>
> [tempo] add missing resources section to values file in tempo chart

- charts/agent-operator/Chart.yaml
- charts/agent-operator/README.md
- charts/agent-operator/crds/monitoring.coreos.com_podmonitors.yaml
- charts/agent-operator/crds/monitoring.coreos.com_probes.yaml
- charts/agent-operator/crds/monitoring.coreos.com_servicemonitors.yaml
- charts/agent-operator/crds/monitoring.grafana.com_grafanaagents.yaml
- charts/agent-operator/crds/monitoring.grafana.com_integrations.yaml
- charts/agent-operator/crds/monitoring.grafana.com_logsinstances.yaml
- charts/agent-operator/crds/monitoring.grafana.com_metricsinstances.yaml
- charts/agent-operator/crds/monitoring.grafana.com_podlogs.yaml
- charts/agent-operator/values.yaml
- Use last agent's release: 0.30.2
- Update CRDs from version 0.30.2
> [agent-operator] Update app version to 0.30.2

- charts/grafana/Chart.yaml
Relate to:
https://github.com/grafana/helm-charts/pull/2137
> [grafana] fix release PR 2137

- charts/tempo/Chart.yaml
- charts/tempo/README.md
- charts/tempo/README.md.gotmpl
- charts/tempo/values.yaml
> [tempo] Tempo 2.0

- charts/loki-distributed/Chart.yaml
- charts/loki-distributed/README.md
> [loki-distributed] update to loki version to 2.7.2

- charts/loki-distributed/Chart.yaml
- charts/loki-distributed/README.md
> [loki-distributed] update loki version to 2.7.3

- charts/loki-distributed/Chart.yaml
- charts/loki-distributed/README.md
- charts/loki-distributed/values.yaml
From https://github.com/monitoring-mixins/website/blob/master/assets/loki/rules.yaml
> [loki-distributed] Add Prometheus rules example

- charts/promtail/Chart.yaml
- charts/promtail/README.md
- charts/promtail/templates/_helpers.tpl
- charts/promtail/templates/ingress.yaml
- charts/promtail/values.yaml
Hey folks 👋 ,
Little PR here to add that capability to get an ingress object linked to the deployment of Promtail
It is especially useful when we deploy a promtail agent in "Push API" mode as a kubernetes deployment object
Don't hesitate to ask me if you have any questions 
Cheers 😉
> [promtail] add ingress

- charts/promtail/Chart.yaml
- charts/promtail/README.md
[promtail] bumped loki version to 2.7.4
> [promtail] bumped loki version to 2.7.4

- charts/grafana/Chart.yaml
- charts/grafana/templates/role.yaml
- charts/grafana/values.yaml
Minor fix with psp role and change default value for pspEnable as false.
> [grafana] minor fix for psp in role

- charts/tempo-distributed/Chart.yaml
- charts/tempo-distributed/README.md
https://github.com/grafana/tempo/releases/tag/v2.0.1
> [tempo-distributed] Update AppVersion to 2.0.1

- charts/tempo/Chart.yaml
- charts/tempo/README.md
- charts/tempo/values.yaml
https://github.com/grafana/tempo/releases/tag/v2.0.1
> [tempo] Update AppVersion to 2.0.1

- charts/promtail/Chart.yaml
- charts/promtail/README.md
- charts/promtail/ci/ingress-values.yaml
- charts/promtail/ci/service-values.yaml
- charts/promtail/templates/_helpers.tpl
- charts/promtail/templates/ingress.yaml
- charts/promtail/values.yaml
I just discovered that we can now deploy an ingress and ran right into this issue that @rasta-rocket must've overseen in c0c9638.
I also created a ci values file that works just fine.
I didn't add it to any actions though.
Update:
This PR edits the ingress section to be configured per `extraPorts`.
Each `extraPort` will have its own ingress with own annotations, ingressclass, you name it.
Checks are working.
> [promtail] fix ingress deployment

- charts/loki-distributed/Chart.yaml
- charts/loki-distributed/README.md
[loki-distributed] bumped loki to v2.7.4
> [loki-distributed] bumped loki to v2.7.4

- charts/grafana/Chart.yaml
- charts/grafana/values.yaml
Hi, I think this PR is very helpful for users with poor network conditions. Thanks
> [grafana] docs: Add some usage instructions about plugins

- charts/tempo-distributed/Chart.yaml
- charts/tempo-distributed/README.md
- charts/tempo-distributed/values.yaml
Hello 👋 
This MR allow to manage reporting for tempo-distributed (the same way tempo chart handle it)
> [tempo-distributed] Allow to manage reporting to grafana.com

- charts/tempo-distributed/Chart.yaml
- charts/tempo-distributed/README.md
- charts/tempo-distributed/values.yaml
**[tempo-distributed]**
- added more structured configs to the tempo distributed chart
- conditional config of memcached
> [tempo-distributed] added more structured configs to the tempo distributed chart

- charts/tempo-distributed/Chart.yaml
- charts/tempo-distributed/README.md
- charts/tempo-distributed/values.yaml
Addresses https://github.com/grafana/helm-charts/issues/2286
> [tempo-distributed] Do not mandate use of both metrics_generator_processors

- charts/tempo/Chart.yaml
- charts/tempo/README.md
- charts/tempo/values.yaml
Minor fix for:
https://github.com/grafana/helm-charts/issues/2302
> [tempo] fix storage trace comment

- charts/tempo-vulture/Chart.yaml
- charts/tempo-vulture/README.md
- charts/tempo-vulture/templates/deployment.yaml
> [tempo-vulture] add priorityClassName

- charts/agent-operator/Chart.yaml
- charts/agent-operator/README.md
- charts/agent-operator/templates/operator-deployment.yaml
> [agent-operator] add priorityClassName to operator's pods

- charts/grafana/Chart.yaml
- charts/grafana/README.md
resolves #2316 
fixed RBAC configurations in README to match the values.yaml
> [grafana] fixed RBAC configurations to match the values.yaml

- charts/rollout-operator/Chart.yaml
- charts/rollout-operator/README.md
- charts/rollout-operator/templates/deployment.yaml
- charts/rollout-operator/values.yaml
> [rollout-operator] add priorityClassName to deployment

- charts/tempo-vulture/Chart.yaml
- charts/tempo-vulture/README.md
- charts/tempo-vulture/templates/deployment.yaml
- charts/tempo-vulture/values.yaml
> [tempo-vulture] add podLabels to vulture's deployment

- charts/grafana/Chart.yaml
- charts/grafana/templates/clusterrole.yaml
If you enable just an alerting sidecar, it won't work as there are no RBAC rules for it.
> [grafana] RBAC rules for alerting sidecar

- charts/rollout-operator/Chart.yaml
- charts/rollout-operator/README.md
- charts/rollout-operator/templates/deployment.yaml
- charts/rollout-operator/values.yaml
Closes: https://github.com/grafana/helm-charts/issues/2311
> [rollout-operator] add podLabels to deployment

- charts/grafana/Chart.yaml
- charts/grafana/values.yaml
The trivy scanner requested these hardenings and explicit capabilities usage.
> [grafana] Add additional securityContext defaults

- charts/promtail/Chart.yaml
- charts/promtail/README.md
- charts/promtail/values.yaml
See:
https://github.com/grafana/helm-charts/issues/2336
> [promtail] feat: add traceconfig support (#2336)

- charts/tempo-distributed/Chart.yaml
- charts/tempo-distributed/README.md
- charts/tempo-distributed/templates/query-frontend/deployment-query-frontend.yaml
- charts/tempo-distributed/templates/query-frontend/ingress-query-frontend.yaml
- charts/tempo-distributed/templates/query-frontend/service-query-frontend-discovery.yaml
- charts/tempo-distributed/templates/query-frontend/service-query-frontend.yaml
- charts/tempo-distributed/values.yaml
Signed-off-by: ydissen <yonahdissen@gmail.com>
> [tempo-distributed] add ingress for jaeger ui in tempo distributed chart

- charts/tempo/Chart.yaml
- charts/tempo/README.md
- charts/tempo/README.md.gotmpl
Upgrades the helm chart to 2.1.
> [tempo] Release 2.1.1

- charts/tempo-distributed/Chart.yaml
- charts/tempo-distributed/README.md
- charts/tempo-distributed/README.md.gotmpl
- charts/tempo-distributed/values.yaml
Upgrades the helm chart to 2.1.
> [tempo-distributed] Release 2.1.1

- charts/tempo/Chart.yaml
- charts/tempo/README.md
- charts/tempo/templates/statefulset.yaml
> [tempo] Add http legacy port in tempo stateful set

- charts/tempo-distributed/Chart.yaml
- charts/tempo-distributed/README.md
- charts/tempo-distributed/templates/_helpers.tpl
- charts/tempo-distributed/templates/query-frontend/ingress-query-frontend.yaml
Signed-off-by: Chris Duong <chrisduong83@gmail.com>
> [tempo-distributed] fix-ingress-query-frontend-typo

- charts/grafana/Chart.yaml
- charts/grafana/README.md
fix README typo
`pdos` -> `pods`
> [grafana] fix typo pdos -> pods

- charts/agent-operator/Chart.yaml
- charts/agent-operator/README.md
- charts/agent-operator/crds/monitoring.grafana.com_grafanaagents.yaml
- charts/agent-operator/crds/monitoring.grafana.com_integrations.yaml
- charts/agent-operator/crds/monitoring.grafana.com_logsinstances.yaml
- charts/agent-operator/values.yaml
This PR updates the agent operator and its CRDs to the latest upstream version (v0.34.1).
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1204862492310341
> [agent-operator] update helm chart for new agent version v0.34.1

- charts/tempo-distributed/Chart.yaml
- charts/tempo-distributed/README.md
- charts/tempo-distributed/README.md.gotmpl
- charts/tempo-distributed/templates/_helpers.tpl
- charts/tempo-distributed/templates/compactor/deployment-compactor.yaml
- charts/tempo-distributed/templates/configmap-runtime.yaml
- charts/tempo-distributed/templates/configmap-tempo.yaml
- charts/tempo-distributed/templates/distributor/deployment-distributor.yaml
- charts/tempo-distributed/templates/ingester/statefulset-ingester.yaml
- charts/tempo-distributed/templates/metrics-generator/deployment-metrics-generator.yaml
- charts/tempo-distributed/templates/querier/deployment-querier.yaml
- charts/tempo-distributed/templates/query-frontend/deployment-query-frontend.yaml
- charts/tempo-distributed/templates/tokengen/tokengen-job.yaml
- charts/tempo-distributed/values.yaml
Fixes #2461
* Moves runtime/overrides configuration to separate configmap
> [tempo-distributed] Move overrides configuration to separate runtime configmap

- charts/promtail/Chart.yaml
- charts/promtail/README.md
- charts/promtail/templates/hpa.yaml
- charts/promtail/values.yaml
This PR enables to specify HPA scaling behavior policies: https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/#configurable-scaling-behavior
> [promtail] HPA scaling behavior support

- charts/promtail/Chart.yaml
- charts/promtail/README.md
- charts/promtail/values.yaml
That looks like a copy-paste issue
> [promtail] fix instance label

- charts/tempo-distributed/Chart.yaml
- charts/tempo-distributed/README.md
- charts/tempo-distributed/templates/enterprise-federation-frontend/service-federation-frontend.yaml
Create service-federation-frontend service only if enabled
> [tempo-distributed] create service-federation-frontend service only if enabled

- charts/tempo-distributed/Chart.yaml
- charts/tempo-distributed/README.md
- charts/tempo-distributed/values.yaml
This PR adds the full set of memberlist configuration options to the default values.yaml, which allows for user overrides
Fixes https://github.com/grafana/helm-charts/issues/2317
> [tempo-distributed] feat: add memberlist values

- charts/grafana/Chart.yaml
- charts/grafana/values.yaml
> [grafana] Adding missing mountPath for csi extraVolumeMount

- charts/loki-distributed/Chart.yaml
- charts/loki-distributed/README.md
- charts/loki-distributed/templates/compactor/deployment-compactor.yaml
- charts/loki-distributed/templates/distributor/deployment-distributor.yaml
- charts/loki-distributed/templates/gateway/deployment-gateway.yaml
- charts/loki-distributed/templates/index-gateway/statefulset-index-gateway.yaml
- charts/loki-distributed/templates/ingester/deployment-ingester.yaml
- charts/loki-distributed/templates/ingester/statefulset-ingester.yaml
- charts/loki-distributed/templates/memcached-chunks/statefulset-memcached-chunks.yaml
- charts/loki-distributed/templates/memcached-frontend/statefulset-memcached-frontend.yaml
- charts/loki-distributed/templates/memcached-index-queries/statefulset-memcached-index-queries.yaml
- charts/loki-distributed/templates/memcached-index-writes/statefulset-memcached-index-writes.yaml
- charts/loki-distributed/templates/querier/deployment-querier.yaml
- charts/loki-distributed/templates/querier/statefulset-querier.yaml
- charts/loki-distributed/templates/query-frontend/deployment-query-frontend.yaml
- charts/loki-distributed/templates/query-scheduler/deployment-query-scheduler.yaml
- charts/loki-distributed/templates/ruler/deployment-ruler.yaml
- charts/loki-distributed/templates/ruler/statefulset-ruler.yaml
- charts/loki-distributed/templates/table-manager/deployment-table-manager.yaml
- charts/loki-distributed/values.yaml
I need to set hostAliases in my environment for loki-distributed
> [loki-distributed] Add host aliases

- charts/loki-distributed/Chart.yaml
- charts/loki-distributed/README.md
- charts/loki-distributed/templates/compactor/deployment-compactor.yaml
- charts/loki-distributed/templates/compactor/service-compactor.yaml
- charts/loki-distributed/values.yaml
- Adds grpc port to compactor's `Service` and `Deployment`
Closes https://github.com/grafana/loki/issues/9539
> [loki-distributed] Add grpc port to compactor service

- charts/tempo-distributed/Chart.yaml
- charts/tempo-distributed/README.md
- charts/tempo-distributed/values.yaml
See https://github.com/grafana/tempo/issues/2699 for details.
> [tempo-distributed] use DNS lookup for memberlist default

- charts/tempo/Chart.yaml
- charts/tempo/README.md
Upgrade the tempo chart to 2.2
> [tempo] Upgraded to 2.2

- charts/agent-operator/Chart.yaml
- charts/agent-operator/README.md
- charts/agent-operator/templates/operator-deployment.yaml
- charts/agent-operator/values.yaml
I need to set hostAliases in my environment for loki-distributed. 
> [agent-operator] Add host aliases

- charts/promtail/Chart.yaml
- charts/promtail/README.md
- charts/promtail/templates/_pod.tpl
- charts/promtail/values.yaml
> [promtail] Add host aliases

- charts/rollout-operator/Chart.yaml
- charts/rollout-operator/README.md
- charts/rollout-operator/templates/deployment.yaml
- charts/rollout-operator/values.yaml
> [rollout-operator] Add host aliases

- charts/promtail/Chart.yaml
- charts/promtail/README.md
- charts/promtail/templates/verticalpodautoscaler.yaml
- charts/promtail/values.yaml
Adds support for Vertical Pod Autoscaler for DaemonSet kind.
> [promtail] feat: add vpa support

- charts/fluent-bit/Chart.yaml
- charts/fluent-bit/templates/daemonset.yaml
- charts/fluent-bit/values.yaml
> [fluent-bit] Add host aliases

- charts/tempo-distributed/Chart.yaml
- charts/tempo-distributed/README.md
- charts/tempo-distributed/templates/querier/deployment-querier.yaml
Querier is missing the readiness probe which causes the downtime of query path each time the deployment is rolled out.
> [tempo-distributed] Querier readiness probe

- charts/loki/README.md
I had a user who was confused as to which of the Loki charts they should be using. Adding a sentence to each Loki Helm Chart to help distinguish which chart is recommended.
Breaking up https://github.com/grafana/helm-charts/pull/2519 into separate PRs.
> [loki] Update README

- charts/promtail/Chart.yaml
- charts/promtail/README.md
- charts/promtail/values.yaml
Implements the suggestion by #2412 which allows us to work around the `toYaml` problems described under #2428
> [promtail] Render pipelineStages with tpl function

- charts/grafana/Chart.yaml
- charts/grafana/README.md
Removes the double line break which breaks the Markdown table
> [grafana] Remove table breaking line break

- charts/tempo/Chart.yaml
- charts/tempo/README.md
> [tempo] Upgrade tempo to 2.2.1

- charts/tempo-distributed/Chart.yaml
- charts/tempo-distributed/README.md
Upgrade tempo-distributed to 2.2.1
> [tempo-distributed] Upgrade tempo-distributed to 2.2.1

- charts/grafana/Chart.yaml
- charts/grafana/README.md
- charts/grafana/templates/_helpers.tpl
- charts/grafana/values.yaml
Issue: https://github.com/grafana/helm-charts/issues/2571
> [grafana] Add support for PDB apiVersion to be specified

- .github/workflows/lint-test.yaml
trying to get a newer version of kubernetes.
> Update kind action version

- charts/tempo/Chart.yaml
- charts/tempo/README.md
- charts/tempo/templates/statefulset.yaml
tempo support image pullSecrets
> [tempo] Support imagePullSecrets

- charts/agent-operator/Chart.yaml
- charts/agent-operator/README.md
- charts/agent-operator/values.yaml
Following instructions: https://github.com/grafana/agent/blob/main/docs/developer/release/8-update-helm-charts.md
> [agent-operator] Udpate agent version to 0.36.0

- charts/grafana/Chart.yaml
Lot's of little fixes: https://github.com/grafana/grafana/releases/tag/v10.1.1
> [grafana] bump grafana version to 10.1.1

- charts/tempo-vulture/Chart.yaml
- charts/tempo-vulture/README.md
ChangesS: https://github.com/grafana/tempo/compare/v2.1.1...v2.2.2
> [tempo-vulture] bump tempo version to 2.2.2

- charts/enterprise-logs-simple/Chart.yaml
- charts/enterprise-logs-simple/templates/tokengen/job-tokengen.yaml
- charts/enterprise-logs-simple/values.yaml
- ct.yaml
> [enterprise-logs-simple] Add host aliases

- charts/grafana/Chart.yaml
- charts/grafana/templates/role.yaml
- charts/grafana/templates/rolebinding.yaml
See:
https://github.com/grafana/helm-charts/issues/2625
> [grafana] Deprecate rbac.authorization.k8s.io/v1beta1

- charts/grafana/Chart.yaml
- charts/grafana/values.yaml
Fix:
https://github.com/grafana/helm-charts/issues/2623
See:
https://github.com/kiwigrid/k8s-sidecar/issues/301
> [grafana] Fix Security vulnerability found in scan 2623

- charts/tempo-distributed/Chart.yaml
- charts/tempo-distributed/README.md
- charts/tempo-distributed/templates/_helpers.tpl
See:
https://github.com/grafana/helm-charts/issues/2564
> [tempo-distributed] fix pdb api policy/v1beta1 policy/v1 detection

- charts/loki-distributed/Chart.yaml
- charts/loki-distributed/README.md
- charts/loki-distributed/templates/config-secret.yaml
I forgot to remove that label prior to submitting the feature-PR.
> [loki-distributed] remove pointless label

- charts/loki-distributed/Chart.yaml
- charts/loki-distributed/README.md
- charts/loki-distributed/templates/ingester/statefulset-ingester.yaml
- charts/loki-distributed/values.yaml
I followed a similar implementation from [loki-simple-scalable] [PR-1488](https://github.com/grafana/helm-charts/pull/1488) for this.
Signed-off-by: Ivan Farre  [ivan@bluelabs.eu](mailto:ivan@bluelabs.eu)
> [loki-distributed] enable StatefulSetAutoDeletePVC feature for ingester

- charts/tempo-distributed/Chart.yaml
- charts/tempo-distributed/README.md
- charts/tempo-distributed/templates/_helpers.tpl
> [tempo-distributed] Propagate settings for tempo-query to container

- charts/grafana/Chart.yaml
- charts/grafana/templates/clusterrole.yaml
- charts/grafana/templates/clusterrolebinding.yaml
- charts/grafana/values.yaml
Signed-off-by: Gadi Sneh <gadisn@gmail.com>
Fixes issue #2690
> [grafana] fix: allow using existing clusterrole

- charts/tempo-vulture/Chart.yaml
- charts/tempo-vulture/README.md
bumping the tempo version. Bug fix https://github.com/grafana/tempo/releases/tag/v2.2.3
> [tempo-vulture] bump tempo version to 2.2.3

- charts/grafana/Chart.yaml
- charts/grafana/README.md
- charts/grafana/templates/_pod.tpl
- charts/grafana/templates/image-renderer-deployment.yaml
- charts/grafana/templates/tests/test.yaml
- charts/grafana/values.yaml
This PR allows overriding of the grafana registry at a global level
> [grafana] add global image registry support

- charts/loki-distributed/Chart.yaml
- charts/loki-distributed/README.md
- charts/loki-distributed/values.yaml
Enclosed the date within double quotes as asked in the issue #2463
> [loki-distributed] Corrected date format

- charts/tempo-distributed/Chart.yaml
- charts/tempo-distributed/README.md
- charts/tempo-distributed/values.yaml
#2704 forget add storage.trace.pool.max_workers & storage.trace.pool.queue_depth settings in tempo config
> [tempo-distributed] fix for tempo config setting missing

- charts/grafana/Chart.yaml
- charts/grafana/templates/_pod.tpl
- charts/grafana/values.yaml
See:
https://github.com/grafana/helm-charts/issues/2754
https://github.com/grafana/helm-charts/pull/2753
> [grafana] revert 2748 and CVE fix

- charts/grafana/Chart.yaml
https://github.com/grafana/helm-charts/pull/2737
https://github.com/grafana/helm-charts/pull/2766
> [grafana] Update Grafana to v10.2.2

- charts/grafana/Chart.yaml
- charts/grafana/templates/_pod.tpl
> [grafana] Fix config secret typo

- .github/workflows/release.yaml
This one is failing as well now.
> Remove old minio from release workflow

- charts/loki-stack/Chart.yaml
- charts/loki-stack/requirements.yaml
> [loki-stack] Updated Prometheus chart version

- charts/agent-operator/Chart.yaml
- charts/agent-operator/README.md
- charts/agent-operator/README.md.gotmpl
Update links to CRDs to the new folder.
Part of grafana/agent#6077.
> [agent-operator] update links to CRDs

- charts/grafana/Chart.yaml
Closes https://github.com/grafana/helm-charts/issues/2878
> [grafana] app version to 10.2.3

- charts/loki-stack/Chart.yaml
> [loki-stack] Bumped loki stack version

- charts/loki-distributed/Chart.yaml
- charts/loki-distributed/README.md
- charts/loki-distributed/templates/config-secret.yaml
- charts/loki-distributed/values.yaml
Fixes https://github.com/grafana/helm-charts/issues/2870
> [loki-distributed] Allow setting labels and annotations in config-secret.yaml

- charts/tempo-distributed/Chart.yaml
- charts/tempo-distributed/README.md
- charts/tempo-distributed/values.yaml
> [tempo-distributed] update memcached image to 1.6.23

- charts/agent-operator/Chart.yaml
- charts/agent-operator/README.md
- charts/agent-operator/values.yaml
This patch includes fixes for security issues.
> [agent-operator] v0.39.1

- charts/loki-stack/Chart.yaml
> [loki-stack] Bumped version

- charts/tempo-distributed/Chart.yaml
- charts/tempo-distributed/README.md
- charts/tempo-distributed/ci/parquet-dedicated-columns.yaml
- charts/tempo-distributed/values.yaml
Fixes the dedicated_columns value introduced at #2907, that was not properly rendered
> [tempo-distributed] Fix rendering for parquet dedicated columns value

- charts/grafana/Chart.yaml
grafana appversion update to 10.3.1
> [grafana] app version to 10.3.1

- charts/tempo-distributed/Chart.yaml
- charts/tempo-distributed/README.md
- charts/tempo-distributed/values.yaml
add max_outstanding_per_tenant config in query frontend as per https://grafana.com/docs/tempo/latest/configuration/#query-frontend
> [tempo-distributed] add max_outstanding_per_tenant config in query frontend

- charts/grafana/Chart.yaml
- charts/grafana/templates/_pod.tpl
- charts/grafana/values.yaml
fixes https://github.com/grafana/helm-charts/issues/2986
fixes https://github.com/grafana/helm-charts/pull/2987
> [grafana] Add value for pod.spec.automountServiceAccountToken

- charts/grafana/Chart.yaml
- charts/grafana/templates/pvc.yaml
This fix upgrade problem where helm try to override immutable field
> [grafana] fix: lookup volumename on pvc

- charts/tempo-distributed/Chart.yaml
- charts/tempo-distributed/README.md
- charts/tempo-distributed/README.md.gotmpl
Removes example bucket from a comment.
> [tempo-distributed] remove example name

- charts/grafana/Chart.yaml
As 10.4.3 has been released some time ago https://github.com/grafana/grafana/releases/tag/v10.4.3
> [grafana] Update app version to v10.4.3

- charts/agent-operator/Chart.yaml
- charts/agent-operator/README.md
- charts/agent-operator/templates/operator-deployment.yaml
> [agent-operator] Add missing namespace in deployment template.

- charts/rollout-operator/Chart.yaml
- charts/rollout-operator/README.md
Update helm chart for rollout-operator.
> [rollout-operator] update Helm chart with version v0.17.0

- charts/promtail/Chart.yaml
- charts/promtail/README.md
- charts/promtail/templates/service-metrics.yaml
> [promtail] Update service template to fix broken promtail.

- charts/grafana/Chart.yaml
Update Grafana version.
From 11.0.0 to 11.1.0.
> [grafana] Update Grafana to 11.1.0

- .github/CODEOWNERS
- charts/tempo/Chart.yaml
- charts/tempo/README.md
This PR Follows my recent PR https://github.com/grafana/helm-charts/pull/3195#issue-2379008044 where I wanted to help in maintaining the tempo-distributed, tempo and grafana charts, Since I am already a maintainer of tempo-distributed now, this PR is intended for tempo, and will be opening a same for grafana in the coming days.
> [tempo] Add Sheikh-Abubaker as Maintainer

- charts/loki-distributed/Chart.yaml
- charts/loki-distributed/README.md
Fixes multiples security issues.
> [loki-distributed] Update Loki to v2.9.8

- charts/promtail/Chart.yaml
- charts/promtail/README.md
- charts/promtail/templates/service-extra.yaml
- charts/promtail/values.yaml
> [promtail] service-extra: custom labels not working

- charts/grafana/Chart.yaml
- charts/grafana/README.md
- charts/grafana/values.yaml
> [grafana] chore: update k8s-sidecar to 1.27.4

- charts/agent-operator/Chart.yaml
- charts/agent-operator/README.md
- charts/agent-operator/values.yaml
This PR also fixes a broken link to the Agent repo.
> [agent-operator] Update chart to Agent 0.42.0

- charts/loki-distributed/Chart.yaml
- charts/loki-distributed/README.md
- charts/loki-distributed/values.yaml
Split from https://github.com/grafana/helm-charts/pull/2791
@Whyeasy @unguiculus Anything else needed changing here?
> [loki-distributed] DOCS fix typo ingester

- charts/grafana/Chart.yaml
This PR updates Grafana to version 11.1.4
> [grafana] Update Grafana version to 11.1.4

- charts/grafana/Chart.yaml
- charts/grafana/README.md
Removed extra hyphen before `extraSecretMounts:` in code examples to match the syntax in the default values.yaml
> [grafana] Update README.md

- charts/grafana/Chart.yaml
This PR updates Grafana to version 11.1.5
> [grafana] Update Grafana version to 11.1.5

- charts/grafana/Chart.yaml
Update application version to 11.2.0
> [grafana] Update to 11.2.0

- charts/loki-distributed/Chart.yaml
- charts/loki-distributed/README.md
- Fixes multiple CVE ([#13835](https://github.com/grafana/loki/pull/13835))
> [loki-distributed] Update Loki to version 2.9.10

- charts/grafana/Chart.yaml
- charts/grafana/README.md
- charts/grafana/values.yaml
- bump k8s-sidecar to 1.28.0
resolves #3340
> [grafana] chore: bump k8s-sidecar to 1.28.0

- charts/grafana/Chart.yaml
- charts/grafana/templates/deployment.yaml
https://github.com/grafana/helm-charts/issues/3337
> [grafana] Replicas could be 0 #3337 

- charts/grafana/Chart.yaml
> [grafana] use release with security fix for CVE-2024-9264

- charts/grafana/Chart.yaml
- charts/grafana/templates/_pod.tpl
- charts/grafana/values.yaml
> [grafana] add extraMounts to plugins sidecar

- charts/grafana/Chart.yaml
bumps appVersion for Grafana to v11.3.0
> [grafana] Bump Grafana appVersion to v11.3.0

- charts/tempo/Chart.yaml
- charts/tempo/README.md
- charts/tempo/templates/_helpers.tpl
- charts/tempo/values.yaml
Every object created by the chart can have custom labels.
Fixes https://github.com/grafana/helm-charts/issues/3319
I edited Tempo Charts using the same logic used for https://github.com/grafana/mimir/issues/9067
I didn't edit dependency charts; I'm waiting for a feedback on how to proceed https://github.com/grafana/mimir/issues/9067#issuecomment-2439073840
> [tempo] Add commonLabels (#3319) 

- charts/grafana/Chart.yaml
- charts/grafana/templates/_helpers.tpl
- charts/grafana/templates/hpa.yaml
- charts/grafana/templates/image-renderer-hpa.yaml
xref: https://github.com/grafana/helm-charts/issues/3394
and https://github.com/grafana/helm-charts/pull/3389
> [grafana] `managed-by` should not be templated

- charts/tempo-vulture/Chart.yaml
- charts/tempo-vulture/README.md
- charts/tempo-vulture/templates/_helpers.tpl
- charts/tempo-vulture/values.yaml
Every object created by the chart can have custom labels.
Fixes https://github.com/grafana/helm-charts/issues/3319
I edited 3 Tempo Vulture Charts using the same logic used for https://github.com/grafana/mimir/issues/9067
I didn't edit dependency charts; I'm waiting for a feedback on how to proceed https://github.com/grafana/mimir/issues/9067#issuecomment-2439073840
> [tempo-vulture] Add commonLabels (#3319)

- charts/tempo-vulture/Chart.yaml
- charts/tempo-vulture/README.md
> [tempo-vulture] Update tempo-vulture to 2.6.1

- charts/grafana/Chart.yaml
This PR updates Grafana to version 11.3.1
> [grafana] Update Grafana version to 11.3.1

- charts/grafana/Chart.yaml
- charts/grafana/templates/deployment.yaml
- charts/grafana/templates/statefulset.yaml
Updated labels on pods to include same labels that exist on statefulset/deployment to improve traceability throughout the application.  Updated labels include selectorLabels which were previously being used.
> [grafana] Updated pod labels to include all labels

- charts/tempo-distributed/Chart.yaml
- charts/tempo-distributed/README.md
- charts/tempo-distributed/templates/ingester/_helpers-ingester.tpl
fix: https://github.com/grafana/helm-charts/issues/3434
[helm-playground validation](https://helm-playground.com/#t=LQhQG92ACATBTAZgSwHb2gIgC7wLYAOA9gHRoDm8AzrgE4CSeAhpQAoCuANpwMrwDGteNiqZowAL4SIUaABJYyftmgAuALxwlKnPmJiSANSad21ErkKlkzSln5Er6VNgPHT5itTplbGTOScRABGJm4mZlQkgSEmviwYktKQMGj8pghYlsTxbFy8AkIiYgra4lIyMPCosNAVKXBIaP5eNPC0JABeROgAggDuTEIASvAEnEpM2Mg9ALJMBGJJlfLd6FTzBGqaABSKygCU5cmyCkhMXNgAWj0YGtB7ZZhMiCioyNgAngbKAB5GEU8qEobQ6LzeH0%2BWFQRAQfE4AmwRFoP2w-3ckTIwO87RIMLh8ARymRWCE40momgJD%2BAI8UVaPjJE34TCoWBoyISAGFOKzKdS0bTMQzcRzaNzeVQqEdlg1kIgqTSMUCQT41vABkN4KNySzpj0SNUmMEEbVZadUOw8MF2gB5RA3dbbaAI1CKwXK%2BnY0FdW6akZjZlTGaoX1O82pBWcFRyS3Wu0O25sgDMxxWiCYyE4WAA6gALarQdXAJiDITrNnINlGk3wWAAGmgnyI7GgeHYNGgeaYADcMFMXfBWSpU%2Bq2Qg3nWSEt6rJqmbZzA5EIAI6RXCwHVBtn3AXowFe1W4pkUtMNZeByasdqOu6aRQ9h5MWC …
> [tempo-distributed] fix: multiline template for ingester.zoneAwareReplicationMap helper

- charts/tempo-distributed/Chart.yaml
- charts/tempo-distributed/README.md
- charts/tempo-distributed/README.md.gotmpl
Hi,
Not all components were mentioned in the chart.
Cheers
> [tempo-distributed] Added missing components

- charts/grafana/Chart.yaml
- charts/grafana/values.yaml
See https://github.com/grafana/grafana-image-renderer/issues/565
> [grafana] Fix "Error: Failed to launch the browser process!\nchrome_crashpad_handler: --database is required" with "image-renderer"

- charts/tempo-distributed/Chart.yaml
- charts/tempo-distributed/README.md
- charts/tempo-distributed/values.yaml
Fixed a few issue within the comments
> [tempo-distributed] Fixed comments

- charts/tempo/Chart.yaml
- charts/tempo/README.md
- charts/tempo/README.md.gotmpl
Updates to the recently released Tempo 2.7 images.
> [tempo] Update to Tempo 2.7

- charts/grafana/Chart.yaml
- charts/grafana/README.md
- charts/grafana/templates/service.yaml
- charts/grafana/values.yaml
> [grafana] add session affinity config

- charts/grafana/Chart.yaml
An intermediate update for new fix version of Grafana 11.4 (before going straight to 11.5.0)
> [grafana] Update to version 11.4.1

- charts/tempo/Chart.yaml
- charts/tempo/README.md
> [tempo] bump tempo version

- charts/tempo-distributed/Chart.yaml
- charts/tempo-distributed/README.md
> [tempo-distributed] bump tempo version to 2.7.1

- charts/tempo-distributed/Chart.lock
- charts/tempo-distributed/Chart.yaml
- charts/tempo-distributed/README.md
> [tempo-distributed] bump rollout operator

- charts/grafana/Chart.yaml
This PR updates Grafana to version 11.6.0
> [grafana] Update Grafana version to 11.6.0

- charts/rollout-operator/Chart.yaml
- charts/rollout-operator/README.md
- charts/rollout-operator/templates/deployment.yaml
- charts/rollout-operator/templates/role.yaml
- charts/rollout-operator/templates/rolebinding.yaml
- charts/rollout-operator/templates/service.yaml
- charts/rollout-operator/templates/serviceaccount.yaml
- charts/rollout-operator/templates/servicemonitor.yaml
Addresses https://github.com/grafana/helm-charts/issues/3632
> [rollout-operator] Add namespace to metadata for components

- charts/rollout-operator/Chart.yaml
- charts/rollout-operator/README.md
Update rollout-operator Helm chart to v0.26.0.
> [rollout-operator] update image to v0.26.0

- charts/tempo-distributed/Chart.yaml
- charts/tempo-distributed/README.md
- charts/tempo-distributed/templates/distributor/deployment-distributor.yaml
- charts/tempo-distributed/values.yaml
[tempo-distributed] Add strategy to distributor deployment
Resolve  the #3458 issue.
> [tempo-distributed] Resolve issue #3458. 

- charts/tempo-distributed/Chart.yaml
- charts/tempo-distributed/README.md
- charts/tempo-distributed/values.yaml
These additional configs are important for us to tweak polling to reduce number of ListObjects calls.
> [tempo-distributed] add configs for storage search and blocklist

- charts/cloudcost-exporter/Chart.yaml
- charts/cloudcost-exporter/README.md
- charts/cloudcost-exporter/templates/deployment.yaml
- charts/cloudcost-exporter/templates/service.yaml
- charts/cloudcost-exporter/values.yaml
* Container port name is not the same as the Service's external port. Update values to reflect this.
> [cloudcost-exporter] Fix portName

- charts/cloudcost-exporter/Chart.yaml
- charts/cloudcost-exporter/README.md
> [cloudcost-exporter] Release v1.0.3

- .github/workflows/check-codeowners.yaml
- .github/workflows/ci.yml
- .github/workflows/lint-test.yaml
- .github/workflows/linter.yml
- .github/workflows/release.yaml
- .github/workflows/sync-readme.yaml
- .github/workflows/update-helm-repo.yaml
- .github/workflows/validate-pr.yaml
> Github actions: harden workflows

- charts/tempo-distributed/Chart.yaml
- charts/tempo-distributed/README.md
- charts/tempo-distributed/templates/query-frontend/deployment-query-frontend.yaml
This fixes the error described in [3527](https://github.com/grafana/helm-charts/issues/3527). 
Solution is basically the same as [here](https://github.com/grafana/helm-charts/pull/3503/files)
> [tempo-distributed] - fix tempo-frontend args

- .github/workflows/update-helm-repo.yaml
Related to [this conversation](https://raintank-corp.slack.com/archives/C08Q3NB2VL3/p1746139023450059?thread_ts=1746043218.511839&cid=C08Q3NB2VL3) on Slack
> ci: fix github actions shared workflow ref tag

- charts/promtail/Chart.yaml
- charts/promtail/README.md
> [promtail] update appVersion to 3.5.1

- charts/grafana/Chart.yaml
Please update Grafana's appVersion to `12.0.1`
> [grafana] Update Grafana to 12.0.1

- charts/tempo-distributed/Chart.yaml
- charts/tempo-distributed/README.md
- charts/tempo-distributed/README.md.gotmpl
> [tempo-distributed] bump tempo-distributed to version 2.8

- charts/grafana/Chart.yaml
> [grafana] bump grafana version to 12.0.2

- charts/tempo/Chart.yaml
- charts/tempo/README.md
> [tempo] bump to 2.8.1

- charts/grafana/Chart.yaml
- charts/grafana/values.yaml
> [grafana] bump kiwigrid/k8s-sidecar image to 1.30.5

- .github/CODEOWNERS
I'm already part of `grafana/tempo`
> Remove me from CODEOWNERS of `tempo-distributed`

- charts/tempo-distributed/Chart.lock
- charts/tempo-distributed/Chart.yaml
- charts/tempo-distributed/README.md
> [tempo-distributed] update rollout operator to 0.30.0

- charts/tempo-distributed/Chart.yaml
- charts/tempo-distributed/README.md
> [tempo-distributed] bump to 2.8.2

- charts/tempo/Chart.yaml
- charts/tempo/README.md
> [tempo] bump to 2.8.2

- charts/grafana/Chart.yaml
- charts/grafana/templates/headless-service.yaml
- charts/grafana/templates/image-renderer-service.yaml
- charts/grafana/templates/service.yaml
> [grafana] switch targetport from number to port name
